- include/types/wlr_tablet_v2.h
- include/wlr/types/wlr_data_device.h
- include/wlr/types/wlr_primary_selection.h
- include/wlr/types/wlr_seat.h
- types/data_device/wlr_data_device.c
- types/seat/wlr_seat.c
- types/seat/wlr_seat_keyboard.c
- types/seat/wlr_seat_pointer.c
- types/seat/wlr_seat_touch.c
- types/tablet_v2/wlr_tablet_v2_pad.c
- types/tablet_v2/wlr_tablet_v2_tool.c
- types/wlr_data_control_v1.c
- types/wlr_gtk_primary_selection.c
- types/wlr_pointer_gestures_v1.c
- types/wlr_primary_selection.c
- types/wlr_primary_selection_v1.c
- xwayland/selection/incoming.c
See also commit message, and #755. In short, this change verifies, for copy selection requests, that the serial numbers used to determine which request corresponds to the most recent user input were actually sent to the client.
Right now the code registers serial numbers for the keyboard, pointer, and touch events; serial numbers produced by any other input source will fail validation when provided by a client. (Serial numbers generated by e.g. xwayland code have no associated seat or client, and are not checked.) I'm not familiar with all of wlroots' protocols, so I don't know if e.g. tablet events are associated with a seat and should be allowed to trigger copy requests. 
This change alters the size of `struct wlr_seat_client`, silently breaking ABI for compositors which use that struct …
> Implement serial validation for selection requests

- types/seat/wlr_seat_touch.c
When the surface is destroyed clear it's reference but wait for the up
event to destroy the touch point via wlr_seat_touch_notify_up().
If the surface is destroyed before the up event we end up with
incomplete sequences sent to the client like
```
[915821.276] wl_touch@3.down(146, 2475027, wl_surface@38, 0, 236.000000, 515.000000)
[915821.608] wl_touch@3.frame()
[915821.637] wl_touch@3.motion(2475027, 0, 236.000000, 515.000000)
[915821.779] wl_touch@3.frame()
```
so there's never an up event. While it should be something like
```
[2461229.051] wl_touch@3.down(81, 3236959, wl_surface@34, 0, 218.000000, 478.000000)
[2461229.435] wl_touch@3.frame()
[2461229.484] wl_touch@3.motion(3236959, 0, 218.000000, 478.000000)
[2461229.636] wl_touch@3.frame()
[2461277.520] wl_touch@3.up(82, 3237007, 0) …
```
> wlr_seat_touch: Don't destroy touch point with surface

- rootston/xdg_shell.c
- rootston/xdg_shell_v6.c
set_maximized and set_fullscreen calls can come before the view is
constructed and before its signal handlers are registered.
> xdg_shell(_v6): Take maximize/fullscreen state into account on view init

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
This fixes a crash where the compositor tries to access `surface->configure_list` after the surface was destroyed via `handle_surface_destroy()->layer_surface_destroy()` but the resource is still around.
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==22322==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000070 (pc 0x55f4117f8d96 bp 0x7ffdadca6040 sp 0x7ffdadca6000 T0)
==22322==The signal is caused by a READ memory access.
==22322==Hint: address points to the zero page.
#0 0x55f4117f8d95 in layer_surface_handle_ack_configure ../subprojects/wlroots/types/wlr_layer_shell_v1.c:65
#1 0x7f65158a58ed in ffi_call_unix64 (/usr/lib/x86_64-linux-gnu/libffi.so.6+0x68ed)
#2 0x7f65158a52be in ffi_call …
```
> Layer shell crash

- rootston/text_input.c
When we move from one surface to another we ought to handle leave
for the old one but also send enter for the new one.
This fixes the case where an application with multiple windows gets the osk shown in the initial one but not subsequently opened ones.
> text_input: Don't forget to send enter events

- include/render/gles2.h
- include/wlr/util/log.h
- meson.build
- util/log.c
This PR applies the same change as https://github.com/swaywm/sway/pull/4282.
I have tested this change with Clang (8.0.0) and GCC (9.1.0, has `-fmacro-prefix-map`), with `--buildtype release`, and with wlroots built both standalone and as a subproject of sway.
To check that `-fmacro-prefix-map` actually strips paths correctly, run `strings libwlroots.so | grep wlroots`.
> Use -fmacro-prefix-map to strip build path, when available

- include/wlr/types/wlr_output.h
- types/wlr_output.c
AFAIK this was always set to zero. Instead, compute wl_output mode flags on the
fly.
Technically this is a breaking change, but I don't think anybody uses this
field.
> output: drop wlr_output_mode.flags

- include/wlr/types/wlr_screencopy_v1.h
- types/wlr_export_dmabuf_v1.c
- types/wlr_screencopy_v1.c
This fixes 3 crashes and hangs I encountered in sway when testing the screencopy and export-dmabuf protocols with multi-monitor setups. These all require at least two monitors.
1. Run [grim](https://github.com/emersion/grim) with `WAYLAND_DEBUG=1` on an output that is disabled
- Application hangs after `zwlr_screencopy_frame_v1_copy()`, no `failed()` or `ready()` event is sent
- Expected: `failed()` event
2. Run `examples/dmabuf-capture` on an output
- Run `swaymsg "output <name> disable"` on that output
- Get a segfault in sway
- Expected: permanent `cancel()` event
3. Run my [test application](https://gist.github.com/cyclopsian/57435c6fd0f34ec4a5b98bdcc2beb310) that copies the screen as fast as possible
- Repeatedly disable and enable some outputs with swaymsg either manually or with …
> Fix issues with multi-monitors and screencopy/export-dmabuf 

- backend/drm/drm.c
- backend/headless/output.c
- backend/noop/output.c
- backend/rdp/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- rootston/output.c
- types/wlr_output.c
This commit makes more output properties (mode, enabled, scale and transform)
atomic. This means that they are double-buffered and only applied on commit.
Compositors now need to call wlr_output_commit after setting any of those
properties.
Internally, backends still apply properties sequentially. The behaviour should
be exactly the same as before. Future commits will update some backends to take
advantage of the atomic interface. Some backends are non-atomic by design, e.g.
the X11 backend or the legacy DRM backend.
Updates: https://github.com/swaywm/wlroots/issues/1640
> output: atomic mode, enabled, scale and transform

- backend/drm/drm.c
- include/backend/drm/drm.h
Instead of waiting for the next pageflip, destroy the output immediately
since we can now handle flips for outputs which no longer exist.
Also demote the missing crtc on flip to debug.
Fixes #1739
Creating as draft since I have not tested this yet.
> backend/drm: destroy output immediately

- backend/drm/drm.c
- backend/headless/output.c
- backend/noop/output.c
- backend/rdp/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- rootston/output.c
- types/wlr_output.c
This reverts commit ee5f98ad49fed0439f3313ec685307831d1d1d05.
This intoduced problems where outputs could not be turned off because
they had flips pending.
> Revert "output: atomic mode"

- types/wlr_input_method_v2.c
It's added to manager->input_methods list in manager_get_input_method, but wasn't removed anywhere, leading to possible use-after-free in wlr_input_method_manager_v2_destroy.
> wlr_input_method_v2: Remove input method's resource from the list on destroy

- backend/drm/drm.c
The loop populating the format list was exiting early if ARGB8888 was found.
> backend/drm: fix missing plane formats

- include/wlr/types/wlr_xdg_shell.h
- types/xdg_shell/wlr_xdg_surface.c
- types/xdg_shell/wlr_xdg_toplevel.c
Fixes  swaywm/sway#4421
[From the xdg-shell specification:](https://github.com/wayland-project/wayland-protocols/blob/630fb089103a1d0eab1a684b853ab5c4d2b252aa/stable/xdg-shell/xdg-shell.xml#L555)
If the parent is unmapped then its children are managed as
though the parent of the now-unmapped parent has become the
parent of this surface. If no parent exists for the now-unmapped
parent then the children are managed as though they have no
parent surface.
> wlr_xdg_toplevel: reparent on parent unmap

- backend/libinput/touch.c
libinput_event_touch_get_slot always returns -1 for single touch devices. Using
libinput_event_touch_get_seat_slot instead ensures that they are assigned actual
slot ids.
Also, this is what Weston does, so this change yields a more consistent
behaviour between different compositors.
> backend: touch: Assign good ids to single touch devices

- backend/libinput/touch.c
All instances of libinput_event_touch_get_slot need to be converted to
libinput_event_touch_get_seat_slot for things to work.
I didn't test my last patch well enough. This clears up the mess.
> backend: touch: Fixup incomplete patch for single touch devices.

- types/wlr_layer_shell_v1.c
Mirrors #1530 (xdg-shell) for wlr-layer-shell-v1
Supersedes/Closes #1418 (#1530 + this is basically #1418)
Fixes swaywm/sway#4477
This destroys the xdg popups associated with a layer surface when the
layer surface is unmapped. It does not make sense to keep the popups
open when unmapped.
> wlr-layer-shell-v1: destroy xdg popups on unmap

- types/xdg_shell/wlr_xdg_popup.c
- types/xdg_shell_v6/wlr_xdg_popup_v6.c
This reverts commit 52037d13f7617bef8e0f2566cb4609646cf8cd8f.
Fixes #1801
> Revert "wlr_xdg_popup: don't treat all surfaces of grabbing client as grabbing surfaces"

- render/gles2/renderer.c
I believe there is a calculation error in the gles2_read_pixels() function, causing issue #1699 .
The calculation is OK for the first readout of the entire viewport, but once a partial area roughly below the middle of the viewport is changed, the data offset will make the glReadPixels() overflow the buffer, causing the seg fault and strange display behaviour discussed in the bug report.
> Fix calculation for partial gles2 pixel read

- backend/drm/drm.c
Instead of checking that the path property is not 0 to determine if the
connector is an MST connector, check if the path contains the mst:
string.
Fixes #1813
TODO:
> backend/drm: check for mst: in path property

- types/wlr_layer_shell_v1.c
When the surface is closed, we destroy all pending serials waiting to be accepted. This means we need to ignore any future ack events, because we can have the following events:
1. -> configure()
2. -> close()
3. <- ack_configure()
At point 3, wlroots will error the client because of invalid serial,
however the client hasn't processed close() yet.
> layer-shell: ignore ack_configure() on closed surfaces

- include/wlr/types/wlr_seat.h
- types/seat/wlr_seat_touch.c
Since e26217c51e3a5e1d7dfc95a8a76299e056497981, touchpoints can outlive
surfaces. This works fine as long as the client stays around, but fails
horribly otherwise; therefore we have to make sure that touchpoints don't
outlive their clients.
Fixes #1788
> wlr_seat_touch: Destroy the touchpoint on client destroy

- render/egl.c
I don't know why on earth I didn't include this when I originally added this.
It's not worth creating and trying to maintain a big lookup table of EGL error values. You can just search the EGL headers for it, which is also why the error code is in hexadecimal.
> render/egl: Change KHR_debug log to include error code

- types/wlr_xdg_output_v1.c
xdg-output version 3 requires to send wl_output.done
"after all xdg_output properties have been sent when the object is created"
> xdg-output: send wl_output.done after xdg_output created

- include/wlr/types/wlr_presentation_time.h
- types/wlr_presentation_time.c
cc https://github.com/swaywm/sway/issues/4451
The idea is that feedback goes from nothing to committed to either sampled (and subsequently presented) or discarded.
Sway patch: https://github.com/swaywm/sway/pull/4465
* * *
Compositor maintainers: call `wlr_presentation_surface_sampled` when rendering a surface.
> presentation_feedback: add the sampled state

- backend/libinput/tablet_pad.c
- backend/meson.build
- backend/wayland/backend.c
- backend/wayland/tablet_v2.c
- backend/wayland/wl_seat.c
- include/backend/wayland.h
- include/wlr/types/wlr_tablet_tool.h
- protocol/meson.build
- types/tablet_v2/wlr_tablet_v2_pad.c
- types/wlr_tablet_pad.c
This adds tablet support to the wlroots wayland backend.
I've only tested this against rootston itself as parent compositor and some of the math might be off, converting from [0,65536] to [0,1] and back.
> Tablet v2 client

- examples/meson.build
Successful wlroots build in Sway CI: https://builds.sr.ht/~emersion/job/95358#task-wlroots
(The failure at the sway stage is fixed by https://github.com/swaywm/sway/pull/4615)
> build: workaround for meson disabler object not working with if not

- include/wlr/xwayland.h
- xwayland/xwm.c
This allows compositors to know which elements are valid. Without this,
it is impossible to tell which are invalid. This means if only position or size
are valid for instance, the compositor can discard the values of the rest.
> xwayland: Expose configure mask

- render/egl.c
There's some ongoing work to advertise the modifiers EGL extension even if modifiers aren't supported so that we can use `eglQueryDmaBufFormatsEXT`. However we need to be prepared for `eglQueryDmaBufModifiersEXT` to return zero modifiers.
> render/egl: support formats with zero modifiers

- backend/drm/drm.c
- backend/drm/renderer.c
- include/backend/drm/renderer.h
On my Intel GPU, the primary plane ends up using X_TILED instead of LINEAR.
Closes: https://github.com/swaywm/wlroots/issues/1840
> backend/drm: use modifiers for our GBM buffers

- types/wlr_box.c
- types/wlr_cursor.c
- types/wlr_output_layout.c
If box->width/height is <= 0, the box doesn't contain any points, and so there is no closest point. wlr_box_closest_point should return NAN in this case.
In addition, we need to handle empty boxes in a few other output-layout-related places, because outputs can have size 0x0 when they are created or destroyed.
> wlr_box: properly calculate closest point for non-positive area boxes

- glgen.sh
- include/wlr/render/egl.h
- include/wlr/render/interface.h
Define both MESA_EGL_NO_X11_HEADERS and EGL_NO_X11 for
backward combatibility.
Newer versions of mesa now define -DEGL_NO_X11 instead of -DMESA_EGL_NO_X11_HEADERS.
> Add new define EGL_NO_X11 for newer mesa library

- include/wlr/types/wlr_output.h
- types/wlr_output.c
For sway PR: https://github.com/swaywm/sway/pull/4588.
Idle frame block: when delaying the output render after a presentation, idle frames need to be blocked because they interfere (and a render is scheduled anyway).
Frame done timer: used for delayed frame callbacks.
cc #655
> Additions for repaint scheduling

- include/wlr/types/wlr_layer_shell_v1.h
- protocol/wlr-layer-shell-unstable-v1.xml
- types/wlr_layer_shell_v1.c
[Implementation in Way Cooler](https://github.com/way-cooler/way-cooler/pull/649)
> layer_shell: set layer of existing surface

- glgen.sh
eglext.h no longer inludes eglmesaext.h, include it within wlroots
explicitly.
Fixes #1862
> Add missing include required by mesa and libglvnd change

- backend/drm/drm.c
- include/backend/drm/drm.h
We need to destroy the gbm_bo we imported and drmModeRmFb.
Closes: https://github.com/swaywm/sway/issues/4662
> backend/drm: track gbm_bo during direct scan-out

- backend/drm/drm.c
- backend/drm/renderer.c
- include/backend/drm/renderer.h
- render/egl.c
On some Intel cards using modifiers can fill the FIFO and prevent
hotplugged outputs from being properly enabled.
Add a fallback without modifiers.
References: https://github.com/swaywm/wlroots/issues/1840
Closes: https://github.com/swaywm/wlroots/issues/1852
> backend/drm: retry without modifiers for the primary plane

- backend/drm/cvt.c
- backend/drm/drm.c
- backend/meson.build
- include/backend/drm/cvt.h
- include/wlr/backend/drm.h
Use the CVT algorithm to create a drmModeModeInfo.
* * *
Breaking change: `wlr_drm_connector_add_mode` now returns the new mode instead of a `bool`.
> backend/drm: add support for custom modes

- types/wlr_output_management_v1.c
Makes it easier to figure out when the compositor submits an invalid
output state.
References: https://github.com/swaywm/sway/pull/4673
> output-management-v1: add assertion as a safety net

- types/tablet_v2/wlr_tablet_v2_pad.c
See swaywm/sway#4660
This change does fix the crash, but I am not sure if this is the proper way to do it, so I want someone with knowledge about wlroots memory management to review this.
cc @emersion @Ongy
> Fix heap-use-after-free in wlr_send_tablet_v2_tablet_pad_leave

- backend/x11/backend.c
- backend/x11/meson.build
- backend/x11/output.c
- include/backend/x11.h
This is some work split out of one of my renderer v6 PRs.
Makes use of the present extension to get notified of vsync, and not require any stupid timer hacks. Also make use of the present version of ConfigureNotify, because why not?
> backend/x11: Give X11 a real rendering loop

- backend/session/logind.c
Closes #1424.
A number of sway users have been reporting that sway fails to start on systemd 243 in swaywm/sway#4672 and elsewhere. I'm guessing this could be fixed by waiting for the logind CanGraphical property on the seat before trying TakeDevice.
Unfortunately, it seems that systemd-logind has been broken for some time and doesn't actually emit PropertiesChanged when it should for CanGraphical, see systemd/systemd#13811. So users with broken sway will need both patches for the fix.
The issue was tagged easy so I thought I'd give it a shot, but this is my first attempt with wlroots code, so there may be some bad assumptions or silly mistakes.
I'm not sure what should happen, if anything, when CanGraphical changes true->false. I'm not sure under what circumstances that would happen. I …
> session/logind: support CanGraphical property

- include/wlr/types/meson.build
- include/wlr/types/wlr_keyboard.h
- include/wlr/types/wlr_keyboard_group.h
- types/meson.build
- types/wlr_keyboard.c
- types/wlr_keyboard_group.c
Closes #1217 
Supersedes/Closes #1421
Sway PR: swaywm/sway#4373
A wlr_keyboard_group allows for multiple keyboard devices to be
combined into one logical keyboard. Each keyboard device can only be
added to one keyboard group. This helps with the situation where one
physical keyboard is exposed as multiple keyboard devices. It is up to
the compositors on how they group keyboards together, if at all.
Since a wlr_keyboard_group is one logical keyboard, the keys are a set.
This means that if a key is pressed on multiple keyboard devices, the
key event will only be emitted once, but the internal state will count
the number of devices that the key is pressed on. Likewise, the key
release will not be emitted until the key is released from all devices.
If the compositor wants access to which keys …
> Introduce wlr_keyboard_group

- include/render/gles2.h
- render/gles2/renderer.c
- render/gles2/texture.c
While I was writing https://github.com/swaywm/wlroots/issues/1826#issuecomment-550171172 and looking through our code, I realised it's not as simple as it should be.
We don't need our own enum for types. Instead we just use GL_TEXTURE_{2D,EXTERNAL_OES}, which already describes usage.
Also fixes a situation where we were using GL_TEXTURE_2D in a situation we should not have. wl_drm buffers are always GL_TEXTURE_EXTERNAL_OES, no matter if they're RGB or any other format.
> render/gles: Simplify textures a bit

- include/wlr/render/gles2.h
- render/gles2/texture.c
Prior to this commit, compositors needed to render the texture to an
intermediate off-screen buffer using wlr_renderer APIs if they wanted to
use a custom rendering path (e.g. render to a 3D scene).
A new wlr_gles2_texture_get_attribs exposes the GL texture target and ID
so that compositors can render wlr_textures with their own shaders. An
example of a compositor doing so is available at [1].
[1]: https://git.sr.ht/~sircmpwn/wxrc/tree/3db905b7842ac42cf1878876e647005b41f00a52/src/render.c#L227
> render/gles2: provide public API to access GL texture

- types/wlr_surface.c
Sometimes if one don't want to get sx or sy, they can pass NULL after this PR, and will not cause segfault.
> Skip assign when sub_x or sub_y is NULL in wlr_surface_surface_at

- backend/wayland/backend.c
- backend/wayland/wl_seat.c
- include/backend/wayland.h
We just send relative motion events alongside absolute motion events.
Compositors can figure out how absolute and relative events are related
(e.g. whether they have been triggered by the same logical event) with
the frame event.
> backend/wayland: add support for relative-pointer-unstable-v1

- backend/wayland/backend.c
- backend/wayland/output.c
- backend/wayland/wl_seat.c
- include/wlr/backend/wayland.h
Expose the remote wl_display, wl_surface and wl_seat used by the Wayland
backend.
This allows compositors to customize the Wayland backend and to have
more freedom. For instance a compositor might want to handle clipboard
and drag-and-drop from the remote Wayland compositor. Another compositor
might want to setup pointer constraints.
> backend/wayland: expose remote objects

- backend/drm/drm.c
- include/wlr/types/wlr_output.h
- types/wlr_output.c
This is set to the value of wlr_output.commit_seq when the frame has
been submitted. This allows to track presentation with more than 1 full
frame of latency.
References: https://github.com/swaywm/wlroots/issues/1917
> output: add wlr_output_event_present.commit_seq

- backend/backend.c
- backend/x11/backend.c
This can really mess with the session if logind is not being used, and it's going to always fail anyway.
---
We say 1.2, but I don't think we actually use anything that was
introduced past 1.0.
> Backend fixes

- meson.build
Eliminates this warning when building wlroots as a subproject:
subprojects/wlroots/meson.build:216: DEPRECATION: Library wlroots
was passed to the libraries keyword argument of a previous call
to generate() method instead of first positional argument. Adding
wlroots to Requires field, but this is a deprecated behaviour
that will change in a future version of Meson. Please report the
issue if this warning cannot be avoided in your case.
> build: Pass lib_wlr as first argument to pkgconfig.generate()

- backend/x11/backend.c
- backend/x11/meson.build
- backend/x11/output.c
- include/backend/x11.h
This reverts commit 3317134adff0ed179e0ecaea6d778dbd0684f771.
This reverts commit a3c3b928a3814f1a44babf487b1508415958c721.
There are some serious issues when running this on a real X server, as
opposed to running this on Xwayland, where this was tested.
More investigation needs to be done into why these issues happen and if
our usage of the present extension is correct.
> backend/x11: Revert usage of present extension

- examples/screencopy.c
Similar to https://github.com/cyclopsian/wdisplays/pull/6
wlroots already uses `shm_open` correctly elsewhere:
https://github.com/swaywm/wlroots/blob/16e5e9541b3de49e397a3d2caa3212db25487648/util/shm.c#L29
> Unbreak examples/screencopy on FreeBSD

- include/wlr/types/wlr_presentation_time.h
- types/wlr_output.c
- types/wlr_presentation_time.c
The wlr_presentation_feedback struct now tracks presentation feedback
for multiple resources (but still a single surface content update). This
allows the compositor to properly send presentation events even when
there is more than one frame of latency or when it references a
surface's buffer.
Most of the time, compositors just display the surface's current buffer
on an output. Add an helper to make it easy to support presentation-time
in this case.
References: https://github.com/swaywm/sway/issues/4572
Closes: https://github.com/swaywm/wlroots/issues/1917
cc @YaLTeR 
* * *
Breaking change: instead of calling `wlr_presentation_surface_sampled` at render time and `wlr_presentation_send_surface_presented` at presentation time, most compositors now just need to call …
> Improve presentation-time API

- render/wlr_texture.c
Otherwise this error happens:
../subprojects/wlroots/render/wlr_texture.c: In function ‘wlr_texture_get_size’:
../subprojects/wlroots/render/wlr_texture.c:47:9: error: ISO C forbids ‘return’ with expression, in function returning void [-Werror=pedantic]
47 |  return texture->impl->get_size(texture, width, height);
|         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../subprojects/wlroots/render/wlr_texture.c:45:6: note: declared here
45 | void wlr_texture_get_size(struct wlr_texture *texture, int *width,
|      ^~~~~~~~~~~~~~~~~~~~
> render: remove return in wlr_texture_get_size

- render/gles2/renderer.c
My take on #1770 
As @emersion says [this comment](https://github.com/swaywm/wlroots/pull/1898#pullrequestreview-311603780)
> Hmm, I'm really not a fan of adding get_scale/set_scale to the renderer. I'd rather manually call glTexParameteri in the compositor before rendering a texture.
I found in [the reference](https://www.khronos.org/registry/OpenGL-Refpages/es2.0/xhtml/glTexParameter.xml):
> GL_TEXTURE_MAG_FILTER
The texture magnification function is used when the pixel being textured maps to an area less than or equal to one texture element. [...] The initial value of GL_TEXTURE_MAG_FILTER is GL_LINEAR.
Since it just so happens that GL_LINEAR is the default value, my idea is to just not set MAG_FILTER at all in wlroots, and let it remain the default value. It shouldn't cause any change …
> render/gles2: do not set GL_TEXTURE_MAG_FILTER

- types/wlr_virtual_keyboard_v1.c
- util/array.c
This comes as a follow-up to https://github.com/swaywm/wlroots/issues/1821 and https://github.com/swaywm/wlroots/pull/1833
That merge resolved the crash when keycode 0 (8) was received, but it didn't allow the keycode to be accepted, causing some head scratching on squeekboard side.
It seems that keycode 0 (8 in xkb keymaps) is not an invalid one:
```
grep -r ' 8;' /usr/share/X11/xkb/keycodes/
/usr/share/X11/xkb/keycodes/sony:    <FK01> = 8;
/usr/share/X11/xkb/keycodes/sun:    <STOP> = 8;
/usr/share/X11/xkb/keycodes/amiga:    <TLDE> = 8;
/usr/share/X11/xkb/keycodes/amiga:    <TLDE> = 8;
/usr/share/X11/xkb/keycodes/xfree98:    <ESC>  =   8;
/usr/share/X11/xkb/keycodes/xfree86:    <MDSW> =     8;
/usr/share/X11/xkb/keycodes/macintosh:    <AC01> = 8; …
```
> virtual_keyboard: Accept keycode 0

- docs/env_vars.md
Testing with exporting WLR_BACKENDS=drm worked, and it wasn't documented. Checking the backends folder, and it also mentions an RDP backend as well
> Update environment variable documentation to include more backends

- include/wlr/types/wlr_output.h
- types/wlr_output.c
This reverts commit cbb2781fed7944dae680a66a35443f5b1a678ec7.
In [1], we found issues with block_idle_frame and replaced it with
frame_pending. block_idle_frame is now unused.
[1]: https://github.com/swaywm/sway/pull/4772
> Revert "output: add block_idle_frame"

- types/wlr_keyboard.c
Sometimes compositors don't need an XKB keymap at all, they just handle
raw keycodes. Emit key events even if no keymap is set.
> keyboard: emit key events without keymap

- backend/drm/backend.c
- backend/libinput/backend.c
- include/backend/drm/drm.h
- include/backend/libinput.h
This fixes a heap-use-after-free when the session is destroyed before
the backend during wl_display_destroy:
==1085==ERROR: AddressSanitizer: heap-use-after-free on address 0x614000000180 at pc 0x7f88e3590c2d bp 0x7ffdc4e33f90 sp 0x7ffdc4e33f80
READ of size 8 at 0x614000000180 thread T0
#0 0x7f88e3590c2c in find_device ../subprojects/wlroots/backend/session/session.c:192
#1 0x7f88e3590e85 in wlr_session_close_file ../subprojects/wlroots/backend/session/session.c:204
#2 0x7f88e357b80c in libinput_close_restricted ../subprojects/wlroots/backend/libinput/backend.c:24
#3 0x7f88e21af274  (/lib64/libinput.so.10+0x28274)
#4 0x7f88e21aff1d  (/lib64/libinput.so.10+0x28f1d)
#5 0x7f88e219ddac  (/lib64/libinput.so.10+0x16dac)
#6 0x7f88e21b415d in libinput_unref (/lib64/libinput.so.10+0x2d15d)
#7 …
> backend/drm, backend/libinput: listen to session destroy

- backend/drm/renderer.c
When surf->gbm was previously set, we destroy it without setting it to
NULL. Later on, we only create the GBM surface if surf->gbm is NULL.
This result in a use-after-free when we start using surf->gbm.
Closes: https://github.com/swaywm/wlroots/issues/1868
Closes: https://github.com/swaywm/wlroots/issues/1874
Closes: https://github.com/swaywm/sway/issues/4785
Closes: https://github.com/swaywm/sway/issues/4717
Closes: https://github.com/swaywm/sway/issues/4730
Fixes: 2bdd1d0896cc ("backend/drm: use modifiers for our GBM buffers")
> backend/drm: fix segfault in init_drm_surface

- types/wlr_output.c
> This change ensures that `wl_surface::leave` is sent when a surface associated with the cursor is disassociated, e.g. when the cursor is reset or its image is changed.
One way to test this fix is to run a program linked to a beta version Qt 5.14, and move the cursor onto and off of a window (so that the cursor surface changes); before this change, the program will print a warning. Alternatively, apply [0001-surface-warn.patch.txt](https://github.com/swaywm/wlroots/files/3935514/0001-surface-Warn-on-redundant-wl_surface.-enter-leave.patch.txt), which modifies wlroots to detect and log an error when `wlr_surface_send_leave` and `wlr_surface_send_enter` are incorrectly invoked a second time.
> output: fix cursor wl_surface.{enter,leave} tracking

- types/wlr_buffer.c
- types/wlr_surface.c
In case the texture can't be imported, release the buffer so that the
client can submit another one. In case the allocation fails, disconnect
the client.
> buffer: improve error handling

- types/wlr_output.c
`mode` points to an invalid pointer (head of the list) when the loop
stops.
Closes: https://github.com/swaywm/sway/issues/4717
> output: fix wlr_output_preferred_mode fallback

- types/tablet_v2/wlr_tablet_v2_tool.c
Tablet events, including `proximity_out`, are supposed to be grouped into frames. GTK will only "forget" a tool on the frame event after `proximity_out`. Not sending a frame event can cause a crash:
- have GTK >= 3.24.9
- launch a GTK app that likes to change cursors, e.g. gnome-terminal or tilix, on a HiDPI monitor
- interact with the app using a tablet
- start moving the mouse over the app
- GTK tries to reference the destroyed tablet tool, boom, crash in `wl_proxy_marshal` under `gdk_window_set_cursor`
(btw, I'm not sure about the `send_tool_frame` *above*, maybe having only this one is better?)
> Send tablet tool frame on proximity_out

- backend/drm/drm.c
While printing the supported output modes, annotate the preferred mode.
> backend/drm: print preferred mode

- .builds/archlinux.yml
Arch Linux maintainers are still figuring out whether they should ask
people to explicitely install it or make it a dependency of xcb again.
In the meantime, add it as an explicit dependency. I'll revert this
patch if they decide otherwise.
[1]: https://bugs.archlinux.org/task/64914
> ci: add xorgproto dep to Arch build

- render/egl.c
Some extensions are only advertised by the EGL implementation with a
non-zero EGLDisplay. That's the case when the extension can only be
enabled when the hardware/driver supports it for instance.
Instead of checking for all extensions without a display, check only for
EGL_EXT_platform_base and EGL_KHR_debug which are used before
eglGetDisplay. Check for all other extensions when we have a display.
Closes: https://github.com/swaywm/wlroots/issues/1955
Closes: https://github.com/swaywm/sway/issues/4828
> render: fix EGL extensions not loaded

- .builds/archlinux.yml
This reverts commit 35bc3e662a34fe92a3de4e3768dc976f8ac2c242.
Per [1], the dependency has been re-added and we shouldn't need to
explicitly install it anymore.
[1]: https://bugs.archlinux.org/task/64914
> Revert "ci: add xorgproto dep to Arch build"

- backend/drm/drm.c
- backend/headless/output.c
- backend/rdp/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/types/wlr_output.h
- include/wlr/types/wlr_xdg_output_v1.h
- types/wlr_output.c
- types/wlr_output_management_v1.c
- types/wlr_xdg_output_v1.c
wlr_output.description is a string containing a human-readable string
identifying the output. Compositors can customise it via
wlr_output_set_description, for instance to make the name more
user-friendly.
References: https://github.com/swaywm/wlroots/issues/1623
cc @agx
> output: add description

- types/wlr_keyboard_group.c
This fixes a memory leak the refresh_state function for
wlr_keyboard_group. The event struct was being dynamically allocated and
never free'd. This changes it to a static allocation.
> wlr_keyboard_group: fix mem leak in refresh_state

- backend/drm/drm.c
- backend/headless/output.c
- backend/noop/output.c
- backend/rdp/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- tinywl/tinywl.c
- types/wlr_output.c
This reverts commit 01f903874b7e27539488fad7f31476d5bcbc6ac9 and re-applies
commit ee5f98ad49fed0439f3313ec685307831d1d1d05.
Updates: https://github.com/swaywm/wlroots/issues/1640 (Atomic output updates issue)
See also: https://github.com/swaywm/wlroots/pull/1762 (Atomic output updates original PR)
See also: https://github.com/swaywm/wlroots/issues/1780 (Issue caused by atomic output updates)
See also: https://github.com/swaywm/sway/issues/4419 (Issue caused by atomic output updates)
See also: https://github.com/swaywm/wlroots/pull/1781 (Revert PR)
Sway PR: https://github.com/swaywm/sway/pull/4845
* * *
* Compositors now need to call `wlr_output_commit` after `wlr_output_enable`, `wlr_output_set_mode`, `wlr_output_set_custom_mode`, `wlr_output_set_transform` or …
> output: re-introduce atomic mode, enabled, scale and transform

- include/wlr/types/wlr_xdg_shell.h
- types/xdg_shell/wlr_xdg_surface.c
Closes: https://github.com/swaywm/sway/issues/4834
Closes: https://github.com/swaywm/wlroots/issues/1890
> xdg-shell: fix inert xdg_surface handling

- types/wlr_output.c
- Regular clients shouldn't care about modes
- Modes exposed are missing metadata such as aspect-ratio, interleaved, etc
- Modes exposed cannot be pruned [1]
- wlr-output-management provides a better API for privileged clients
[1]: https://gitlab.freedesktop.org/wayland/wayland/issues/92
Closes: https://github.com/swaywm/wlroots/issues/1099
> output: only advertise current mode

- backend/drm/backend.c
- backend/drm/drm.c
This fixes a segfault in drm_connector_set_mode (mode = NULL).
This happens because we set wlr_output.enabled to true if the connector
is attached to the CRTC. When the user disables an output in the
wlroots-based compositor, switches to another VT (enabling the output),
then switches back, wlroots sets wlr_output.enabled to true but
wlr_output.current_mode is NULL.
We should consider not reading properties from KMS after a TTY switch,
disabling all connectors. However this may result in flickering (outputs
being disabled then re-enabled).
Closes: https://github.com/swaywm/wlroots/issues/1874
> backend/drm: don't modeset with a NULL mode after TTY switch

- examples/meson.build
- examples/virtual-pointer.c
- include/wlr/types/wlr_virtual_pointer_v1.h
- protocol/meson.build
- protocol/wlr-virtual-pointer-unstable-v1.xml
- types/meson.build
- types/wlr_virtual_pointer_v1.c
This is mostly copy of the virtual-keyboard code.
I am sort of unsure if this is the correct way to handle the axis_start/axis_stop calls. At the moment it looks like they get automatically generated inside wlroots (should they even be in the virtual-pointer protocol?).
> virtual-pointer: Add support for wlr-virtual-pointer-unstable-v1

- include/wlr/render/wlr_renderer.h
- render/wlr_renderer.c
Add a wlr_renderer.rendering bool, set it to true between
wlr_renderer_begin() and wlr_renderer_end(). Assert we're rendering when
calling functions that render.
> render: guard rendering operations between begin() and end()

- backend/wayland/output.c
This got removed in [1]. I probably messed up the rebase.
[1]: https://github.com/swaywm/wlroots/pull/1797/files#diff-3065f86e6de87d143d4a7673a8ee3a2d
Fixes: 5d1ba0f44687 ("output: re-introduce atomic mode, enabled, scale and transform")
> backend/wayland: fix frame callback not registered

- types/wlr_virtual_pointer_v1.c
It turns out that scrolling doesn't work unless this value is set somewhere.
> virtual-pointer: Actually use the value passed to axis_discrete

- xwayland/xwm.c
Although currently this problem is present in only Steam, and it is actually a client bug.
Relevant discussion:  https://github.com/swaywm/sway/issues/1865 and #1645 
What I am not sure: should we update `xwm->focus_surface` ?
> xwm: allow applications to change focus between their own surfaces

- backend/wayland/output.c
- include/backend/wayland.h
Previously, we just assumed submitting a new frame would make the
compositor release the current one. This isn't always the case, for
instance Sway retains old buffers when a transaction is pending. This
resulted in synchronization issues with clients writing in
front-buffers.
Fix this by un-referencing a wlr_buffer when the parent compositor sends
wl_buffer.release.
Tested by running a fullscreen mpv instance in Sway with the Wayland
backend.
> backend/wayland: listen to wl_buffer.release events

- types/wlr_text_input_v3.c
Found this when debugging swaywm/sway#4740
> text-input: fix missing destroy signal init

- render/gles2/renderer.c
- render/gles2/texture.c
Keeping textures bound results in hard-to-debug situations where some GL
operations incorrectly affect the texture.
> render/gles2: unbind textures after use

- meson.build
Closes #1994 
There was an issue in 0.51.0 and earlier, where lists of dependencies
and disablers weren't acting like they should. Instead of disabling a
build, it would error out instead.
Changing this logic to work around it is annoying, so just bump the
version instead.
> Bump meson version to 0.51.2

- backend/drm/drm.c
This would happen if initializing the renderer fails. Instead, we just
mark the output as disabled.
References: https://github.com/swaywm/sway/pull/4917
> backend/drm: prevent outputs from being destroyed on commit

- types/wlr_keyboard_group.c
Previously, creating a keyboard group without any keymap set would
result in an error:
Device keymap does not match keyboard group's
> keyboard-group: two NULL keymaps are equal

- meson.build
The `examples` options defined in `meson_options.txt` currently has no effect, which I assume is not intended. From cursory glance into `git blame`, it seems that the `if` statement that checked it was removed in commit fd3fa760d336312acafeb6812b5b0068f5851f27, but I was also not able to tell if that was intentional.
As we use this option to disable the examples when packaging wlroots for Fedora, this PR adds the check for the option back. Alternatively, the option could be removed from the options (and we will adjust our packaging accordingly).
> Honor the `examples` meson setting

- backend/wayland/meson.build
- examples/meson.build
- protocol/meson.build
This should fix the alpine build, due to underspecifying the example dependencies.
> meson: Fix protocol includes for compositor examples

- contrib/_incr_version
- include/wlr/meson.build
- meson.build
This allows us to have a single number to update when doing a release.
* * *
Breaking change: `WLR_VERSION_API_*` definitions are dropped.
> build: replace version with soversion

- backend/drm/drm.c
- docs/env_vars.md
In some cases modesets fail if the planes are initialized with
modifiers. Since in this case possibly all planes need to reinitialized,
which is not possible in the current wlroots design, add an environment
variable for affected users.
> backend/drm: add env variable to disable modifiers

- backend/drm/drm.c
The previous PR was overzealous in adding a finish_drm_surface call
which was also done by the caller. Remove the call and also move the
comment to the correct code location.
> backend/drm: remove overzealous finish_drm_surface

- include/wlr/render/egl.h
- include/wlr/render/interface.h
Even if the X11 backend or Xwayland is enabled, we don't rely on
EGL/egl.h including Xlib headers.
> render: unconditionally disable implicit X11 includes

- include/types/wlr_seat.h
When compiling wlroots with GCC 10, the linking fails with `multiple definition of 'default_pointer_grab_impl'` and similar errors for `default_keyboard_grab_impl` and `default_touch_grab_impl`. Full error: [gcc-10-ld.err.txt](https://github.com/swaywm/wlroots/files/4122843/gcc-10-ld.err.txt)
If I recall my C correctly, these should be marked `extern` – they just declare that the objects exist somewhere in the linked library, not necessarily in the current translation unit. Adding the `extern` qualifier causes the linking to pass successfully.
> Declare wlr_seat globals as extern

- meson.build
- types/seat/wlr_seat.c
Having 1.16 results in the following error when running the compositor:
2019-04-27 17:30:50 - [wayland] wl_global_create: implemented version for 'wl_seat' higher than interface version (7 > 6)
2019-04-27 17:30:50 - [sway/input/seat.c:428] seat_create:could not allocate seat
We require wayland-server >= 1.17 for wl_seat version 7.
Fixes: a671fc51d25c2adb723d2edf96c36011211f4b81
cc @ascent12
> meson: fix wayland-server minimum required version

- examples/fullscreen-shell.c
- examples/multi-pointer.c
- examples/output-layout.c
- examples/pointer.c
- examples/rotation.c
- examples/simple.c
- examples/tablet.c
- examples/touch.c
Due to the way the wlr_output API was changed, these examples would
never get a frame event to start the rendering loop. We now commit the
outputs to start it.
> examples: Fix compositor-examples

- backend/session/session.c
Depends on https://github.com/FreeBSDDesktop/libudev-devd/pull/7 ([D23715](https://reviews.freebsd.org/D23715) in ports). CC @myfreeweb, @zeising
> backend/session: allow GPU enumeration on FreeBSD

- include/util/global.h
- types/seat/wlr_seat.c
- types/wlr_output.c
- util/global.c
- util/meson.build
- wlroots.syms
Depends on:
* https://gitlab.freedesktop.org/wayland/wayland/merge_requests/28 (merged upstream)
* https://gitlab.freedesktop.org/wayland/wayland/merge_requests/30 (merged upstream)
Build with Wayland's master branch.
Closes: https://github.com/swaywm/sway/issues/3625
> output: don't destroy global immediately

- types/wlr_box.c
- types/wlr_cursor.c
- types/wlr_matrix.c
- types/wlr_output.c
- util/region.c
See https://gitlab.freedesktop.org/wayland/weston/issues/99 for motivation. I also found and fixed a small issue in `wlr_output_transform_compose` when composing transforms with flips and rotations.
This change breaks forward compatibility for past versions of wlroots; for example, upgrading wlroots with a corresponding patch, without upgrading sway, could change monitor orientations for anyone using sway's https://github.com/swaywm/sway/blob/master/sway/commands/output/transform.c .
I have tested these changes using ~the wlroots example `rotation` compositor~ and `swaymsg output eDP-1 transform flipped-90 clockwise`, and by patching an image display program to call wl_surface::set_buffer_transform() with a given value.
* * *
Breaking change: output transformations have been aligned with …
> Fix wl_output_transform rotation direction, and composition

- meson.build
This updates the version requirement for wayland-server to 1.18, which
is needed for wl_global_remove and wl_global_set_user_data
> meson.build: update wayland requirement to 1.18

- include/wlr/types/wlr_output_management_v1.h
- types/wlr_output_management_v1.c
Previously, if the current configuration contains an output X which is destroyed, its head is automatically removed. If the compositor submits the new configuration after X was removed, the current output configuration is incorrectly detected to be the same as the previous one, and no done event is sent. To prevent this, we can just keep track of whether the current configuration is dirty, i.e whether we have sent a done event for it.
> output-management: add current_configuration_dirty

- xwayland/xwm.c
This reflects what i3 does [1].
[1]: https://github.com/i3/i3/blob/b3faf9fca9254679a4715486a4de80ebaee70410/src/handlers.c#L1076
Fixes: c067fbc010da ("xwm: allow applications to change focus between their own surfaces")
Closes: https://github.com/swaywm/sway/issues/4926
> xwayland: ignore pointer focus changes

- include/wlr/types/wlr_text_input_v3.h
- types/wlr_text_input_v3.c
With this information, consumers can realize they will never retrieve some state, and adjust their strategy.
---
The protocol specifies that features are either supported or unsupported, so while the API user is able to determine this by the received calls, this functionality will be required by pretty much every API user in exactly the same form, so it makes sense to make it available here.
> text_input_v3: Note features supported by the text field

- examples/keyboard-shortcuts-inhibit.c
- examples/meson.build
- include/wlr/types/wlr_keyboard_shortcuts_inhibit_v1.h
- protocol/meson.build
- types/meson.build
- types/wlr_idle_inhibit_v1.c
- types/wlr_keyboard_shortcuts_inhibit_v1.c
The keyboard shortcuts inhibitor protocol is useful for remote desktop
and virtualization software in order to request all keyboard events to
be passed to it and (almost) none being resonded to by the compositor.
This allows the session at the other end of the remote desktop
connection or inside the virtual machine to be interacted with as usual
(e.g. Alt+Tab to switch windows on the remote system instead of
locally).
Add the wayland protocol to the meson build files.
Copy'n'search'n'replace the very similar idle inhibit protocol
implementation. This already provides all the basic functionality:
- creating and destroying inhibitors upon request by a client,
- destruction in reaction to destruction of surfaces or displays,
- a list of inhibitors to search through for existing ones as well …
> Keyboard shortcuts inhibit

- types/xdg_shell/wlr_xdg_popup.c
- types/xdg_shell_v6/wlr_xdg_popup_v6.c
Leave positioner inverted on the individual axis if it's no longer constrained. Otherwise constraint adjustment like `slide_x & flip_y` could render popup outside of the screen when both axes are constrained.
Fixes Alexays/Waybar#532
> xdg-shell: fix popups rendered outside of the screen

- types/wlr_output_power_management_v1.c
This makes sure the `wl_list_remove(&output_power->link)` in
`output_power_destroy()` does not crash even when the output_power never
got added to a list. This can e.g. happen in the `mgmt->output ==
output` error path of `output_power_manager_get_output_power`.
> wlr_output_power_management_v1: Init output_power->link

- backend/wayland/meson.build
- backend/wayland/seat.c
I never got why we have a wl_ prefix here.
> backend/wayland: rename wl_seat.c to seat.c

- backend/drm/drm.c
- backend/wayland/output.c
- include/wlr/interfaces/wlr_output.h
- types/wlr_output.c
This function allowed backends to provide a custom function for frame
scheduling. Before resuming the rendering loop, the DRM and Wayland
backends would wait for vsync.
There isn't a clear benefit of doing this. The only upside is that we
get more stable timings: the delay between two repaints doesn't change too
much and is close to a mutliple of the refresh rate.
However this introduces latency, especially when a client misses a
frame. For instance a fullscreen game missing vblank will need to wait
more than a whole frame before being able to display new content. This
worst case scenario happens as follows:
- Client is still rendering its frame and cannot submit it in time
- Deadline is reached
- Compositor decides to stop the rendering loop since nothing changed on
screen
- Client …
> output: remove wlr_output_impl.schedule_frame

- backend/wayland/seat.c
Previously, each time a wl_seat.capabilities event was received the
Wayland backend created new input devices. It now only does so the first
time.
Input devices are now destroyed when the cap is removed.
Closes: https://github.com/swaywm/sway/issues/5055
> backend/wayland: fix seat caps handling

- meson_options.txt
- xcursor/meson.build
Some Linux distributions and all BSDs install packages somewhere other than `/usr` by default. This breaks server-side theming e.g., on Sway empty workspaces use unstyled cursor vs. styled cursor in Gtk3 and X11 applications. To fix just override `ICONDIR` like libwayland and libXcursor have been doing for years.
Same as https://github.com/swaywm/wlroots/pull/2049.
> xcursor: look under ${datadir}/icons instead of /usr/X11R6/lib/X11/icons by default

- include/wlr/types/wlr_buffer.h
- include/wlr/types/wlr_surface.h
- types/wlr_buffer.c
- types/wlr_surface.c
Split out the client/resource handling out of wlr_buffer by introducing
wlr_client_buffer. Make wlr_buffer an interface so that compositors can
create their own wlr_buffers (e.g. backed by GBM, like glider [1]).
[1]: https://github.com/emersion/glider/blob/c66847dd1cf8ae5e68666ce7cb3be41427b38dc7/include/gbm_allocator.h#L7
Should we move `wlr_client_buffer` to its own header file?
* * *
This is a breaking change. Compositors that don't directly use `wlr_buffer` shouldn't need an update. For compositors which use it directly:
* `wlr_buffer` has been renamed to `wlr_client_buffer`
* `wlr_buffer_{ref,unref,get_dmabuf}` still take a `wlr_buffer`, compositors need to use `&wlr_client_buffer->base`
* `wlr_buffer_create` and `wlr_buffer_apply_damage` have been renamed to …
> Introduce wlr_client_buffer

- backend/drm/drm.c
- backend/drm/properties.c
- backend/x11/backend.c
- backend/x11/output.c
- include/backend/drm/properties.h
- include/backend/x11.h
- include/wlr/types/wlr_output.h
- types/wlr_output.c
Fixes: https://github.com/swaywm/wlroots/issues/1406
~~Depends on: https://github.com/swaywm/wlroots/pull/2046~~
Future work: Wayland protocol to opt-in to VRR.
> Variable Refresh Rate

- types/wlr_output.c
This way, wlr_output_schedule_frame will always be followed by a
wlr_output_commit. This forces the compositor to render an extra
frame before stopping the rendering loop.
To test, run wleird's frame-callback [1], make sure it's the only
visible client on the output and check the interval between frame
events is the output's refresh period instead of zero.
[1]: https://github.com/emersion/wleird/blob/master/frame-callback.c
Closes: https://github.com/swaywm/wlroots/issues/2051
> output: make wlr_output_schedule_frame set output->needs_frame

- util/log.c
This is useful when debugging a rendering loop.
> util/log: improve time prefix

- include/wlr/types/wlr_buffer.h
- types/wlr_buffer.c
- types/wlr_surface.c
Forgot to remove these, they are superseded by fields in wlr_buffer. Some
functions were still using them.
Fixes: 8afc1ed68cfa ("Introduce wlr_client_buffer")
Closes: https://github.com/swaywm/sway/issues/5087
> buffer: remove unused wlr_client_buffer fields

- types/wlr_output.c
Add a comment to not forget why this call is necessary.
References: https://github.com/swaywm/wlroots/pull/2053
> output: add comment about needs_frame in wlr_output_schedule_frame

- include/wlr/types/wlr_output.h
- include/wlr/types/wlr_output_damage.h
- types/wlr_output.c
- types/wlr_output_damage.c
This patch disambiguates the needs_frame event by uncoupling it from
damage. A new separate damage event is emitted when the backend damages
the output (this happens e.g. VT is changed or software cursors are
used). The event specifies the damaged region.
The wlr_output.damage field is removed. wlr_output is no longer
responsible for tracking its own damage, this is wlr_output_damage's
job.
This is a breaking change, but wlr_output_damage users shouldn't need an
update.
Bugs fixed:
- Screen flashes on VT switch
- Cursor damage issues on the X11 and headless backends
Closes: https://github.com/swaywm/sway/issues/5086
References: https://github.com/swaywm/wlroots/pull/2059
cc @soreau @any1 @thejh @kchibisov 
* * *
Breaking change: `wlr_output.damage` is removed, listen to …
> output: replace wlr_output.damage with a damage event

- include/types/wlr_seat.h
- types/seat/wlr_seat.c
- types/seat/wlr_seat_keyboard.c
This is more correct according to the protocol and fixes issues with
clients that wait for an enter event before processing key events.
This can be tested by focusing alacritty, switching to a tty and back, then typing.  Without this commit, input is ignored as the client is waiting for an enter event.
Fixes https://github.com/swaywm/sway/issues/5085 (though it was closed as a duplicate already)
A second PR doing the same thing for pointers is in the works.
> Send keyboard enter/leave on capability change

- types/seat/wlr_seat_keyboard.c
This corrects an oversight made in 3f617631cb68c0e90a755b86f9c241caf0080f9a
> Properly popluate keys array for enter on creation

- include/types/wlr_seat.h
- types/seat/wlr_seat.c
- types/seat/wlr_seat_pointer.c
This is more correct according to the protocol and fixes issues with
clients that wait for an enter event before processing pointer events.
This can be tested by typing a url into alacritty, switching to a tty and back
with alacritty focused, then hovering over the link. Without this commit, the
pointer is ignored and no underline is shown.  With this commit the url is
underlined and clickable.
Fixes https://github.com/swaywm/sway/issues/3244
> Send pointer enter/leave on capability change

- backend/drm/drm.c
Because of the larger gamma table on Icelake platforms, there is a 32 bit overflow leading to the issue https://github.com/swaywm/sway/issues/4826
Closes https://github.com/swaywm/sway/issues/4826
> Fix uint32 overflow in fill_empty_gamma_table on Icelake platform

- backend/wayland/seat.c
We don't actually need the keymap. We need to close the FD or we will
run out of FDs.
References: https://github.com/swaywm/sway/issues/5115
> backend/wayland: close keymap FD

- types/wlr_surface.c
Fixes #2074 
This fixes an assertion failure if a client tries to do this, e.g. by
creating multiple toplevel objects for the same surface. If the same
role data is set multiple times, this does not cause an error, which is
how cursors use this interface.
> wlr_surface: Post error if multiple role objects created

- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- render/gles2/renderer.c
- render/wlr_renderer.c
This makes it easier for the user of this library to properly handle
failure of this function.
> Return failure of wlr_renderer_init_wl_display()

- include/wlr/types/wlr_keyboard.h
- types/wlr_keyboard.c
This allows users of the library to handle or ignore the error as they
see fit.
> Return false on wlr_keyboard_set_keymap() failure

- .builds/archlinux.yml
- backend/session/meson.build
- meson_options.txt
The logind provider defaulted to systemd and in order to use elogind,
-Dlogin-provider=elogind was required. This adds 'auto' as a choice
for the login-provider option and sets it as default. Using 'auto',
the build will check for systemd first and if it's not found, try
to find and use elogind automatically.
> build: Add 'auto' to logind-provider combo option

- examples/screencopy.c
If someone want to use screencopy as is processing multiple screenshots - it could be hard to find this issue with SHM. It's better to make sure it's creating just once - because the SHM file will not be removed from the shared memory until the application is terminated.
> Prevent memory leak in copypaste of the screencopy example

- backend/drm/drm.c
- backend/wayland/output.c
- include/wlr/types/wlr_buffer.h
- types/wlr_buffer.c
- types/wlr_output.c
- types/wlr_surface.c
~~Depends on https://github.com/swaywm/wlroots/pull/2043~~
This PR adds the required infrastructure to `wlr_buffer` to support swapchains. glider has been updated to use it: https://github.com/emersion/glider/pull/7.
Once this PR is merged, it will be possible to add DRM support to https://github.com/swaywm/wlroots/pull/1985 via libliftoff.
* * *
`wlr_buffer` now has a concept of "released", "producer" and "consumer". A buffer is created by a producer (the allocator or the client). It's then referenced by consumers (e.g. the backend or the compositor). Once all consumers are done with the buffer (ie. once they have un-referenced the buffer), the buffer is released and can be re-used (by the swapchain or the client).
This is inspired from glider's buffer: …
> Augment wlr_buffer to support swapchains

- backend/drm/drm.c
- backend/headless/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/backend/drm/drm.h
- include/backend/wayland.h
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- types/wlr_output.c
This PR adds `wlr_output_test`, which can be used to check whether pending output changes would be accepted by the backend. This allows compositors to try different changes before attempting a commit.
Right now this function just performs the check previously done in `attach_buffer` and `commit`. This change allows test-only commits to be run in `wlr_output_test`, which is necessary for using libliftoff (thus necessary for DRM support of output layers introduced in https://github.com/swaywm/wlroots/pull/1985).
Compositors implementing wlr-output-management can now call this function instead of returning true unconditionally.
Should `wlr_output_test` be implicitly called in `wlr_output_commit`? This would add a guarantee for backends that the output changes are valid when their `commit` …
> output: introduce wlr_output_test

- backend/drm/drm.c
- backend/headless/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
- types/wlr_output.c
Most of the pending output state is not forwarded to the backend prior
to an output commit. For instance, wlr_output_set_mode just stashes the
mode without calling any wlr_output_impl function.
wlr_output_impl.commit is responsible for applying the pending mode.
However, there are exceptions to this rule. The first one is
wlr_output_attach_render. It won't go away before renderer v6 is
complete, because it needs to set the current EGL surface.
The second one is wlr_output_attach_buffer.
wlr_output_impl.attach_buffer is removed in [1].
When wlr_output_rollback is called, all pending state is supposed to be
cleared. This works for all the state except the two exceptions
mentionned above. To fix this, introduce wlr_output_impl.rollback.
Right now, the backend resets the current EGL surface. …
> Reset EGL current surface after output commit/rollback

- render/gles2/renderer.c
- render/wlr_renderer.c
Only expose linux-dmabuf extension if EGL_EXT_image_dmabuf_import_ext is
supported.
Closes: https://github.com/swaywm/wlroots/issues/2076
> render: only expose linux-dmabuf if EGL extension is supported

- backend/drm/drm.c
- backend/wayland/output.c
- include/wlr/interfaces/wlr_output.h
- types/wlr_output.c
The scaling factor was being implicitly cast to an int.
Closes: https://github.com/swaywm/sway/issues/4927
* * *
Breaking change for backends: `wlr_output_impl.set_cursor` now takes a `float scale` instead of an `int32_t`.
> output: fix blurred hw cursors with fractional scaling

- backend/drm/drm.c
- backend/wayland/output.c
- types/wlr_output.c
Instead of checking for buffer size compatibility in each backend,
centralize the check in wlr_output itself.
If the buffer doesn't have a supported format/modifier, make the test
fail.
> output: misc. wlr_output_test fixes

- types/wlr_output.c
GCC is complaining about a maybe-uninitialized variable when doing a
release build. Even if that can't actually happen because all enum
values are handled, add an abort call to silence the warning.
> output: fix maybe-uninitialized warning

- types/seat/wlr_seat_keyboard.c
Check for a NULL keyboard_state.keyboard value in
seat_client_create_keyboard() before trying to use it, as is done in
other functions like seat_client_send_repeat_info(). Prevents a segfault
in certain situations on keyboard removal, as seen in the sway issue.
Closes: https://github.com/swaywm/sway/issues/5205
Closes: https://github.com/swaywm/wlroots/issues/2073
> Add check for NULL keyboard (fix sway #5205)

- backend/multi/backend.c
This allows wlr_multi_for_each_backend to iterate on the backends in the
order where they have been added.
> backend/multi: add backends at end of list

- backend/session/logind.c
This speeds up shutdown significantly, and is in line with how Weston
does it.
> logind: Close fd before releasing device

- backend/libinput/tablet_tool.c
Otherwise, the cursor will briefly jump to (0, 0). This is particularly
noticeable in the referenced issue (the game osu!).
Refs swaywm/sway#3633
> backend/libinput: correctly populate x/y fields on tablet proximity in

- meson.build
When built as a subproject, this removes the need for the parent project
to know about the dependency variable name.
This requires Meson 0.54.0.
> build: use meson.override_dependency

- render/drm_format_set.c
It doesn't make sense to add DRM_FORMAT_INVALID to a format set. Adding
an assertion allows us to safely query the format set with
DRM_FORMAT_INVALID. See [1].
[1]: https://github.com/swaywm/wlroots/pull/2021#discussion_r385839668
> render/drm_format_set: disallow DRM_FORMAT_INVALID

- backend/headless/backend.c
- backend/headless/output.c
- include/backend/headless.h
- include/render/gles2.h
- include/wlr/backend/headless.h
- include/wlr/render/gles2.h
- render/gles2/renderer.c
Allows the headless backend to use another backend's renderer.
> backend/headless: use FBOs instead of pbuffers

- backend/libinput/tablet_tool.c
This commit doesn't fix any issue that I'm aware of, since sway
incidentally does not use these fields. Still, they exist, so they
should probably be filled in to prevent fun surprises in the future.
> input/tablet: populate tool tip event position

- types/wlr_export_dmabuf_v1.c
A client requesting frames in the ready callback may miss frames that
happen while it is waiting to receive the event or sending the request.
If that happens, the client will have an outdated frame for an
indefinite period. A new frame might not be scheduled for a very long
time.
With this change, clients will receive new frames immediately upon
request.
> export-dmabuf: Schedule output frame on request

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- backend/drm/renderer.c
- backend/drm/util.c
- include/backend/drm/drm.h
- include/backend/drm/iface.h
- include/backend/drm/renderer.h
- include/backend/drm/util.h
Same as https://github.com/swaywm/wlroots/pull/2021 but rebased, review comments addressed and:
- "backend/drm: Don't allow legacy to use direct scanout" has been dropped
- FB state fields have been reworked: the pending FB is empty if no new buffer has been submitted by the compositor
My changes are in the last commit. I'll integrate them into previous commits before merging.
> backend/drm: introduce wlr_drm_fb

- tinywl/tinywl.c
Previously, when dragging the left border of a window with the mouse in tinywl,
there was a bug where it snap the top level surface's geometry X coordinate
directly to the position of the mouse, as if you started the resize right on the
border. This also affected the other (right, top and bottom) borders.
I think that the previous resize code was hard to understand. Honestly I
have not spent a lot of time trying to understand why it didn't work and
I wrote another resize algorithm instead. I hope this is fine. Now, instead of working directly with widths and heights which are complicated, we work with the borders (left,
right, top, bottom). This is easier to understand IMO.
Note: I originally fixed this [in the waybox compositor](https://github.com/wizbright/waybox/pull/23) but
then I …
> tinywl: Fix window resize slightly off

- include/render/gles2.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_texture.h
- render/gles2/texture.c
- render/wlr_texture.c
See individual commits.
* * *
Breaking changes for renderers:
* `wlr_texture_init` now takes the size of the texture
* `wlr_texture_impl.get_size` has been removed
> Texture improvements

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- README.md
- backend/session/direct-ipc.c
- backend/session/meson.build
- meson.build
- meson_options.txt
This is simply a false sense of security, and is worse than just using
setuid. CAP_SYS_ADMIN is an extremely serious capability that is
effectively as powerful as root.
It also required users to be in the input group, which allows any
process to keylog the entire system.
> Remove libcap support

- backend/drm/drm.c
Reconnecting an external display fails on initial
page-flip.  This occurs when the pageflip_pending flag
has been set on the connector at the time the monitor
is removed.  Once the connector's CRTC has been deallocated,
page_flip_handler cannot find the connector by its crtc_id,
so pageflip_pending will remain set.  This causes
initialization to fail when the monitor is reconnected
with the error messages:
Skipping pageflip on output 'X'
Failed to initialize renderer on connector 'X': initial page-flip failed
To fix this problem, clear the pageflip_pending flag
when cleaning up the connector.
Test plan:
1. Start sway (I tested with https://github.com/swaywm/sway/commit/59acc12b32736dc3f7b8b7060c165c2b49359f15 and https://github.com/swaywm/wlroots/commit/22d345d98200b421abf91b4b2700b101bdca …
> Fix error when reconnecting external display

- util/log.c
When colors aren't used, write the log importance to stderr. This makes
it easier to grep for errors and avoids mistaking error messages for
debug messages.
> util/log: write log importance

- backend/drm/drm.c
The logs don't currently display the importance of a line. It's easy to
read "skipping page-flip" as a debug message instead of an error
message.
Change the error message to make it more explicit.
References: https://github.com/swaywm/wlroots/pull/2147
> backend/drm: make page-flip error scarier

- include/wlr/types/wlr_seat.h
- types/seat/wlr_seat_touch.c
This is needed to simulate pointer events when a surface hasn't bound to touch events.
> Add wlr_surface_accepts_touch

- backend/wayland/tablet_v2.c
This doesn't fix any issue, but is (I'm pretty sure) wrong. The Wayland backend in general doesn't seem to process tablet tool events correctly; what's sent (as per `WAYLAND_DEBUG`) seems reasonable, but nested sway doesn't seem to receive/process the events correctly.
Minor trailing-whitespace-stripping cleanup included, I can remove it if desired.
> backend/wayland: emit tablet tool axis events to the axis handler

- include/wlr/types/wlr_keyboard.h
- types/wlr_keyboard.c
- types/wlr_keyboard_group.c
sway needs this logic too, and currently ships a version that has fallen
behind in terms of bugfixes (b1a63bc). It might be reasonable for
wlroots to expose this functionality instead.
> input/keyboard: expose keymap matching helper

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
- include/backend/drm/iface.h
This PR starts re-working the DRM backend interface to apply all pending state in `crtc_pageflip`, instead of having one function per property.
A new bitfield `wlr_drm_crtc.pending` is introduced and contains the set of modified properties.
This PR doesn't touch the common logic in `drm.c`. Some refactoring will be done after this PR is merged.
> backend/drm: replace all interface setters with a unified commit

- backend/drm/atomic.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/iface.h
- include/backend/drm/properties.h
GAMMA_LUT_SIZE isn't an atomic property. It can be used with the legacy
interface too. So we can unify both codepaths and remove
wlr_drm_interface.crtc_get_gamma_size.
It's no guaranteed to exist though, so we still need to keep the
fallback.
> backend/drm: GAMMA_LUT_SIZE isn't atomic

- backend/drm/atomic.c
- backend/drm/drm.c
- include/backend/drm/drm.h
We don't need a per-CRTC atomic request anymore. Let's make the request
per-commit so that it's easier to debug.
This is also groundwork for supporting wlr_output_test properly.
> backend/drm: simplify atomic commit logic

- backend/drm/backend.c
conn->crtc is NULL in case the output is disabled.
However, the DRM backend will set the GAMMA_LUT property anyway. On each
commit the whole state is sent to KMS. Adding WLR_DRM_CRTC_GAMMA_LUT to
the pending state would just make the backend re-create the blob
containing the gamma LUT.
> backend/drm: fix crash in session_signal

- include/wlr/config.h.in
- include/wlr/render/egl.h
- meson.build
This pull request makes the EGL/eglmesaext.h header included only if present. The EGL_WL_bind_wayland_display is now standard, and some EGL/GLES drivers are providing it without the eglmesaext.h file.
Those patches were tested in Buildroot, compiled with imx-gpu-viv gpu driver, on an i.MX8M Mini EVK board (case without eglmesaext.h).
They were also tested against a Mesa 20.0.6 (case with eglmesaext.h).
> Make EGL/eglmesaext.h header inclusion optional, only if present. Makes wlroots compile on any egl/gles driver.

- backend/drm/drm.c
We have a workaround for legacy drivers that support drmModeSetCursor
without exposing a cursor plane. It doesn't work anymore now that we've
moved to a more atomic interface.
Let's just remove this workaround and fallback to software cursors.
Closes: https://github.com/swaywm/wlroots/issues/2166
> backend/drm: remove missing cursor plane workaround

- backend/drm/drm.c
When an output is enabled and modeset at the same time,
drm_connector_commit would first try to modeset then try to commit. This
won't work because both will trigger a page-flip. KMS will reject that.
Change the logic to only enable an output if no modeset has been
requested. The logic in wlr_output already checks that the user isn't
doing a modeset and disabling the output at the same time.
> backend/drm: fix combined modeset+enable commits

- backend/drm/atomic.c
- backend/drm/drm.c
dealloc_crtc was destroying GBM surfaces, but the cursor_enabled flag
was left as-is. When re-enabling the output, atomic_crtc_pageflip would
try enabling the cursor plane, but would fail because no framebuffer is
available.
Closes: https://github.com/swaywm/wlroots/issues/2150
> backend/drm: disable cursor in dealloc_crtc

- include/wlr/types/wlr_pointer_constraints_v1.h
- types/wlr_pointer_constraints_v1.c
This allows a compositor to know when warping back into the region is
appropriate.
Refs swaywm/sway#5268.
> input/pointer: notify compositor when constraint region changes

- backend/drm/drm.c
When no cursor plane is available, drm_crtc_page_flip would segfault.
> backend/drm: fix segfault in drm_crtc_page_flip

- backend/drm/atomic.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
- include/backend/drm/iface.h
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- types/wlr_gamma_control_v1.c
- types/wlr_output.c
wlr_output_set_gamma is now double-buffered and applies the gamma LUT on
the next output commit.
* * *
* `wlr_output_set_gamma` is now double-buffered and applied on the next output commit
* `wlr_output_impl.set_gamma` is gone. Backends now need to read the pending output state on commit instead.
> output: make wlr_output_set_gamma atomic

- backend/drm/atomic.c
We already have the logic to fallback to the legacy interface above. We
just need to avoid calling atomic_add with a zero prop ID.
Closes: https://github.com/swaywm/wlroots/issues/2187
Closes: https://github.com/swaywm/wlroots/issues/2193
> backend/drm: fix atomic commits when the GAMMA_LUT prop is missing

- include/wlr/types/wlr_xcursor_manager.h
- types/wlr_xcursor_manager.c
This is currently inconsistent with the rest of the library and a bit of
a footgun for new compositors. However, this breaks the API in a very
unfortunate way for existing compositors.
* * *
Breaking change: `wlr_xcursor_manager_load` now returns a bool, making it consistent with other wlroots functions. Compositors that check the return value need to invert their check.
> Make wlr_xcursor_manager_load() return a bool

- backend/libinput/tablet_tool.c
- backend/wayland/tablet_v2.c
- types/tablet_v2/wlr_tablet_v2_tool.c
- types/xdg_shell/wlr_xdg_positioner.c
When calling assert(0) instead of returning a value, -Wreturn-type
warnings are triggered because assertions can be disabled. Replace these
assertions with abort().
> Fix -Wreturn-type warnings

- backend/drm/drm.c
- backend/headless/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/render/egl.h
- render/egl.c
- render/gles2/renderer.c
- render/gles2/texture.c
This function can be called after wlr_egl_make_current to cleanup the
EGL context. This avoids having lingering EGL contexts that make things
work by chance.
Closes: https://github.com/swaywm/wlroots/issues/2197
> render/egl: introduce wlr_egl_unset_current

- backend/drm/drm.c
- backend/drm/renderer.c
get_tex_for_bo changes the current EGL context. Rendering operations
must immediately follow drm_surface_make_current.
Closes: https://github.com/swaywm/wlroots/issues/2209
> backend/drm: EGL context fixes for multi-GPU

- include/wlr/xwayland.h
- include/xwayland/xwm.h
- xwayland/meson.build
- xwayland/server.c
- xwayland/xwayland.c
- xwayland/xwm.c
Split the server part of wlr_xwayland into wlr_xwayland_server. This
allows compositors to implement their own XWM when wlroots' isn't a good
fit.
~~Sway PR: https://github.com/swaywm/sway/pull/5314~~ A Sway PR isn't necessary for this change.
* * *
Breaking change: `wlr_xwayland.display_name` is now a `const char *` field. Most compositors should still be able to use it like before. Server-specific fields have been moved from `wlr_xwayland` to `wlr_xwayland_server`.
> xwayland: split server

- backend/drm/drm.c
- backend/drm/renderer.c
- backend/wayland/output.c
- backend/x11/output.c
- render/egl.c
After swapping buffers, it doesn't make sense to perform more rendering
operations. Unset the context to reflect this.
This commit makes it so the context is always only current between
wlr_egl_make_current and wlr_egl_swap_buffers.
This is an alternative to [1].
[1]: https://github.com/swaywm/wlroots/pull/2212
Closes: #2209
* * *
This is ready for review, ~~but let's wait for user feedback before merging it, in case I missed something again~~.
> render/egl: unset current context after swapping buffers

- util/log.c
On some terminals under default settings, black is truly rendered as
`#000`, making it unreadable when the background is also black.
Refs swaywm/sway#5141.
> util/log: use bright black rather than black for WLR_DEBUG

- xwayland/xwm.c
This fixes issues with (at least) dialogs in Jetbrains IDEs becoming
unclickable if they ever lost focus (ref. swaywm/sway#5373). Prior to
this change, since `xwm->focus_surface` would be set prior to
`xwm_surface_activate` being called, the latter would short-circuit
immediately and not notify the application of the focus change.
> xwayland: send focus change event unconditionally

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
See individual commits. Overall this brings us closer to being able to expose test-only atomic commits.
> backend/drm: refactor modesetting

- include/wlr/types/wlr_seat.h
- types/seat/wlr_seat.c
- types/seat/wlr_seat_keyboard.c
- types/seat/wlr_seat_pointer.c
- types/seat/wlr_seat_touch.c
We should throw a protocol error if the relevant capability has never
existed when get_(pointer|keyboard|touch) is called. Otherwise, it
should succeed, even if the capability is not currently present.
This follows the spec, and avoids possible races with the client when
capabilities are lost.
Closes: https://github.com/swaywm/wlroots/issues/2227
> seat: Create inert objects for missing capabilities

- backend/wayland/tablet_v2.c
- types/tablet_v2/wlr_tablet_v2_tool.c
And stop using default cases, so that we know which parts of the code
need an update when adding a new enum entry.
Closes: https://github.com/swaywm/wlroots/issues/2208
> Add comments for missing tablet tool entries

- types/seat/wlr_seat.c
As discussed on IRC, we don't need to send capability updates to clients if the capabilities haven't changed (i.e. a redundant mouse was removed). Ultra simple PR, just checks if the capability has changed, and returns otherwise. LMK if I missed/forgot/misunderstood something.
> Don't send redundant capability updates

- include/types/wlr_keyboard.h
- include/wlr/types/wlr_keyboard_group.h
- types/wlr_keyboard.c
- types/wlr_keyboard_group.c
Related swaywm/sway#4975
Sway PR: swaywm/sway#5393
This introduces the enter and leave events for wlr_keyboard_group.
The enter event is emitted when a keyboard is added to the group while a
key is pressed that is not pressed by any other keyboard in the group.
The data is a wl_array of the pressed key codes unique to the keyboard
that should now be considered pressed.
Similarly the leave event is emitted when a keyboard is removed from the
group while at least one key is pressed that is not pressed by any other
keyboard in the group. The data is a wl_array of the pressed key codes
unique to the keyboard that should now be considered released.
The purpose of these events are to allow the compositor to update its
state to avoid corruption. Additionally, for the leave event, the
focused …
> wlr_keyboard_group: introduce enter and leave

- types/wlr_export_dmabuf_v1.c
This fixes a crash that happens when a client requests a frame on a
backend that does not implement export_dmabuf.
An assertion fails with the message:
sway: types/wlr_output.c:777: wlr_output_lock_attach_render: Assertion
`output->attach_render_locks > 0' failed.
> export-dmabuf: Keep frame->output = NULL until frame is ready

- backend/drm/atomic.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
This PR:
- Makes adaptive sync atomic
- Performs a blocking atomic commit if no modeset or buffer is pending
The second point fixes output state updates not applied when no modeset or page-flip is performed. For instance, `wlr_output_set_gamma` followed by `wlr_output_commit` was a no-op (but shouldn't be).
No Sway PR required, since `wlr_output_enable_adaptive_sync` is already followed by `wlr_output_commit`.
Closes: https://github.com/swaywm/wlroots/issues/2096
* * *
Breaking change: `wlr_output_enable_adaptive_sync` must now be followed by `wlr_output_commit` to apply the change.
> backend/drm: atomic improvements

- backend/wayland/output.c
This was introduced in [1]. However after reverting that PR I still
can't reproduce the bug the PR aimed to fix [2].
Since there's no good explanation why we would need to swap buffers
before resizing, let's just revert the PR.
[1]: https://github.com/swaywm/wlroots/pull/1486
[2]: https://github.com/swaywm/wlroots/issues/1371
Closes: https://github.com/swaywm/wlroots/issues/1768
> backend/wayland: fix spurious eglSwapBuffers failures

- render/egl.c
- render/gles2/renderer.c
This leaves an EGL context current behind. wlr_gles2_renderer_create was
assuming the EGL context was already current because of this (because it
called a GL function right off the bat).
> render: stop making EGL context current in wlr_egl_init

- backend/drm/drm.c
This patch fixes this failure:
01:57:16.642 [ERROR] [backend/drm/drm.c:360] Failed to page-flip output 'eDP-1': a page-flip is already pending
01:57:16.684 [ERROR] [backend/drm/drm.c:360] Failed to page-flip output 'eDP-1': a page-flip is already pending
01:57:16.684 [ERROR] [backend/drm/drm.c:732] Failed to initialize renderer on connector 'eDP-1': initial page-flip failed
01:57:16.684 [ERROR] [backend/drm/drm.c:805] Failed to initialize renderer for plane
01:57:16.684 [sway/config/output.c:423] Failed to commit output eDP-1
References: https://github.com/swaywm/sway/issues/5101
> backend/drm: fix black screens when enabling output

- include/wlr/types/wlr_seat.h
- types/data_device/wlr_drag.c
- types/seat/wlr_seat_keyboard.c
- types/seat/wlr_seat_pointer.c
- types/xdg_shell/wlr_xdg_popup.c
- types/xdg_shell_v6/wlr_xdg_popup_v6.c
This is necessary for some grabs, which currently have no way of knowing when the pointer/keyboard focus has left a surface. For example, without this, a drag-and-drop grab can erroneously drop into a window that the cursor is no longer over.
This is the plumbing needed to properly fix swaywm/sway#5220. The existing fix, swaywm/sway#5222, relies on every grab's `enter()` hook allowing a `NULL` surface. This is not guaranteed by the API and, in fact, is not the case for the xdg-shell popup grab and results in a crash when the cursor leaves a surface and does not immediately enter another one while a popup is open (#2161).
This fix also adds an assertion to wlr_seat_pointer_notify_enter() that ensures it's never called with a `NULL` surface. This will make Sway crash much more until it …
> Allow keyboard and pointer grabs to hook clear_focus()

- include/wlr/render/egl.h
- render/egl.c
- render/gles2/texture.c
EGL_EXT_image_dma_buf_import_modifiers tells us whether we should use
GL_TEXTURE_2D or GL_TEXTURE_EXTERNAL_OES. Using the right texture target
can fix some failures and/or improve performance on some drivers.
This does the same as a Weston commit [1].
[1]: https://gitlab.freedesktop.org/wayland/weston/commit/40c519a3e613
Closes: https://github.com/swaywm/wlroots/issues/2173
> render: choose DMA-BUF texture target via eglQueryDmaBufModifiersEXT

- backend/drm/drm.c
Call drm_crtc_commit directly instead of calling drm_connector_set_mode.
This restores the previous behaviour where conn_enable was called [1].
[1]: https://github.com/swaywm/wlroots/blob/0c7c562482575cacaecadcd7913ef25aeb21711f/backend/drm/drm.c#L1093
Closes: https://github.com/swaywm/wlroots/issues/2253
> backend/drm: fix stack overflow in dealloc_crtc

- include/wlr/types/wlr_buffer.h
- include/wlr/types/wlr_output.h
`wlr_buffer_get_dmabuf`'s behaviour avoids exporting the buffer as a DMA-BUF over and over each time we want to import it (e.g. to KMS or EGL).
cc @any1
> Improve DMA-BUF lifetime docs

- examples/screencopy-dmabuf.c
The original code wasn't wrong since we were manually writing a null
byte anyway, but this makes GCC happy.
Closes: https://github.com/swaywm/wlroots/issues/2273
> examples/screencopy-dmabuf: call strncpy with maxlen - 1

- examples/fullscreen-shell.c
Remove the wlr_linux_dmabuf_v1_create call. wlr_renderer_init_wl_display
will take care of creating the linux-dmabuf global if the OpenGL
implementation supports it.
> examples/fullscreen-shell: stop advertising linux-dmabuf unconditonally

- render/wlr_renderer.c
Width and height should always be > 0 for render functions which take a
wlr_box.
References https://github.com/swaywm/wlroots/issues/2281
> render: assert sane values for box functions

- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- include/wlr/types/wlr_box.h
- include/wlr/types/wlr_surface.h
- include/wlr/types/wlr_viewporter.h
- include/wlr/util/region.h
- protocol/meson.build
- render/gles2/renderer.c
- render/gles2/shaders.c
- render/wlr_renderer.c
- types/meson.build
- types/wlr_surface.c
- types/wlr_viewporter.c
- util/region.c
The [viewporter protocol](https://gitlab.freedesktop.org/wayland/wayland-protocols/blob/master/stable/viewporter/viewporter.xml) allows clients to ask the compositor to crop and scale buffers during composition. This allows clients to avoid having to crop and scale in an intermediary buffer. The use-cases are:
- Xwayland games that expect to be able to perform modeset
- Video players that present DMA-BUFs coming out of VA-API
- Optimized scrolling in web browsers
TODO:
Test plan:
Future plans: wire this up with direct scan-out. With my [wlr_output_layer proposal](https://github.com/swaywm/wlroots/pull/1985), I think we can extend [the API](https://github.com/swaywm/wlroots/pull/1985/files#diff-bc323577ae8471cb9563146f750574a7) to allow compositors to feed src/dst rectangles to the …
> Implement the viewporter protocol

- types/seat/wlr_seat_keyboard.c
Will fix Firefox bug https://bugzilla.mozilla.org/show_bug.cgi?id=1643991.
Fixes swaywm/sway#5462.
> input/keyboard: send modifiers on first keyboard enter

- types/wlr_surface.c
During surface finalization we may not have received a new buffer,
resetting width and height in this case is wrong since we display the
old buffer in this case.
> surface: don't unset width and height in finalize

- types/wlr_surface.c
According to the viewporter protocol:
> If the wl_buffer is NULL, the surface has no content and therefore no size.
> surface: ignore viewport src rect on NULL buffer

- render/egl.c
> render/egl: print error name

- backend/drm/drm.c
- backend/headless/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
- types/wlr_output.c
The output backend API is now mostly state-less thanks to the atomic
hooks (commit and test). There is one exception though: attach_render.
This function makes the rendering context current. However sometimes the
compositor might decide not to render after attach_render (e.g. when
there's nothing new to render to the back buffer). Thus
wlr_output_rollback has been introduced to revert the pending state.
Because the output backend API is mostly state-less, the only thing
wlr_output_impl.rollback needs to do is revert the current rendering
context. Rename the function to rollback_render to make this clear. Add
a check in the common wlr_output code to only call rollback_render when
attach_buffer has been previously called.
On the long term, we'll be able to remove attach_render and …
> output: fix dangling renderer context after wlr_output_preferred_read_format

- backend/noop/output.c
3c5dbfd97c77 ("output: make rollback_render mandatory") makes a no-op
output init fail without this function.
> backend/noop: add missing rollback_render output impl

- examples/pointer.c
Calling wlr_renderer_end after wlr_output_commit would make an
assertion fail.
> examples/pointer: fix wlr_renderer_end call order

- include/render/gles2.h
- render/gles2/renderer.c
> render/gles2: use glGetAttribLocation instead of hardcoded indices

- types/wlr_layer_shell_v1.c
- types/wlr_xdg_decoration_v1.c
- types/xdg_shell/wlr_xdg_surface.c
- types/xdg_shell_v6/wlr_xdg_surface_v6.c
- Wrapping overflow of the display serial is currently not accounted for in the handling of layer-shell and xdg-shell configure handling.
- Old xdg-decoration configure structs are not currently destroyed on acking a newer configure.
> Improve robustness of configure serial handling

- xcursor/xcursor.c
This should match default XCURSORPATH, which is used by libwayland-cursor
and other xcursor loading libraries more closely.
> xcursor: add xorg-x11 and cursors path to XCURSORPATH

- types/data_device/wlr_drag.c
wlr_drag sets up keyboard, pointer and touch grabs, which block 'enter'
events (and thus focus changes). For the compositor to be able to update
focus (e.g. to focus the drop target) from the destroy handler, the
grabs must be released before the destroy event is signalled.
> wlr_drag: Destroy drag after releasing grabs

- include/wlr/interfaces/wlr_output.h
Depends on https://github.com/swaywm/wlroots/pull/2292
> output: add backend docs

- xwayland/server.c
- xwayland/xwayland.c
- xwayland/xwm.c
This fixes two problems on Xwayland restart:
- The xwayland ready signal now fires on restart
- xwm is destroyed instead of leaked
The latter caused compositors to consume all cpu once Xwayland was restarted.
Closes: https://github.com/swaywm/wlroots/issues/2174
> Fix Xwayland restart

- backend/drm/legacy.c
This mirrors what the atomic code does in create_mode_blob.
Closes: https://github.com/swaywm/wlroots/issues/2312
> backend/drm: fix DPMS on legacy interface

- include/xwayland/selection.h
- xwayland/selection/outgoing.c
- xwayland/xwm.c
This improves the failure cases when incremental transfers fail to complete successfully for one reason or another. In particular it should vastly improve the failure case seen at https://github.com/swaywm/sway/issues/4007, especially because QXcb uses a special temporary window for its requestor, that gets always destroyed in the case that the error happens.
> xwm: end transfers when the requestor is destroyed

- examples/idle.c
> examples: fix improper use of `free`

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
This was rendered useless in 5cde359.
> layer-shell: remove unused surface list

- backend/drm/drm.c
drm_connector_set_cursor wasn't checking the return value of the
drm_surface_make_current call. On failure, this results in a failed
assertion in wlr_renderer_begin (because no rendering context is
current).
> backend/drm: check drm_surface_make_current return value

- examples/input-method-keyboard-grab.c
- examples/meson.build
- include/wlr/types/wlr_input_method_v2.h
- include/wlr/types/wlr_virtual_keyboard_v1.h
- types/wlr_input_method_v2.c
- types/wlr_virtual_keyboard_v1.c
I'm interested in implementing CJK input method in wayland so I try to implement this.
I've tested with my local client code but it's not suitable for a test example.
Should I extend examples/input-method.c for this or write a new one
> Implement input-method keyboard grab

- render/egl.c
eglGetCurrentDisplay() returns NULL when there is no context current and
eglMakeCurrent() needs a display argument.
Fixes #2327
> render: egl: Use current display to restore NULL context

- xwayland/xwm.c
In case wl_event_loop_add_timer errors out, don't insert the free'd
wlr_xwayland_surface in the list.
Closes: https://github.com/swaywm/wlroots/issues/1721
> xwayland/xwm: don't insert surface in list on error

- types/wlr_virtual_pointer_v1.c
Got it! Fixes swaywm/sway#5578.
What looks like a typo in `virtual_pointer_axis` was causing AXIS_HORIZONTAL events to indicate the pointer had two valid events, but it was actually just overwriting the first event leaving the horizontal event blank and crashing sway.
> virtual_pointer: remember current axis for axis events

- backend/drm/drm.c
- backend/session/logind.c
- backend/wayland/backend.c
- types/seat/wlr_seat_keyboard.c
- types/wlr_compositor.c
- types/wlr_layer_shell_v1.c
- types/wlr_linux_dmabuf_v1.c
- types/wlr_surface.c
- types/wlr_virtual_pointer_v1.c
- xcursor/wlr_xcursor.c
- xwayland/selection/dnd.c
- xwayland/selection/outgoing.c
- xwayland/xwayland.c
- xwayland/xwm.c
Hi!
This is a collection of small patches fixing some warnings reported by PVS-Studio.
Happy to change things if I got the "bug fix" wrong.
I’m not so sure about my fix for 7d1d619 "types/wlr_output: fix pointer to stack variable escaping scope".
> Patches to address static analysis warnings

- include/render/gles2.h
- include/wlr/render/gles2.h
- render/gles2/renderer.c
- render/gles2/texture.c
* * *
Breaking change: the `wlr_gles2_texture_from_*` family of functions are no longer public API.
> render/gles2: remove gles2_procs global

- include/xwayland/xwm.h
- xwayland/xwm.c
Resend of #2339 , as @emersion suggested we simply deny requests that are too old. For requests after the latest focus change of wlroots, we allow changing focus between surfaces of the same application, as before.
> xwayland: do not allow apps to change focus after wlroots request

- backend/drm/drm.c
get_drm_prop_blob does not set path_len if it returns NULL.  Check the
return value before path_len to avoid reading uninitialized memory.
(Granted, this doesn't change the logic at all, but it does make
Valgrind a bit happier.)
> drm: fix uninitialized read

- types/wlr_gamma_control_v1.c
gamma_control_send_failed destroys gamma_control.
> gamma-control-v1: fix use-after-free in gamma_control_handle_set_gamma

- backend/session/logind.c
Sets systemd-logind session type to `wayland` so that systemd recognises a graphical session is running. Needed for logind idle inhibition to work. Relies on the logind session `SetType` command which is not yet released (in systemd master, tagged for v246).
Relevant systemd PR here - https://github.com/systemd/systemd/pull/14925
Will close #2144.
> Implement logind session SetType method to change session type to wayland

- types/wlr_virtual_keyboard_v1.c
virtual_keyboard_keymap needs to close the fd it is given
> wlr_virtual_keyboard: fix fd leak

- backend/wayland/seat.c
Fixes #2243
Fixes #2106
The two issues almost seem like duplicates to me.
> wayland: destroy relative pointer when output is disconnected

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- backend/session/direct.c
- backend/session/libseat.c
- backend/session/logind.c
- backend/session/meson.build
- backend/session/noop.c
- backend/session/session.c
- include/backend/session/session.h
- include/wlr/config.h.in
- meson.build
- meson_options.txt
[libseat](https://sr.ht/~kennylevinsen/seatd) provides logind, [seatd](https://sr.ht/~kennylevinsen/seatd) and embedded seatd ("direct"-style) seat management backends.
This WIP PR merely adds libseat as an additional backend to aid libseat/seatd testing, while the true end-goal is to remove the pluggable session infrastructure entirely, offloading that to libseat.
> libseat session backend

- backend/wayland/backend.c
- examples/dmabuf-capture.c
- examples/foreign-toplevel.c
- examples/gamma-control.c
- examples/idle-inhibit.c
- examples/idle.c
- examples/input-inhibitor.c
- examples/input-method-keyboard-grab.c
- examples/input-method.c
- examples/keyboard-shortcuts-inhibit.c
- examples/output-power-management.c
- examples/pointer-constraints.c
- examples/relative-pointer-unstable-v1.c
- examples/screencopy-dmabuf.c
- examples/screencopy.c
- examples/text-input.c
- examples/toplevel-decoration.c
- examples/virtual-pointer.c
wl_display_roundtrip already takes care of dispatching the display.
> Remove unnecessary wl_display_dispatch calls

- backend/session/direct-freebsd.c
bad1e9afa8ea ("session: Add libseat backend") introduced a change to to
how session backends initialize, but failed to update the FreeBSD
specific version of the direct backend accordingly.
Closes: https://github.com/swaywm/wlroots/issues/2376
> session: Add missing init to direct-freebsd

- include/wlr/types/wlr_xdg_shell.h
- include/wlr/types/wlr_xdg_shell_v6.h
- types/xdg_shell/wlr_xdg_toplevel.c
- types/xdg_shell_v6/wlr_xdg_toplevel_v6.c
These states are distinct in the time period between the ack_configure
and the next commit on the surface. Splitting these states avoids the
following race for example:
- client starts at 1000x1000
- wlr_xdg_toplevel_set_size 500x500
- size is different -> configure sent
- client acks the configure
- wlr_xdg_toplevel_set_size 1000x1000
- compare_xdg_toplevel_state returns true since there is no pending
configure and the currently committed size is still 1000x1000
- no new configure is sent
- client commits at the size it last acked, 500x500
For reference, this is the cause of https://github.com/ifreund/river/issues/31
Closes #762
> xdg-shell: split last-acked and current state

- render/wlr_renderer.c
Don't force compositors to check when an empty shape is being renderered.
References #2282. This was motivated by dwl crashing when setting window
borders to 0 (djpohly/dwl#51).
> render: Don't crash on 0 dimensions

- include/wlr/types/wlr_output.h
- include/wlr/types/wlr_output_power_management_v1.h
- types/wlr_output.c
- types/wlr_output_power_management_v1.c
This event contains a `committed` bitfield, which allows callers to know
which output fields changed during the commit.
This allows users to setup a single atomic commit listener, instead of
setting up one listener for each event (mode, scale, transform, and so
on).
References: https://github.com/swaywm/wlroots/issues/2098
* * *
Breaking change: the `wlr_output.events.commit` event now has a data argument of type `struct wlr_output_event_commit *` instead of `struct wlr_output *`
> Introduce wlr_output_event_commit

- examples/dmabuf-capture.c
This example was relying on wl_display_dispatch being enough to fetch
output information. This worked by chance.
Add an explicit wl_display_roundtrip.
Other examples don't setup wl_output listeners, so they should be fine.
Fixes: 297354f84772 ("Remove unnecessary wl_display_dispatch calls")
Closes: https://github.com/swaywm/wlroots/issues/2386
> examples/dmabuf-capture: add extra roundtrip for wl_output listener

- include/xcursor/xcursor.h
- xcursor/xcursor.c
Copied from the two commit messages:
Use fixed size integer type
This type is meant to be 4 bytes large as seen in _XcursorReadUInt which
always reads 4 bytes. An unsigned int is often 4 bytes large but this
isnt' guaranteed so it is cleaner to use the exact type we want.
Fix undefined behavior
Without the casts the bytes accesses get converted to int. but int is
not guaranteed to be 4 bytes large. Even when it is 4 bytes large
`bytes[3] << 24` does not fit because int is signed.
> Fix undefined behavior in xcursor

- backend/session/libseat.c
- backend/session/meson.build
Route libseat errors through wlroots logging infrastructure.
> backend/session/libseat: register log handler

- backend/session/logind.c
(almost certainly due to systemd version <246)
This will move a log regarding a failure to set the logind session type to `wayland` down to debug level. It will always fail on systemd <246, and (hopefully never) on systemd >246. 
I've left the `XDG_SESSION_TYPE` as an error, as failure to set an environment variable seems like a error to me, and apparently not setting this breaks Zoom at least. I've also made the whole function return void as there seems to be no reason to check this error as we can do nothing about it and it's not fatal. 
Fixes https://github.com/swaywm/sway/issues/5655
> Quieten failure to set login session type

- backend/session/direct-ipc.c
When starting a compositor that's using the "direct" session backend,
wlroots needs to handle calls to `drmSetMaster()` and `drmDropMaster()`.
As both calls used to require `CAP_SYS_ADMIN`, wlroots thus simply
refused starting in case the process doesn't enjoy evelated privileges.
Permission rules have changed since linux.git commit 45bc3d26c95a (drm:
rework SET_MASTER and DROP_MASTER perm handling, 2020-03-19). As a
result, starting with Linux v5.8, both ioctls will now also succeed if
the process is currently or has been the DRM master. And as the first
process to open render nodes will become the DRM master automatically,
this effectively means that process elevation is not strictly required
in all setups anymore.
So let's drop the `geteuid() != 0` permission check to allow those new …
> session: Don't refuse unprivileged creation of "direct" backend

- backend/session/logind.c
This has not been tested on a kernel that has been compiled with CONFIG_VT=0, but it has been tested on one with CONFIG_VT=1
> Accommodate for CONFIG_VT=0, all TTYs are in seat0, but not all seat0s have TTYs

- xwayland/server.c
I got this shutdown crash where Xwayland isn't deinitialized properly. I think the problem might be that Xwayland itself crashes after shutdown has started but fails to restart (since we're already tearing things down).
Anyway, it can be seen that this is a problem: https://github.com/swaywm/wlroots/blob/master/xwayland/server.c#L250
The listener is added, then display sockets are opened, if that fails, `server_finish_display` is called but it is a no-op because of the check in the beginning.
> xwayland: disconnect display destroy listener even if xwayland didn't initialize

- protocol/wlr-output-management-unstable-v1.xml
- types/wlr_output_management_v1.c
Add events to zwlr_output_head_v1 for make, model and serial number of a display. This allows clients to identify displays from previous compositor sessions and reload accordingly configurations that were saved previously.
I have an example implementation with:
* Generic Wayland client library: https://gitlab.com/kwinft/wrapland/-/merge_requests/75
* Output management client library: https://gitlab.com/kwinft/disman/-/merge_requests/9
* KDisplay client: https://gitlab.com/kwinft/kdisplay/-/merge_requests/6
The form in which the client combines this information to recognize the display again is unspecified and depends on how permissive it is.
For example in case of Disman I use a string `<make>:<model>:<serial_number>:<name>` which I then MD5-hash and hex convert for the name of the output …
> output-management-v1: add head identifying information

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
This brings the layer-shell api in line with that of xdg-shell and
avoids reimplementing this function in every compositor in order to
render layer shell popups correctly.
> layer-shell: add for_each_popup

- backend/backend.c
I'm not sure what this was used for, but it's not used by libwayland.
Setting _WAYLAND_DISPLAY would result in the Wayland backend being
picked but would ignore the actual value of the env variable.
> backend: remove check for _WAYLAND_DISPLAY

- types/wlr_layer_shell_v1.c
The protocol requires clients to set opposing anchors when requesting
a width or height of 0.
The goal of this patch is not to break clients that rely on this
behavior but to improve the consistency of the layer shell ecosystem
through adherence to the protocol.
> layer-shell: error on 0 dimension without anchors

- backend/libinput/backend.c
- Add a prefix to make it clear log messages come from libinput
- Properly convert libinput log priority to wlroots'
> backend/libinput: improve logger callback

- examples/screencopy-dmabuf.c
- examples/screencopy.c
- examples/virtual-pointer.c
- xwayland/selection/outgoing.c
This one was awful to track down, but calls to `wlr_log` with `%m` have
the errno masked by the `isatty` call in `log_stderr`. Switch them to
`wlr_log_errno` instead.
Cue quality "how can `read(2)` POSSIBLY be returning `ENOTTY`??" moments :)
While at it, I replaced the remaining usages of `%m` (in examples/) with
`perror`, since `%m` is a GNU extension.
> Using %m in `wlr_log` is broken, use `wlr_log_errno` / `perror` instead

- xwayland/selection/outgoing.c
Fixes #2425.
wlroots can only handle one outgoing transfer at a time, so it keeps a
list of pending selections. The head of the list is the currently-active
selection, and when that transfer completes and is destroyed, the next
one is started.
The trouble is when you have a transfer to some app that is misbehaving.
fcitx is one such application. With really large transfers, fcitx will
hang and never(?) wake up again. So, you can end up with a transfer list
that looks like this:
```
| T1: started | T2: pending | T3: pending | T4: pending |
^
|
first
```
The file descriptor for transfer T1 is registered in libwayland's epoll
loop. The rest are waiting in wlroots' list.
As a user, you want your clipboard back, so you `pkill fcitx`. Now
Xwayland sends `XCB_DESTROY_NOTIFY` to let us know to …
> xwayland: fix use-after-free in selection handling

- docs/env_vars.md
- xwayland/server.c
When debugging Xwayland-related issues, a common first step in debugging
has been to ask the reporter to move their real Xwayland to
/usr/bin/Xwayland.bin, and create a shell script starting Xwayland with
extra arguments under the original /usr/bin/Xwayland location.
Introducing a `WLR_XWAYLAND` environment variable makes this less
invasive, by allowing the user to swap out Xwayland without resorting to
global system changes (or source patches).
> xwayland: introduce WLR_XWAYLAND for specifying which Xwayland to use

- include/wlr/xwayland.h
- xwayland/xwm.c
This is necessary to react to changes in position of override-redirect views.
Example of where this is necessary is dragging the "Search everywhere" dialog in Android Studio. It configures itself in order to move around the screen, but compositors up to now can only react when the surface is committed. In the meantime, the compositor and the Xserver state is out-of-sync causing jumps of the view because the mouse coordinates are wrong.
See also https://github.com/WayfireWM/wayfire/pull/784
> xwayland: add set_geometry event

- include/wlr/types/wlr_xdg_shell.h
The resource field of wlr_xdg_positioner is never initialized or
accessed within wlroots. The wl_resource for this interface is stored
in the wlr_xdg_positioner_resource struct.
> xdg_positioner: remove unused field

- backend/wayland/seat.c
- include/backend/wayland.h
Goal currently is to get support working for a single output, thus there is only one touch device created.
Multi-output support is left for later.
> wayland: add touch support to the wayland backend

- backend/wayland/backend.c
- backend/wayland/output.c
- backend/wayland/seat.c
- include/backend/wayland.h
~~*Note  that this PR is based on `0.11.0`, because `master` at the moment is crashing my sway for some reason.*~~
This is just to bring in sync `seat.c` (we propagate events to `current_pointer`) and `output.c`. Though we have at most one pointer at the moment, this may simplify some further work by dropping implicit assumption `assert(!wl->current_pointer || wl->current_pointer->wl_pointer == wl->pointer)` that we already seems to have in `seat.c`.
```sh
WLR_WL_OUTPUTS=2 WLR_NO_HARDWARE_CURSORS=1 WLR_BACKENDS=wayland cage -s -D -- weston-terminal
```
Started under Sway (running system `wlroots-0.11.0`) with single seat.
> Factor out wlr_wl_seat in Wayland backend

- examples/foreign-toplevel.c
- include/wlr/types/wlr_foreign_toplevel_management_v1.h
- protocol/wlr-foreign-toplevel-management-unstable-v1.xml
- types/wlr_foreign_toplevel_management_v1.c
This is an implementation for https://github.com/swaywm/wlr-protocols/pull/52
Works together with: https://github.com/dkondor/wayfire/tree/foreign-toplevel-report-parent
Example client: https://github.com/dkondor/cairo-dock-core/tree/wayland_egl
Tested: not displaying child views in the taskbar
Untested: actually grouping together views with the same parent
I'm happy to work on additional test cases if needed.
Potential issues:
- I've added a field storing the parent to the wlr_foreign_toplevel_handle_v1 struct. This is necessary so that foreign_toplevel_manager_bind() can send information about parents to the new client. This breaks ABI though.
- In wlr_foreign_toplevel_handle_v1_destroy(), I've added code to check if the destroyed handle is not stored in the parent field for any other …
> foreign-toplevel-management: Report parent toplevel

- backend/wayland/backend.c
- backend/wayland/seat.c
- include/backend/wayland.h
This is partially follow on comments for https://github.com/swaywm/wlroots/pull/2413 and https://github.com/swaywm/wlroots/pull/2435 .
Note that releasing `wl_keyboard` is managed by `wlr_wl_keyboard` created in association 1:1 most of the time. With one exception when back-end is not yet started.
> Minor fixes in Wayland backend seat and input device handling alloc errors

- xwayland/server.c
This accidentally slipped through 1b0e4c7.
> xwayland: fix minor typo in debug log

- types/wlr_foreign_toplevel_management_v1.c
> foreign toplevel: send parent event only to clients that support it

- types/xdg_shell/wlr_xdg_surface.c
This could help with #2432, it seems like this overwrites undefined memory locations...
> xdg_shell: fix a typo

- backend/drm/drm.c
This is my first contribution to wlroots so I'm not quite sure if this is the right place to fix the bug.
But since it is only a one line change it should be easy to review.
When an output is disabled one last pageflip will happen to disable it.
Since the output is disabled we don't want to send frame events anymore.
Currently one last event is send after the output is disabled (and the disable is committed ofc).
> backend/drm: Check if output is enabled before sending frame event

- include/wlr/render/egl.h
- include/wlr/render/interface.h
This avoids Xlib.h inclusion via EGL headers. See [1] for discussion.
This change is based on a Weston commit [2].
[1]: https://github.com/KhronosGroup/EGL-Registry/pull/111
[2]: https://gitlab.freedesktop.org/wayland/weston/commit/526765ddfdfd
> render: define EGL_NO_PLATFORM_SPECIFIC_TYPES

- backend/drm/drm.c
When performing a modeset, the DRM backend will request a page-flip
event. However frame_pending wasn't set to true, so any subsequent
wlr_output_schedule_frame calls would imemdiately trigger a synthetic
frame event, asking the compositor to submit a new frame. Committing the
new frame fails with "a page-flip is already pending" error in the DRM
backend.
> backend/drm: fix "a page-flip is already pending" errors on modeset

- types/xdg_shell/wlr_xdg_surface.c
~~This is an attempt to~~ Fixes #2432 
@dkondor please test
> xdg-surface: handle inert toplevels and popups in when committing

- backend/libinput/keyboard.c
- backend/wayland/seat.c
- backend/x11/input_device.c
- examples/output-layout.c
- examples/rotation.c
- include/wlr/types/wlr_keyboard.h
- tinywl/tinywl.c
- types/wlr_keyboard.c
- types/wlr_keyboard_group.c
There's no reason to have duplicate enums.
* * *
Breaking change: `enum wlr_key_state` has been replaced with `enum wl_keyboard_key_state`.
> Replace wlr_key_state with wl_keyboard_key_state

- include/wlr/render/wlr_renderer.h
- render/wlr_renderer.c
This matches the signature of wlr_renderer_impl.begin
> Use uint32_t in wlr_renderer_begin signature

- backend/headless/output.c
- backend/libinput/backend.c
- examples/multi-pointer.c
- examples/pointer.c
- examples/simple.c
- examples/tablet.c
- examples/touch.c
- include/backend/wayland.h
- include/backend/x11.h
- include/wlr/types/wlr_input_device.h
- include/wlr/types/wlr_pointer.h
- include/wlr/types/wlr_seat.h
- types/tablet_v2/wlr_tablet_v2_pad.c
- types/wlr_cursor.c
This uncovered many places where we were using things without directly including them.
This allows us to avoid including tablet-unstable-v2 in many of the example compositors.
~~depends on #2469~~
* * *
Breaking change: `wlr/types/wlr_input_device.h` no longer pulls in all device-specific headers.
> Remove unneeded includes from wlr_input_device.h

- backend/wayland/backend.c
- backend/wayland/output.c
- backend/wayland/seat.c
- backend/wayland/tablet_v2.c
- include/backend/wayland.h
*~~Note  that this PR is based on https://github.com/swaywm/wlroots/pull/2413 `0.11.0`, because latest changes at the moment are crashing my sway test setup https://github.com/swaywm/wlroots/issues/2416.~~*
Intention is to get close to resolving https://github.com/swaywm/wlroots/issues/1499 by getting in one of these:
- ~~exclusive seat per backend (or output)~~.
- ~~muxing pointers/keyboards into virtual ones (same seat)~~
- ~~muxing multiple seats into single virtual one with single/multiple pointer and keyboard~~
- proxying seats as inputs 1:1
Any of those should work for my needs.
Worth to note that as of now we multiple pointers by amount of outputs ~~. Not sure purpose of this.~~ to map absolute coordinates on particular output.
* ~~Switching (`backend->current_pointer`) between …
> Mutli-seat support in Wayland backend

- backend/drm/drm.c
- backend/drm/renderer.c
- include/backend/drm/renderer.h
- include/render/allocator.h
- include/render/drm_format_set.h
- include/render/gbm_allocator.h
- include/render/gles2.h
- include/render/swapchain.h
- include/render/wlr_renderer.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- include/wlr/types/wlr_buffer.h
- render/allocator.c
- render/drm_format_set.c
- render/gbm_allocator.c
- render/gles2/renderer.c
- render/meson.build
- render/swapchain.c
- render/wlr_renderer.c
- types/wlr_buffer.c
This is an alternative to https://github.com/swaywm/wlroots/pull/1355. Instead of re-working the whole API, this PR just uses the new infrastructure inside the DRM backend.
The DRM backend used `EGLSurface` and `gbm_surface` until now. Stop using them and switch to `wlr_allocator` and `wlr_swapchain`. These new interfaces are mostly copied over from [glider](https://github.com/emersion/glider).
This PR doesn't break the wlroots API. For now the new APIs are not exposed in public header, once we add APIs that allow compositors to use it directly, we can easily move the headers to the public dir.
TODO:
References: https://github.com/swaywm/wlroots/issues/1352
* * *
Breaking changes: some implicit assumptions about `wlr_renderer`'s EGL context no longer hold true. Compositors not using EGL …
> Renderer v6, incremental version

- backend/headless/backend.c
- backend/headless/output.c
- include/backend/headless.h
- include/render/gles2.h
- include/wlr/render/egl.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- render/egl.c
- render/gles2/renderer.c
- render/wlr_renderer.c
Same as https://github.com/swaywm/wlroots/pull/2240 but for the headless backend. Supersedes https://github.com/swaywm/wlroots/pull/2268.
> Renderer v6: headless backend

- include/wlr/config.h.in
- include/wlr/render/egl.h
- meson.build
This is a Mesa-specific header that was needed because some Wayland EGL
extensions were missing from the Khronos registry. Now that this has
been fixed [1] and Mesa [2] & glvnd [3] have sync'ed their headers, we
can drop this workaround.
[1]: https://github.com/KhronosGroup/EGL-Registry/pull/95
[2]: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/4953
[3]: https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/225
* * *
* [glvnd 1.3.2](https://gitlab.freedesktop.org/glvnd/libglvnd/-/tags/v1.3.2) contains the patch
* [Mesa 20.2.0](https://docs.mesa3d.org/relnotes/20.2.0.html) contains the patch
> render/egl: stop including eglmesaext.h

- render/egl.c
This error is generated by various egl functions that handle egl devices, and also potentially by glvnd when dispatching those functions. Printing a human-readable name for it is helpful in debugging issues like #2480.
> render/egl: recognize EGL_BAD_DEVICE_EXT error

- include/wlr/render/wlr_texture.h
Supersedes: https://github.com/swaywm/wlroots/pull/2438
> texture: document that functions should not be called while rendering

- backend/drm/drm.c
This is a quick fix for https://github.com/swaywm/wlroots/issues/2429.
> backend/drm: Use legacy gamma size for legacy backend

- backend/backend.c
- backend/drm/backend.c
- backend/libinput/backend.c
- backend/session/direct-freebsd.c
- backend/session/direct.c
- backend/session/libseat.c
- backend/session/logind.c
- backend/session/session.c
- include/backend/drm/drm.h
- include/wlr/backend/drm.h
- include/wlr/backend/session.h
This PR refactors `wlr_session` to prepare support for GPU hotplug. cc @neon64 
- The session API doesn't deal with FDs anymore, `wlr_device` is used instead. This allows callers to directly listen on `wlr_device` events. This will be useful for a future "remove" event.
- A new `add_drm_card` event is introduced. It's used to replace the logind-specific `CanGraphical` property.
- Signals are renamed and moved into an embedded `events` struct, for consistency with the rest of wlroots.
* * *
* `wlr_drm_backend_create` takes a `wlr_device` instead of a DRM FD
* `wlr_device.signal` has been replaced by `wlr_device.events.change`
* `wlr_session.session_signal` has been replaced by `wlr_session.events.active`
* `wlr_session_open_file` and …
> backend/session: misc. refactoring, replace CanGraphical with udev

- include/wlr/types/wlr_output.h
- include/wlr/types/wlr_surface.h
- types/wlr_output.c
- types/wlr_surface.c
surface: Make send_enter store entered outputs
wlr_surface_send_enter now stores outputs that have been entered.
Combined with a new 'bind' event on wlr_output, this allows us to delay
enter events as necessary until the respective wl_output global has been
bound.
Closes: https://github.com/swaywm/wlroots/issues/2466
> Implement new surface enter/leave API

- backend/session/libseat.c
This should return true on success and false on failure not vice-versa.
> backend/libseat: fix change_vt return value

- backend/drm/drm.c
After discussing with Pekka and Daniel on #dri-devel, we concluded [1]
that user-space shouldn't need to force-probe connectors. Force-probing
can take some time, so using drmModeGetConnectorCurrent can result in
faster start-up.
Users can manually trigger a force-probe if necessary:
echo detect | sudo tee /sys/class/drm/card0-DP-1/status
Or just by running a tool like drm_info.
A similar change has been submitted to Weston [2].
[1]: https://lists.freedesktop.org/archives/dri-devel/2020-November/287728.html
[2]: https://gitlab.freedesktop.org/wayland/weston/-/issues/437
> backend/drm: stop force-probing connectors

- types/wlr_output_management_v1.c
Handle allocation failure in wlr_output_configuration_head_v1_create
> wlr-output-management: add missing NULL check

- backend/headless/backend.c
- include/render/wlr_renderer.h
- include/wlr/render/egl.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- render/egl.c
- render/gles2/renderer.c
- render/wlr_renderer.c
- types/wlr_linux_dmabuf_v1.c
The main motivation for this PR is to ensure we select a format we can render to in the headless backend.
It contains also some breaking changes that clarify what formats advertised by `wlr_renderer` are good for.
* * *
* `wlr_egl_get_dmabuf_formats` has been renamed to `wlr_egl_get_dmabuf_texture_formats`
* `wlr_renderer_get_formats` has been renamed to `wlr_renderer_get_shm_texture_formats`
* `wlr_renderer_get_dmabuf_formats` has been renamed to `wlr_renderer_get_dmabuf_texture_formats`
* `wlr_renderer_format_supported` has been removed (instead, use `wlr_renderer_get_shm_texture_formats`)
> render: add wlr_renderer_get_dmabuf_render_formats

- include/wlr/xwayland.h
- xwayland/xwm.c
This PR adds a simple function for restacking Xwayland surfaces above or below each other.
To allow the most flexibility, this function receives a sibling and a mode argument, like the corresponding X11 configure event does.
EDIT: this is needed because in X11 the surface which gets pointer events is determined by the stacking order. Thus, if a compositor has the concept of always-on-top views or similar, they need to tell the Xserver what the real stacking order is.
> xwm: add wlr_xwayland_surface_restack()

- backend/drm/drm.c
This reverts commit 713c1661b742f93a7d2167321837c0d99541ca87.
It turns out we do need to force-probe on startup and on hotplug [1].
This is unfortunate, but that's just how the uAPI works. Fixing this
would require patching the kernel.
[1]: https://lists.freedesktop.org/archives/dri-devel/2020-November/289506.html
Closes: https://github.com/swaywm/wlroots/issues/2499
cc @ammen99
> Revert "backend/drm: stop force-probing connectors"

- backend/drm/renderer.c
- include/render/drm_format_set.h
- render/drm_format_set.c
~~Depends on https://github.com/swaywm/wlroots/pull/2483~~
On some platforms it's possible that the display engine supports
modifiers not supported by the render engine.
Query render formats and intersect them with plane formats to accommodate
for this.
> backend/drm: query render formats

- backend/session/libseat.c
libseat will call logind's SetType method if necessary.
> backend/session/libseat: set XDG_SESSION_TYPE

- types/wlr_screencopy_v1.c
Damage the full output if the compositor didn't submit damage but did
submit a buffer.
> screencopy: handle compositor not setting damage

- backend/drm/drm.c
Otherwise, compositors do not have access to make/model when the output is being removed.
Note: not sure about the name `drm_connector_reset`, if someone has a better suggestion, I'll update the PR.
> drm: do not unset make/model before emitting destroy event

- types/wlr_screencopy_v1.c
Only wlr_output_damage works in transformed coordinates,
wlr_output->damage is in output-buffer-local coordinates.
This essentially reverts 1ecc1b5 and fixes 1477401.
> screencopy: don't use output transform for damage copy

- types/wlr_output_management_v1.c
The DRM backend adds custom modes to wlr_output.modes
Currently modes that are added after the first occurence of
wlr_output_configuration_head_v1 are not added to wlr_output_head.mode_resources.
> wlr-output-management: Handle modes added after initializing

- backend/headless/backend.c
- render/egl.c
- render/wlr_renderer.c
This is preliminary work for https://github.com/swaywm/wlroots/pull/2505.
With `wlr_swapchain`, we stop using `EGLSurface` entirely, so we can skip selecting an `EGLConfig`.
> backend/headless: use config-less context

- include/wlr/xwayland.h
- xwayland/server.c
Closes: https://github.com/swaywm/wlroots/issues/2154
> xwayland: use pipe instead of SIGUSR1 to signal readiness

- include/wlr/types/wlr_output.h
output-buffer-local coordinates are neither scaled nor transformed
> docs: fix error in wlr_output_set_damage() comment

- backend/drm/renderer.c
drm_fb_import_wlr may need to change the current EGL context. For
instance by calling drm_fb_clear, which calls wlr_buffer_unlock, which
may destroy a buffer if the cursor swapchain size has changed, which
calls gles2's destroy_buffer, which calls glDeleteFramebuffers.
Closes: https://github.com/swaywm/wlroots/issues/2479
> backend/drm: unset current surface before importing

- backend/drm/drm.c
- include/backend/drm/drm.h
This is an improved implementation of the plane matching logic when the kernel DRM does not enforce a single CRTC per plane.
This is not a bullet proof implementation but it should work fine for the Raspberry Pi 4 where all CRTCs are possible for all planes. 
Closes: https://github.com/swaywm/wlroots/issues/1943
> Improve DRM plane matching logic

- backend/drm/drm.c
- backend/drm/renderer.c
- include/backend/drm/renderer.h
Since we're using wlr_swapchain, we don't need to provide an EGL config.
> backend/drm: remove EGL config

- render/gles2/renderer.c
If we don't have an EGL config, don't try to query anything from it.
If we're using a render buffer, query the alpha size from it.
Closes: #2527
cc @any1
> render/gles2: query alpha size from render buffer 

- backend/wayland/backend.c
- backend/wayland/output.c
- examples/meson.build
- include/backend/wayland.h
- meson.build
- types/wlr_output.c
~~Depends on #2496~~
TODO:
Future work:
- Don't create a `wl_buffer` on each commit -- cache them (https://github.com/swaywm/wlroots/pull/2538)
- Use linux-dmabuf hints to get render FD
References: #1352
> backend/wayland: use wlr_swapchain

- backend/x11/backend.c
- backend/x11/meson.build
- backend/x11/output.c
- include/backend/x11.h
~~Depends on #2496~~
This PR switches away from `EGLSurface` in the X11 backend. Instead, it uses directly the DRI3 and Present extensions.
TODO:
Future improvements:
- Don't create a pixmap on each commit -- cache them (https://github.com/swaywm/wlroots/pull/2539)
- Use `DRI3Open` to get the render node (https://github.com/swaywm/wlroots/pull/2540)
- Take advantage of Present to remove the frame timer (prior art: https://github.com/swaywm/wlroots/pull/1894)
References: https://github.com/swaywm/wlroots/issues/1352
> backend/x11: use wlr_swapchain

- backend/drm/drm.c
- backend/drm/renderer.c
- include/backend/drm/renderer.h
gbm_bo_create_with_modifiers doesn't take GBM flags, so our
wlr_gbm_allocator interface doesn't either. We were still internally
using GBM flags in the DRM backend, leading to awkward back-and-forth
conversions.
The only flag passed to drm_plane_init_surface was GBM_BO_USE_LINEAR, so
turn that into a bool to make sure other flags can't be passed in.
Move the "force linear" logic out of init_drm_surface, because the
supplied wlr_drm_format should already contain that information.
> backend/drm: stop using GBM flags

- backend/x11/backend.c
We queried DRI3 formats, but we weren't using them. Because of a typo,
only render formats were used.
Fixes: c59aacf94465 ("backend/x11: query modifiers supported by X11 server")
Closes: https://github.com/swaywm/wlroots/issues/2552
> backend/x11: fix DRI3 formats not used

- backend/drm/renderer.c
- include/render/drm_format_set.h
- render/drm_format_set.c
~~Depends on https://github.com/swaywm/wlroots/pull/2530~~
Instead of manually allocating and initializing the structs, introduce new `wlr_drm_format_set` helpers.
> render/drm_format_set: add wlr_drm_format_{create,add}

- backend/x11/output.c
- include/util/time.h
- util/time.c
Instead of sending dummy output present events, use the X11 Present
extension to send more precise events.
> backend/x11: send more precise output present events

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
This allows the DRM code to have direct access to the wlr_drm_backend
without having to go through an upcast via get_drm_backend_from_backend.
Simplify and unify connector-specific logging with a new
wlr_drm_conn_log macro. This makes it easier to understand which
connector a failure is about, without having to explicitly integrate the
connector name in each log message.
The DRM backend is a little special when it comes to wlr_outputs: the
wlr_drm_connectors are long-lived and are created even when no screen is
connected.
A wlr_drm_connector only advertises a wlr_output to the compositor when
a screen is connected. As such, most of wlr_output's state is invalid
when the connector is disconnected.
We want to stop using wlr_output state on disconnected connectors.
Introduce …
> backend/drm: refactor wlr_output destruction

- backend/drm/drm.c
fixes #2559 
Maybe worth noting that the -1 might not be necessary in the first place – since wlr_conn->name field is filled by snprintf I believe it is guaranteed to be null-terminated.
EDIT: dropped the -1
> backend/drm: avoid gcc stringop-truncation warning

- xwayland/server.c
This function may end up being called more than once if the Xwayland
binary does not exist on the system.
Fixes https://github.com/ifreund/river/issues/167
> xwayland: avoid crash on repeated server_finish_display() call

- backend/wayland/backend.c
We don't use EGLSurface anymore, so we don't need to choose an EGL
config anymore.
This is the last EGL config we use in wlroots.
> backend/wayland: remove EGL config

- backend/wayland/backend.c
- backend/wayland/output.c
- include/backend/wayland.h
Instead of re-importing a buffer each time we submit a new frame, re-use
the wl_buffer objects if possible.
~~Depends on https://github.com/swaywm/wlroots/pull/2498~~
> backend/wayland: re-use wl_buffers

- backend/x11/output.c
- include/backend/x11.h
Instead of re-importing a buffer each time we submit a frame, re-use the
pixmaps if possible.
~~Depends on https://github.com/swaywm/wlroots/pull/2495~~
> backend/x11: re-use pixmaps

- backend/drm/atomic.c
- backend/drm/drm.c
- backend/drm/legacy.c
- backend/drm/renderer.c
- backend/drm/util.c
- include/backend/drm/renderer.h
Try to remove as much of the `wlr_drm_fb` complexity as possible:
- Import to GBM and to KMS at the same time. Stop doing any kind of import in the legacy/atomic commit hooks.
- Only import to GBM on the scanout device. Stop needlessly importing to GBM on the render device.
- Remove unused mgpu renderer field.
- Stop stuffing things in `gbm_bo` user data field.
- Avoid using GBM for `export_dmabuf`. Instead, directly use `wlr_buffer_get_dmabuf` and drop `export_drm_bo`.
* * *
Tested:
> backend/drm: simplify wlr_drm_fb handling

- backend/x11/output.c
- include/backend/x11.h
This is a respin of https://github.com/swaywm/wlroots/pull/1894
~~Depends on https://github.com/swaywm/wlroots/pull/2544~~
> backend/x11: implement a real rendering loop

- backend/drm/util.c
This pull request implements a fallback `get_fb_for_bo_legacy` function which uses the legacy `drmAddModeFB` function to set up the framebuffer.
This is based on the logic in xf86-video-modesetting, and allows both Sway and my own compositor to run on older cards which otherwise support the necessary features for Wayland to function.  Tested on a machine with ATI Radeon 7500 AGP graphics.
> drm: add fallback drmModeAddFB for drivers which do not support drmModeAddFB2

- backend/x11/backend.c
- backend/x11/output.c
- include/backend/x11.h
The Present protocol states:
> An event context is associated with a specific window; using an existing
> event context with a different window generates a Match error.
Instead of a global event context, use a per-window event context to fix
this error:
[backend/x11/backend.c:608] X11 error: op Present (SelectInput), code Match (no extension), sequence 63, value 4194307
Closes: https://github.com/swaywm/wlroots/issues/2577
> backend/x11: create per-window present event contexts

- backend/backend.c
- backend/drm/backend.c
- backend/drm/renderer.c
- backend/headless/backend.c
- backend/wayland/backend.c
- backend/x11/backend.c
- examples/fullscreen-shell.c
- examples/multi-pointer.c
- examples/output-layout.c
- examples/pointer.c
- examples/rotation.c
- examples/simple.c
- examples/tablet.c
- examples/touch.c
- include/backend/drm/renderer.h
- include/wlr/backend.h
- include/wlr/backend/drm.h
- include/wlr/backend/headless.h
- include/wlr/backend/wayland.h
- include/wlr/backend/x11.h
This callback allowed compositors to customize the EGL config used by
the renderer. However with renderer v6 EGL configs aren't used anymore.
Instead, buffers are allocated via GBM and GL FBOs are rendered to. So
customizing the EGL config is a no-op.
cc @ammen99 
* * *
* `wlr_backend_autocreate`, `wlr_drm_backend_create`, `wlr_headless_backend_create`, `wlr_wl_backend_create`, `wlr_x11_backend_create` no longer take a `wlr_renderer_create_func_t` parameter.
* The `wlr_renderer_create_func_t` type has been removed.
> Remove wlr_create_renderer_func_t

- backend/noop/backend.c
- include/backend/noop.h
Not sure if this is needed, but I guess it is a good idea, since most objects which are related to the display are destroyed when it is destroyed?
> noop: listen to display destroy and destroy the backend

- backend/drm/backend.c
When the session is inactive, we can't change the KMS state. Ignore
hotplug events so that compositors don't try to perform a modeset when
a connector is plugged in. We already re-scan connectors when the
session becomes active.
To test, run a wlroots compositor on VT 1, switch to VT 2, unplug a
connector, re-plug it, switch back to VT 1. Without this patch the
screen is black on VT 1.
References: https://github.com/swaywm/wlroots/issues/2370
> backend/drm: ignore hotplug events while inactive

- backend/drm/drm.c
- include/backend/drm/drm.h
wlr_drm_connector.crtc may be updated by the DRM backend while a
page-flip is pending. In this case, the page-flip handler won't be able
to find the right wlr_drm_connector from the CRTC ID.
Save the CRTC when performing a page-flip to ensure we always find the
right connector when we get the event.
> backend/drm: stash pending page-flip CRTC

- backend/wayland/output.c
We were importing cursor buffers as wl_buffers over and over again.
Instead, only import these once.
> backend/wayland: re-use cursor wl_buffers

- backend/backend.c
- backend/session/session.c
- include/wlr/backend/session.h
Sometimes wlr_session_find_gpus will encounter an error. This is
different from finding zero GPUs.
On error, wlr_session_find_gpus already returns -1. However, this is
casted to size_t, so callers uncorrectly assume this is a success.
Instead, make wlr_session_find_gpus return a ssize_t and allow callers
to handle the error accordingly.
* * *
Breaking change: `wlr_session_find_gpus` now returns a `ssize_t` instead of a `size_t`.
> backend/session: allow wlr_session_find_gpus to return an error

- backend/wayland/seat.c
keyboard_handle_leave would always process 1 keycode more than was
pending, which meant reading uninitialized memory from the "pressed"
array.
Found by valgrind.
> backend/wayland: Avoid uninitialized read

- types/wlr_gtk_primary_selection.c
- types/wlr_primary_selection_v1.c
Found thanks to @kennylevinsen's valgrind log:
```
==11666== Invalid write of size 8
==11666==    at 0x4F3173B: wl_list_remove (in /usr/lib64/libwayland-server.so.0.1.0)
==11666==    by 0x48AE988: device_destroy (wlr_primary_selection_v1.c:341)
==11666==    by 0x48AE988: device_handle_seat_destroy (wlr_primary_selection_v1.c:275)
==11666==    by 0x48B84CB: wlr_signal_emit_safe (signal.c:29)
==11666==    by 0x4892E82: wlr_seat_destroy (wlr_seat.c:162)
==11666==    by 0x4892E82: wlr_seat_destroy (wlr_seat.c:157)
==11666==    by 0x4F2C3E4: wl_display_destroy (in /usr/lib64/libwayland-server.so.0.1.0)
==11666==    by 0x41924F: server_fini (server.c:203)
==11666==    by 0x40E9DD: main (main.c:436)
==11666==  Address 0xf436ac0 is 16 bytes inside a block of size 72 free'd
==11666==    at …
```
> primary selection: destroy devices before manager 

- .builds/alpine.yml
- .builds/freebsd.yml
- README.md
- include/meson.build
- include/util/uuid.h
- include/wlr/config.h.in
- include/wlr/types/wlr_xdg_foreign_registry.h
- include/wlr/types/wlr_xdg_foreign_v1.h
- include/wlr/types/wlr_xdg_foreign_v2.h
- include/wlr/types/wlr_xdg_shell.h
- meson.build
- meson_options.txt
- protocol/meson.build
- types/meson.build
- types/wlr_xdg_foreign_registry.c
- types/wlr_xdg_foreign_v1.c
- types/wlr_xdg_foreign_v2.c
- types/xdg_shell/wlr_xdg_toplevel.c
- util/meson.build
- util/uuid.c
Supersedes #1841 (for now only rebased) and thus fixes #1702 
TODO:
> implementation of xdg-foreign protocol

- backend/drm/renderer.c
- backend/headless/backend.c
- backend/wayland/backend.c
- backend/x11/backend.c
- include/wlr/render/wlr_renderer.h
- render/wlr_renderer.c
This isn't used anymore by any backend.
Some examples still provide an EGL config to wlr_egl_init, so we can't
drop it yet there.
References: https://github.com/swaywm/wlroots/issues/2563
* * *
Breaking change: `wlr_renderer_autocreate` no longer takes the parameters `EGLint *config_attribs` and `EGLint visual_id`.
> render: remove EGL config and visual from wlr_renderer_autocreate

- types/wlr_layer_shell_v1.c
This should have been done in 45c0877 but was overlooked unfortunately.
> layer shell: advertise version 3

- include/wlr/types/wlr_seat.h
- types/seat/wlr_seat.c
This fixes use-after-free in surface destroy signal listeners.
> types/seat: Clear focus in wlr_seat_destroy()

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- tinywl/tinywl.c
The ci now builds tinywl, which requires wlroots to be installed first.
> CI builds tinywl

- backend/drm/backend.c
- backend/drm/renderer.c
- backend/headless/backend.c
- backend/headless/output.c
- backend/wayland/backend.c
- backend/wayland/output.c
- backend/x11/backend.c
- backend/x11/output.c
- include/backend/drm/drm.h
- include/backend/drm/renderer.h
- include/backend/headless.h
- include/backend/wayland.h
- include/backend/x11.h
- include/wlr/backend.h
- include/wlr/backend/interface.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- render/gles2/renderer.c
- render/wlr_renderer.c
Removes the `wlr_egl` member from various backend to keep it into the `wlr_renderer`. This also removes various includes of the `render/egl.h` header that were made useless by this patch.
References: https://github.com/swaywm/wlroots/issues/2563
* * *
Breaking change: `wlr_renderer_autocreate` no longer takes a `struct wlr_egl *` as parameter.
> Remove wlr_egl from backends

- include/wlr/types/wlr_xdg_shell.h
- types/xdg_shell/wlr_xdg_surface.c
~~Omitting these is a bug. Firefox for example only renders stuff to
the subsurfaces of its popups for whatever reason.~~
When rendering, it is necessary to iterate the subsurfaces as well,
so add a function that makes this easy.
> xdg shell: add wlr_xdg_surface_for_each_popup_surface() 

- util/uuid.c
Fixes:
```
FAILED: subprojects/wlroots/libwlroots.so.7.p/util_uuid.c.o
cc -Isubprojects/wlroots/libwlroots.so.7.p -Isubprojects/wlroots -I../subprojects/wlroots -Isubprojects/wlroots/include -I../subprojects/wlroots/include -Isubprojects/wlroots/protocol -I../subprojects/wlroots/protocol -I/usr/local/include -I/usr/local/include/libepoll-shim -I/usr/local/include/libdrm -I/usr/local/include/pixman-1 -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g -DWLR_USE_UNSTABLE -Wundef -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter …
```
> util: fix uuid support for freebsd

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- backend/drm/renderer.c
- include/backend/drm/drm.h
- include/backend/drm/renderer.h
Instead of importing buffers to GBM and KMS at each frame, cache them and re-use them while the wlr_buffer is alive.
This is the same as #2538 and #2539 but for the DRM backend.
Closes: https://github.com/swaywm/wlroots/issues/2276
> backend/drm: re-use FBs

- xwayland/xwm.c
Developers can use x11trace or similar to analyze the protocol messages.
> xwayland: remove protocol debug messages

- backend/wayland/backend.c
- backend/wayland/meson.build
- include/backend/wayland.h
- protocol/drm.xml
- protocol/meson.build
Just like other backends, use the EGL GBM platform. This will make it
easier to move the allocator and renderer initialization out of the
backends.
> backend/wayland: use the EGL GBM platform

- include/wlr/types/wlr_output_management_v1.h
- types/wlr_output_management_v1.c
This is more correct and also makes things much nicer for languages
that don't allow implicit conversions between these types.
> output-management: use same types as wlr_output

- include/wlr/types/wlr_xdg_shell.h
- types/xdg_shell/wlr_xdg_surface.c
~~This function is not well suited to rendering as it does not iterate
over subsurfaces. Therefore, it makes little sense to use the standard
surface iterator function. Introduce an new xdg-popup iterator function
and use that instead.~~
This function is inferior to wlr_xdg_surface_for_each_popup_surface()
for rendering as it does not iterate over subsurfaces. Furthermore,
no compositor known to use this to iterate popups for any purpose other
than rendering. Therefore remove the function which may of course be
reintroduced at a later date if a use-case is found.
* * *
Breaking change: `wlr_xdg_surface_for_each_popup` has been removed, use `wlr_xdg_surface_for_each_popup_surface` instead.
> xdg shell: remove wlr_xdg_surface_for_each_popup() 

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
This iterates over the subsurfaces of popups as well, so rename it to
match wlr_xdg_surface_for_each_popup_surface().
* * *
Breaking change: `wlr_layer_surface_v1_for_each_popup` has been renamed to `wlr_layer_surface_v1_for_each_popup_surface`.
> layer shell: rename popup iterator for consistency

- backend/drm/renderer.c
- backend/headless/output.c
- backend/wayland/output.c
- backend/x11/output.c
- examples/idle-inhibit.c
- examples/input-inhibitor.c
- examples/keyboard-shortcuts-inhibit.c
- examples/layer-shell.c
- examples/pointer-constraints.c
- examples/relative-pointer-unstable-v1.c
- examples/text-input.c
- examples/toplevel-decoration.c
- include/wlr/render/egl.h
- render/egl.c
- render/gles2/renderer.c
- render/gles2/texture.c
- render/wlr_renderer.c
* * *
* The `EGLint visual_id` parameter of `wlr_egl_init` has been removed.
* `wlr_egl_swap_buffers` has been removed.
* `wlr_egl_init` and `wlr_egl_finish` have been replaced with `wlr_egl_create` and `wlr_egl_destroy`.
* `wlr_egl_make_current` no longer takes the arguments `EGLSurface surface, int *buffer_age`.
> render/egl: remove unused features, introduce create/destroy

- examples/layer-shell.c
- include/wlr/types/wlr_layer_shell_v1.h
- protocol/wlr-layer-shell-unstable-v1.xml
- types/wlr_layer_shell_v1.c
Implementation for https://github.com/swaywm/wlr-protocols/pull/100
The goal of this is to enable layer-shell clients to have "regular" keyboard focus semantics. This can make it easier to implement layer-shell clients (no need to adjust the keyboard-interactivity setting when needed); also, it allows better support for keyboard interaction on the main layer-shell surface, including being notified of keyboard notifiers along with mouse clicks.
For clients using the old version of the protocol, any value is still interpreted as requesting exclusive focus. For clients with using the new protocol version, the compositor can interpret the given value. according to its policies.
Question: should there be a way for compositors to specify which version to use in wlr_layer_shell_v1_create()?
* * …
> Keyboard interactivity options

- include/wlr/types/wlr_output.h
- include/wlr/types/wlr_output_damage.h
- types/wlr_output.c
- types/wlr_output_damage.c
- types/wlr_output_layout.c
Per https://github.com/swaywm/wlroots/issues/2098, compositors should use the commit event instead.
Unfortunately we can't do the same for the `mode` and `enabled` events, because the backend can update those behind the compositor's back (without an output commit).
* * *
Breaking change: the `scale` and `transform` output events have been removed, compositors should use the `commit` event instead.
> output: remove scale/transform events

- include/render/gbm_allocator.h
- render/gbm_allocator.c
We need to destroy any gbm_bo we've created before gbm_device_destroy.
Closes: https://github.com/swaywm/wlroots/issues/2601
> render/gbm_allocator: fix gbm_device use-after-free

- backend/backend.c
- backend/drm/backend.c
- backend/drm/renderer.c
- backend/headless/backend.c
- backend/headless/output.c
- backend/multi/backend.c
- backend/wayland/backend.c
- backend/wayland/output.c
- backend/x11/backend.c
- backend/x11/output.c
- include/backend/backend.h
- include/backend/headless.h
- include/backend/wayland.h
- include/backend/x11.h
- include/wlr/backend/interface.h
- include/wlr/render/egl.h
- include/wlr/render/wlr_renderer.h
- render/egl.c
- render/wlr_renderer.c
Fixes #2563, requires https://github.com/swaywm/wlroots/pull/2613
* * *
Breaking change: `wlr_renderer_autocreate` no longer takes the arguments `EGLenum platform, void *remote_display`. Instead it takes a `struct wlr_backend *`.
> Drop EGL from wlr_renderer_autocreate

- backend/drm/renderer.c
- backend/headless/output.c
- backend/wayland/output.c
- backend/x11/output.c
- render/gles2/renderer.c
Instead of requiring callers to manually make the EGL context current
before binding a buffer and unsetting it after unbinding a buffer, do
it inside wlr_renderer_bind_buffer.
This hides renderer-specific implementation details inside the
wlr_renderer interface. Non-GLES2 renderers may not use EGL.
This removes almost all EGL dependencies from the backends, the only
remaining one is wlr_renderer_autocreate args.
References: https://github.com/swaywm/wlroots/issues/2618
References: https://github.com/swaywm/wlroots/pull/2615#issuecomment-756687006
cc @bl4ckb0ne @any1
* * *
This is _not_ a breaking change because `wlr_renderer_bind_buffer` is a private wlroots API.
> render/gles2: make EGL context current in bind_buffer

- include/wlr/types/wlr_output_damage.h
- types/wlr_output.c
- types/wlr_output_damage.c
References: https://github.com/swaywm/wlroots/issues/2098
* * *
Breaking change: Compositors can no longer read the to-be-committed state from`wlr_output.pending` in an output `commit` event handler. Instead, use the current state and `wlr_output_event_commit`.
> output: send commit event after pending state is cleared

- backend/drm/renderer.c
- include/render/wlr_renderer.h
- render/wlr_renderer.c
The new wlr_renderer_autocreate API is great for compositors, however
it causes some issues with DRM multi-GPU support.
A DRM child backend wants the compositor to use the parent GPU, so it
exposes the parent's DRM FD in get_drm_fd. However, in order to be able
to perform multi-GPU buffer copies, the child DRM backend still needs to
create a local renderer.
Use the new private wlr_renderer_autocreate_with_drm_fd function to
avoid creating a renderer for the parent GPU.
Fixes: e128e6c08dc0 ("render: drop egl parameters from wlr_renderer_autocreate")
> backend/drm: use local DRM FD for wlr_rend

- xwayland/xwayland.c
Running the asan build has detected what seems like a large number of memory leaks on shutdown. This was the first one I saw and seems like a relatively simple fix (the old cursor memory is freed in [wlr_xwayland_set_cursor.c:119](https://github.com/neon64/wlroots/blob/28584167dd50b388e3e1755be2946e45d9d0c2bd/xwayland/xwayland.c#L119) but not on shutdown)
> xwayland/cursor: free cursor in wlr_xwayland_destroy

- backend/drm/drm.c
- backend/drm/properties.c
- include/backend/drm/properties.h
The subconnector property indicates the connector sub-type. This is
useful because that usually indicates what kind of connector the user
has plugged in to their monitor, e.g. a DisplayPort-to-DVI cable will
indicate a DVI subconnector. Also some laptops have non-DP connectors
that are internally linked to a DP port on the GPU.
Set the output description accordingly.
See https://drmdb.emersion.fr/properties/3233857728/subconnector
> backend/drm: add support for the subconnector property

- backend/drm/drm.c
- include/wlr/backend/drm.h
This allows a compositor to get a KMS connector object ID from a
wlr_output. The compositor can then query more information about
the connector via libdrm.
This gives more freedom to compositors and allows them to read
KMS properties that wlroots doesn't know about. For instance,
they could read the EDID or the suggested_{X,Y} properties and
change their output configuration based on that.
> backend/drm: add wlr_drm_connector_get_id

- backend/x11/backend.c
- backend/x11/input_device.c
- backend/x11/output.c
- include/backend/x11.h
This actually simplifies the logic since we no longer have to wait for
enter/leave events, and also improves the UX when e.g. handling a crash
with gdb attached.
See #2659
> backend/x11: set a blank cursor rather than hiding globally

- types/wlr_xdg_output_v1.c
Since output_destroy() calls wl_list_remove() on the output's link,
the manager must still be valid. This is the same bug fixed in bf926e3
but with a different interface.
valgrind log that led to discovery thanks to @Leon-Plickat
```
==12503== Invalid write of size 8
==12503==    at 0x4873F07: wl_list_remove (wayland-util.c:55)
==12503==    by 0x49F3D5A: output_destroy (wlr_xdg_output_v1.c:75)
==12503==    by 0x49F4077: handle_output_destroy (wlr_xdg_output_v1.c:168)
==12503==    by 0x49F6A25: wlr_signal_emit_safe (signal.c:29)
==12503==    by 0x49DE57B: output_layout_output_destroy (wlr_output_layout.c:50)
==12503==    by 0x49DE665: wlr_output_layout_destroy (wlr_output_layout.c:70)
==12503==    by 0x237A00: Root.deinit (Root.zig:121)
==12503==    by 0x220133: Server.deinit …
```
> xdg-output: destroy outputs before manager

- include/wlr/xwayland.h
- xwayland/xwm.c
In certain situations windows can have their input field set to false.
In these cases windows should only receive focus if WM_TAKE_FOCUS
is enabled. Otherwise the window should never receive focus.
Relates to #2604
> Expose ICCCM input status

- backend/x11/output.c
The transform matrix was all 0's, which meant that effectively nothing
got rendered other than the clear color.
Not sure whether the refresh rate matters for anything... or where to get it from if it does.
> backend/x11: make sure output transform matrix is initialized

- include/wlr/render/egl.h
- render/egl.c
- render/wlr_renderer.c
Reverts swaywm/wlroots#2654
The EGL device platform doesn't expose `EGL_WL_bind_wayland_display`. This means we won't be able to enable the `wl_drm` global. Some clients will just stop working, some clients will fallback to llvmpipe.
We need to write a Mesa patch to add `EGL_WL_bind_wayland_display` to the device platform.
Closes: https://github.com/swaywm/wlroots/issues/2667
> Revert "render: add wlr_egl_create_from_drm_fd function"

- xwayland/selection/incoming.c
Previously, any error would be masked by an internal isatty call:
```
24:31:48.174 [DEBUG] [wlr] [xwayland/selection/incoming.c:386] XCB_SELECTION_NOTIFY (selection=277, property=278, target=256)
24:31:48.174 [ERROR] [wlr] [xwayland/selection/incoming.c:30] write error to target fd: Inappropriate ioctl for device
```
> xwayland: use strerror(...) instead of %m

- xwayland/selection/incoming.c
Since we never end up calling xcb_convert_selection, the file descriptor
ends up getting leaked (i.e., not cleaned up within
xwm_data_source_write).
> xwayland/selection: prevent fd leak on unsupported MIME type

- include/xwayland/selection.h
- xwayland/selection/incoming.c
- xwayland/selection/outgoing.c
- xwayland/selection/selection.c
Previously, wlr_xwm_selection_transfer.source_fd meant:
- the source of data in a Wayland -> X11 copy (good)
- the destination of data in a X11 -> Wayland copy (confusing)
This made reading through xwayland/selection/incoming.c difficult: in
many places, "source" actually means "destination".
> xwayland/selection: rename Wayland-facing data and helpers

- docs/env_vars.md
- render/egl.c
The creation of `wlr_egl` will fail is the device extension
EGL_MESA_device_software is defined. The creation process is allowed to
continue only if the environment variable `WLR_RENDERER_ALLOW_SOFTWARE`
is defiled.
> render/egl: fail to create wlr_egl on software renderer

- xwayland/xwm.c
wlroots would log "Unhandled NET_WM_STATE property change" log
messages for atoms we know about. Simplify the code structure
and remove these extra messages.
> xwayland: fix extraneous NET_WM_STATE log messages

- examples/egl_common.c
- examples/egl_common.h
- examples/idle-inhibit.c
- examples/input-inhibitor.c
- examples/keyboard-shortcuts-inhibit.c
- examples/layer-shell.c
- examples/meson.build
- examples/pointer-constraints.c
- examples/relative-pointer-unstable-v1.c
- examples/text-input.c
- examples/toplevel-decoration.c
- include/wlr/render/egl.h
- render/egl.c
- render/gles2/renderer.c
- render/wlr_renderer.c
Just another part of #2624 and #1352 that I felt needed to be done.
`EGLint *config_attribs`, `wlr_egl->config`, `wlr_egl_create_surface` and `wlr_egl_destroy_surface` have been removed and no longer exist.
CC(if needed):
@emersion @bl4ckb0ne @ascent12 
EDIT: Fixed a typo.
EDIT 2: Removed `wlr_egl_create_surface` and `wlr_egl_destroy_surface` and removed a dependency on `wlr_egl` from some example clients.
> render/egl: remove *config_attribs, wlr_egl->config and wlr_egl_(create, destroy)_surface

- include/xwayland/selection.h
- xwayland/selection/incoming.c
- xwayland/selection/selection.c
This PR makes incremental transfer error-handling a bit simpler to follow, and easier to ascertain the correctness of. There should be no behavioral changes; I've tested transfers (incremental and non-incremental) still work. See individual commits for details and rationale.
> xwayland/selection: simplify incremental transfer control flow

- examples/egl_common.c
Remove "major" and "minor" from egl_common.c as they are not used by the examples that use `egl_common.c`.
In other words, just polishing `egl_common.c`
Also, whoops! Sorry about that. I should've removed those two variables as those were leftovers when I was copying from `render/egl.c` before #2666 got merged. :grimacing:
> examples: remove "major" and "minor" from egl_common.c

- render/egl.c
As surfaces are no longer going to be used for `wlr_egl`, I may as well just go and add this check as it is needed for safety whenever surface-less rendering is being used.
EDIT: I think this is also relevant: #1352
> render/egl: add check for EGL_KHR_surfaceless_context

- render/gles2/texture.c
Clamping texture coordinates prevents OpenGL from blending the left and
right edge (or top and bottom edge) when scaling textures with GL_LINEAR
filtering. This prevents visual artifacts like swaywm/sway#5809.
Per discussion on IRC, this behaviour is made default. Compositors that want
the wrapping behaviour (e.g. for tiled patterns) can override this by doing:
```c
struct wlr_gles2_texture_attribs attribs;
wlr_gles2_texture_get_attribs(texture, &attribs);
glBindTexture(attribs.target, attribs.tex);
glTexParameteri(attribs.target, GL_TEXTURE_WRAP_S, GL_REPEAT);
glTexParameteri(attribs.target, GL_TEXTURE_WRAP_T, GL_REPEAT);
glBindTexture(attribs.target, 0);
```
* * *
Breaking change: The GLES2 renderer no longer wraps textures with `GL_REPEAT`. If you want to repeat a texture, manually …
> render/wlr_texture: clamp texture coordinates to edge by default

- include/types/wlr_region.h
- include/wlr/types/wlr_region.h
- types/wlr_compositor.c
- types/wlr_region.c
This function should only be called from the handler for
wl_compositor.create_region requests.
* * *
Breaking change: `wlr_region_create` has been removed.
> region: make wlr_region_create private

- backend/wayland/backend.c
- backend/wayland/output.c
It turns out wl_event_source_check is not enough to guarantee that the
remote wl_display will be flushed after we queue requests. We need to
explicitly flush, just like we do in our X11 code.
References: https://gitlab.freedesktop.org/wayland/wayland/-/issues/187
> backend/wayland: flush remote display

- examples/egl_common.c
Make `(config, context)_attribs` `const` just to be on the safe side.
I wanted to do this in the last PR that I made for `egl_common.c`, but then it got merged, so I thought "forget about it", but now I've made this PR, so... Yeah.
> examples/egl_common: make attribs const

- include/xwayland/xwm.h
- xwayland/selection/dnd.c
- xwayland/selection/selection.c
- xwayland/xwm.c
As before, this PR is based on https://github.com/swaywm/wlroots/pull/2701 and only the last commit contains changes.
---
Previously, the clipboard and primary selections shared the same window.
This was racey, and could have led to pasting failures.
On xfixes selection owner change notification, the logic for requesting
the supported mimetypes of the new owner's selection looks like:
```c
xcb_convert_selection(
xwm->xcb_conn,
selection->window,
selection->atom,
xwm->atoms[TARGETS],
xwm->atoms[WL_SELECTION],
selection->timestamp
);
```
This means: ask the selection owner to write its TARGETS for the
`selection->atom` selection (one of PRIMARY, CLIPBOARD, DND_SELECTION)
to `selection->window`'s WL_SELECTION atom.
However, `selection->window` is shared for both PRIMARY and CLIPBOARD …
> xwayland/selection: use one target window per selection

- backend/drm/backend.c
- backend/libinput/tablet_tool.c
- backend/multi/backend.c
- backend/session/session.c
- backend/wayland/backend.c
- backend/wayland/output.c
- backend/wayland/seat.c
- include/wlr/interfaces/wlr_tablet_tool.h
- include/wlr/types/wlr_tablet_tool.h
- include/xcursor/cursor_data.h
- include/xwayland/xwm.h
- types/tablet_v2/wlr_tablet_v2.c
- types/tablet_v2/wlr_tablet_v2_pad.c
- types/tablet_v2/wlr_tablet_v2_tablet.c
- types/tablet_v2/wlr_tablet_v2_tool.c
- types/wlr_input_inhibitor.c
- types/wlr_tablet_tool.c
- xcursor/wlr_xcursor.c
- xwayland/xwm.c
The three commits in this PR add const (and in one case, file-static) qualifiers to global variables that were missing them.
* The list of atoms in xwayland/xwm.c
* The cursor data used by the default theme
* A number of "implementation function lists", which include structs of function pointers for wlroots backends, and for handling Wayland events and requests
Since `xwayland/xwm.h` is an internal header, and `wlr/interfaces/wlr_tablet_tool.h` and `wlr/types/wlr_tablet_tool.h`  are unstable API, I presume changing types slightly is fine.
I found these variables by checking ``objdump -t libwlroots.so.7 | grep "\.data" ``for initialized global variables not linked as read only. I did not look at tinywl or any of the examples.
* * *
Breaking change: `wlr_tablet.impl` is now `const`.
> Add static+const qualifiers

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- backend/x11/backend.c
- backend/x11/meson.build
- backend/x11/output.c
- include/backend/x11.h
- xwayland/xwm.c
Note that I played around with returning 'false' for non-NULL textures. However this did not have the desired effect. But I don't think it's a shortcoming of this change. The native cursor was correctly removed in that case though.
> backend/x11: Use native cursors

- include/types/wlr_region.h
`resource_list` no longer exists for regions. Remove the last remaining description of what it was responsible for.
> region: remove leftover description of resource_list

- types/tablet_v2/wlr_tablet_v2_tool.c
Store the previously focused surface in `state->focused` as well as in
`state->original` when starting an implicit grab. That way at the end
of an implicit grab, the detection whether the grab started and ended
on the same surface works as intended, even if the original surface was
never left at all.
Some notes on how I found this bug:
I use Xournal++ to write down handwritten notes on my tablet. Xournal++ changes the cursor to a small unobtrusive dot when writing with a stylus. However, under sway, I always got short blinks of the original cursor when ending a stroke. Some investigation shows lots of the following errors:
`[sway/input/tablet.c:117] denying request to set cursor from unfocused client`
This is due to the focused surface temporarily being `null` after the stylus tip goes up …
> tablet_v2: Fix implicit grab end detection

- README.md
- backend/x11/backend.c
- backend/x11/meson.build
- include/backend/x11.h
We don't need it anymore now that we've stopped using the EGL Xlib
platform.
> backend/x11: drop x11-xcb dependency

- types/wlr_xdg_foreign_v1.c
- types/wlr_xdg_foreign_v2.c
Fixes a double-free experienced with Firefox and xdg-desktop-portal-gtk (when closing a file dialog window):
```
==13501==ERROR: AddressSanitizer: attempting double-free on 0x60700019b7a0 in thread T0:
#0 0x7f6d0acc5b6f in __interceptor_free (/nix/store/sipmc4wnbcws4vahqlf5i06zz7xgnp23-gcc-10.2.0-lib/lib/libasan.so.6+0xacb6f)
#1 0x7f6d0a59e882 in finish_imported ../types/wlr_xdg_foreign_v1.c:162
#2 0x7f6d0a59e8e3 in xdg_imported_handle_resource_destroy ../types/wlr_xdg_foreign_v1.c:279
#3 0x7f6d0a5efdbe in destroy_resource (/nix/store/w6rq0kfag1yqb3pj0bi9g84nrv9nbckf-wayland-1.18.0/lib/libwayland-server.so.0+0x7dbe)
#4 0x7f6d0a5f04ff in wl_resource_destroy (/nix/store/w6rq0kfag1yqb3pj0bi9g84nrv9nbckf-wayland-1.18.0/lib/libwayland-server.so.0+0x84ff)
#5 0x7f6d0a59eb30 in …
```
> xdg-foreign: Make imported object inert when exported is destroyed

- backend/x11/output.c
- include/render/gles2.h
- include/render/shm_format.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- include/wlr/render/wlr_texture.h
- include/wlr/types/wlr_linux_dmabuf_v1.h
- include/wlr/types/wlr_output.h
- render/gles2/pixel_format.c
- render/gles2/renderer.c
- render/gles2/texture.c
- render/meson.build
- render/shm_format.c
- render/wlr_renderer.c
- render/wlr_texture.c
- types/wlr_output.c
- types/wlr_screencopy_v1.c
Replace everything with DRM fourcc formats and use it as the only source of truth for format definitions.
Closes: https://github.com/swaywm/wlroots/issues/2738
> Stop using wl_shm_format

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- README.md
- include/meson.build
- include/xwayland/meson.build
- xwayland/meson.build
- xwayland/server.c
Check that the pkg-config file is available. This will be required
in the future to check whether xwayland supports features such as
-listenfd, -initfd or -verbose.
This effectively makes our relationship with xwayland closer to what
a dynamic library is: checked at build-time, but can be overridden
at run-time.
Instead of walking PATH like a previous proposal (#2314), this one
checks that the Xwayland path specified in the pkg-config file
exists.
I think this is a reasonable compromise:
- Users that don't have Xwayland installed system-wide won't get
a bogus DISPLAY env variable set up.
- Users that have WLR_XWAYLAND set won't be affected by this check.
- Users that have Xwayland installed system-wide and a different
Xwayland in their PATH still get their custom Xwayland.
- Users that …
> xwayland: check executable exists on init, take 2

- xcursor/xcursor.c
Fix false positive stringop-truncation warning/error with GCC 10 on s390x by indicating GCC to explicitly ignore this case, as it is clearly a false positive (NUL is set in the following line).
This allow the compilation to succeed with -Werror on.
Fixes: https://github.com/swaywm/wlroots/issues/2018
> Fix #2018, false positive -Wstringop-truncation warning

- backend/x11/output.c
When a new texture is set, the hotspot may actually belong to the
previous texture and be out of bounds. Rather than incur X errors for
these, clamp the hotspot to be inside of the texture.
This fixes weston examples updating their cursors (e.g.
weston-eventdemo).
> backend/x11: clamp hotspot to texture bounds

- backend/drm/drm.c
- backend/drm/renderer.c
- backend/wayland/output.c
- backend/x11/output.c
- include/render/gles2.h
- render/gles2/renderer.c
- types/wlr_output.c
Improve transform matrix calculation in `wlr_output` to help the pixman rendering process.
* * *
Breaking change: the projection has been moved from `wlr_output.transform_matrix` to the GLES2 renderer. Compositors using `wlr_output.transform_matrix` only with the GLES2 renderer don't need an update.
> Update output transform matrix calculation

- backend/drm/drm.c
- backend/wayland/output.c
- backend/x11/output.c
- types/wlr_output.c
We need to adjust the second translation depending on the transform
we applied.
Fixes: 9601a2abf024 ("output: improve transform matrix calculation"
Closes: https://github.com/swaywm/wlroots/issues/2774
cc @bl4ckb0ne
> output: fix transform matrix for 90/270 rotations

- render/egl.c
Mesa may advertise EGL_MESA_device_software even when hardware
drivers are in use [1]. Demote the error to a warning until the Mesa
bug is fixed.
[1]: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4178
References: https://github.com/swaywm/wlroots/pull/2689
cc @bl4ckb0ne
> render/egl: don't fail on EGL_MESA_device_software

- backend/session/libseat.c
Without INFO, the user won't know what seat backend got selected, only which ones failed.
> backend/session/libseat: Set loglevel to INFO

- README.md
- docs/env_vars.md
The optional dependency wasn't mentioned in the readme, and the env docs incorrectly listed "seatd" as being the WLR_SESSION selector for it.
> docs: Minor libseat corrections

- types/wlr_linux_dmabuf_v1.c
Some clients (like Xwayland) will fallback to wl_drm if the compositor
doesn't explicitly advertise support for implicit modifiers, even when
the compositor supports explicit modifiers. This behavior sounds correct
from a protocol point of view.
> linux-dmabuf-v1: always advertise support for implicit modifiers

- include/wlr/types/wlr_surface.h
- types/wlr_surface.c
Cached states allow a surface commit to be delayed. They are useful for:
- Subsurfaces
- The upcoming transactions protocol [1]
- Explicit synchronization
[1]: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/26
Prior art: https://github.com/swaywm/wlroots/pull/1685
> surface: introduce cached states

- backend/wayland/backend.c
- render/egl.c
Split render/display setups have two separate devices: one display-only
with a primary node, and one render-only with a render node. However
in these cases the EGL implementation and the Wayland compositor will
advertise the display device instead of the render device [1]. The EGL
implementation will magically open the render device when the display
device is passed in.
So just pass the display device as if it were a render device. Maybe in
the future Mesa will advertise the render device instead and we'll be
able to remove this workaround.
[1]: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4178
> render/egl, backend/wayland: add workaround for split render/display setups

- README.md
- include/wlr/config.h.in
- include/xwayland/xwm.h
- meson.build
- meson_options.txt
- xwayland/meson.build
- xwayland/xwm.c
> xwayland: ICCCM improvements

- backend/session/meson.build
This allows libseat to be compiled as a Meson subproject when it's
not installed system-wide. This can ease development and compilation
on distributions where libseat isn't packaged.
> build: add subproject fallback for libseat

- include/backend/drm/drm.h
- include/types/wlr_keyboard.h
- include/wlr/types/wlr_keyboard_group.h
Because the included file here is in the same directory as itself, it is
more appropriate to write only the file name, and doing so can help
unify the code style of the entire project.
> Remove unnecessary directories in the include path

- include/types/wlr_surface.h
- include/wlr/types/wlr_surface.h
- types/wlr_compositor.c
- types/wlr_surface.c
Same as https://github.com/swaywm/wlroots/pull/2662.
* * *
Breaking change: `wlr_surface_create` has been removed.
> surface: make wlr_surface_create private

- render/egl.c
All backends use the GBM platform. We can't use it to figure out
whether the DRM backend is used anymore.
Let's just try to always request a high-priority EGL context. Failing
to do so is not fatal.
> render/egl: stop relying on platform for high priority

- util/meson.build
We can just use to_int() instead of having two if branches.
> build: simplify HAS_LIBUUID definition

- include/xwayland/meson.build
This fixes the following warning:
WARNING: Project targeting '>=0.56.0' but tried to use feature deprecated since '0.56.0': Dependency.get_pkgconfig_variable. use Dependency.get_variable(pkgconfig : ...) instead
> build: use get_variable instead of get_pkgconfig_variable

- backend/drm/atomic.c
- backend/drm/drm.c
This allows callers to use wlr_output_test to figure out whether a
buffer can be scanned out prior to committing the output.
References: https://github.com/swaywm/wlroots/issues/2250
> backend/drm: use atomic test-only commits for direct scan-out

- render/egl.c
See the https://www.khronos.org/registry/EGL/extensions/KHR/EGL_KHR_platform_gbm.txt
example code. In use EGL_PLATFORM_GBM_KHR before, should be check the
"EGL_KHR_platform_gbm" extension.
> render/egl: check "EGL_KHR_platform_gbm" for EGL_PLATFORM_GBM_KHR platform

- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- render/gles2/renderer.c
- render/wlr_renderer.c
It can be replaced with wlr_renderer_bind_buffer. blit_dmabuf is
broken as-is (dies on an assertion).
If we want to optimize blits with e.g. `glBlitFramebuffer`, a function that deals with `wlr_buffer`s would be better (as it would better integrate with the Pixman renderer for instance).
~~Depends on https://github.com/swaywm/wlroots/pull/2788~~
> render: drop wlr_renderer_blit_dmabuf

- include/wlr/render/egl.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_texture.h
- render/egl.c
- render/gles2/texture.c
- render/wlr_texture.c
This is unused in wlroots, and the use-cases for compositors are
pretty niche since they can access the original DMA-BUF via the
wlr_buffer.
> render: remove wlr_texture_to_dmabuf

- include/render/gles2.h
- include/wlr/render/interface.h
- include/wlr/render/wlr_renderer.h
- render/gles2/renderer.c
- render/gles2/shaders.c
- render/wlr_renderer.c
For anything more complicated than quads, compositors can easily
ship their own shaders.
Closes: https://github.com/swaywm/wlroots/issues/2759
> render: drop support for ellipses

- backend/x11/backend.c
- include/backend/x11.h
- include/wlr/config.h.in
- include/xwayland/xwm.h
- meson.build
- xwayland/meson.build
- xwayland/xwm.c
wlroots' dependency on this library doesn't change the features
exposed to compositors. It's purely a wlroots implementation detail.
Thus downstream compositors shouldn't really care about it.
> Remove WLR_HAS_XCB_ERRORS

- backend/session/meson.build
When libseat is built as a subproject, we're not interested in
building the server or the man pages.
> build: disable libseat subproject server and man pages

- backend/drm/drm.c
- render/gbm_allocator.c
- render/gles2/renderer.c
PRIME support for buffer sharing has become mandatory since the renderer
rewrite. Make sure we check for the appropriate capabilities in backend,
allocator and renderer.
See also #2819.
> drm: check for PRIME support

- backend/backend.c
- backend/multi/backend.c
- include/backend/backend.h
- include/wlr/backend.h
- render/wlr_renderer.c
As discussed on IRC: The get_drm_fd was made available in an internal header with a53ab146f. Move it now to the public header so consumers opting in to the unstable interfaces can make use of it.
> backend: move get_drm_fd to public interface

- xcursor/xcursor.c
This reverts commit 7dffe9339bf8a92a556098d86712c4c38ac95226, which introduced
another linter error with -O3:
error: ‘strncat’ specified bound 7 equals source length [-Werror=stringop-overflow=]
and replace strncpy() with memcpy() to suppress the original warning.
> Fix #2777, compiler false positive in xcursor.c

- render/gles2/texture.c
The compositor shouldn't write to client buffers if the client
attaches a DMA-BUF to a wl_surface, then attaches a shm buffer.
Make gles2_texture_write_pixels return an error to prevent this
from happening.
> render/gles2: prevent imported DMA-BUF textures from being mutated

- backend/wayland/backend.c
- backend/wayland/output.c
- include/backend/wayland.h
- include/render/pixman.h
- include/render/shm_allocator.h
- include/types/wlr_buffer.h
- include/wlr/render/pixman.h
- include/wlr/types/wlr_buffer.h
- meson.build
- render/meson.build
- render/pixman/meson.build
- render/pixman/pixel_format.c
- render/pixman/renderer.c
- render/shm_allocator.c
- render/wlr_renderer.c
- types/wlr_buffer.c
Closes: https://github.com/swaywm/wlroots/issues/2399
> Pixman renderer

- examples/multi-pointer.c
- examples/output-layout.c
- examples/pointer.c
- examples/rotation.c
- examples/simple.c
- examples/tablet.c
- examples/touch.c
- tinywl/tinywl.c
If a NULL xkb_rule_names pointer is passed to
xkb_keymap_new_from_names, libxkbcommon will default to reading
the XKB_* env variables. So there's no need to do it ourselves.
Also s/xkb_map_new_from_names/xkb_keymap_new_from_names/ since the
latter is more consistent with the returned struct name.
[1]: https://xkbcommon.org/doc/current/structxkb__rule__names.html
> Stop specifying xkb_rule_names

- include/wlr/types/wlr_linux_dmabuf_v1.h
- types/wlr_linux_dmabuf_v1.c
- types/wlr_screencopy_v1.c
Previously, the same struct was used for linux-dmabuf-v1 params
and buffer. This made the whole logic a little bit awkward, because
a wlr_dmabuf_v1_buffer could either be still being constructed, or
be a complete buffer.
Introduce a separate wlr_linux_buffer_params_v1 struct for buffer
params still being constructed. Once the params are complete (ie.
once the create request is sent), the params struct is destroyed
and the buffer struct is created.
This will help with #2664 as well.
> linux-dmabuf-v1: split params and buffer

- examples/meson.build
- examples/quads.c
- examples/rotation.c
This examples uses `wlr_render_quad_with_matrix` to render coloured
squares on the screen, and uses the rotation to make them spin on their
middle.
The code is copy pasted from `examples/rotation`, with the arguments removed and a new `output_frame_notify` so maintenance should not be too hard.
The idea behind this is to have an example that uses `render_quad` without having a tablet around.
> examples: introduce quads example

- render/wlr_texture.c
Assert that the case found in #2771 does not happen.
> render: Assert that texture dimensions are > 0

- README.md
- backend/x11/backend.c
- backend/x11/meson.build
- backend/x11/output.c
- include/backend/x11.h
Closes #2866.
This doesn't work in Xwayland for me, since `shared_pixmaps` is 0 when running there.
I'm not sure if that's the case for Xwayland in general.
> backend/x11: add support for shm buffers

- types/wlr_output.c
This fixes a crash when calling wlr_output_test() on a headless
output.
Closes: https://github.com/swaywm/sway/issues/6213
> output: correctly handle outputs without a test() impl

- include/render/gles2.h
- include/render/pixman.h
- render/gles2/renderer.c
- render/gles2/texture.c
- render/pixman/renderer.c
This prevents some leaks and stray `wlr_texture`s that don't have a renderer anymore.
cc @bl4ckb0ne for the pixman bits
> render: destroy textures with renderer

- render/egl.c
Partial revert of https://github.com/swaywm/wlroots/pull/2783/commits/60d2e44485db3e73c3863e2ea2def074f4b29825 since [mesa #4178][1] has been fixed.
We must wait the next mesa bugfix release before merging this.
[1]: https://gitlab.freedesktop.org/mesa/mesa/-/issues/4178
> render/egl: fail on EGL_MESA_device_software

- xcursor/wlr_xcursor.c
Stop listing all available cursors each time a cursor theme is
loaded. They can be obtained from the CLI instead, e.g.
ls /usr/share/icons/Adwaita/cursors
> xcursor: quiet debug log

- backend/drm/backend.c
- backend/drm/drm.c
- backend/session/session.c
- include/backend/drm/drm.h
- include/wlr/backend/session.h
This is half of the GPU hotplug work, see https://github.com/swaywm/wlroots/pull/2423.
To test:
```
udevadm trigger --verbose --type=devices --action=remove --subsystem-match=drm --property-match="MINOR=1"
```
> backend/drm: handle unplug event

- backend/drm/util.c
This reverts commit f9f90b417366581b58d806956c9b2099417ed4b3.
gbm_bo_get_modifier may return a modifier in these cases:
- The kernel doesn't support modifiers but Mesa does
- WLR_DRM_NO_MODIFIERS=1 is set
However, in both of these cases, the gbm_bo has been allocated
without modifiers.
There is already a check in drm_fb_create for modifiers:
wlr_drm_format_set_has will make sure buffers with an explicit
modifier will be rejected if the DRM backend doesn't support them.
So no need for an additional check in get_fb_for_bo.
Closes: https://github.com/swaywm/wlroots/issues/2896
> Revert "backend/drm: fail instead of stripping a modifier"

- include/types/wlr_buffer.h
- include/wlr/types/wlr_buffer.h
- render/pixman/renderer.c
- render/shm_allocator.c
- types/wlr_buffer.c
Allow wlr_buffer_impl.get_data_ptr to return a format.
This allows the Pixman renderer to not care about get_dmabuf/get_shm,
and only care about get_data_ptr. This will also help with [1], because
client wl_shm buffers can't implement get_shm.
[1]: https://github.com/swaywm/wlroots/pull/2892
References: https://github.com/swaywm/wlroots/issues/2864
cc @bl4ckb0ne
> buffer: add format param to get_data_ptr

- backend/backend.c
- backend/drm/backend.c
- backend/drm/renderer.c
- backend/headless/backend.c
- backend/wayland/backend.c
- backend/x11/backend.c
- include/backend/backend.h
- include/backend/drm/renderer.h
- include/render/allocator.h
- include/render/gbm_allocator.h
- include/render/shm_allocator.h
- include/render/wlr_renderer.h
- include/types/wlr_buffer.h
- include/wlr/backend/interface.h
- include/wlr/render/interface.h
- render/allocator.c
- render/gbm_allocator.c
- render/gles2/renderer.c
- render/pixman/renderer.c
- render/shm_allocator.c
- render/wlr_renderer.c
Implements https://github.com/swaywm/wlroots/issues/2861
> wlr_allocator_autocreate

- backend/drm/renderer.c
- include/render/allocator.h
- render/allocator.c
On multi-GPU setups, there is a primary DRM backend and secondary
DRM backends. wlr_backend_get_drm_fd will always return the parent
DRM FD even on secondary backends, so that users always use the
primary device for rendering.
However, for our internal rendering we want to use the secondary
device. Use allocator_autocreate_with_drm_fd to make sure the
allocator will create buffers on the secondary device.
We do something similar to ensure our internal rendering will
happen on the secondary device with renderer_autocreate_with_drm_fd.
Fixes: cc1b663 ("backend: use wlr_allocator_autocreate")
cc @bl4ckb0ne
> backend/drm: fix allocator DRM FD on multi-GPU setups

- render/gles2/renderer.c
Rendering a wlr_texture with a different wlr_renderer is invalid.
Add an assert to make sure this doesn't happen.
> render/gles2: assert texture comes from the same renderer

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
- include/backend/drm/iface.h
This is a re-do of #2704, but with the changes better split up and a few enhancements.
> backend/drm: take output state as arg in commit functions, take 2

- backend/drm/drm.c
This was not required before, and the assert is tripped by simple
display disable/enable cycles.
Closes: https://github.com/swaywm/wlroots/issues/2904
> backend/drm: Do not require mode conmit on enable

- xcursor/xcursor.c
The libXcursor fix for CVE-2013-2003 has never been imported into
wlroots, leaving it vulnerable to it.
Changing the argument type to an unsigned type is an effective merge of
Ilja Van Sprundel's commit in libXcursor.
Proof of Concept (compile with address sanitizer):
$ mkdir -p ~/.local/share/icons/poc/cursors
$ base64 -d <<< WGN1chAAAAAAAAAA/////w== > \
~/.local/share/icons/poc/cursors/poc
$ echo "seat seat0 xcursor_theme poc 10" > ~/poc-config
$ sway -c ~/poc-config
> xcursor: fix CVE-2013-2003

- xwayland/server.c
eec2e1d3b16ba40c85483badcc7809277274ce5d introduced logic to use the Xwayland
binary discovered via pkg-config.
While the newly introduced checks correctly used the binary from pkg-config,
the actual execution still used the previous PATH-search logic.
> xwayland: actually use Xwayland from pkg-config

- include/wlr/render/wlr_texture.h
- render/wlr_texture.c
Users can just access the width/height fields directly.
> render: remove wlr_texture_get_size

- render/gles2/renderer.c
- render/gles2/texture.c
We require the ext in the renderer init function.
> render/gles2: remove unnecessary EGL import ext checks

- backend/drm/renderer.c
- include/render/gles2.h
- include/render/wlr_texture.h
- include/wlr/render/interface.h
- include/wlr/types/wlr_linux_dmabuf_v1.h
- render/gles2/renderer.c
- render/gles2/texture.c
- render/wlr_texture.c
- types/wlr_buffer.c
- types/wlr_linux_dmabuf_v1.c
- types/wlr_screencopy_v1.c
If a client creates a `wl_buffer` and attaches it to a `wl_surface`, there's a good chance they're going to re-use it.
References: https://github.com/swaywm/wlroots/issues/2664
> Cache and re-use DMA-BUF textures

- render/gbm_allocator.c
- render/meson.build
This ensures we get the right FD for multi-planar buffers.
Depends on [1].
[1]: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5442
> render/gbm_allocator: add support for gbm_bo_get_fd_for_plane

- render/pixman/renderer.c
When the matrix doesn't have a rotation, we can avoid a sqrt() call.
Tested with Sway's tabbed containers.
cc @bl4ckb0ne
> render/pixman: avoid sqrt() in render_quad without rotation

- render/wlr_texture.c
Some formats have a byte-per-pixel lower than 1. Let's not encode
an arbitrary limitation into the wlr_renderer API.
> render: relax stride check in wlr_texture_from_pixels

- backend/backend.c
- backend/drm/backend.c
- backend/headless/backend.c
- backend/headless/output.c
- backend/libinput/backend.c
- backend/multi/backend.c
- backend/noop/backend.c
- backend/wayland/backend.c
- backend/wayland/output.c
- backend/x11/backend.c
- backend/x11/output.c
- include/backend/backend.h
- include/backend/headless.h
- include/backend/wayland.h
- include/backend/x11.h
- include/wlr/backend.h
- include/wlr/backend/interface.h
This is part of #2505 split out in a separate PR, and rebased on top of #2884.
Instead of explicitly creating the renderer and allocator inside the backends, do it in common code. The motivation is:
- Nothing of this is backend-specific. With #2505 backends won't need to care about renderers and allocators anymore (except for the edge case of DRM multi-GPU).
- Allow #2507 and #2505 to get access to a renderer and an allocator outside of the backend for creating swapchains and rendering.
With this PR, backends now get access to the renderer and allocator via `wlr_backend_get_renderer` and `backend_get_allocator`. This makes it pretty obvious that a lot of the backend logic no longer needs to live in the backend, and can be moved in common code as done in #2507 and #2505.
The DRM backend is …
> backend: add common renderer and allocator creation

- include/render/gles2.h
- render/gles2/renderer.c
- render/gles2/texture.c
When importing a DMA-BUF wlr_buffer as a wlr_texture, the GLES2
renderer caches the result, in case the buffer is used for texturing
again in the future. When the wlr_texture is destroyed by the caller,
the wlr_buffer is unref'ed, but the wlr_gles2_texture is kept around.
This is fine because wlr_gles2_texture listens for wlr_buffer's destroy
event to avoid any use-after-free.
However, with this logic wlr_texture_destroy doesn't "really" destroy
the wlr_gles2_texture. It just decrements the wlr_buffer ref'count.
Each wlr_texture_destroy call must have a matching prior
wlr_texture_create_from_buffer call or the ref'counting will go south.
Wehn destroying the renderer, we don't want to decrement any wlr_buffer
ref'count. Instead, we want to go through any cached wlr_gles2_texture
and …
> render/gles2: fix texture cleanup on destroy

- backend/wayland/backend.c
- backend/x11/backend.c
- include/render/allocator.h
- render/allocator.c
- render/drm_dumb_allocator.c
- render/gbm_allocator.c
- render/shm_allocator.c
When picking a format, the backend needs to know whether the
buffers allocated by the allocator will be DMA-BUFs or shared
memory. So far, the backend used the renderer's supported
buffer types to guess this information.
This is pretty fragile: renderers in general don't care about the
SHM cap (they only care about the DATA_PTR one). Additionally,
nothing stops a renderer from supporting both DMA-BUFs and shared
memory, but this would break the backend's guess.
Instead, use wlr_allocator.buffer_caps. This is more reliable since
the buffers created with the allocator are guaranteed to have these
caps.
cc @bl4ckb0ne 
* * *
Not a breaking change since `wlr_allocator` is still a private wlroots API.
> backend: stop using renderer to get the buffer type

- render/wlr_renderer.c
This probably already felt apart, but let's make it explicit that
this is not allowed.
> render: disallow wlr_renderer_destroy while rendering

- include/wlr/render/wlr_renderer.h
- render/wlr_renderer.c
This allows compositors to choose a wlr_buffer to render to. This
is a less awkward interface than having to call bind_buffer() before
and after begin() and end().
Closes: https://github.com/swaywm/wlroots/issues/2618
cc @dos1: would something like this be useful to phosh?
> render: add wlr_renderer_begin_with_buffer

- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/renderer.c
- backend/wayland/output.c
- backend/x11/output.c
- include/backend/drm/drm.h
- include/backend/drm/renderer.h
- include/backend/wayland.h
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- types/wlr_output.c
We want to remove the rendering bits from the backends. To do so, we need to stop feeding them `wlr_texture` for cursors.
Switch to `wlr_buffer`. The common `wlr_output` code is responsible for allocating and rendering cursor textures.
This will also help with [explicit synchronization](https://github.com/swaywm/wlroots/pull/2070).
TODO:
~~Depends on https://github.com/swaywm/wlroots/pull/2498~~
~~Depends on https://github.com/swaywm/wlroots/pull/2556~~
~~Depends on https://github.com/swaywm/wlroots/pull/2613~~
~~Depends on https://github.com/swaywm/wlroots/pull/2901~~
~~Depends on https://github.com/swaywm/wlroots/pull/2947~~
* * *
Breaking change for backends: `wlr_output_impl.set_cursor` now takes a `wlr_buffer`. Backends should no longer allocate a swapchain for the cursor. Backends …
> output: take a wlr_buffer in set_cursor

- include/wlr/types/wlr_xdg_activation_v1.h
- meson.build
- protocol/meson.build
- types/meson.build
- types/wlr_xdg_activation_v1.c
See https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/50
> xdg-activation-v1: new protocol implementation

- include/wlr/types/wlr_surface.h
- types/wlr_surface.c
Prior to this commit, subsurfaces could only be placed above their
parent. Any place_{above,below} request involving the parent would
fail with a protocol error.
However the Wayland protocol allows using the parent surface in the
place_{above,below} requests, and allows subsurfaces to be placed
below their parent.
Weston's implementation adds a dummy wl_list node in the subsurface
list. However this is potentially dangerous: iterating the list
requires making sure the dummy wl_list node is checked for, otherwise
memory corruption will happen.
Instead, split the list in two: one for subsurfaces above the parent,
the other for subsurfaces below.
Tested with wleird's subsurfaces demo client.
Closes: https://github.com/swaywm/wlroots/issues/1865
* * *
Breaking change: …
> surface: allow placing subsurfaces below parent

- include/render/pixman.h
- include/types/wlr_buffer.h
- include/wlr/types/wlr_buffer.h
- render/allocator.c
- render/drm_dumb_allocator.c
- render/gles2/texture.c
- render/pixman/renderer.c
- render/shm_allocator.c
- types/wlr_buffer.c
This allows the Pixman renderer to stop `memcpy`'ing textures.
Depends on: https://github.com/swaywm/wlroots/pull/2851
cc @bl4ckb0ne
> render/pixman: avoid copy when creating textures

- backend/headless/backend.c
- backend/headless/output.c
- backend/wayland/backend.c
- backend/wayland/output.c
- backend/x11/backend.c
- backend/x11/output.c
- include/backend/headless.h
- include/backend/wayland.h
- include/backend/x11.h
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- types/wlr_output.c
Move the allocator/renderer-related code out of backends into the common backend/output code for everything related to the primary buffer. This process shouldn't break any compositor.
The DRM backend has not been migrated yet, because it requires more work.
References: https://github.com/swaywm/wlroots/issues/1352
~~Depends on: https://github.com/swaywm/wlroots/pull/2496~~
~~Depends on: https://github.com/swaywm/wlroots/pull/2498~~
~~Depends on: https://github.com/swaywm/wlroots/pull/2495~~
~~Depends on: https://github.com/swaywm/wlroots/pull/2511~~
~~Depends on: https://github.com/swaywm/wlroots/pull/2507~~
~~Depends on: https://github.com/swaywm/wlroots/pull/2561~~
> Move primary wlr_swapchain handling out of backends

- include/wlr/types/wlr_matrix.h
This function has baked-in GL assumptions. Compositors shouldn't
need to use it.
> matrix: deprecate wlr_matrix_projection

- backend/drm/renderer.c
- backend/x11/output.c
- include/render/wlr_renderer.h
- render/wlr_renderer.c
- types/wlr_output.c
- types/wlr_screencopy_v1.c
Make it clear this function is a private wlroots API and will stay that way. The only reason why it exists is to allow `wlr_output_attach_render` to continue to be supported.
Convert all other call sites to `wlr_renderer_begin_with_buffer`, which is the future-proof public API.
> render: drop wlr_ prefix from wlr_renderer_bind_buffer

- include/wlr/render/interface.h
- render/gles2/renderer.c
- render/pixman/renderer.c
- render/wlr_renderer.c
The types of buffers supported by the renderer might depend on the
renderer's instance. For instance, a renderer might only support
DMA-BUFs if the necessary EGL extensions are available.
Pass the wlr_renderer to get_buffer_caps so that the renderer can
perform such checks.
Fixes: 982498fab3c4 ("render: introduce renderer_get_render_buffer_caps")
> render: add missing arg to wlr_renderer_impl.get_buffer_caps

- types/wlr_output.c
On commit failure, we need to unbind the back buffer from the
renderer.
This fixes assertions triggered on commits following a failed commit
where the compositor called wlr_output_attach_render.
> output: reset back buffer on failed commit

- backend/drm/drm.c
The set_cursor() hook is a little bit special: it's not really
synchronized to commit() or test(). Once set_cursor() returns true,
the new cursor is part of the current state.
This fixes a state where wlr_drm_connector.cursor_enabled is true
but there is no FB available. This is triggered by set_cursor()
followed by a failed commit(), which resets pending_fb.
We should definitely fix the output interface to make the cursor part
of the pending state, but that's a more involved change.
> backend/drm: populate cursor plane's current_fb

- backend/session/session.c
- meson.build
This moves the magic incantation into libdrm and is clearer. See
[1] for details.
While at it, fixup the doc comment and improve logging.
[1]: https://gitlab.freedesktop.org/mesa/drm/-/commit/523b3658aa8efa746417e916c987de23740ce313
> backend/session: use drmIsKMS

- backend/session/session.c
Instead of hardcoding the string "card", use DRM_PRIMARY_MINOR_NAME.
Some systems may use another prefix, e.g. OpenBSD uses "drm" instead.
> backend/session: use DRM_PRIMARY_MINOR_NAME

- .builds/alpine.yml
- .builds/archlinux.yml
- meson.build
Static libraries are not affected by our symbol file, so private symbols
are globally visible by default.
Use objcopy to make symbols that we do not want to expose local.
Closes: https://github.com/swaywm/wlroots/issues/1892
Closes: https://github.com/swaywm/wlroots/issues/2952
> meson: Make private static library symbols local

- wlroots.syms
Let's expose all of our prefixed symbols. Instead of trying to have
fine-grained rules and only expose our public API, let's just expose
all symbols that won't cause a conflict.
Users won't be able to use the symbols without a proper header
declaration anyways. If they go through the process of re-defining
wlr_ symbols manually, that's on them if their build breaks.
This aligns the rules with [1].
[1]: https://github.com/swaywm/wlroots/pull/2969
> build: simplify version script

- meson.build
This reverts commit 28d23ba6bda4f799b8d6689555cd33a40adda17e.
The prelinking and symbol filtering pass breaks builds with link-time
optimization enabled.
Building static libs in CI should be fine, so I didn't revert that.
cc @emersion
> Revert "meson: Make private static library symbols local"

- backend/drm/drm.c
- backend/headless/output.c
- backend/noop/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
Right now, when a new output state field is added, all backends by
default won't reject it. This means we need to add new checks to
each and every backend when we introduce a new state field.
Instead, introduce a bitmask of supported output state fields in
each backend, and error out if the user has submitted an unknown
field.
Some fields don't need any backend involvment to work. These are
listed in WLR_OUTPUT_STATE_BACKEND_OPTIONAL as a convenience.
> backend: add output state allow-lists

- examples/meson.build
This reverts commit 9796abccedef881e99d293a2658c4da9466acd88.
This Meson issue has been fixed upstream for a while. We require 0.56.0 so we should never hit an unpatched Meson.
> Revert "build: workaround for meson disabler object not working with if not"

- include/render/egl.h
- include/wlr/render/egl.h
- render/egl.c
- render/gles2/renderer.c
- render/gles2/texture.c
The wlr_egl functions are mostly used internally by the GLES2
renderer. Let's reduce our API surface a bit by hiding them. If
there are good use-cases for one of these, we can always make them
public again.
The functions mutating the current EGL context are not made private
because e.g. Wayfire uses them.
cc @ammen99
> render/egl: make most functions private

- .builds/alpine.yml
- .builds/archlinux.yml
- .builds/freebsd.yml
- meson.build
New warnings can be hard to notice in CI, since CI will just pass in
that case. Meson sometimes uses warnings for important mistakes, e.g.
invalid option.
Let's turn warnings into errors so that we can spot these more easily.
* * *
Note, we need to bump the Meson version to get rid of the `meson.build_root()` warning.
> ci: make Meson warnings fatal

- include/types/wlr_surface.h
- include/wlr/types/wlr_surface.h
- types/wlr_compositor.c
- types/wlr_surface.c
Same as [1], but for wlr_subsurface.
[1]: https://github.com/swaywm/wlroots/pull/2814
> surface: make wlr_subsurface_create private

- types/wlr_surface.c
There are still many situations where the buffer scale is not
divisible by scale. The fix will require a tad more work, so
let's just log the client error for now and continue handling
the surface commit as usual.
Closes: https://github.com/swaywm/sway/issues/6352
> surface: accept commits with buffer size not divisible by scale

- include/render/egl.h
- render/egl.c
- render/gles2/renderer.c
We never create an EGL context with the platform set to something
other than EGL_PLATFORM_GBM_KHR. Let's simplify wlr_egl_create by
taking a DRM FD instead of a (platform, remote_display) tuple.
This hides the internal details of creating an EGL context for a
specific device. This will allow us to transparently use the device
platform (#2671) when the time comes.
~~Depends on: https://github.com/swaywm/wlroots/pull/2985~~
cc @bl4ckb0ne
> render/egl: replace wlr_egl_create with wlr_egl_create_with_drm_fd

- types/tablet_v2/wlr_tablet_v2_pad.c
- types/tablet_v2/wlr_tablet_v2_tool.c
These were hardcoded to 1. Instead, create the resource with the
version of the parent object.
> tablet-v2: fix pad and tool object versions

- include/render/gles2.h
- include/types/wlr_buffer.h
- include/wlr/render/interface.h
- render/gles2/renderer.c
- render/gles2/texture.c
- render/pixman/renderer.c
- render/wlr_renderer.c
- render/wlr_texture.c
- types/wlr_buffer.c
Instead, unify all of the code-paths with `wlr_renderer_impl.texture_from_buffer`.
> render: drop wlr_renderer_impl.texture_from_{pixels,dmabuf}

- backend/drm/backend.c
- backend/drm/drm.c
- backend/headless/backend.c
- backend/wayland/backend.c
- backend/wayland/output.c
- backend/x11/backend.c
- backend/x11/output.c
- include/types/wlr_buffer.h
- include/wlr/types/wlr_buffer.h
- render/allocator.c
- render/drm_dumb_allocator.c
- render/gbm_allocator.c
- render/gles2/renderer.c
- render/shm_allocator.c
Custom backends and renderers need to implement `wlr_backend_impl.get_buffer_caps` and `wlr_renderer_impl.get_render_buffer_caps`. They can't if `enum wlr_buffer_cap` isn't made public.
* * *
This was an oversight I made during the 0.14.0 release. I'd say it would make sense to backport to 0.14.1.
> buffer: make enum wlr_buffer_cap public

- backend/libinput/tablet_tool.c
Instead of using a single-field wl_list, let's just use a wl_array.
~~Depends on: https://github.com/swaywm/wlroots/pull/3002~~
> backend/libinput: use wl_array for wlr_libinput_tablet.tools

- types/wlr_surface.c
We were bumping the pending sequence number after emitting the
commit event, so commit handlers were seeing inconsistent state
where current.seq == pending.seq. This prevents commit handlers
from immediately locking the pending state.
Fix this by bumping the pending sequence number before firing the
commit event.
> surface: allow locking pending state in commit handler

- include/wlr/types/wlr_matrix.h
- include/wlr/util/edges.h
- include/wlr/util/log.h
- include/wlr/util/region.h
- include/wlr/xcursor.h
The mailing list has never been used.
I think listing the deprecated functions in the release notes is
enough. I'd rather not add the burden of maintaining a separate
communication medium.
> Remove reference to the announce mailing list

- include/wlr/types/wlr_region.h
As per [1], the mailing list isn't used anymore.
[1]: https://github.com/swaywm/wlroots/pull/3016
Fixes: 82af6e720870 ("region: stabilize interface")
> region: drop leftover reference to the mailing list

- backend/drm/drm.c
Populating wlr_drm_plane.current_fb messes up the buffer's locking.
The previous buffer is released while it's still being displayed
on-screen.
Instead, stop clearing the pending cursor FB on a failed commit. The
pending cursor FB will remain for the next commit.
Fixes: 6c3d080 ("backend/drm: populate cursor plane's current_fb")
> backend/drm: don't clear pending cursor FB on failed commit 

- types/wlr_output_damage.c
When wlr_output.swapchain is used instead of the backend's, the
buffer_type will be set to SCANOUT even if wlr_output_attach_render
has been called. This tricks wlr_output_damage into thinking the
whole output needs to be repainted.
Workaround this issue by forcing buffer_type to RENDER when the
output has a back-buffer set.
Will clean all of that up when removing the precommit event handler
altogether.
This commit fixes damage tracking on the Wayland, X11 and headless
backends.
> output-damage: fix output swapchain handling

- backend/libinput/events.c
- backend/libinput/touch.c
- backend/wayland/seat.c
- backend/x11/input_device.c
- include/backend/libinput.h
- include/wlr/types/wlr_cursor.h
- include/wlr/types/wlr_seat.h
- include/wlr/types/wlr_touch.h
- types/seat/wlr_seat_touch.c
- types/wlr_cursor.c
- types/wlr_touch.c
- types/xdg_shell/wlr_xdg_popup.c
Up until now, we were (wrongly) sending `wl_touch.frame` events after every touch event. This prevents clients from being able to group multiple touch events together and recognize touch gestures.
Fix this by allowing backends to send touch frame events.
* * *
Breaking change: compositors now need to listen to touch frame events and call `wlr_seat_touch_notify_frame`.
Sway patch: https://github.com/swaywm/sway/pull/6353
> Add support for touch frame events

- backend/libinput/backend.c
- backend/libinput/events.c
- backend/libinput/tablet_tool.c
- types/tablet_v2/wlr_tablet_v2_pad.c
- types/tablet_v2/wlr_tablet_v2_tablet.c
- types/wlr_tablet_pad.c
- types/wlr_tablet_tool.c
[1] and [2] have introduced new wl_array usage in wlroots, but
contains a mistake: wl_array_for_each iterates over pointers to
the wl_array entries, not over entries themselves.
Fix all wl_array_for_each call sites. Name the variables "ptr"
to avoid confusion.
Found via ASan:
==148752==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x602000214111 in thread T0
#0 0x7f6ff2235f19 in __interceptor_free /build/gcc/src/gcc/libsanitizer/asan/asan_malloc_linux.cpp:127
#1 0x7f6ff1c04004 in wlr_tablet_destroy ../subprojects/wlroots/types/wlr_tablet_tool.c:24
#2 0x7f6ff1b8463c in wlr_input_device_destroy ../subprojects/wlroots/types/wlr_input_device.c:51
#3 0x7f6ff1ab9941 in backend_destroy ../subprojects/wlroots/backend/wayland/backend.c:306
#4 0x7f6ff1a68323 in …
> Fix invalid uses of wl_array_for_each

- backend/drm/backend.c
Some buffers need to be copied across GPUs. Such buffers need to be
allocated with a format and modifier suitable for both the source
and the destination.
When explicit modifiers aren't supported, we were forcing the buffers
to be allocated with a linear layout, because implicit modifiers
aren't portable across GPUs. All is well with this case.
When explicit modifiers are supported, we were advertising the whole
list of destination modifiers, in the hope that the source might
have some in common and might be able to allocate a buffer with a
more optimized layout. This works well if the source supports explicit
modifiers. However, if the source doesn't, then wlr_drm_format_intersect
will fallback to implicit modifiers, and everything goes boom: the
source uses a GPU-specific tiling and the …
> backend/drm: force linear layout for multi-GPU buffers

- render/pixman/renderer.c
A texture is opaque when it does *not* have alpha.
Fixes https://github.com/swaywm/wlroots/issues/2907
> render/pixman: fix texture_is_opaque()

- backend/drm/atomic.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/iface.h
The legacy checks will get a bit more complicated with https://github.com/swaywm/wlroots/pull/2903.
> backend/drm: move legacy-specific checks to legacy.c

- include/wlr/types/wlr_buffer.h
- include/wlr/types/wlr_surface.h
- types/wlr_buffer.c
- types/wlr_surface.c
Fixes #3015 
~~Turns out `wlr_surface_state` buffer member can be avoided, I'm fairly sure there's a way to make it hold only a `wlr_buffer` and get the `buffer_resource`, `buffer_width` and `buffer_height` from it without having to duplicate them. Let me know if you want that in this patch or in another one.~~
cc @emersion 
* * *
Breaking change:
- `wlr_resource_get_buffer_size` has been removed.
- `wlr_client_buffer_import` has been split into two functions: `wlr_buffer_from_resource` and `wlr_client_buffer_create`.
> Remove wlr_resource_get_buffer_size

- include/wlr/types/wlr_buffer.h
- types/wlr_buffer.c
> buffer: drop wlr_client_buffer.resource

- include/render/gles2.h
- include/wlr/render/egl.h
- render/egl.c
- render/gles2/renderer.c
Khronos refers to extensions with their namespace as a prefix in
uppercase. Change our naming to align with Khronos conventions.
This also makes grepping easier.
> render/{egl,gles2}: rename wlr_egl.exts to better match Khronos

- render/gles2/renderer.c
- render/gles2/texture.c
We don't always need to enable blending: when the texture doesn't
have alpha or when the color is opaque, we can disable it.
> render/gles2: disable blending opportunistically

- include/wlr/types/wlr_buffer.h
- types/wlr_buffer.c
- types/wlr_surface.c
This function doesn't need the wl_resource anymore.
In the failure paths, wlr_buffer_unlock in surface_apply_damage
will take care of sending wl_buffer.release.
> buffer: drop resource arg from wlr_client_buffer_create

- backend/drm/drm.c
- backend/headless/output.c
- include/backend/headless.h
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- types/wlr_export_dmabuf_v1.c
- types/wlr_output.c
When wlr_output manages its own swap-chain, there's no need to
hook into the backend to grab DMA-BUFs. Instead, maintain a
`wlr_output.front_buffer` field with the latest committed buffer.
> output: add generic wlr_output_export_dmabuf implementation 

- backend/wayland/seat.c
We were missing destroy calls for gestures, and we were only
destroying the relative pointer on output destroy.
> backend/wayland: properly cleanup wlr_wl_pointer

- include/wlr/types/wlr_seat.h
- types/seat/wlr_seat_pointer.c
Only one wl_pointer.axis_source event is permitted per frame, according
to the Wayland specification.
Fixes https://github.com/swaywm/wlroots/issues/2973
> input/pointer: send axis source once per frame

- backend/drm/backend.c
wl_event_loop_add_fd was called with a NULL data argument, but the
function expects the data argument to be set to the wlr_drm_backend.
Fixes: 053ebe7c278b ("backend/drm: terminate display on drmHandleEvent failure")
> backend/drm: fix NULL data in handle_drm_event

- include/types/wlr_buffer.h
- types/wlr_buffer.c
The first time wlr_buffer_from_resource is called with a wl_buffer
resource that originates from wl_shm, create a new
wlr_shm_client_buffer as usual. If wlr_buffer_from_resource is called
multiple times, re-use the existing wlr_shm_client_buffer.
This commit changes how the wlr_shm_client_buffer lifetime is managed:
previously it was destroyed as soon as the wlr_buffer was released.
With this commit it's destroyed when the wl_buffer resource is.
Apart from de-duplicating wlr_shm_client_buffer creations, this allows
to easily track when a wlr_shm_client_buffer is re-used. This is useful
for the renderer and the backends, e.g. the Pixman renderer can keep
using the same Pixman image if the buffer is re-used. In the future,
this will also allow to re-use resources in the Wayland and X11 …
> buffer: re-use wlr_shm_client_buffer

- backend/drm/backend.c
- backend/drm/drm.c
- include/backend/drm/drm.h
This is the cause of the spurious "drmHandleEvent failed" messages
at exit. restore_drm_outputs calls handle_drm_event in a loop without
checking whether the FD is readable, so drmHandleEvent ends up with a
short read (0 bytes) and returns an error.
The loop's goal is to wait for all queued page-flip events to complete,
to allow drmModeSetCrtc calls to succeed without EBUSY. The
drmModeSetCrtc calls are supposed to restore whatever KMS state we were
started with. But it's not clear from my PoV that restoring the KMS
state on exit is desirable.
KMS clients are supposed to save and restore the (full) KMS state on VT
switch, but not on exit. Leaving our KMS state on exit avoids unnecessary
modesets and allows flicker-free transitions between clients. See [1]
for more details, and note that …
> backend/drm: stop restoring CRTCs on exit

- include/wlr/render/interface.h
- render/gles2/renderer.c
- render/wlr_renderer.c
Now that we have our own wl_drm implementation, there's no reason
to provide custom renderer hooks to init a wl_display in the
interface. We can just initialize the wl_display generically,
depending on the renderer capabilities.
> render: drop wlr_renderer_impl.init_wl_display

- render/egl.c
Without setting this the EGL implementation is allowed to perform
destructive actions on the buffer when imported: its contents
become undefined.
This is mostly a pedantic change, because Mesa processes the attrib
and does absolutely nothing with it.
> render/egl: set EGL_IMAGE_PRESERVED_KHR

- include/wlr/render/egl.h
- render/egl.c
This EGL extension has been added in [1]. The upsides are:
- We directly get a render node, instead of having to convert the
primary node name to a render node name.
- If EGL_DRM_RENDER_NODE_FILE_EXT returns NULL, that means there is
no render node being used by the driver.
[1]: https://github.com/KhronosGroup/EGL-Registry/pull/127
Mesa patch: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/11797
libglvnd patch: https://gitlab.freedesktop.org/glvnd/libglvnd/-/merge_requests/245
> render/egl: add support for EGL_EXT_device_drm_render_node

- include/wlr/render/egl.h
- render/egl.c
This function relies on the extension EGL_WL_bind_wayland_display being present. If not, the creation of `wlr_egl` will fallback on using GBM.
I see in the logs that the client extensions are being printed twice, would you prefer the fallback to be in `wlr_egl_create_from_drm_fd` rather than in `wlr_renderer_autocreate_with_drm_fd`?
I also I fixed an issue regarding `eglMakeCurrent` when processing the error, `EGL_NO_DISPLAY` is not a valid display handle and will cause an `EGL_BAD_DISPLAY` error.
> As with other commands taking EGLDisplay parameters, if display is not a valid EGLDisplay handle, an EGL_BAD_DISPLAY error is generated. (Some implementations have chosen to allow EGL_NO_DISPLAY as a valid display parameter for eglMakeCurrent. This behavior is not portable to all EGL …
> render/egl: initialize wlr_egl with EGL_PLATFORM_DEVICE_EXT

- util/time.c
This fixes static linking with libseat.
Closes #3072
> util/time: make NSEC_PER_SEC static

- backend/backend.c
- backend/drm/backend.c
- backend/drm/drm.c
- backend/drm/legacy.c
- backend/drm/renderer.c
- include/backend/drm/drm.h
- include/backend/drm/renderer.h
- include/wlr/backend.h
- types/wlr_output.c
This is https://github.com/swaywm/wlroots/pull/2505 but with the DRM backend changes too. This essentially completes the plan laid out in https://github.com/swaywm/wlroots/issues/1352, while keeping the existing compositor-facing `wlr_output` API intact.
~~Depends on: https://github.com/swaywm/wlroots/pull/2505~~
~~Depends on: https://github.com/swaywm/wlroots/pull/2829~~
~~Depends on: https://github.com/swaywm/wlroots/pull/3035~~
> backend/drm: move primary wlr_swapchain handling out of backend

- backend/drm/drm.c
These are bools but should be pointers.
> backend/drm: fix wrong type for get_cursor_format return values

- backend/drm/drm.c
- backend/noop/output.c
- backend/wayland/output.c
- backend/x11/output.c
- include/wlr/interfaces/wlr_output.h
- include/wlr/types/wlr_output.h
- include/wlr/types/wlr_output_damage.h
- types/wlr_output.c
- types/wlr_output_damage.c
~~Depends on: https://github.com/swaywm/wlroots/pull/2903~~
> Drop legacy output APIs

- render/gles2/pixel_format.c
- render/pixel_format.c
On little-endian, we can enable pixel formats which don't use
gl_type = GL_UNSIGNED_BYTE. See [1].
[1]: https://afrantzis.com/pixel-format-guide/
> render/gles2: add support for some 24 and 16-bit formats

- include/render/gles2.h
- render/gles2/pixel_format.c
- render/gles2/renderer.c
- render/pixel_format.c
In addition to adding support for XBGR2101010, ABGR2101010, XBGR16161616F, and ABGR16161616F, this PR introduces a mechanism to filter the list of available shm formats based on the GL extensions that the renderer supports. See also commit messages.
I have a modified weston-simple-shm which supports these formats at https://gitlab.freedesktop.org/mstoeckl/weston/-/tree/simple-shm-10 ; there is also https://gitlab.freedesktop.org/jadahl/wayland-test-clients/blob/master/gradient-test.c .
> Add support for some 10-bit and FP16 formats

- types/wlr_viewporter.c
According to the viewport protocol, upon [`wp_viewport::destroy()`][1]:
> The associated `wl_surface`'s crop and scale state is removed.
> The change is applied on the next `wl_surface.commit`.
Therefore, `wp_viewport_destroy(viewport)` should remove all viewport state.
Currently, wlroots does not remove the crop and scale state. Instead, a client must do:
```c
wl_fixed_t clear = wl_fixed_from_int(-1);
wp_viewport_set_source(viewport, clear, clear, clear, clear);
wp_viewport_set_destination(viewport, -1, -1);
wp_viewport_destroy(viewport);
```
This commit adds the necessary logic into `viewport_destroy` and makes wlroots comply with the protocol.
[1]: https://github.com/wayland-project/wayland-protocols/blob/main/stable/viewporter/viewporter.xml#L129-L134
> viewporter: remove crop and scale state upon destruction

- backend/drm/drm.c
- types/wlr_output.c
The kernel orders the mode list from highest to lowest. Preserve
this ordering in the wlr_output.modes list.
> backend/drm: preserve mode order from kernel

- render/pixel_format.c
- render/pixman/pixel_format.c
Add a bunch of new formats for Pixman: a few missing 32-bit ones,
some 16-bit and 32-bit formats as well.
Mostly based on a Weston patch [1].
[1]: https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/664
cc @mstoeckl @bl4ckb0ne
> render/pixman/pixel_format: add more formats

- backend/drm/drm.c
When testing a modeset, make sure the caller has also provided a
buffer. This allows df0e75ba05e2 ("output: try skipping buffer
allocation if the backend allows it") to work as expected with the
DRM backend.
Closes: https://github.com/swaywm/wlroots/issues/3086
> backend/drm: require buffer on modeset in drm_connector_test

- types/seat/wlr_seat_keyboard.c
The protocol allows compositors to not send any keymap to Wayland
clients. Handle a keymap-less keyboard correctly by sending
WL_KEYBOARD_KEYMAP_FORMAT_NO_KEYMAP instead of erroring out in the
mmap call.
> seat: allow compositors to not load a keymap

- .builds/archlinux.yml
Add a very basic smoke test which uses VKMS to fire up the DRM
backend.
It's a bit hacky atm:
- `sleep` could be replaced with polling for the socket to be created
- `chmod` is necessary because the dumb buffer allocator needs to open the card directly
> ci: add smoke test

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
The protocol specifies that all requests (aside from destroy) are
ignored after the compositor sends the closed event. Therefore,
destroying the wlroots object and rendering the resource inert
when sending the closed event keeps things simpler for wlroots and
compositors.
> layer-shell: replace close() with destroy() 

- backend/libinput/tablet_tool.c
Looks like this instance was missed in e035f2b9c42b39e3eff37d0fe98bfa6422877d7a.
Fixes #3110.
> input/tablet: fix `wl_array_for_each` usage on tablet proximity

- xwayland/xwayland.c
If XWayland terminates for any reason, `xwm_set_cursor()` has to to be called again, so the cursor has to stick around.
> xwayland: do not free cursor in handle_server_ready()

- backend/drm/drm.c
This should fix the following backtrace, seen on my desktop with one
output disabled:
```
#0  atomic_crtc_commit (conn=0x270f5c0, state=0x270f6d0, flags=0, test_only=<optimized out>) at ../backend/drm/atomic.c:178
drm = 0x1ae9c10
output = 0x270f5c0
crtc = 0x0
modeset = false
active = false
mode_id = 43989232
gamma_lut = 0
prev_vrr_enabled = <optimized out>
vrr_enabled = <optimized out>
atom = {req = 0x270f5c0, failed = 48}
ok = <optimized out>
#1  0x00007f1104f33128 in drm_crtc_commit (conn=conn@entry=0x270f5c0, state=state@entry=0x270f6d0, flags=flags@entry=0, test_only=test_only@entry=true) at ../backend/drm/drm.c:339
__PRETTY_FUNCTION__ = "drm_crtc_commit"
drm = <optimized out>
crtc = 0x0
ok = <optimized out>
#2  0x00007f1104f34e6c in drm_connector_test (output=output@entry=0x270f5c0) …
```
> backend/drm: return true on test if no crtc

- backend/drm/drm.c
- types/wlr_output.c
Alternative to #3118. We now check if the output is enabled before emitting the frame event in `wlr_output_send_frame` and revert the commit within the DRM backend which added a similar check but forgot to reset `frame_pending` to false.
Closes #3118
> Handle output enabled in wlr_output_send_frame

- types/wlr_surface.c
If a subsurface is being placed below a subsurface right above it, this
should be a noop. However, `node` pointed to the subsurface that was
moved, which resulted in `subsurface->parent_pending_link` being
inserted into itself, breaking parent's pending subsurface list.
This commit separates finding the requested node and getting it's `prev`
field, fixing the issue.
> surface: fix place_below handling

- backend/drm/atomic.c
- backend/drm/properties.c
- include/backend/drm/properties.h
This allows the kernel to access our buffer damage. Some drivers
can take advantage of this, e.g. for PSR2 panels (Panel Self
Refresh) or for transfer over USB.
Closes: https://github.com/swaywm/wlroots/issues/1267
> backend/drm: add support for FB_DAMAGE_CLIPS

- backend/drm/drm.c
To retrieve the formats, an allocated crtc is required. If there is no
currently no crtc available, try to allocate it. This reproducable by
having a disabled output and going through a suspend cycle with amdgpu.
On start CRTCs look like this:
```
00:00:00.588 [DEBUG] [wlr] [backend/drm/drm.c:1099] Reallocating CRTCs
00:00:00.588 [DEBUG] [wlr] [backend/drm/drm.c:1110] State before reallocation:
00:00:00.588 [DEBUG] [wlr] [backend/drm/drm.c:1116]   'DP-1' crtc=0 state=1 desired_enabled=1
00:00:00.588 [DEBUG] [wlr] [backend/drm/drm.c:1116]   'DP-2' crtc=1 state=1 desired_enabled=1
00:00:00.588 [DEBUG] [wlr] [backend/drm/drm.c:1116]   'HDMI-A-1' crtc=-1 state=0 desired_enabled=0
00:00:00.588 [DEBUG] [wlr] [backend/drm/drm.c:1116]   'HDMI-A-2' crtc=-1 state=0 desired_enabled=0
00:00:00.588 …
```
> backend/drm: try to allocate crtc for formats

- backend/drm/drm.c
The Coordinated Video Timings (CVT) spec [1] defines two types of
timings: the "CVT standard CRT" timings and the "CVT reduced blanking"
timings (see section 3.6).
The standard CRT timings include pauses in the video stream to allow
CRT displays to reposition their electron beam at the end of each
horizontal scan line [2]. While this was desirable a few decades ago,
nowadays we can just generate a CVT reduced blanking timing by default.
wlroots users can still set full custom DRM modes via
wlr_drm_connector_add_mode.
[1]: https://glenwing.github.io/docs/VESA-CVT-1.2.pdf
[2]: https://en.wikipedia.org/wiki/Coordinated_Video_Timings#Reduced_blanking
> backend/drm: generate CVT reduced modes

- backend/drm/atomic.c
- backend/drm/backend.c
- backend/drm/bo_handle_table.c
- backend/drm/drm.c
- backend/drm/legacy.c
- backend/drm/meson.build
- backend/drm/renderer.c
- backend/drm/util.c
- include/backend/drm/bo_handle_table.h
- include/backend/drm/drm.h
- include/backend/drm/iface.h
- include/backend/drm/renderer.h
- include/backend/drm/util.h
- render/egl.c
Using GBM to import DRM dumb buffers tends to not work well. By
using GBM we're calling some driver-specific functions in Mesa.
These functions check whether Mesa can work with the buffer.
Sometimes Mesa has requirements which differ from DRM dumb buffers
and the GBM import will fail (e.g. on amdgpu).
Instead, drop GBM and use drmPrimeFDToHandle directly. But there's
a twist: BO handles are not ref'counted by the kernel and need to
be ref'counted in user-space [1]. libdrm usually performs this
bookkeeping and is used under-the-hood by Mesa.
We can't re-use libdrm for this task without using driver-specific
APIs. So let's just re-implement the ref'counting logic in wlroots.
The wlroots implementation is inspired from amdgpu's in libdrm [2].
Closes: #2916
[1]: …
> backend/drm: introduce wlr_drm_bo_handle_table

- xwayland/xwm.c
Currently, upon activating a surface, wlroots restacks it on top of all
others.
This may not necessarily be correct from the calling compositor's point
of view, where having focus may not imply being top-of-stack (e.g.,
focusing a window under an always-on-top window).
In Sway's case, this means that focused tiling windows will always be on
top of floating windows, at least in the order communicated to X11 apps.
This breaks drag-and-drop from a focused tiling X11 window to a floating
X11 window which partially obscures the former.
This is a breaking change; to retain the previous behavior, users that
were calling
wlr_xwayland_surface_activate(xsurface, true);
should now be calling
wlr_xwayland_surface_activate(xsurface, true);
wlr_xwayland_surface_restack(xsurface, NULL, …
> xwm: do not restack surfaces on activation 

- CONTRIBUTING.md
This is shamelessly stolen from Weston [1].
It's been a while we've transitioned away from merge commits and
work-style commit history, so it'd be nice to mention this in the
docs.
[1]: https://gitlab.freedesktop.org/wayland/weston/-/blob/main/CONTRIBUTING.md#formatting-and-separating-commits
> contributing: add new section about commit log

- include/wlr/types/wlr_scene.h
- types/wlr_scene.c
If nodes are arranged in a tree rather than at a single level (e.g. if #3128 is merged), then it makes sense to have a way to move them to a completely different parent in addition to moving up or down among siblings.
> scene: add node reparent function

- render/allocator/allocator.c
- render/allocator/drm_dumb.c
- render/allocator/gbm.c
Using the same DRM file description for the DRM backend and for the
GBM allocator will result in GEM handle ref'counting issues [1].
Re-open the DRM FD to fix these issues.
[1]: https://gitlab.freedesktop.org/mesa/drm/-/merge_requests/110
> render/allocator: re-open GBM FD

- CONTRIBUTING.md
Commits named "Fix #XXX" make it pretty complicated to figure out
exactly what the commit is doing from the shortlog. A better place
for issue references is in the extended commit message.
> contributing: don't reference issues in commit first line

- examples/scene-graph.c
- include/wlr/types/wlr_scene.h
- types/wlr_scene.c
Adds a new scene-graph node type for rendering solid-colored rectangles, which may be useful for simple window decorations. A little reworking was needed in the scene-graph implementation, since it would break the assumption that every rendered node has an associated surface.
Thoughts/questions:
1. Should there be a `wlr_scene_rect_set_size()` and/or `wlr_scene_rect_set_color()` function, or is it straghtforward enough to change the fields directly? (Maybe damage tracking considerations tip the scale toward functions?)
1. How should RECTs interact with `wlr_scene_node_surface_at()`?
1. Would it complicate the scene-graph example too much if I were to add a handler for wlr_surface.commit? It would allow us to get the surface dimensions and draw something less ugly than what I currently …
> scene: add RECT node type

- backend/drm/drm.c
drm_surface_blit returns NULL on error. This can happen e.g. when
the source buffer cannot be imported into EGL.
Closes: https://github.com/swaywm/wlroots/issues/3154
> backend/drm: handle drm_surface_blit errors

- render/allocator/gbm.c
Makes it easier to find out which branch is taken when debugging
issues like [1].
[1]: https://github.com/swaywm/wlroots/issues/3156
> render/allocator/gbm: add log message for gbm_bo_get_fd_for_plane

- include/util/shm.h
- include/wlr/types/wlr_keyboard.h
- types/seat/wlr_seat_keyboard.c
- types/wlr_keyboard.c
- util/shm.c
If a client supports wl_keyboard version 7, no need to allocate
and copy a new keymap file. We can use a read-only file instead.
> seat: avoid copying the keymap for each client 

- include/wlr/types/wlr_surface.h
- types/wlr_surface.c
A bunch of commits from #3143, including #3120 and #3122.
cc @emersion 
- `wlr_subsurface.parent_link` is removed
Instead, use `wlr_subsurface.current.link`; same goes for `wlr_subsurface.parent_pending_link`.
- `wlr_surface.subsurfaces_{above,below}` is moved to `wlr_surface_state`
Use `wlr_surface.current.subsurfaces_{above,below}`.
> Minor surface refactor

- include/wlr/types/wlr_surface.h
- types/wlr_surface.c
- types/wlr_viewporter.c
- types/xdg_shell/wlr_xdg_surface.c
- xwayland/xwm.c
Instead, use wlr_surface_state.buffer only.
~~Depends on: https://github.com/swaywm/wlroots/pull/3104~~
~~Depends on: https://github.com/swaywm/wlroots/pull/3103~~
> surface: drop wlr_surface_state.buffer_resource

- types/wlr_surface.c
Fixes: ba0525c5c08b ("surface: drop wlr_surface_state.buffer_resource")
Closes: https://github.com/swaywm/wlroots/issues/3173
> surface: fix abort on NULL buffer attach

- backend/drm/atomic.c
- backend/drm/drm.c
- backend/drm/legacy.c
- include/backend/drm/drm.h
- include/backend/drm/iface.h
Previously, we were copying wlr_output_state on the stack and
patching it up to be guaranteed to have a proper drmModeModeInfo
stored in it (and not a custom mode). Also, we had a bunch of
helpers deriving DRM-specific information from the generic
wlr_output_state.
Copying the wlr_output_state worked fine so far, but with output
layers we'll be getting a wl_list in there. An empty wl_list stores
two pointers to itself, copying it on the stack blindly results in
infinite loops in wl_list_for_each.
To fix this, rework our DRM backend to stop copying wlr_output_state,
instead add a new struct wlr_drm_connector_state which holds both
the wlr_output_state and additional DRM-specific information.
> backend/drm: introduce wlr_drm_connector_state

- backend/drm/drm.c
Constify drmModeConnector while at it.
> backend/drm: drop unused arg from get_possible_crtcs

- backend/drm/drm.c
- include/backend/drm/drm.h
Modesets require a buffer. The DRM backend tried to auto-enable
outputs when a CRTC becomes available in the past, but now that
fails because no buffer is available.
Instead of having this magic inside the DRM backend, a better
approach is to do it in the compositor or in an optional helper.
> backend/drm: drop attempt_enable_needs_modeset

- backend/drm/drm.c
- backend/drm/properties.c
- include/backend/drm/drm.h
- include/backend/drm/properties.h
- include/wlr/backend/drm.h
- include/wlr/types/wlr_drm_lease_v1.h
- include/wlr/types/wlr_output.h
- protocol/meson.build
- types/meson.build
- types/wlr_drm_lease_v1.c
This patch is a rework from the https://github.com/swaywm/wlroots/pull/2821
The implementation has been reviewed and rework to fit the requirements of the newest version of the [drm-lease-v1][1] protocol. It requires `WLR_DRM_DEVICES` to be set to your device which has the HMD plugged in, otherwise the offered output will not be available for leasing.
The patch has been tested with my own fork of [kmscube][2]
Closes: https://github.com/swaywm/wlroots/issues/1723
[1]: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/67
[2]: https://git.sr.ht/~bl4ckb0ne/kmscube
> Introduce wlr_drm_lease_v1

- examples/scene-graph.c
- include/wlr/types/wlr_scene.h
- types/wlr_scene.c
Introduce `wlr_scene_output` to have per-output state in the scene-graph.
I've decided to _not_ make `wlr_scene_output` a `wlr_scene_node` to make a clear cut between elements that are rendered on screen and viewports in the scene.
~~Depends on: https://github.com/swaywm/wlroots/pull/1966~~
Cage patch: https://github.com/Hjdskes/cage/pull/203
> scene: add support for damage tracking

- types/wlr_scene.c
On release builds, gcc detects a variable uninitialized error, and generates
a warning, which gets converted to an error due to -Werror:
```
cc -Ilibwlroots.so.10.p -I. -I.. -Iinclude -I../include -Iprotocol -I../protocol -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -O3 -DWLR_USE_UNSTABLE -DWLR_LITTLE_ENDIAN=1 -DWLR_BIG_ENDIAN=0 -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow -Wmissing-prototypes -Walloca -Wno-missing-braces -Wno-missing-field-initializers -Wno-unused-parameter -fmacro-prefix-map=../= -DHAS_GBM_BO_GET_FD_FOR_PLANE=0 …
```
> scene: fix compile error in release builds

- include/wlr/types/wlr_screencopy_v1.h
- types/wlr_screencopy_v1.c
This simplifies screencopy by copying pixels to shm in the commit callback rather than the pre-commit callback, so both dmabuf and shm buffers are handled in commit.
Because commit always happens after pre-commit, damage accumulation is also simplified because we no longer need to ascertain whether the damage callback or the frame-copy callback happened first.
Supersedes #2591
> Simpler screencopy

- include/types/wlr_buffer.h
- include/wlr/types/wlr_buffer.h
- render/allocator/drm_dumb.c
- render/allocator/shm.c
- render/gles2/texture.c
- render/pixman/renderer.c
- types/wlr_buffer.c
This allows callers to specify the operations they'll perform on
the returned data pointer. The motivations for this are:
- The upcoming Linux MAP_NOSIGBUS flag may only be usable on
read-only mappings.
- gbm_bo_map with GBM_BO_TRANSFER_READ hurts performance.
References: https://github.com/swaywm/wlroots/issues/2864
> buffer: add data_ptr access flags

- include/wlr/xwayland.h
- include/xwayland/xwm.h
- xwayland/xwayland.c
- xwayland/xwm.c
A launchee notifies with a "remove"¹ message when done starting up.
Catch these and forward to the compositor. This allows the compositor to
end the startup sequence that might have been started by another
protocol like xdg-activation.
We don't handle other messages since we expect the launcher to use a
wayland protocol like xdg-activation.
While `_NET_STARTUP_ID` helps to associate toplevels with startup-ids
this signals the end of the startup sequence.
This would e.g. allow to remove tokens that we got via xdg-activation and where the launchee started an x11 application. 
1) https://specifications.freedesktop.org/startup-notification-spec/startup-notification-latest.txt
Related: #2968 , #3136
> xwayland: Allow to retrieve startup-id via _NET_STARTUP_INFO

- include/types/wlr_xdg_shell.h
- include/wlr/types/wlr_xdg_shell.h
- types/xdg_shell/wlr_xdg_popup.c
- types/xdg_shell/wlr_xdg_surface.c
- types/xdg_shell/wlr_xdg_toplevel.c
*See individual commits.*
Fixes https://github.com/swaywm/wlroots/issues/2330
---
Preliminary work for https://github.com/swaywm/wlroots/pull/3151.
If this is fine, I'll make a similar PR for `wlr_layer_surface`.
This is a breaking change: compositors that used to check `wlr_xdg_toplevel.client_pending` will now have to check `wlr_xdg_toplevel.requested`.
> xdg-toplevel: refactor configure/state flow

- include/wlr/types/wlr_scene.h
- include/wlr/types/wlr_surface.h
- types/meson.build
- types/scene/subsurface_tree.c
- types/scene/wlr_scene.c
- types/wlr_surface.c
Representing each sub-surface as a scene-graph node allows us to remove a bunch of special cases. Damage tracking for instance works without any special casing for sub-surfaces.
~~Depends on: https://github.com/swaywm/wlroots/pull/1966~~
> scene: add support for sub-surfaces

- include/xwayland/meson.build
- protocol/meson.build
With recent-ish Meson we can stop repeating the variable name for
each provider.
> build: simplify get_variable calls

- backend/drm/drm.c
- backend/drm/properties.c
- include/backend/drm/properties.h
- include/wlr/backend/drm.h
Expose the panel orientation with wlr_drm_connector_get_panel_orientation.
Leave it to the compositor to consume this information and configure the
output accordingly.
Closes: https://github.com/swaywm/wlroots/issues/1581
Sway patch: https://github.com/swaywm/sway/pull/6534
> backend/drm: add support for panel orientation

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
Same logic as xdg-toplevel.
---
Preliminary work for #3151.
This is a breaking change: compositors that used to check `wlr_layer_surface_v1.client_pending` will now have to check `wlr_layer_surface_v1.pending`
> layer-shell: refactor configure/state flow

- include/wlr/types/wlr_layer_shell_v1.h
- types/wlr_layer_shell_v1.c
Supersedes https://github.com/swaywm/wlroots/pull/2794.
`current.committed` indicates what has changed since last commit, mirroring `wlr_surface_state` behavior from https://github.com/swaywm/wlroots/pull/3143.
Not sure if `actual_{width,height}` must have a flag too.
> layer-shell: add `committed` bitmask

- backend/libinput/events.c
- backend/libinput/meson.build
- backend/libinput/pointer.c
- backend/wayland/backend.c
- backend/wayland/seat.c
- include/backend/libinput.h
- include/backend/wayland.h
- include/wlr/types/wlr_cursor.h
- include/wlr/types/wlr_pointer.h
- include/wlr/types/wlr_pointer_gestures_v1.h
- protocol/meson.build
- types/wlr_cursor.c
- types/wlr_pointer.c
- types/wlr_pointer_gestures_v1.c
As touchpad touches are generally fully abstracted, a client cannot currently know when a user is interacting with the touchpad without moving. This is solved by hold gestures.
Hold gestures are notifications about one or more fingers being held down on the touchpad without significant movement.
Hold gestures are primarily designed for two interactions:
- Hold to interact: where a hold gesture is active for some time a menu could pop up, some object could be selected, etc.
- Hold to cancel: where e.g. kinetic scrolling is currently active, the start of a hold gesture can be used to stop the scroll.
Unlike swipe and pinch, hold gestures, by definition, do not have movement, so there is no need for an "update" stage in the gesture.
- …
> Hold gestures

- backend/backend.c
- backend/drm/backend.c
- backend/headless/backend.c
- backend/wayland/backend.c
- backend/x11/backend.c
Instead of ensuring the renderer and allocator are initialized in each
backend, do it in wlr_backend_autocreate. This allows compositors to
create backends without any renderer/allocator if they side-step
wlr_backend_autocreate.
Since the wlr_backend_get_renderer and backend_get_allocator end up
calling wlr_renderer_autocreate and wlr_allocator_autocreate, it sounds
like a good idea to centralize all of the opimionated bits in one place.
> backend: create renderer and allocator in wlr_backend_autocreate

- include/wlr/types/wlr_xdg_shell.h
- types/wlr_layer_shell_v1.c
- types/xdg_shell/wlr_xdg_popup.c
- types/xdg_shell/wlr_xdg_surface.c
This is preliminary work for properly handling cached state in
xdg-shell.
cc @vyivel
> xdg-shell: introduce wlr_xdg_surface_state

- backend/drm/drm.c
- backend/drm/renderer.c
- backend/x11/backend.c
- include/render/drm_format_set.h
- render/allocator/gbm.c
- render/drm_format_set.c
- render/egl.c
- types/wlr_linux_dmabuf_v1.c
See [1] for the motivation.
[1]: https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/75
> Require INVALID for implicit format modifiers

- backend/drm/drm.c
- backend/drm/renderer.c
- backend/x11/backend.c
- include/render/drm_format_set.h
- render/allocator/gbm.c
- render/drm_format_set.c
- render/egl.c
- types/wlr_linux_dmabuf_v1.c
Reverts swaywm/wlroots#2815
This is broken, see https://github.com/swaywm/wlroots/pull/2815#issuecomment-932069125.
> Revert "Require INVALID for implicit format modifiers"

- include/wlr/types/wlr_layer_shell_v1.h
- include/wlr/types/wlr_surface.h
- include/wlr/types/wlr_xdg_shell.h
- types/wlr_layer_shell_v1.c
- types/wlr_surface.c
- types/xdg_shell/wlr_xdg_surface.c
These functions are used mostly for rendering, where including unmapped surfaces is undesired.
This is a breaking change. However, few to no usages will have to be updated.
Tested in kiwmi (with https://github.com/buffet/kiwmi/commit/d69ccc7bdd6d2e6d2930bdbeadbc6c1d679e55a0 reverted) using [`tiosgz/wleird@subsubsurface:subsubsurface.c`](https://github.com/tiosgz/wleird/blob/subsubsurface/subsubsurface.c) (when the black surface hides, its subsurface \[the red one\] should also be hidden). Can also be tested in tinywl.
> for_each_surface and surface_at: skip unmapped surfaces

- render/allocator/allocator.c
If we aren't trying to create a dumb buffer allocator, and if the
DRM device has a render node (ie, not a split render/display SoC),
then we can use the render node instead of the primary node. This
should allow wlroots to run under seatd when the current user
doesn't have the permission to open primary nodes (logind has a
quirk to allow physically logged in users to open primary nodes).
> render/allocator: use render node if available in reopen_drm_node

- backend/backend.c
See [error log](https://github.com/swaywm/wlroots/files/7282201/wlroots-0.14.0.288.log) (`-Dbackends= -Drenderers= -Dxwayland=disabled`).
> backend: unbreak build without libinput package

- types/wlr_layer_shell_v1.c
- types/xdg_shell/wlr_xdg_surface.c
From what I understand, (confusingly named) `surface_apply_damage()` doesn't update `wlr_surface.buffer` if the upload has failed.
> Remove redundant NULL buffer checks
