backend/drm/backend.c, backend/drm/drm.c, example/main.c, include/backend/drm/drm.h, include/wlr/backend/drm.h
Initial support for DPMS. We don't support it per-output, as I don't really see the point of doing that.
=> DPMS support

session/logind.c
The old way of getting the session path was to simply append the session id to
the path "/org/freedesktop/login1/session/". However this is not the correct
path for newer systems like Fedora 26.
Instead, get the session path directly from the session manager from the id via
a dbus call to GetSession().
fixes #35
=> Correctly get session path

examples/compositor/wl_compositor.c, include/wlr/types/wlr_region.h, types/wlr_region.c
Complete the implementation of wlr_region_create and put it in the compositor.
=> implement compositor create region

render/gles2/renderer.c
This makes transparency work correctly.
fixes #56
=> enable gl blending

include/wlr/types/wlr_input_device.h, include/wlr/types/wlr_keyboard.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_pointer.h, include/wlr/types/wlr_surface.h, include/wlr/types/wlr_tablet_pad.h, include/wlr/types/wlr_tablet_tool.h, include/wlr/types/wlr_touch.h, include/wlr/types/wlr_xdg_shell_v6.h
=> Add user data to wlr_* structs

backend/drm/backend.c, backend/libinput/backend.c, backend/multi/backend.c, include/wlr/backend/drm.h, include/wlr/backend/libinput.h
=> Add backend detection functions

backend/libinput/events.c, backend/wayland/output.c, backend/wayland/wl_seat.c, include/wlr/types/wlr_region.h, include/wlr/util/list.h, render/gles2/renderer.c, types/wlr_input_device.c, types/wlr_keyboard.c, types/wlr_pointer.c, types/wlr_surface.c, types/wlr_tablet_pad.c, types/wlr_touch.c, util/list.c, xcursor/wlr_cursor.c
Inspired by the many cleanup contributions in the last days i fixed some (often self-caused) code style issues.
=> Fix style issues

backend/libinput/events.c, backend/libinput/keyboard.c, backend/multi/backend.c, backend/wayland/wl_seat.c, examples/compositor/main.c, examples/rotation.c, examples/tablet.c, examples/touch.c, render/gles2/renderer.c, render/gles2/texture.c, types/wlr_surface.c, types/wlr_xdg_shell_v6.c, util/list.c
=> Prevent alloc errors from crashing

backend/libinput/backend.c
This runs through events pending at init on initialization so we can
tell if some devices are available.
Note that with the way wlr_device_lists is managed, this checks that
there is at least one device we handle - it doesn't have to be a
keyboard, but there is at least a mouse or tablet_pad or something
that we care about.
Instead of failing inconditionally it might be better to leave the
decision to the user, e.g. add a "backend_has_devices" function to
call later.
(Tested by moving /dev/input off)
Fixes #24.
=> libinput: fail if no input found on init

backend/meson.build, backend/wayland/backend.c, backend/wayland/output.c, backend/wayland/registry.c, include/backend/wayland.h, protocol/meson.build
A few notes:
- I made a new list for protos to only generate some as client headers, we might want to always generate them and simplify that.
- as described in 2nd commit message, failing to create any display does not fail the backend, it probably should.
- I didn't find how to set a class, closest I could find was app_id. Should I? (there is a comment in the code)
Rest looks like it works ok.
=> Wayland backend xdg

examples/output-layout.c, examples/rotation.c, examples/shared.c, examples/shared.h
Put all the config parsing into shared.h so it is shared among the examples.
=> Refactor example output config

examples/config.c, examples/config.h, examples/output-layout.c, examples/pointer.c, include/wlr/types/wlr_output.h, include/wlr/types/wlr_output_layout.h, types/wlr_output.c, types/wlr_output_layout.c
=> implement output layout auto configuration

README.md
Use #sway-devel instead of #sway
=> Fix IRC channel link

types/wlr_cursor.c
Refactor wlr_cursor_device creation and destruction into their own functions.
Properly unsubscribe from signals in the wlr_cursor_device_destroy function.
=> wlr_cursor_device create and destroy

examples/compositor.c
TODO:
* render surfaces within the correct place in the layout
* focus a window with the pointer
* move a window with the pointer
=> compositor example basic cursor and layout

examples/compositor.c
Add data structures to compositor.c xdg-surface implementation that allows them
to be rendered in the correct position in the layout, spanning outputs if
necessary.
=> compositor.c: xdg-surface layout position

examples/compositor.c, include/wlr/types/wlr_seat.h, types/wlr_seat.c
Test by doing a mouse wheel over this [pointer test window](https://github.com/acrisci/scribbles/blob/master/gtk-window-helpers/pointer-helper.py).
=> wlr-seat cursor axis events

README.md, backend/meson.build, backend/session/logind.c, backend/session/session.c, meson.build, meson_options.txt
=> Add elogind support

examples/compositor.c, examples/output-layout.c, examples/rotation.c, examples/shared.c, examples/shared.h, include/wlr/types/wlr_seat.h, types/wlr_seat.c
TODO:
I'm going to try to take as much out of shared.c as makes sense.
=> [wip] wlr-seat-keyboard: keyboard events

backend/drm/backend.c, backend/drm/drm-atomic.c, backend/drm/drm-legacy.c, backend/drm/drm.c, include/backend/drm.h
This implements the basics of DisplayPort MST, as mentioned in #130. Fortunately, due to the way we were already doing things, not a lot of code actually needed to be added.
It _seems_ to work on my specific set of hardware, but this is something I really want others to test. I don't know if there are some assumptions I'm accidentally making based on my setup.
=> DisplayPort MST

examples/compositor.c, include/rootston/desktop.h, include/rootston/view.h, include/wlr/types/wlr_wl_shell.h, rootston/desktop.c, rootston/meson.build, rootston/wl_shell.c, types/wlr_wl_shell.c
Test client: https://gist.github.com/emersion/7e453eb466beb3c2958c042ccf239ba7
=> Add wl_shell to rootston

backend/backend.c, backend/drm/drm.c, backend/meson.build, backend/wayland/backend.c, backend/x11/backend.c, include/backend/x11.h, include/wlr/backend/x11.h, include/wlr/egl.h, meson.build, render/egl.c
An X11 backend.
It's deliberately been written to be pretty basic. I don't really care enough to write something fancy for this.
There is a segfault that sometimes happens when you click on a blank `examples/compositor`. I don't really know enough about that code to fix it.
=> X11 backend

include/rootston/view.h, include/wlr/types/wlr_wl_shell.h, include/wlr/xwayland.h, rootston/xwayland.c, xwayland/xwm.c, xwayland/xwm.h
See https://github.com/Cloudef/wlc/blob/master/src/xwayland/xwm.c#L135
=> Improve xwayland, batch 2

types/wlr_seat.c
=> wlr-seat: honor seat version

backend/drm/backend.c, backend/drm/drm.c, include/rootston/desktop.h, include/rootston/input.h, render/gles2/renderer.c, rootston/input.c, rootston/main.c, rootston/output.c, xwayland/xwm.c
Some definite memory leaks from valgrind
=> Fix memory leaks

include/rootston/config.h, include/rootston/input.h, rootston/config.c, rootston/cursor.c, rootston/desktop.c, rootston/output.c, rootston/rootston.ini.example
=> rootston: force move, resize and rotate

xwayland/xwm.c
=> Flush xwayland surface configuration

backend/drm/drm.c, backend/wayland/output.c, backend/wayland/wl_seat.c, examples/pointer.c, include/backend/wayland.h, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_output.h, rootston/output.c, types/wlr_cursor.c, types/wlr_output.c
=> Transform hotspot with cursor

rootston/cursor.c, rootston/xwayland.c, xwayland/xwm.c
=> Activate only active xwayland views

include/rootston/input.h, include/rootston/view.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/cursor.c, rootston/desktop.c, rootston/keyboard.c, rootston/rootston.ini.example, rootston/wl_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c, types/wlr_xdg_shell_v6.c
=> Add command to close views

backend/libinput/keyboard.c, backend/wayland/wl_seat.c, backend/x11/backend.c, include/wlr/interfaces/wlr_keyboard.h, include/wlr/types/wlr_keyboard.h, types/wlr_keyboard.c
=> Use xkb_state_update_mask() with Wayland backend

types/wlr_data_device_manager.c, types/wlr_data_source.c
The clipboard was mostly there but I fixed some bugs that it works.
Also fixed a related crash with drag and drop, but that support is lacking.
Also did some refactoring in preparation for some further work I need to do to this interface.
=> fix clipboard

backend/x11/backend.c
Support axis events in the X11 backend.
=> x11-backend: axis events

include/rootston/input.h, include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c
=> Center views in rootston

glgen.sh
I tried running this with dash (used by debian/ubuntu for their /bin/sh) and apparently this wasn't conforming.
=> Fix glgen to be more POSIX corformant

include/rootston/config.h, include/rootston/desktop.h, include/rootston/server.h, include/rootston/view.h, meson.build, meson_options.txt, rootston/config.c, rootston/desktop.c, rootston/meson.build, rootston/rootston.ini.example
=> Make Xwayland optional

include/wlr/types/wlr_surface.h, rootston/output.c, types/wlr_surface.c
An attempt to fix #226.
Quick testing didn't show any regressions, but I'm not very familiar with wayland architecture and thus do not know if any additional changes are necessary.
=> Upload texture on surface commit

types/wlr_output_layout.c
=> Fix wlr_output_layout_intersects

include/wlr/util/log.h
Apparently I am first guy to ever call this...
=> Fixed wrong function name

rootston/config.c, rootston/keyboard.c, rootston/rootston.ini.example
=> Window switching binding

include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/wl_shell.c, rootston/xwayland.c
Add `view_set_position()` which configures xwayland windows and fix various window initialization bugs.
fixes #292
=> rootston: view set position

types/wlr_xdg_shell_v6.c
Keeping an eye on this:
https://patchwork.freedesktop.org/patch/183214/
=> xdg-shell: send same-as-current configure if needed

include/wlr/types/wlr_output.h, types/wlr_output.c, types/wlr_output_layout.c
=> wl-output: send layout position

include/rootston/config.h, rootston/config.c, rootston/main.c
Allows specifying a command to run at startup.
Closes: #214
=> Add startup command option to rootston

types/wlr_compositor.c, types/wlr_data_device_manager.c, types/wlr_gamma_control.c, types/wlr_output.c, types/wlr_screenshooter.c, types/wlr_seat.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c
=> Remove interface version checks

backend/drm/drm.c, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_gamma_control.h, include/wlr/types/wlr_output.h, types/wlr_gamma_control.c, types/wlr_output.c
This includes:
* Style cleanup
* Properly free resources
* Listen for output destroy
(A test client is available here: https://github.com/Lourens-Rich/redshift)
=> Cleanup wlr_gamma_control

include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_seat.h, rootston/cursor.c, types/wlr_data_device.c, types/wlr_seat.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c
=> Rename wlr_seat_handle to wlr_seat_client

backend/x11/backend.c
=> bug: free x11 backend output in destroy

backend/drm/backend.c, backend/drm/drm.c, backend/libinput/backend.c, backend/libinput/events.c
=> Fix rootston exit segfaults

include/wlr/types/wlr_output.h, types/wlr_output.c
=> Add wlr_output.needs_swap

backend/libinput/backend.c, backend/wayland/output.c, backend/wayland/registry.c, xwayland/xwm.c
Sorry for bulking in the indentation fixes again, this was ready, is just one line, and I really cba making a separate PR.
=> Rootston: flush close event for xwayland

backend/libinput/backend.c, backend/multi/backend.c
A couple more shutdown fixes, and no more obvious leak I could see. Good job!
=> Shutdown ASAN fixes

include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c
=> Fix moving views when resizing below min size

include/wlr/types/wlr_data_device.h, types/wlr_data_device.c
=> Adds wlr_data_device_manager destructor

types/wlr_output.c
After reading xwayland's source code, I realized we aren't sending the `done` signal when the current mode is updated.
The spec says:
>This event is sent after all other properties have been sent after binding to the output object and after any other property changes done after that. This allows changes to the output properties to be seen as atomic, even if they happen via multiple events. 
(https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_output-event-done)
Also fixes window maximization on xwayland.
Test plan: run `xrandr`, update rootston window size, run `xrandr` again.
Fixes #330
=> Call wl_output_send_done when current mode is updated

include/rootston/cursor.h, include/rootston/desktop.h, include/rootston/seat.h, include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_seat.h, rootston/cursor.c, rootston/main.c, rootston/output.c, rootston/seat.c, types/wlr_data_device.c, types/wlr_seat.c
Move roots_drag_icon into wlroots.
=> wlr- drag-icon

glgen.sh, render/meson.build
This is how I originally wanted to write this file, but due to some meson limitations, I couldn't.
It's been fixed in 0.43.0, so now we can do this.
=> Change glapi.sh to generate both source and header simeltaneously

include/rootston/config.h, include/wlr/types/wlr_keyboard.h, include/wlr/types/wlr_seat.h, rootston/config.c, rootston/keyboard.c, types/wlr_keyboard.c, types/wlr_seat.c
Test plan:
```ini
[keyboard]
repeat-rate = 100
repeat-delay = 1000
```
Repeat rate is in repeats/second, repeat delay is in ms.
=> Make keyboard repeat info configurable

backend/wayland/wl_seat.c, include/rootston/config.h, include/wlr/types/wlr_cursor.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_xcursor_manager.h, rootston/config.c, rootston/seat.c, types/wlr_cursor.c, types/wlr_output.c, types/wlr_xcursor_manager.c
Test plan:
```ini
[output:XXX]
scale = 1.5
```
Try various wayland and xwayland apps. Check rendering and input events. Try fullscreen.
=> Add fractional scaling support

types/wlr_output.c
=> Remove fractional output PR artifact

backend/drm/drm.c, backend/drm/renderer.c, backend/headless/backend.c, backend/headless/input_device.c, backend/headless/output.c, backend/meson.build, backend/wayland/backend.c, backend/wayland/output.c, backend/x11/backend.c, include/backend/headless.h, include/wlr/backend/headless.h, include/wlr/interfaces/wlr_output.h, include/wlr/render/egl.h, include/wlr/types/wlr_output.h, render/egl.c, rootston/main.c, types/wlr_output.c
Test plan: launch rootston, open `gnome-calculator`, take a screenshot.
Fixes #495
=> Headless backend

types/wlr_output.c
Fixes setting a hardware cursor image twice (used to fallback to software cursor) and destroy handlers.
=> Output fixes

.editorconfig, include/rootston/desktop.h, include/wlr/types/wlr_primary_selection.h, include/wlr/types/wlr_seat.h, protocol/gtk-primary-selection.xml, protocol/meson.build, rootston/desktop.c, types/meson.build, types/wlr_primary_selection.c, types/wlr_seat.c
Test plan: open two different GNOME apps, select some text on one of them, focus the other, and press the middle mouse button. The text should be pasted.
=> Add gtk-primary-selection protocol

include/wlr/types/wlr_keyboard.h, types/wlr_keyboard.c, types/wlr_seat.c
Makes this useful for sway bindcode.
=> wlr-keyboard: keep track of number of keycodes pressed

backend/drm/util.c, examples/screenshot.c, types/wlr_data_device.c, types/wlr_primary_selection.c, types/wlr_seat.c, types/wlr_xdg_shell_v6.c, xwayland/selection.c
Not quite perfect, but arguably better than nothing.
=> ENOMEM checks: consistently check wl_array_add return

backend/multi/backend.c
Fixes multi backend teardown issue found in #532.
=> Remove display_destroy on multi-backend destroy

examples/output-layout.c, include/rootston/desktop.h, include/wlr/types/wlr_box.h, include/wlr/types/wlr_output_layout.h, rootston/desktop.c, rootston/output.c, types/wlr_box.c, types/wlr_output.c, types/wlr_output_layout.c
Test plan:
* Open some views on two outputs
* Remove one output (close output window or unplug it)
* There should be no views outside the output layout
Updates #168
=> Fix views outside output layout

examples/idle.c, examples/meson.build, include/rootston/desktop.h, include/wlr/types/wlr_idle.h, protocol/idle.xml, protocol/meson.build, rootston/desktop.c, rootston/seat.c, types/meson.build, types/wlr_idle.c
Add idle protocol
My question is if it's ok how I get notified about input events, because on rootstoon mouse motion on an empty desktop will lead to idle state bacause in this case rootston doesn't call wlr_seat_pointer_notify_motion
I am heghe on IRC
=> Idle protocol

backend/session/logind.c, backend/session/session.c, backend/wayland/backend.c, examples/rotation.c, examples/screenshot.c, types/wlr_surface.c, xwayland/xwm.c
I found some minor violations of the code style reference described in CONTRIBUTING.md, which I want to fix with this pull request. I hope this kind of quibble is welcome here :wink:
=> Improve code style in accordance with CONTRIBUTING.md

meson.build
This makes it simpler to figure out what was enabled.
=> meson: print enabled options

meson.build
to create tag files. Idea taken from systemd.
Signed-off-by: Guido Günther <agx@sigxcpu.org>
=> meson: add tags and ctags targets

types/wlr_data_device.c
Test plan: @Ongy can you try this PR?
Fixes #586
=> Fix assertion failed in data_source_notify_finish

include/wlr/types/wlr_output.h, types/wlr_output.c
=> output: add destroy signal for wlr_output_cursor

backend/drm/drm.c
=> backend/drm: update output enabled property on modeset

backend/drm/drm.c
On the drm output the wlr_drm_connector structs are reused.
This struct contains the wlr_output struct, which is reused as well.
The old code kept modes/edid and output state persistent over hotplug.
This nulls the relevant strings, reads newer edid data and removes old
modes on unplug.
I don't think most of this is observable for the most part in rootston.
I added a log of the physical size, which shouldn't change on the old code as well.
I'm not sure if I can just free the modes as I do, @ascent12 some feedback would be nice.
Fixes https://github.com/swaywm/wlroots/issues/608
=> prevents reuse of outdated wlr_output state

include/rootston/seat.h, rootston/cursor.c, rootston/keyboard.c, rootston/seat.c
=> Cancel rootson move/resize/rotate on escape

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/legacy.c, backend/drm/properties.c, include/backend/drm/drm.h, include/backend/drm/iface.h, include/backend/drm/properties.h
=> Add atomic gamma control

include/rootston/output.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_output_damage.h, rootston/output.c, types/meson.build, types/wlr_output_damage.c
=> Add wlr_output_damage

backend/meson.build, render/meson.build, types/meson.build, xwayland/meson.build
This fixes compilation on openSUSE Tumbleweed.
=> Add missing dependencies

render/egl.c
=> Log GL and EGL vendor

backend/x11/backend.c, include/backend/x11.h
This makes windows identifiable in the window list
=> x11 backend: set window title

types/wlr_primary_selection.c
=> primary-selection: fix crash in device_handle_set_selection

types/wlr_surface.c
Test plan: please try this PR @occivink @martinetd @Ongy (if this doesn't work, try this one with #654)
Fixes #643
=> surface: don't reset frame_callback_list on resize

include/rootston/output.h, include/wlr/types/wlr_compositor.h, include/wlr/xwm.h, rootston/output.c, rootston/seat.c, types/wlr_compositor.c, xwayland/xwm.c
=> Fix a bunch of use-after-free

rootston/output.c
=> rootston: send frame done events unconditionally

wlroots.syms
Needed for sway [here](https://github.com/swaywm/sway/blob/wlroots/common/log.c#L11).
=> add _wlr_vlog to syms global

backend/drm/drm.c, backend/drm/renderer.c, examples/output-layout.c, examples/rotation.c, examples/touch.c, include/rootston/view.h, include/wlr/render.h, include/wlr/render/interface.h, render/gles2/renderer.c, render/wlr_renderer.c, rootston/desktop.c, rootston/keyboard.c, rootston/output.c, rootston/rootston.ini.example, rootston/wl_shell.c, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c, types/wlr_output.c
I wonder what's the best way forward here?
=> Make wlr_render_with_matrix use alpha

render/egl.c
Due to the strstr prefix match EGL_EXT_foo would be incorrectly matched
if EGL_EXT_foobar would be available but not foo.
This doesn't matter for the currently checked extensions but will matter
for EGL_EXT_image_dma_buf_import_modifiers vs
EGL_EXT_image_dma_buf_import
Code borrowed from weston
=> Avoid false positives on egl extension matching

types/wlr_output.c, types/wlr_surface.c
Also removes some extraneous assertions.
Fixes #620
=> Fix clients binding multiple times to the same output

backend/drm/drm.c
Fixes #581
~~Depends on #710~~
Tried to do not update the output when a new cursor image is set and the cursor isn't visible, but in the end IMHO it's not worth it: it complicates the DRM code and the benefits are too low.
=> Fix cursor hotspot update

examples/screenshot.c
=> examples: simplify screenshot client

render/egl.c
Useful for debugging dmabuf related problems e.g. when a client requests a certain and we fail to support it.
=> egl: print supported dmabuf formats

backend/drm/backend.c, backend/drm/renderer.c, backend/headless/output.c, backend/wayland/output.c, include/wlr/render/egl.h, render/egl.c, render/glapi.txt, render/gles2/texture.c
=> render/egl: use EGL_KHR_debug

examples/tablet.c, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, render/gles2/renderer.c, render/wlr_renderer.c, rootston/output.c
This PR ports the simple renderer interface from #319.
Updates #558
=> render: add simple functions to render rectangles and ellipses

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h
We just spent a lot of tim efigurin gout what that is :^)
=> xdg-shell-v6, xdg-shell: explain what popup geometry is

xwayland/selection.c
=> Fix segfault in xwm_read_data_source

include/render/gles2.h, include/wlr/render/egl.h, render/egl.c, render/gles2/renderer.c
=> render: remove GL calls from wlr_egl

backend/drm/legacy.c, backend/libinput/events.c, backend/libinput/pointer.c, backend/libinput/tablet_tool.c, backend/libinput/touch.c, backend/wayland/wl_seat.c, backend/x11/backend.c, examples/multi-pointer.c, examples/pointer.c, examples/support/shared.c, examples/support/shared.h, examples/tablet.c, examples/touch.c, include/wlr/types/wlr_cursor.h, include/wlr/types/wlr_input_device.h, include/wlr/types/wlr_pointer.h, include/wlr/types/wlr_tablet_tool.h, include/wlr/types/wlr_touch.h, rootston/cursor.c, types/wlr_cursor.c
=> Use libinput transformed events instead of width_mm/height_mm

types/wlr_surface.c
When a client attaches a wl_drm or a linux_dmabuf buffer, we only
update it if the size is different from the one of the old buffer.
This means that if the client attaches a new, updated buffer with
the same size as the old buffer, the texture won't get updated.
This commit changes this behavior and re-creates the texture if
the client attaches a new buffer, without requiring the size to be
different.
Fixes #773
=> surface: fix texture not updated on commit

include/wlr/xwayland.h
I just wanted to add a newline before `#endif`.
=> xwyaland: fix style issues

backend/drm/drm.c
=> Fix cursor transform on DRM backend

include/wlr/types/wlr_output_layout.h, types/wlr_output_layout.c
=> annotate wlr-output-layout coord variables

include/wlr/meson.build, meson.build
Follow includedir parameter when installing include directory.
=> Install include directory into includedir

backend/backend.c, backend/libinput/backend.c, examples/idle-inhibit.c, examples/input-inhibitor.c, examples/meson.build, include/backend/libinput.h, include/rootston/desktop.h, include/rootston/seat.h, include/wlr/backend.h, include/wlr/types/wlr_input_inhibitor.h, include/wlr/types/wlr_seat.h, protocol/meson.build, protocol/wlr-input-inhibitor-unstable-v1.xml, rootston/cursor.c, rootston/desktop.c, rootston/seat.c, types/meson.build, types/wlr_input_inhibitor.c
Ref https://github.com/swaywm/wlr-protocols/pull/9
Test plan:
1. Open various combinations of shell surfaces and layer surfaces
2. `./examples/input-inhibitor`
3. Provide input and ensure all of it goes to input-inhibitor and none of it anywhere else
Ideally test touch pointer, keyboard, touch, and tablet input.
=> Input inhibit

include/wlr/types/wlr_output.h
Let me know if you think something's missing.
=> output: document wlr_output_set_custom_mode

include/wlr/types/wlr_output_layout.h
Needed for https://github.com/swaywm/wlroots-rs/issues/131
=> Added userdata to wlr_output_layout

rootston/desktop.c
=> Initialize rootston _surface

include/wlr/types/wlr_output_layout.h, include/wlr/types/wlr_xdg_output.h, protocol/meson.build, rootston/desktop.c, types/meson.build, types/wlr_xdg_output.c
=> Add wlr_xdg_output_manager

types/wlr_xdg_output.c
=> Fix sending updates to xdg-output resources

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, include/wlr/xwayland.h, xwayland/xwm.c
=> Always unmap before destroying surface

include/wlr/xwayland.h, rootston/xwayland.c, xwayland/xwm.c
Fixes #838
~~Depends on #857~~
=> xwayland: emit new_surface when unmapped

backend/drm/drm.c, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
This also fixes #535.
@Timidger, can you confirm?
=> output: don't emit the mode event if it hasn't changed

include/wlr/render/wlr_renderer.h, render/wlr_renderer.c, rootston/main.c
Not sure this is the right place to do it. Also not sure if it'll work well with multiple renderers.
=> Advertize supported renderer formats

include/wlr/types/wlr_compositor.h, include/wlr/types/wlr_surface.h, rootston/desktop.c, rootston/output.c, types/wlr_compositor.c, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c, xwayland/xwm.c
* Remove `wlr_surface::subsurface`, because a subsurface is a just a role, nothing special (updates #833)
* Add `wlr_subcompositor`, which was missing (for now it's tied to `wlr_compositor`)
=> Remove wlr_surface::subsurface, add wlr_subcompositor

types/wlr_compositor.c
Fixes #888
Fixes swaywm/sway#1842
=> Fix protocol error when a client destroys and re-creates a subsurface

backend/headless/backend.c, backend/wayland/backend.c, backend/x11/backend.c, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, include/wlr/types/wlr_compositor.h, include/wlr/types/wlr_region.h, include/wlr/types/wlr_surface.h, render/wlr_renderer.c, types/wlr_compositor.c, types/wlr_region.c, types/wlr_surface.c
Known issue: we still leak a few Wayland objects, probably some `wl_resource`.
=> Various memory leaks

types/wlr_xdg_shell.c
Introduced in 874909dca6f58e91b2db4827c9bbc7f356292123
=> xdg-shell: fix invalid xdg-positioner cast

xwayland/xwm.c
=> xwayland: forward configure events to compositor when unmapped

rootston/xdg_shell.c, rootston/xdg_shell_v6.c
=> Fix a rootston crash when a client creates non-topmost popups

include/wlr/xwayland.h, xwayland/xwm.c
=> Use UTF-8 xwayland window title if available

include/rootston/config.h, include/rootston/desktop.h, include/wlr/xwayland.h, rootston/config.c, rootston/desktop.c, rootston/main.c, rootston/rootston.ini.example, xwayland/xwayland.c
=> Add the option to start Xwayland only when a client connects

include/wlr/xwayland.h, xwayland/xwayland.c
=> Fix Xwayland cleanup

examples/pointer.c
Update the pointer example to actually show the pointer (it didn't show up before) and use the new xcursor manager.
=> pointer example fixes

types/wlr_output.c
I cannot test this patch, please try it for me.
Fixes #976 ~~(I hope)~~
=> output: fix lingering hardware cursors

xwayland/xwayland.c
Just a small fix I noticed while reading some code.
=> Remove unused argument

render/egl.c
=> fix server error on exit: eglMakeCurrent Invalid display

include/wlr/types/wlr_xdg_shell.h, types/xdg_shell/wlr_xdg_shell.c, types/xdg_shell/wlr_xdg_toplevel.c
Required for https://github.com/swaywm/sway/issues/1988
=> xdg-shell: add wlr_xdg_toplevel_set_tiled

types/wlr_surface.c
=.= Only looked at it and proofread it 100 times
=> Fix type in wlr_surface_get_extends

types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell_v6/wlr_xdg_popup_v6.c
These are just things I spotted while staring down the code. I'm not sure how to test them, but they certainly look like mistakes.
=> Fix mistakes in xdg_popup and xdg_popup_v6

backend/backend.c, backend/drm/atomic.c, backend/drm/drm.c, backend/headless/input_device.c, backend/session/direct-ipc.c, backend/wayland/output.c, backend/wayland/wl_seat.c, backend/x11/backend.c, render/wlr_renderer.c, rootston/layer_shell.c, types/wlr_export_dmabuf_v1.c, types/wlr_keyboard.c, types/wlr_output.c, util/os-compatibility.c
A bunch of very small fixes.
I'd rather not name what tool it was as I'm using the paid version of a tool I have through work (If I say we could use the "free for open-source scan" it's probably enough to guess what it is, but I really hate the web UI and the free version doesn't give access to the command-line tools... So meh.)
If there is any commit worth discussing I can split it out in its own PR to discuss while we merge the rest, but I think it should all be fairly straightforward
=> Static analysis fixes

types/seat/wlr_seat.c
wl_resource_for_each_safe isn't safe to use here because it accesses
the list's head memory one last time at the end of the loop. Work
around this by breaking out early.
```
==19880==ERROR: AddressSanitizer: heap-use-after-free on address 0x60d0000e6368 at pc 0x7fab68619de2 bp 0x7ffd5c91cee0 sp 0x7ffd5c91ced0
READ of size 8 at 0x60d0000e6368 thread T0
#0 0x7fab68619de1 in wlr_seat_destroy ../types/seat/wlr_seat.c:179
#1 0x7fab68619fb9 in handle_display_destroy ../types/seat/wlr_seat.c:196
#2 0x7fab688e4f8f in wl_priv_signal_emit src/wayland-server.c:2024
#3 0x7fab688e56ca in wl_display_destroy src/wayland-server.c:1092
#4 0x40c11e in server_fini ../sway/server.c:138
#5 0x40b1a8 in main ../sway/main.c:438
#6 0x7fab67b5e18a in __libc_start_main ../csu/libc-start.c:308
#7 0x409359 in _start …
```
=> wlr_seat destroy: fix use-after-free when destroying clients

types/wlr_output.c
=> output: make wl_output resources inert

types/wlr_export_dmabuf_v1.c, types/wlr_screencopy_v1.c
=> fix: handle 32 bit time_t (or smaller)

include/rootston/desktop.h, include/wlr/types/wlr_linux_dmabuf_v1.h, include/wlr/types/wlr_output.h, rootston/desktop.c, types/meson.build, types/wlr_buffer.c, types/wlr_export_dmabuf_v1.c, types/wlr_linux_dmabuf_v1.c
This prevents some future conflicts with the stable version.
Fixes #1133
=> linux-dmabuf: add v1 suffix

meson.build, util/os-compatibility.c
* `posix_fallocate` was never used
* ~~Use `memfd_create` and seals when possible~~
=> Use posix_fallocate when available

include/types/wlr_xdg_shell.h, include/types/wlr_xdg_shell_v6.h, include/wlr/types/wlr_surface.h, types/wlr_surface.c, types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell/wlr_xdg_toplevel.c, types/xdg_shell_v6/wlr_xdg_popup_v6.c, types/xdg_shell_v6/wlr_xdg_surface_v6.c, types/xdg_shell_v6/wlr_xdg_toplevel_v6.c, xwayland/xwm.c
~~Depends on  #1116~~
Fixes #1065
=> surface: add wlr_surface_role.precommit 

backend/drm/backend.c, backend/drm/drm.c, backend/drm/renderer.c, backend/multi/backend.c, include/render/gles2.h, render/gles2/renderer.c, render/gles2/texture.c
Discussion: https://github.com/swaywm/wlroots/issues/934
=> Fix support for multiple GPU

backend/drm/util.c
See https://gitlab.freedesktop.org/wayland/weston/merge_requests/4
=> backend/drm: add support for DRM_MODE_CONNECTOR_DPI

backend/session/session.c, types/tablet_v2/wlr_tablet_v2.c, types/wlr_gamma_control.c, types/wlr_gamma_control_v1.c, types/wlr_idle.c, types/wlr_idle_inhibit_v1.c, types/wlr_input_inhibitor.c, types/wlr_layer_shell.c, types/wlr_primary_selection.c, types/wlr_screencopy_v1.c, types/wlr_screenshooter.c, types/wlr_server_decoration.c, types/wlr_virtual_keyboard_v1.c, types/wlr_xdg_decoration_v1.c, types/wlr_xdg_output.c, types/xdg_shell/wlr_xdg_shell.c, types/xdg_shell_v6/wlr_xdg_shell_v6.c
I forgot to init the destroy signals that were added by #1200. Sorry about that, I should have tested it.
=> Init the new destroy signals added by #1200

rootston/output.c
This allows to get a usable setup by disabling an output when a graphics card only supports 2 screens and 3 are connected. See #409
This doesn't fix the bug described in #409 though.
=> Do not modeset disabled outputs

include/rootston/desktop.h, render/wlr_renderer.c, rootston/desktop.c
Fixes https://github.com/swaywm/wlroots/issues/1190
=> Init dmabuf global in renderer

rootston/seat.c
=> rootston: fix segfault on tablet pad destroy

backend/drm/drm.c
They can be re-used by another output after a subsequent hotplug.
=> backend/drm: de-allocate unused CRTCs

include/rootston/desktop.h, include/rootston/layers.h, include/rootston/seat.h, include/wlr/types/meson.build, include/wlr/types/wlr_layer_shell_v1.h, rootston/cursor.c, rootston/desktop.c, rootston/layer_shell.c, rootston/output.c, rootston/seat.c, types/meson.build, types/wlr_layer_shell_v1.c
cc @Ongy, @ammen99: this is a breaking change.
=> layer-shell: add _v1 suffix

backend/drm/drm.c, include/backend/drm/drm.h, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_output.h, types/wlr_output.c
This can be used for error checking.
=> output: make wlr_output_enable return a bool

types/wlr_output_layout.c
=> output-layout: don't expose outputs without a mode

backend/drm/backend.c, backend/drm/drm.c, backend/headless/backend.c, backend/headless/input_device.c, backend/headless/output.c, backend/libinput/backend.c, backend/libinput/events.c, backend/libinput/keyboard.c, backend/libinput/tablet_pad.c, backend/libinput/tablet_tool.c, backend/multi/backend.c, backend/session/direct-freebsd.c, backend/session/direct.c, backend/session/logind.c, backend/wayland/backend.c, backend/wayland/output.c, backend/wayland/wl_seat.c, backend/x11/backend.c, backend/x11/output.c, include/backend/drm/drm.h, include/backend/headless.h, include/backend/libinput.h, include/backend/wayland.h, include/backend/x11.h
=> Assert all the things!

backend/session/direct-freebsd.c
This commit applies the multiseat fixes that are part of PR #1063 (commits 964e0a50 and 47895d2) to the FreeBSD direct backend.
=> Apply multiseat fixes to FreeBSD direct backend

examples/layer-shell.c
=> Fix unknown cursor in layer-shell example

backend/drm/atomic.c, backend/drm/backend.c, backend/drm/drm.c, backend/drm/legacy.c, include/backend/drm/drm.h, include/backend/drm/iface.h, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_output.h, types/wlr_output.c
Fixes https://github.com/swaywm/wlroots/issues/1158
=> backend/drm: reset gamma table on VT switch

types/wlr_output.c
=> Revert "Prevent excessive frame events when compositor doesn't swap buffers"

meson.build
Commit 7b523884249f904f45b1e9a7eae8152c2ac1248d uses a function added in logind v237
=> meson.build: require logind v237

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/properties.c, include/backend/drm/properties.h
Fixes https://github.com/swaywm/wlroots/issues/995
=> backend/drm: add support for the link-status property

xwayland/xwm.c
Fixes https://github.com/swaywm/sway/issues/731
Thanks @ixru for debugging this.
=> xwayland: handle configure event mask

backend/backend.c, types/tablet_v2/wlr_tablet_v2_pad.c
See https://builds.sr.ht/~sircmpwn/job/8500#task-clang
=> Fix a few bugs found by the static analyzer

types/wlr_input_method_v2.c
Fixes https://github.com/swaywm/wlroots/issues/1334
=> input-method-v2: initialize destroy signal

backend/headless/backend.c, backend/x11/backend.c, render/wlr_renderer.c
Depends on https://github.com/swaywm/wlroots/pull/1350
=> render: correctly set EGL_RENDERABLE_TYPE 

backend/drm/drm.c
=> Fix interlaced mode rejection

backend/drm/drm.c
wlroots segfaults on aarch64 because of this. Found the cause thanks to ASAN.
We were using a CRTC index instead of an output index.
=> backend/drm: fix VLA overflow

include/types/wlr_xdg_shell.h, types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell/wlr_xdg_toplevel.c
Fixes https://github.com/swaywm/wlroots/issues/1407
=> xdg-shell: emit xdg_surface destroy when role object is destroyed

types/tablet_v2/wlr_tablet_v2.c
Fixes https://github.com/swaywm/wlroots/issues/1374
=> tablet-v2: fix wlr_tablet_seat_v2 leak

include/rootston/desktop.h, include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/output.c, rootston/seat.c, rootston/wl_shell.c, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c
=> rootston: use box for views position

backend/session/logind.c
Will maybe help with https://github.com/swaywm/sway/issues/3136
=> backend/session/logind: improve logging

include/wlr/types/wlr_export_dmabuf_v1.h, types/wlr_export_dmabuf_v1.c
Also document lists in the header file.
=> export-dmabuf-v1: add missing destroy request handler

types/xdg_shell/wlr_xdg_popup.c
The previous code resulted in a crash when we try to unconstrain a popup
which is part of a layer-shell surface popup tree.
Fixes #1425
@emersion is this what you imagined?
=> xdg-popup: fix wlr_xdg_popup_get_toplevel_coords()

backend/drm/drm.c, backend/wayland/output.c, include/wlr/types/wlr_box.h, render/gles2/renderer.c, rootston/output.c, types/wlr_box.c, types/wlr_output.c, types/wlr_output_layout.c, types/wlr_screencopy_v1.c, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell_v6/wlr_xdg_surface_v6.c
Fixes #1094.
This should open up wlr_box for stabilization.
=> Standardize the wlr_box input paramaters

rootston/output.c
Fixes RetroArch fullscreen mode.
=> rootston: fix crash with fullscreen surfaces

include/wlr/types/wlr_xdg_shell.h, rootston/xdg_shell.c, types/xdg_shell/wlr_xdg_surface.c
Closes #1417.
I hope this is along the lines of what is needed.
Sending PR on Sway for this shortly.
=> Remove wlr_xdg_surface_send_close.

meson_options.txt
See https://github.com/swaywm/sway/pull/3452
=> meson: yield xwayland option

types/wlr_xdg_output_v1.c
Since they are only sent once, they can be moved outside of `output_send_details`. (since order of events is not important).
=> wlr_xdg_output_v1: move where name & description are sent

types/wlr_data_control_v1.c
Fixes https://github.com/swaywm/wlroots/issues/1502
=> data-control-v1: handle NULL sources in set_selection

types/data_device/wlr_drag.c
=> Fix swaywm/sway#3545.

xwayland/selection/dnd.c
Fixes swaywm/sway#3545 should it be reopened.
=> Fix another instance of swaywm/sway#3545.

backend/session/logind.c
When a wlroots compositor runs as a systemd user unit there is no session associated with the compositor process. Right now when I try and run sway as a user unit it fails since it can't find a session. Instead we need to attach to an existing user session. 
This change first looks for an available session for the process, and if there isn't one falls back to display in the oldest available graphical session via [`sd_uid_get_display`](https://www.freedesktop.org/software/systemd/man/sd_uid_get_state.html).
This work was modeled after a similar change to mutter - https://gitlab.gnome.org/GNOME/mutter/merge_requests/150.
I've tested that this change allows sway to run as a systemd user unit once I set `XDG_SESSION_TYPE=wayland` in `/etc/environment`. The linked mutter change includes a …
=> Allow compositors to run as systemd user units

types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell/wlr_xdg_surface.c
=> Make popup inert when destroyed.

backend/drm/drm.c
=> Revert "drm: do not modeset to current mode"

backend/drm/drm.c
Not sure if this is the right place to put it though.
=> Add workaround for hardware cursors on nouveau

include/rootston/view.h, include/wlr/types/wlr_surface.h, rootston/desktop.c, types/wlr_surface.c
Fixes https://github.com/swaywm/wlroots/issues/1414
=> subsurface: add map/unmap events

xwayland/xwayland.c
=> xwayland: don't use SOCK_CLOEXEC

include/wlr/types/wlr_seat.h, types/seat/wlr_seat_pointer.c
And also document `time` arguments to be milliseconds.
=> seat: use wlr_button_state enum instead of uint32_t

tinywl/tinywl.c
Fixes https://github.com/swaywm/wlroots/issues/1544
=> tinywl: send pointer frame events

rootston/output.c
Broken by 62fd03a7beb18da6c4a5929e38739cf2199dfa79
Closes: #1631
=> rootston: Also iterate layer shell popups

util/log.c
We already do this for the libinput logs.
=> util/log: setup wayland log handler

include/wlr/types/wlr_output.h, rootston/output.c, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, types/wlr_output.c, types/wlr_output_layout.c, types/wlr_output_management_v1.c
Fixes https://github.com/swaywm/wlroots/issues/1610
=> output: remove lx, ly

include/wlr/types/wlr_output.h, types/wlr_output.c, types/wlr_xdg_output_v1.c
Fixes https://github.com/swaywm/sway/issues/4064
=> Send wl_output.done with xdg_output.done

types/seat/wlr_seat.c
See https://github.com/swaywm/wlroots/pull/1675#issuecomment-487300445
=> seat: fallback to v6 if libwayland 1.17 isn't available

examples/foreign-toplevel.c, include/rootston/view.h, include/wlr/types/wlr_foreign_toplevel_management_v1.h, protocol/wlr-foreign-toplevel-management-unstable-v1.xml, rootston/view.c, types/wlr_foreign_toplevel_management_v1.c
This is the wlroots side of https://github.com/swaywm/wlr-protocols/pull/46
=> Implement support for foreign-toplevel fullscreening

backend/noop/output.c
Closes: https://github.com/swaywm/wlroots/issues/1662
=> backend/noop: disallow rendering

types/wlr_xdg_output_v1.c
This adds support for xdg-output-unstable-v1 version 3, added in [1].
The xdg_output.done event is now deprecated and is replaced with
wl_output.done.
This PR has been tested with [2].
[1]: https://gitlab.freedesktop.org/wayland/wayland-protocols/commit/962dd535372c8e4681374c23d2603cbe06cd7031
[2]: https://gitlab.freedesktop.org/xorg/xserver/merge_requests/234
=> xdg-output: add support for xdg-output-unstable-v1 version 3

backend/libinput/tablet_tool.c, include/wlr/types/wlr_tablet_tool.h, meson.build, types/tablet_v2/wlr_tablet_v2_tool.c
This libinput version adds a new tablet tool type.
=> Add libinput-1.14 support

backend/drm/renderer.c
GBM_BO_IMPORT_FD_MODIFIER doesn't accept the INVALID modifier.
=> drm: use IMPORT_FD for INVALID modifier

types/wlr_virtual_keyboard_v1.c
=> Fixes crash of compositor when unvalidated keycode 0 is passed

examples/meson.build, meson.build
See https://github.com/mesonbuild/meson/issues/6010#issuecomment-539580547
=> build: simplify by using disabler deps

backend/wayland/backend.c, backend/wayland/output.c, include/backend/wayland.h, protocol/meson.build, render/gles2/texture.c
Closes: https://github.com/swaywm/wlroots/issues/1830
=> backend/wayland: add support for direct scan-out

protocol/wlr-layer-shell-unstable-v1.xml
Fixes this warning:
../protocol/wlr-layer-shell-unstable-v1.xml:241: warning: since version not increasing
cc @Timidger
=> protocol: sync layer-shell with upstream

backend/session/logind.c
The original signal matching was using the old interface before sd_bus_match_signal was added, which the new code uses. Change them all to use it now.
=> session/logind: Clean up add_signal_matches

types/wlr_layer_shell_v1.c
Forgot to add this in my last PR, derp.
=> Use layer shell v2

backend/session/direct-freebsd.c
Previously, the path of TTY is generated using snprintf with %d format.
It works with TTY 1 to 10, but fails with TTY with greater number
because the number used in the name is in base 32 instead of base 10.
Since there is no standard function to convert a number to a string with
a custom base, this commit adds a function to do it.
Fixes: https://github.com/swaywm/wlroots/issues/1854
=> backend/session/freebsd: Fix the way to get TTY path

.builds/alpine.yml
Closes: https://github.com/swaywm/wlroots/issues/1255
=> ci: add a build run with all features disabled

xwayland/xwayland.c
When running wlroots compositors with Xwayland executable bits
unset, if DISPLAY is set to the display number wlroots has set
up, then X and gtk clients (at least) hang when they are ran.
X clients should fail with an error and exit while gtk clients
should fall back to wayland backend and run correctly. This is
because wlroots opened sockets for Xwayland but wasn't closing
them if Xwayland failed to start.
=> xwayland: Clean up if Xwayland fails to start

backend/backend.c
=> Allow WLR_RDP_PORT to be any valid TCP/UDP port number

backend/wayland/backend.c
Previously, an error on the remote Wayland display would result in an
infinite loop priting:
2020-01-09 13:39:03 - [wayland] Source dispatch function returned negative value!
2020-01-09 13:39:03 - [wayland] This would previously accidentally suppress a follow-up dispatch
This happens when the remote compositor disconnects the client because
of a protocol error, for instance.
Handle wl_display_dispatch and wl_display_dispatch_pending returning -1
by terminating the local display and printing an error.
=> backend/wayland: handle display errors more gracefully

backend/headless/backend.c, render/egl.c
Users can just pass EGL_DEFAULT_DISPLAY themselves.
=> render/egl: remove SURFACELESS_MESA special case

docs/env_vars.md
=> docs: various fixes

examples/meson.build, examples/output-power-management.c, include/wlr/types/wlr_output_power_management_v1.h, protocol/meson.build, protocol/wlr-output-power-management-unstable-v1.xml, types/meson.build, types/wlr_output_power_management_v1.c
~~only got some light testing therefore wip~~
See https://github.com/swaywm/wlr-protocols/pull/61
=> Implement wlr-output-power-management

include/wlr/types/wlr_output.h, types/wlr_gamma_control_v1.c, types/wlr_screencopy_v1.c, types/wlr_xdg_output_v1.c
Closes: https://github.com/swaywm/wlroots/issues/2088
=> Gracefully handle inert wl_output resources

backend/drm/renderer.c, backend/headless/backend.c, backend/wayland/backend.c, backend/x11/backend.c, include/wlr/render/egl.h, render/egl.c
* render/egl: make config attribs const
* backend: set EGL_RENDERABLE_TYPE and EGL_SURFACE_TYPE
=> EGL config attribs improvements

backend/wayland/meson.build, examples/meson.build, protocol/meson.build
Closes: https://github.com/swaywm/wlroots/issues/1963
=> build: use dicts instead of get_variable

tinywl/tinywl.c
While trying out the tinywl code, I found that the resize mode was behaving weirdly ... so I looked into code. Turns out the `begin_interactive` method stores the cursor position plus the geo_box position; however, `process_cursor_resize` wasn't taking this into account, causing windows to jump down in size unexpectedly when resized and lose alignment with the cursor. To fix this, I simply added a member to the `tinywl_server` struct that stores the geo_box when the mouse enters grab mode, and I referenced that data in the resize method. I considered polling for this data every time instead of storing it in the server struct, but 1) since changes in this value are not relevant and 2) it could potentially decrease performance (I don't know enough about wlroots to know how much) I decided …
=> Fix geo_box bug in cursor resizing

types/wlr_cursor.c
In the case that only one axis received an event, rotating the input can
cause the change to actually happen on the other axis, as far as clients
are concerned.
This commit updates the axes flags to be consistent post-rotation.
Fixes swaywm/sway#4776.
=> input/tablet: fix up updated axes after rotation

backend/drm/renderer.c
Some primary planes don't support ARGB8888, they only support XRGB8888
(for instance on older Intel hardware). The DRM backend would fail to
initialize.
When that's the case, try to allocate buffers without an alpha channel.
=> backend/drm: strip alpha channel if necessary

examples/dmabuf-capture.c
This makes it a little bit less annoying to provide the right arguments.
All options have reasonable defaults.
=> examples/dmabuf-capture: use getopt

backend/headless/backend.c, backend/multi/backend.c, include/backend/headless.h
Closes: https://github.com/swaywm/sway/issues/5296
=> Fix crash on headless backend destroy

backend/drm/drm.c
Closes: https://github.com/swaywm/sway/issues/5319
=> fix missing cursor on external monitors with multi-GPU setup and nouveau

include/wlr/types/wlr_tablet_v2.h, types/tablet_v2/wlr_tablet_v2_tool.c
Refs https://github.com/swaywm/sway/issues/5302.
wlroots counterpart to https://github.com/swaywm/sway/pull/5303.
=> Fixups for tablet tool implicit grabs

examples/output-power-management.c
As discussed in IRC, with oneshot mode, we can use this example client as a keybinding or anything like that. Otherwise, the user will have to manually kill the client each time.
=> examples: make output-power-management oneshot by default

backend/drm/atomic.c
If the atomic commit fails or is test-only, rollback
wlr_drm_crtc.{mode_id,gamma_lut} blob IDs to their previous value. This
prevents the next commits from failing or applying test-only state.
=> backend/drm: rollback atomic blobs

xwayland/server.c
This prevents a very unlikely crash in `xwayland_socket_connected`.
Refs #2163.
=> xwayland: add error-checking to `server_start_lazy`

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/legacy.c, include/backend/drm/drm.h
=> backend/drm: don't set cursor if off-screen

backend/wayland/tablet_v2.c
=> backend/wayland: scale tablet tool position into [0, 1] range

backend/wayland/seat.c, backend/wayland/tablet_v2.c, include/util/time.h, types/tablet_v2/wlr_tablet_v2_tool.c, types/wlr_surface.c, util/log.c, util/meson.build, util/time.c
Refs https://github.com/swaywm/sway/pull/5425.
=> Fix `get_current_time_msec` returning microseconds, and refactor to time utility

backend/drm/renderer.c, types/wlr_screencopy_v1.c
These are fixes for things that I've notice while reading the code and made a mental note of them.
=> Minor fixes

types/xdg_shell/wlr_xdg_popup.c
=> xdg-shell: check for existing role before setting xdg_popup_surface_role

xwayland/xwm.c
=> xwayland/xwm: prop count cleanups

types/wlr_gamma_control_v1.c, types/wlr_output.c
Solution is still not ideal, but should work with all existing compositors, as discussed on IRC.
Fixes #2360
=> make sure to fail setting gamma on disabled outputs

examples/simple.c
=> examples/simple: use more wlroots helpers

xwayland/xwm.c
Implement a simple loop detection while trying to retrieve the parent
for a TRANSIENT_FOR window.
Fixes swaywm/sway#4624
=> xwm: add loop detection for read_surface_parent

xwayland/selection/outgoing.c
It seems that if we ever try to reply to a selection request after
another has been sent by the same requestor (we reply in FIFO order),
the requestor never reads from it, and we end up stalling forever on a
transfer that will never complete.
It appears that `XCB_SELECTION_REQUEST` has some sort of singleton
semantics, and new requests for the same selection are meant to replace
outstanding older ones. I couldn't find a reference for this, but
empirically this does seem to be the case.
Real (contrived) case where we don't currently do this, and things break:
* run fcitx
* run Slack
* wl-copy < <(base64 /opt/firefox/libxul.so)  # or some other large file
* focus Slack (no need to paste)
fcitx will send in an `XCB_SELECTION_REQUEST`, and we'll start
processing it. Immediately after, Slack …
=> xwayland: remove stale transfers from the same requestor

xwayland/selection/outgoing.c
We already mostly did this, but there were a couple of branches
(`calloc` failures) where we'd bail without letting the other side know.
Refs swaywm/sway#4007. Likely not going to be a real improvement there
(if `calloc` fails you're already pretty screwed), but it does address a
theoretical possibility.
=> xwayland: notify requestor when we fail to respond to their request

include/wlr/types/wlr_gamma_control_v1.h, types/wlr_gamma_control_v1.c
~~Depends on https://github.com/swaywm/wlroots/pull/2315~~
Closes: https://github.com/swaywm/wlroots/issues/2372
=> gamma-control-v1: apply gamma LUT when output gets enabled

backend/drm/drm.c, include/wlr/types/wlr_export_dmabuf_v1.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_screencopy_v1.h, types/wlr_export_dmabuf_v1.c, types/wlr_output.c, types/wlr_screencopy_v1.c
=> Fix wlr_output_export_dmabuf off-by-one-frame error

backend/x11/backend.c, include/backend/x11.h
We do something similar in our XWM.
=> backend/x11: log errors and unknown events

render/egl.c
On some setups (e.g. remote access via SSH) the current user won't have
the permission to open the primary node at all. It's still possible to
use drmGetDevices to match the primary node name returned by EGL.
Closes: https://github.com/swaywm/wlroots/issues/2488
=> render/egl: don't rely on being able to open primary node

backend/headless/output.c
I was about to add a check to fail instead of crash when the compositor
uses direct scan-out, but with renderer v6 it's so simple to just add
support for direct scan-out, why bother?
Closes: https://github.com/swaywm/wlroots/issues/2523
=> backend/headless: add support for direct scan-out

render/egl.c
I have noticed this with LeakSanitizer, I hope these are all occurrences.
=> egl: fix memory leak

backend/drm/drm.c
Closes: https://github.com/swaywm/wlroots/issues/2533
=> backend/drm: remove workaround for amdgpu DP MST

backend/headless/backend.c
~~Depends on https://github.com/swaywm/wlroots/pull/2510~~
Backends will eventually stop creating their renderer. To prepare for
this, stop using EGL_PLATFORM_SURFACELESS_MESA in the headless renderer.
Pick a render node using libdrm.
The new allocator/renderer creation logic looks very much like what will
end up in common code.
=> backend/headless: select the rendering device ourselves

backend/x11/backend.c
Instead of relying on EGL to retrieve the DRM FD, query it from the
DRI3 extension.
Use the EGL GBM platform, and drop the EGL config.
~~Depends on https://github.com/swaywm/wlroots/pull/2495~~
=> backend/x11: use DRI3Open to get DRM FD 

include/wlr/types/wlr_surface.h, types/wlr_surface.c
Closes #2542
@ngortheone could you test this?
=> subsurface: handle NULL parent in get_root_surface

backend/drm/drm.c, backend/drm/renderer.c, include/backend/drm/renderer.h, render/drm_format_set.c
=> backend/drm: remove special linear case for cursor plane

backend/x11/backend.c
If we get an authenticated primary node from the X11 server, don't use
it because we can't authenticate our Wayland clients with it. Instead,
open a render node.
Closes: https://github.com/swaywm/wlroots/issues/2576
=> backend/x11: always open render node

types/wlr_foreign_toplevel_management_v1.c
Just a couple of things I noticed while working on the new foreign-toplevel protocols.
=> wlr-foreign-toplevel-management: misc fixes/improvements

include/wlr/types/wlr_layer_shell_v1.h, include/wlr/types/wlr_xdg_shell.h, types/wlr_layer_shell_v1.c, types/xdg_shell/wlr_xdg_surface.c
See commit messages for reasoning.
=> Add popup_surface_at() functions

types/wlr_gamma_control_v1.c
Closes: https://github.com/swaywm/wlroots/issues/2632
=> gamma-control-v1: schedule frame when resetting gamma LUT

render/gles2/texture.c
It can be surprising and unexpected that texture operations (such as
texture upload and import) change the current EGL context, especially
when it's done under-the-hood by wlroots in response to wl_surface
requests.
To prevent surprises, save and restore the previous EGL context.
cc @any1
=> render/gles2: restore EGL context after texture operations

render/gbm_allocator.c
=> render/gbm_allocator: set modifier to INVALID if implicit

backend/x11/backend.c, backend/x11/output.c, include/backend/x11.h
=> backend/x11: add support for DRI3 1.0

include/wlr/render/egl.h, render/egl.c, render/wlr_renderer.c
=> render: add wlr_egl_create_from_drm_fd function

backend/x11/output.c
This makes full-screen with weston-terminal work.
=> backend/x11: add support for scanout mode

backend/x11/backend.c, backend/x11/output.c, include/backend/x11.h
=> backend/x11: keep track of exposed rects, add them to damage regions 

render/gbm_allocator.c
Some drivers (e.g. nouveau) need to do some book-keeping when exporting
a BO handle to a DMA-BUF [1]. Using drmPrimeHandleToFD directly hides
the export from the user-space drivers and causes some ref'counting
issues.
So we can't properly handle BOs with a different handle for each plane
until [2] lands.
[1]: https://gitlab.freedesktop.org/drm/nouveau/-/issues/43#note_772661
[2]: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/5442
Suggested-by: Ilia Mirkin <imirkin@alum.mit.edu>
=> render/gbm_allocator: avoid drmPrimeHandleToFD

examples/foreign-toplevel.c
Made this for testing https://github.com/swaywm/sway/pull/5955.
While I was at it, I added some documentation as well.
=> Add documenation and output selection to foreign toplevel example

include/xwayland/selection.h, xwayland/selection/incoming.c, xwayland/selection/outgoing.c, xwayland/selection/selection.c, xwayland/xwm.c
I was originally going to open a separate PR for each change I made, then realized having them all in one place made testing easier &mdash; so here it is. Commits are independent, and their messages have more details.
=> Clipboard fixes part 2

include/xwayland/selection.h, include/xwayland/xwm.h, xwayland/selection/incoming.c, xwayland/selection/outgoing.c, xwayland/selection/selection.c
Depends on https://github.com/swaywm/wlroots/pull/2699.
=> xwayland/selection: use one X11 window per incoming transfer

xwayland/selection/outgoing.c
There seems to be no reason why we can't service multiple Wayland-to-X11
transfers concurrently, so long as they are to different windows (or
possibly, same windows but different target properties?)
This commit removes the queuing logic, but retains the request
de-duplication from #2428.
=> xwayland/selection: allow simultaneous Wayland-to-X11 transfers

meson.build, types/seat/wlr_seat.c
Depends on [1].
[1]: https://gitlab.freedesktop.org/wayland/wayland/-/merge_requests/79
=> seat: use WL_SEAT_ERROR_CAPABILITY

types/wlr_surface.c
This relies on [1].
[1]: https://gitlab.freedesktop.org/wayland/wayland/-/commit/8d5fadad47aad420b0d83fffc8ad573766a9c75e
=> surface: check buffer size is compatible with scale

examples/egl_common.c, examples/idle-inhibit.c, examples/input-inhibitor.c, examples/keyboard-shortcuts-inhibit.c, examples/layer-shell.c, examples/meson.build, examples/pointer-constraints.c, examples/relative-pointer-unstable-v1.c, examples/text-input.c, examples/toplevel-decoration.c
=> examples: remove wlroots dep from client examples

xwayland/selection/incoming.c, xwayland/selection/outgoing.c, xwayland/selection/selection.c
See commits for details.
Fixes #2192.
=> xwayland/selection: fix self-copy loop 

backend/session/meson.build, backend/x11/meson.build, include/wlr/meson.build, meson.build, types/meson.build, util/meson.build, xwayland/meson.build
=> build: improve feature handling

types/wlr_surface.c
=> surface: don't send protocol error on invalid buffer size

render/gles2/texture.c
If the stride is too small, the driver could end up segfaulting
(e.g. radeonsi segfaults in __memmove_sse2_unaligned_erms).
cc @bl4ckb0ne
=> render/gles2: check buffer stride when uploading texture

render/gles2/renderer.c
All backends now use wlr_swapchain. This means the renderer is
guaranteed to have a current_buffer bound.
Remove the legacy code used for EGLSurface.
=> render/gles2: remove current_buffer checks

backend/session/session.c
As explained in [1], user-space should perform a drmModeGetResources
call to figure out whether a device supports KMS.
[1]: https://gitlab.freedesktop.org/mesa/drm/-/merge_requests/127
=> backend/session: fix KMS device filtering

types/seat/wlr_seat_pointer.c
This seems like unnecessary noise.
=> wlr_seat_pointer: Remove log on notify_button

backend/drm/renderer.c, types/wlr_screencopy_v1.c
_See each commit._
cc @bl4ckb0ne @any1
=> Fix crash in screencopy dmabuf and fix black buffer blits

examples/dmabuf-capture.c
It's deprecated in ffmpeg >= 4.4.
Closes: https://github.com/swaywm/wlroots/issues/2798
=> examples/dmabuf-capture: stop using av_init_packet

backend/drm/drm.c
Instead of an ad-hoc strip_alpha_channel function, use the
centralized format table to get an opaque substitute.
cc @bl4ckb0ne
=> backend/drm: use format table in test_buffer

backend/drm/drm.c, backend/drm/renderer.c
Better logging and better scan-out checks.
=> backend/drm: improve test_buffer

include/wlr/types/wlr_output_layout.h
Hello
Add a small comment to document the function wlr_output_layout_get
Best regards
=> Document the wlr_output_layout_get function

protocol/meson.build
See the Weston discussion [1] for motivation.
[1]: https://gitlab.freedesktop.org/wayland/weston/-/merge_requests/157
=> build: remove wayland-scanner fallback

backend/drm/drm.c, backend/libinput/backend.c, backend/x11/backend.c
Inspired by https://github.com/swaywm/wlroots/pull/2839#discussion_r613032869
=> backend: better handle dispatch errors

backend/session/session.c
=> Session cleanup

docs/env_vars.md, include/wlr/render/gles2.h, render/gles2/renderer.c, render/wlr_renderer.c
Fixes https://github.com/swaywm/wlroots/issues/2865
=> Implement WLR_RENDERER in renderer creation process

include/xwayland/xwm.h, xwayland/meson.build, xwayland/xwm.c
=> xwayland: query window PIDs via XResQueryClientIds

render/wlr_renderer.c
Prior to this commit, WLR_RENDERER was only looked up when the
backend returned a DRM FD.
Make it so WLR_RENDERER is always looked up, so that running wlroots
on a system without a GPU and with WLR_RENDERER=gles2 fails as
expected instead of falling back to the Pixman renderer.
cc @bl4ckb0ne
=> render: unconditionally read WLR_RENDERER

backend/drm/util.c
=> backend/drm: misc get_fb_for_bo improvements

include/render/pixman.h, render/pixman/pixel_format.c, render/pixman/renderer.c, types/wlr_screencopy_v1.c
=> render/pixman: implement screencopy

backend/headless/backend.c
We were not dup'ing the DRM FD coming from wlr_renderer_get_drm_fd,
resulting in a double-close on backend destroy.
=> backend/headless: dup DRM FD in wlr_headless_backend_create_with_renderer

types/wlr_virtual_keyboard_v1.c
According to libinput, release events are generated when device is unplugged,
and libinput copies this behavior for device removal. Let's do the same for
our virtual keyboard.
https://github.com/wayland-project/libinput/commit/8f846a41fa0566fbd72ece676656e20e56ce43e6
This is another attempt to fix #2034 and the following sway issue:
https://github.com/swaywm/sway/issues/6254
Note that we have other key repeating issues in sway, which aren't addressed
by this patch. Since the virtual keyboard itself isn't destroyed when the
keyboard grab is destroyed, we'll probably need some trick to reset the state
of the corresponding virtual keyboard when the grab is released.
https://github.com/swaywm/sway/issues/6095
https://github.com/swaywm/sway/issues/6193
=> virtual_keyboard: Emulate key release events on destroy

include/wlr/types/wlr_xdg_shell.h, types/xdg_shell/wlr_xdg_surface.c
Rename the xdg_popup_get_position to
wlr_xdg_popup_get_position
=> Make the xdg_popup_get_position to public

backend/drm/drm.c
~~Depends on: https://github.com/swaywm/wlroots/pull/2828~~
=> backend/drm: allow committing a buffer and a mode together

include/wlr/render/gles2.h, include/wlr/render/pixman.h, render/gles2/renderer.c, render/pixman/renderer.c
for wlr_renderer:
wlr_renderer_get_current_buffer
for pixmap:
wlr_renderer_is_pixman
wlr_texture_is_pixman
wlr_pixman_texture_get_attribs
wlr_pixman_buffer_get_attribs
for gles:
wlr_renderer_is_gles2
wlr_gles2_buffer_get_attribs
=> render: add renderer-specific functions

include/wlr/types/wlr_region.h, types/wlr_region.c
References: https://github.com/swaywm/wlroots/issues/1008
=> region: stabilize interface

types/wlr_output.c
Right now we rely entirely on implicit sync for synchronizing
access to GPU buffers. Implicit sync works by setting
synchronization points on the buffer in writers, and letting
readers wait on these sync points before accessing the buffer.
With OpenGL, sync points are created using functions such as
eglSwapBuffers or glFlush. If none of these special functions
are called, no sync point will be created and readers will
potentially access a buffer that hasn't finished rendering yet.
In the context of wlroots, OpenGL is the writer and the backend
(KMS or parent Wayland/X11 session) is the reader. After we're
done rendering a frame, and before passing that frame to the
backend, we need to call glFlush.
glFlush is called when the buffer is detached from the renderer.
This is a task done by …
=> output: detach buffer from renderer before commit

backend/drm/renderer.c
drm_surface_make_current and drm_surface_unset_current set implicit
state and are an unnecessary mid-layer. Prefer to use directly
wlr_renderer_begin_with_buffer, which automatically unsets the back
buffer on wlr_renderer_end.
I'd like to get rid of drm_surface_make_current once we stop using
it for the primary swapchain.
=> backend/drm: stop using drm_surface_make_current in drm_surface_blit

backend/backend.c, backend/drm/meson.build, backend/libinput/meson.build, backend/meson.build, backend/x11/meson.build, include/wlr/config.h.in, meson.build, meson_options.txt
Supersedes: https://github.com/swaywm/wlroots/pull/2635
Supersedes: https://github.com/swaywm/wlroots/pull/2809
=> backend: make DRM and libinput backends optional

include/wlr/xwayland.h, xwayland/server.c
These commits are taken from https://github.com/swaywm/wlroots/pull/2988, but can be merged early.
=> xwayland: simplify argv filling, embed options

types/wlr_surface.c
While the compositor may render the locked state, it still needs to make clients think their latest state is being rendered. Achieve that by not caching frame callback lists.
=> surface: don't cache frame callback lists

types/seat/wlr_seat_pointer.c
`wl_fixed_t` is a 32-bit data type, but our doubles are 64-bit. This meant
that two doubles that would map to the same `wl_fixed_t` could compare
unequal, and send a duplicate motion event.
Refs swaywm/sway#4632.
=> input/pointer: try harder to not send duplicate motion events

backend/drm/backend.c
Some listeners weren't removed and caused a use-after-free with
e.g. vkms when used as a secondary GPU.
=> backend/drm: add proper error handling to wlr_drm_backend_create

backend/drm/drm.c
~~Depends on: https://github.com/swaywm/wlroots/pull/2829~~
This allows callers to use wlr_output_test to check whether a mode
can be enabled, for instance.
=> backend/drm: always perform an atomic test-only commit on wlr_output_test

include/wlr/types/wlr_output.h, include/wlr/types/wlr_output_layout.h, include/wlr/util/addon.h, types/wlr_output.c, types/wlr_output_layout.c, util/addon.c, util/meson.build
This is an example of how https://github.com/swaywm/wlroots/pull/3096 can be used. Should speed up things a little bit in case a user has over 100 monitors.
=> wlr_output_layout: use wlr_addons 

include/wlr/util/addon.h, types/wlr_output_layout.c, util/addon.c
This allows to have multiple addons of different types with the same
owner.
=> util/addon: find both by owner and impl

include/wlr/util/box.h, types/wlr_surface.c, util/box.c
Partially fixes https://github.com/swaywm/sway/issues/6322
=> Viewport+transform fix

backend/backend.c, backend/drm/renderer.c, backend/headless/backend.c, backend/wayland/backend.c, backend/x11/backend.c, include/render/allocator/allocator.h, include/render/allocator/drm_dumb.h, include/render/allocator/gbm.h, include/render/allocator/shm.h, render/allocator/allocator.c, render/allocator/drm_dumb.c, render/allocator/gbm.c, render/allocator/meson.build, render/allocator/shm.c, render/meson.build, render/swapchain.c, types/wlr_output.c
Add render/allocator/ and include/render/allocator/ to hold
everything allocator-related.
=> Move allocator stuff into new directory

CONTRIBUTING.md, README.md
gamja offers a better experience than Kiwi.
Obviously I'm 100% biased. Completely fine to not make the switch if someone feels differently.
=> Link to gamja for web chat

render/allocator/allocator.c
Closes: https://github.com/swaywm/wlroots/issues/3156
=> render/allocator: use legacy authentication for primary nodes

include/wlr/types/wlr_buffer.h, types/wlr_buffer.c, types/wlr_surface.c
Instead of taking a wl_resource as argument, take a wlr_buffer.
=> buffer: take a wlr_buffer in wlr_client_buffer_apply_damage

include/wlr/types/wlr_viewporter.h, types/wlr_viewporter.c
=> viewporter: improve docs

backend/drm/drm.c
drm_connector_set_pending_fb already takes care of this.
=> backend/drm: drop drm_connector_init_renderer

backend/backend.c
with seatd as libseat backend, when there is one sway already running on one terminal, new sway on the other terminal could not be started. originally [issue was reported to seatd](https://todo.sr.ht/~kennylevinsen/seatd/8). testing [offered change for seatd](https://git.sr.ht/~kennylevinsen/seatd/commit/9d85513) revealed actual problem in wlroots `wlr_backend_autocreate`. after `wlr_session_create`, it is proceeding to further initialization without ensuring if just created session is active or not. this PR wraps original `wlr_session_create` with waiting on `session->events.active`. code is based on `wlr_session_find_gpus`, thus i had to move `wlr_session_create` below it, as it reuses same functions. original `wlr_session_create` is renamed to `_wlr_session_create`
=> backend: wait for session to become active

types/wlr_output_damage.c
On modeset wlr_output will internally allocate a buffer. The
backend will emit a "mode" output event, then wlr_output will
emit a "commit" event.
wlr_output_damage handles the "mode" event by damaging the whole
output, and then handles the "commit" event. However the commit
event has a buffer, so wlr_output_damage rotates the damage in its
ring buffer, thinking the compositor has rendered a frame. The
compositor hasn't rendered a frame, what wlr_output_damage sees is
the internal wlr_output black buffer used for the modeset.
Let's fix this by damaging the whole output in the "commit" event
handler if the mode has changed. Additionally, damage the whole
output after rotating the damage ring buffer.
=> output-damage: fix damage on modeset

.builds/archlinux.yml
=> ci: switch to seatd-launch

include/wlr/types/wlr_scene.h, include/wlr/util/box.h, types/scene/wlr_scene.c, util/box.c
This new scene-graph node displays a wlr_buffer.
Closes: https://github.com/swaywm/wlroots/issues/3161
=> scene: add wlr_scene_buffer

backend/drm/bo_handle_table.c, include/render/allocator/allocator.h, include/wlr/types/wlr_idle.h, include/wlr/util/box.h, protocol/input-method-unstable-v2.xml, tinywl/tinywl.c
Signed-off-by: Elyes HAOUAS <ehaouas@noos.fr>
=> Fix spelling errors

types/scene/subsurface_tree.c
This approach leaves two unused listeners on each root surface, but i don’t know of a better solution.
=> scene/subsurface_tree: hide unmapped subsurfaces
