backend/drm/backend.c, backend/drm/drm.c, backend/udev.c, include/backend/udev.h
This just allows devices to not need to reconfigure themselves if they get a udev event not intended for them.
This should allow multiple DRM backends to share a wlr_udev.
=> Udev event device matching

CMakeLists.txt, common/log.c, include/common/log.h, include/wlr/common/log.h
Changes the logging to actually use the logging callback that the library user can set. It defaults to the current log function (what was _wlr_vlog).
The output message for the default log function has changed slightly: it uses the ISO 8601 date format instead of a locale dependant one (but the time zone is still locale dependent).
The filename is now relative to the wlroots directory instead of just the basename. We have multiple "backend.c"s, so this is to distinguish them.
This implementation uses preprocessor string concatenation, so we can't pass a non-string literal as the format string to the logging functions anymore, but I think that's fine. Passing a non-string literal would be a mistake, anyway.
There is also a static inline function inside the header. This is so that the …
=> Logging improvements

common/log.c, include/common/log.h
When building with ninja instead of make ```__FILE__``` will be relative
and logging therefore break. This moves stripping the path
from ```__FILE__``` to runtime and handles a relative filepath as
well as a full one.
=> Make logging ninja friendly

backend/drm/backend.c, backend/drm/drm.c, backend/libinput/backend.c, example/pointer.c, example/rotation.c, example/simple.c, example/tablet.c, example/touch.c, include/backend/drm.h, include/backend/libinput.h, include/wlr/session.h, session/direct.c, session/logind.c
The session interface was also changed to only emit a signal only when a DRM device is paused/resumed. The old per-device interface wasn't really appropriate for libinput, as it acquires dozens of devices, and we can't tell it to close them individually. This brings it more in line with the way Weston handles this.
The logind backend currently makes some assumptions that there is only a single DRM device being used. If/when we get multi-GPU support, this will need to be changed, but until I know what using multiple GPUs and DRM backends would look like, I can't really see how this needs to be designed.
=> Fix VT switching with libinput backend

backend/wayland/backend.c, backend/wayland/wl_seat.c, example/pointer.c, example/shared.c, example/shared.h, include/backend/wayland.h
This implements pointer/keyboard input support for the wayland backend.
Touch is not supported yet in any way (cannot test it, probably not as important).
Axis support for pointers could also be improved and it does currently not handle the received keymap (there is no way to do it, xkbcommon would have to be handled by the library).
Due to the current pointer event api, pointer movement events are only handled relatively (not sure about this, should it use wlr_event_pointer_motion_absolute and just imagine some fake mm values?).
=> Basic wayland backend input

backend/drm/drm.c, backend/wayland/output.c, example/pointer.c, example/rotation.c, example/simple.c, example/tablet.c, example/touch.c, include/wlr/interfaces/wlr_output.h, include/wlr/render.h, include/wlr/render/interface.h, include/wlr/types/wlr_output.h, render/CMakeLists.txt, render/gles2/surface.c, render/wlr_surface.c, types/CMakeLists.txt, types/wlr_output.c
Draw a cursor using wlr_renderer if a backend fails to draw a cursor. It also gives the option for a backend that doesn't want/need to handle cursors in a special way to just let this handle it.
There are also a couple of other changes, mainly to make this easier to implement.
- Changed the wlr_output 'frame' signal to *not* automatically make the EGL/OpenGL context current. The user must now explicitly call the new `wlr_output_make_current` and `wlr_output_swap_buffers` functions. This is mainly so the SW cursor can be drawn in swap buffers, but it also gives the user the option to draw something to an output whenever they want to.
- Added stride argument to `wlr_renderer_attach_pixels`. Also the GL_EXT_unpack_subimage extension is used to deal with the stride, so we don't have no …
=> Software cursor + Hardware cursor improvements

CMake/FindLibcap.cmake, CMakeLists.txt, README.md, examples/shared.c, include/session/direct-ipc.h, include/wlr/session.h, include/wlr/session/interface.h, session/CMakeLists.txt, session/direct-ipc.c, session/direct.c, session/logind.c, session/session.c
Updated the 'direct' backend to now fork, so that the child (with privileges) can call drmSetMaster/drmDropMaster. It's up to the library user to drop any extra privileges after they initialise wlroots. It also initialises the TTY properly and handles VT switching.
Libcap was added as an optional dependency, so we can have processes with CAP_SYS_ADMIN instead of needing to seteuid as root. If logind is being used, there is no need to do this.
There are a couple of outstanding issues:
- Just like the logind code, it still makes a lot of assumptions about there being a single GPU per session.
- It's very Linux specific. I know that WLC had some things to get their TTY code to work with FreeBSD, but I'm not going to blindly copy that code if I can't test it. Someone else can take a look at …
=> Forking session backend

.travis.yml, README.md
Add `.travis.yml` for building on travis via [arch-travis](https://github.com/mikkeloscar/arch-travis).
Also adds build badge to README.md.
@SirCmpwn you need to enable the repository in travis for this to work.
Note: The build is currently failing due to an unused variable: https://travis-ci.org/mikkeloscar/wlroots/jobs/252789478
=> Build on travis-ci.

types/wlr_output.c
wlr_surface_attach_pixels() expects a wl_shm_format but a GL format was
given. This caused a bug where software rendering of the cursor would
fail when no pixel format can be found.
=> bugfix: fix cursor software rendering fallback

backend/drm/drm.c
The gbm for the output might be null for the pageflip in the case that
the output has been disconnected. The gbm might be set to null by
wlr_drm_output_cleanup() in this case.
If the output is cleaned up before the pageflip, then a double free
will crash the compositor on the call to gbm_surface_release_buffer()
in the pageflip handler. The outputs buffer object bo[1] will point to
invalid memory.
=> bugfix: add null check on output gbm on pageflip

backend/drm/drm.c
The previous pixel format (RGBA8888) is not supported on all devices for cursors.
Weston uses ARGB8888 exclusively for its cursor buffer object which leads me to
believe this pixel format is better supported.
=> Use ARGB8888 pixel format for cursor bo

examples/touch.c
Fix a call to `wlr_surface_attach_pixels()` in the main method of the touch
example to use the correct enum for this method (wayland instead of gl).
=> Use correct pixel format enum in touch example

examples/compositor.h, examples/compositor/main.c, examples/compositor/wl_compositor.c, include/wlr/render.h, render/gles2/surface.c
Add the wayland surface interface to the example compositor.
Implement the create_surface method to create a new wlr surface from the
wayland surface and add the interface.
=> Add surface interface stubs in compositor example

render/gles2/surface.c
Since wlroots shaders only use one texture at a time (ie there is only one
sampler2D variable in any shader), it is unnecessary to switch between active
texture units at this time.
=> Remove unnecessary calls to glActiveTexture

backend/drm/backend.c, backend/drm/drm-atomic.c, backend/drm/drm-legacy.c, backend/drm/drm-properties.c, backend/drm/drm-util.c, backend/drm/drm.c, backend/egl.c, backend/meson.build, include/backend/drm-properties.h, include/backend/drm-util.h, include/backend/drm.h
This adds support for the new atomic modesetting DRM interface, where available.
It's supposed to be quicker and prevent screen tearing, especially when working with planes.
Most DRM drivers don't have support for this yet, but the latest Linux version enables it by default for the i915 (intel) driver, which is what I tested it on. amdgpu is supposed to get it when their DC/DAL code lands. I have no idea when radeon or nouveau is going to get it.
This splits the DRM functionality between 'drm-legacy' and 'drm-atomic' and creates an interface for the common DRM code to use.
=> Atomic modesetting

.build.yml, .travis.yml, README.md, include/wlr/types/wlr_region.h, meson.build, types/meson.build, types/wlr_region.c
Rather small pr, makes wlr dependent on pixman.
Will be needed to further implement wl_surface.
Not sure if it is ok to not use something wlr_region and instead directly setting the pixman region as the regions resource user data.
=> Implement wlr_region using pixman

examples/compositor/main.c, include/wlr/types/wlr_surface.h, types/wlr_surface.c
The surface frame callback lets a window know when it is a good time to show the next frame if it is animating. In particular, this callback is used by weston-simple-shm to throttle drawing.
=> Implement surface frame callback

types/wlr_surface.c
This fixes a crash in `weston-simple-damage` when there is no damage because the damage buffer isn't implemented yet.
=> release buffer on surface flush when no damage

backend/drm/backend.c, backend/libinput/backend.c, backend/libinput/events.c, backend/libinput/keyboard.c, backend/libinput/pointer.c, backend/libinput/tablet_pad.c, backend/libinput/tablet_tool.c, backend/libinput/touch.c, backend/udev.c, examples/shared.c, types/wlr_output.c
Three parts:
- change libinput events to be on the stack. I went for minimal change with wlr_event = { 0 } to replace calloc, compiler should optimize it out for the fields we set right afterwards anyway -- happy to do slightly different.
- A little bit of cleanup of our destroy functions
- Still missing something obvious in the example code though, the remove functions are never called. Might use a hint there, not sure what is supposed to trigger these events - should our own code in the libinput backend when we destroy notify every device of a remove event?
I still need to test on a computer where I can actually unplug the mouse (e.g. not a laptop with a trackpad), not sure if it's called on unplugging either at this point...
=> Leak plumbing

backend/libinput/backend.c, backend/libinput/events.c
Didn't find anything better than making state->devices a list of list.
Thanksfully it doesn't seem to be used for anything aside of final free, might mess with it more to handle unplug events but this fixes the crash
=> Fix libinput destroy for devices with multiple capabilities

backend/drm/drm.c, backend/libinput/backend.c, backend/libinput/events.c, backend/wayland/backend.c, backend/wayland/output.c, backend/wayland/wl_seat.c, examples/shared.c, include/backend/wayland.h, render/gles2/renderer.c
With that I think we're finally clean, well, ASAN/valgrind only pick a couple more unreachable regions that I didn't see how to fix (eglGetProcAddress and wl_event_loop_add_fd both allocate something and meh - we're down from 1MB of leak to around a hundred, that'll do)
libinput_event_destroy and the GLES stuff are the two big ones. I'm not too familiar with opengl but some wiki says we should always detach/free after linking, and I make a point of always trusting what I read on the internet.
Might be worth noting that the fragment_src_external program never links for me - but the error doesn't come back all the way up so this doesn't change anything at this point.
=> More leaks

render/gles2/texture.c
Going for small fixes at the moment.
EGL images were never destroyed. And we would probably get a gl error if a wlr_texture would be created and then destroyed without ever being used since we then destroy a gl texture never created.
=> Fix egl image leak in gles renderer

render/gles2/shaders.c
Some pr in the last days added support for shader compile error messages that revealed the external shader does not link correctly. This fixes it.
We would have noticed it if we could test it somehow but after some research and if i understand everything correctly it seems the external image/shader stuff is only used in some uncommon situations (yuv buffers) so no idea how to test it.
=> Fix external shader

backend/libinput/events.c
Devices is null for some devices. . . There's way too many things called device or devices in there!
=> libinput: fix segfault when handling non-wlr device removal

backend/wayland/backend.c
Wayland fd is always writable and will busy-loop.
The dispatch function gets called with 0-mask when we need to flush
display anyway, so this saves CPU at no visible impact.
=> wayland backend: do not watch wayland fd for writable

backend/libinput/backend.c, backend/libinput/events.c, backend/libinput/keyboard.c, backend/libinput/pointer.c, backend/libinput/tablet_pad.c, backend/libinput/tablet_tool.c, backend/libinput/touch.c, include/backend/libinput.h
You said feel free, so here it is! Hopefully won't get too much in the way of anyone, might be a pain if they have changes pending in libinput.
Also sneaked in a change that makes wayland backend not hog CPU needlessly, happy to resubmit that separately if you think it is worth discussing.
copy/paste from commit message for summary:
- backend state's 'libinput' to li_context
- libinput_device ('device') to li_dev
- wlr_device ('dev') to wlr_dev
- 'devices' lists tangling of libinput devices to wlr_devices
- 'devices' list of wlr_devices in backend state to wlr_device_lists
=> Libinput renaming

backend/meson.build, backend/wayland/os-compatibility.c, backend/wayland/output.c, backend/wayland/wl_seat.c, include/backend/wayland.h
Branched this off the style issue fix branch by accident, can rebase it as soon as that is merged.
Tested on weston and sway. Had to add os-compatibility.c for the shm buffer (stripped everything unneeded).
There is one (minor) issue, i had to use a void* instead of wl_buffer* in the wlr_wl_backend_output since otherwise the compiler warns (and therefore errors) about wl_buffer being deprecated (since there are wl_buffer structs in the client and server side, deprecated on server side, we actually refer to the client side definition here...). Not sure if this is a problem or if it can be handled better.
Resolves #46.
=> Implement wayland backend cursor

examples/compositor/main.c, include/wlr/render.h, include/wlr/render/interface.h, include/wlr/types/wlr_surface.h, render/gles2/texture.c, render/wlr_texture.c, types/wlr_surface.c
Keep track of the scale of the buffer set by surface.set_buffer_scale.
Calculate the height and width of the texture from the buffer depending on the
scale when it is attached.
Use buffer damage to determine the damage of the buffer when flushing damage.
Convert surface damage to buffer damage and union to the surface buffer_damage
prior to flushing damage.
supercedes #65
=> Buffer damage and scaling (attempt 2)

examples/compositor.h, examples/compositor/main.c, examples/compositor/wl_compositor.c, examples/meson.build, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, types/meson.build, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c
This is just a trivial move that "works" e.g. mpv will create a wl_shell surface and play in it.
BUT there is a lot wrong with the code as it was. I'm getting segfaults when destroying xdg_shell, segfaults when destroying wl_shells, segfaults accessing freed elements in examples/compositor/wl_compositor.c.... (these aren't new, I'm getting them with the old code, but I can't test what I'm doing and I don't like it)
I have more commits that fix part of them, but I need more time to understand what makes xdg_shell xdg_shell and what makes wl_shell wl_shell and what I'm free to modify (e.g. changing how we store a list of surfaces for example)
Unless we really can't move forward without this I'd rather just have another day or so to finish that
=> Move wl_shell into wlroots

backend/drm/drm.c, backend/libinput/events.c, backend/multi/backend.c, backend/wayland/output.c, backend/wayland/wl_seat.c, examples/touch.c, include/wlr/util/list.h, util/list.c
This commit changes the `list_t` api so that alloc errors can be
detected and worked around. Also fixes errors not found in 5cc7342
=> Prevent alloc errors from crashing in `list_t`

examples/meson.build, examples/output-layout.c, examples/shared.c, examples/shared.h, include/wlr/types/wlr_output_layout.h, types/meson.build, types/wlr_output_layout.c
An output layout consists of a mapping of outputs to their position in a global
coordinate system that usually cooresponds to the output position in physical
space in front of the user.
Add an example that allows configuration of an output layout and demonstrates
its boundaries with a bouncing image.
=> Add wlr_output_layout implementation

types/wlr_output.c
This prevents us from telling application our scale is 0, when it has no
reason to be.
=> output: default scale to 1

include/wlr/types/wlr_surface.h, types/wlr_surface.c
The patch from #100.
I only tested this with the wayland backend (where it works now), gnome-calculator seems to still
crash on the drm backend i noticed (due to something else though).
There is no gl error anymore.
I would be still ok with not merging this yet, maybe someone else comes up with something better (or finds the new reason for the crash).
=> Fix surface buffer uploading

backend/drm/drm.c
`index` might be uninitialized. Warning can be produced with gcc and `-01` flag.
=> fix uninitialized warning

types/wlr_surface.c
After the buffer is released from the release event, it should no longer be
accessed.
Fixes a GTK crash.
=> Fix wild pointer to buffer

backend/drm/drm.c
This follows-up on #105 that just initialized to 0.
Instead, make sure we actually found an output that matches
=> drm realloc_crtcs: check we found an output

types/wlr_surface.c
This fixes not sending anything back to the client if the only event
it's waiting for is a buffer release, and nothing else is in the pipe.
Workaround for #102 - there probably is a better solution as weston and
wlc do not need to use post_event here.
=> wlr_surface: use post_event instead of queue

examples/compositor/main.c, include/wlr/interfaces/wlr_data_source.h, include/wlr/types/wlr_data_device_manager.h, include/wlr/types/wlr_data_source.h, include/wlr/types/wlr_seat.h, types/meson.build, types/wlr_data_device_manager.c, types/wlr_data_source.c, types/wlr_seat.c
This implements the most important interfaces for data exchange.
It does more than just stub functions, it basically finishes all implementations already.
wl_data_offer is left completely undone since most of it will be handled by the user and it will only be needed when we want to get clipboard to work. I could therefore also only test this in a theoretical way (creating and setting the selection using weston-terminal) which works.
A little explanation since there may be a few unexpected places and this is handled different (better) than wlc does it:
- it does already correctly implement multi-seat support
- since wl_data_device is basically the child of wl_data_device_manager and wl_seat those resources are added to the seat_handle struct. This might sound weird first but it is closely …
=> Implement wlr_data_{source,device,device_manager}

meson.build, meson_options.txt
We move the warning options into the project's default_options, meaning
a user can configure them with `meson configure` and not need to edit
the file.
We also make it possible to disable logind/libcap even if they're
present.
=> Change meson to be more configurable

examples/compositor.c
the libinput backend does wl_display roundtrips, during which there is a
small window where keystrokes can be handled before the rest of the example
compositor is ready.
Setting the callback later ensures we're not called at this point
=> example compositor: handle keyboard after we're done with init

types/wlr_seat.c
Need to use for_each_safe because wl_resource_destroy's callback will
remove the handle from the list itself
=> wlr_seat: fix destroy with multiple handles

include/wlr/xwayland.h, xwayland/xwayland.c, xwayland/xwm.c
Double-forking xwayland was a bit more complicated than I had hoped (because the SIGUSR1 signal when xserver is ready only goes to parent), but I guess it's not too bad.
Also used the opportunity to move some code around and only try to init xwm if the Xwayland process started properly, that wasn't checked correctly before.
=> Xwayland double fork & leak fix

examples/pointer.c, include/wlr/types/wlr_output_layout.h, types/wlr_cursor.c, types/wlr_output_layout.c
Automatically set the cursor on outputs when a layout is attached.
Add a `destroy` event to wlr_output_layout and listen for it in wlr_cursor to
detach the output layout cleanly.
Add a `change` event to wlr_output_layout and listen for it in wlr_cursor to
set the cursor on the outputs in the layout.
Reconfigure the cursor on the outputs when the xcursor changes.
=> wlr_cursor: automatically handle layout changes

examples/config.c, examples/config.h, examples/pointer.c
It's a bit more readable now, but I'm afraid there's no way we can avoid copy/pasting this into each example that needs a pointer unless they can share `sample_state`.
=> pointer.c: refactor device configuration

backend/drm/drm.c, examples/compositor.c, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_gamma_control.h, include/wlr/types/wlr_output.h, protocol/gamma-control.xml, protocol/meson.build, types/meson.build, types/wlr_gamma_control.c, types/wlr_output.c
This adds the `gamma_control` interface from orbital: https://github.com/giucam/orbital/blob/master/protocol/gamma-control.xml
For reference, this is the PR that added gamma control support to wlc: https://github.com/Cloudef/wlc/pull/216/files. And this is the sway implementation of the protocol: https://github.com/SirCmpwn/sway/blob/4e663ab44f5320f20ec2376f24ea1eb3b458f2c2/sway/extensions.c#L251
=> Add gamma_control interface

types/wlr_input_device.c, types/wlr_keyboard.c, types/wlr_pointer.c
A few structs throughout the code use implementation specific free
functions.
When those functions are not used, they simply call free() on their
data, but this leaves around wl_signals linked into listeners.
When those listeners try to remove themself from the list, they write
into the now free memory.
This commit adds calls to remove the signals from those lists, so the
listeners can safely call wl_list_remove
=> fixes use after free caused by signal lists

examples/compositor.c, include/wlr/types/wlr_surface.h, include/wlr/types/wlr_xdg_shell_v6.h, types/wlr_surface.c, types/wlr_xdg_shell_v6.c
In this PR I want to flesh out the xdg shell toplevel.
We can use this as a basis to decide the abstractions for the other shells and what interface is provided to the user.
Our shell implementation will consist simply of a desktop surface state that is changed by the client through the protocol and convenience functions for common things like configure requests. Library users can choose to interpret these values how they want.
Open questions:
* How are users notified of desktop surface state changes?
* Is there enough similarity between the shells (title, geometry, etc.) to make them a subclass of a `wlr_desktop_surface` to make them easier to work with?
=> xdg shell toplevel

examples/compositor.c, include/wlr/types/wlr_cursor.h, include/wlr/types/wlr_seat.h, types/wlr_seat.c
Implement the wlr-seat pointer events and an example usage in compositor.c.
Feedback wanted on the api.
Test it out by clicking the buttons in gnome-calculator. (if you hover for too long on a button, it will crash but that is likely not related to pointer events.)
=> wlr-seat pointer events

examples/compositor.c
Patterns checked:
* `serial.*\+`
* `\+.*serial`
* `serial` (323 results, checked each one more carefully than the first time)
Hopefully I haven't missed any.
Fixes #153
=> Use wl_display_next_serial

dist/archlinux/PKGBUILD, meson.build
Actually install libwlroots.so and include/wlr, as well as generate a pkg-config file.
I'm not 100% sure I generated the pkg-config file correctly, but I can seem to link wlroots using it.
I also added an Archlinux PKGBUILD, because it'll be useful (at least for me) for when sway is going to be ported. I don't really expect this to live in here forever, but it's still too early to put this on the AUR.
=> Install files with meson

render/egl.c
fixes segfault when closing the compositor with an egl window.
=> unset egl current before terminating display

backend/libinput/keyboard.c, types/wlr_keyboard.c
Fixes use after free error when switching VTs and keyboard gets destroyed and recreated.
=> fix libinput wlr-keyboard use after free

rootston/desktop.c, rootston/input.c, rootston/main.c
This is a workaround for a weston toy toolkit bug which expects the compositor global to be listed before the seat global. Without this change, `weston-terminal` and all other toy toolkit apps will not work. This is because their seat initialization depends on the compositor (to create a pointer surface). So if the seat is listed first, their initialization fails because there is no compositor yet.
=> rootston: create desktop before input

include/rootston/input.h, include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c
=> rootston: add xdg shell resize support

include/wlr/xwayland.h, rootston/xwayland.c, xwayland/xwm.c
Client requests for resize/move are already processed by `handle_request_configure`. I tested that with this program: https://gist.github.com/emersion/cc4909ba3581928871192822fc96d00b
It's the compositor's responsibility to detect mouse clicks near window borders and resize windows, if the compositor wants to have this feature. This is different from xdg shell (since xdg shell clients draw their own decorations).
This adds `view->resize` that will be used to force resize with meta+rclick.
=> rootston: add view->resize for xwayland

rootston/wl_shell.c
Need a client to test this.
Is it really important to set `WL_SHELL_SURFACE_RESIZE_NONE` to the real value when calling `wlr_wl_shell_surface_configure`?
=> rootston: add resize support for wl_shell

include/rootston/desktop.h, include/wlr/types/wlr_surface.h, rootston/cursor.c, rootston/desktop.c, rootston/output.c, types/wlr_compositor.c, types/wlr_surface.c, types/wlr_xdg_shell_v6.c
Test with `weston-subsurfaces` and clicking menus on gnome-calculator.
Currently crashes with `weston-subsurfaces -r1` and on synchronized subsurfaces on surface commits (the green circle) because I'm forgetting to clean up a buffer somewhere, but it's pretty close.
One of the buttons on gnome-calculator will try to get an xdg positioning anchor, so after this is ready, we can actually do the xdg-toplevel.
I wonder if there is any client that actually uses arbitrarily nested subsurfaces and depends on all the little rules.
TODO:
=> Subcompositor

types/wlr_xdg_shell_v6.c
Should fix various xdg-shell related crashes of Rootston on windows being closed. Reminder to implement all of each interface or it will crash our server.
=> xdg-shell: protocol destroy

include/wlr/types/wlr_surface.h, types/wlr_surface.c
Move buffer resource pointer to separate structure to be able easily reset it when buffer get destroyed.
Second attempt to fix #195.
I'm not very proud of this solution, but it is minimal working code I was able to come up with.
=> Reset buffer resource pointer on destroy signal.

types/wlr_seat.c
When surface/resource are destroyed by signal from wayland, list pointers become invalid and are freed second time in `wlr_seat_keyboard_enter()` and `wlr_seat_pointer_enter()`.
E.g.
```
==8704== Invalid write of size 8
==8704==    at 0x529A137: wl_list_remove (in /usr/lib/libwayland-server.so.0.1.0)
==8704==    by 0x506BDE6: wlr_seat_pointer_enter (wlr_seat.c:320)
==8704==    by 0x10C2B7: cursor_update_position (cursor.c:58)
==8704==    by 0x10C5F5: handle_cursor_motion (cursor.c:123)
==8704==    by 0x5069585: wl_signal_emit (wayland-server-core.h:388)
==8704==    by 0x5069FA9: handle_pointer_motion (wlr_cursor.c:269)
==8704==    by 0x505ADDA: wl_signal_emit (wayland-server-core.h:388)
==8704==    by 0x505AF9D: handle_pointer_motion (pointer.c:38)
==8704==    by 0x505A9FF: …
```
=> Fix double free

types/wlr_output.c
The [docs](https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_output-enum-mode) say that:
>The event is sent when binding to the output object and there will always be one mode, the current mode.
However, some backends such as Wayland or X11 don't set any mode. This PR sends a mode in this case.
This fixes support for the screenshooter, which needs to know how much space it will allocate when creating a shared buffer.
=> When output has no modes, send one anyway

rootston/desktop.c
Former calculation always returned true, so the input region of subsurfaces was a vertical line along the screen as you can observe by pointer enter events.
=> bug: subsurface location calculation

backend/x11/backend.c
Fixes segfault with qtcreator.
=> x11-backend: create wlr output global

backend/drm/renderer.c, backend/meson.build, glgen.sh, include/wlr/egl.h, meson.build, render/egl.c, render/glapi.txt, render/gles2/renderer.c, render/meson.build
This is trying to remove a lot of the boilerplate and inconsistency for using GL/EGL extension functions, by automatically generating code to load it and check errors for us.
I've written the shell script to be POSIX compatible, so hopefully it will be portable enough. It passes `checkbashisms`.
It takes a text file with each function we want to load on its own line. If a function begins with a -, it won't fail if it's not loaded.
=> Add GL/EGL extension loader generator

include/rootston/view.h, rootston/desktop.c, types/wlr_surface.c
Removed `view_get_input_bounds()` because this is a surface concern.
According to the spec, input bounds have copy semantics, start out infinite, and pending input bounds are never cleared.
Do an additional check beyond surface bounds if the coordinate is contained within the input bounds for xdg-surfaces and subsurfaces.
=> Use wl_surface input bounds for input handling

types/wlr_surface.c
Before a QT client exits, it attaches a NULL buffer and then commits. This handles that situation by setting the texture to invalid after attaching then committing a NULL buffer.
=> bug: handle commit empty buffer

include/wlr/types/wlr_keyboard.h
The build was failing on my machine until I include these headers directly in the keyboard header file.
=> Fixed include in wlr_keyboard.h

types/wlr_surface.c
Fixes a client crash when gtk apps open a subsurface.
The former test is a false positive when the current buffer has already been flushed.
=> bug: null buffer commit detection

include/wlr/types/wlr_surface.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/desktop.c, types/wlr_surface.c, types/wlr_xdg_shell_v6.c
No logic changes.
I think I broke subsurfaces in an earlier commit so I'm fixing that now.
=> move surface finder functions to wlroots

backend/wayland/output.c, include/rootston/input.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_seat.h, rootston/cursor.c, types/wlr_output.c, types/wlr_seat.c, types/wlr_surface.c
Docs: https://wayland.freedesktop.org/docs/html/apa.html#protocol-spec-wl_pointer-request-set_cursor
=> Client provided cursors

types/wlr_surface.c
Prevents accessing freed memory.
=> Destroy callbacks before callback list reinitialization

README.md, backend/meson.build, backend/session/direct-freebsd.c, backend/session/direct-ipc.c, backend/session/session.c, backend/wayland/os-compatibility.c, backend/x11/backend.c, examples/output-layout.c, meson.build, protocol/meson.build, rootston/cursor.c, rootston/output.c, types/wlr_output.c, util/log.c, xcursor/meson.build, xwayland/sockets.c, xwayland/xwayland.c
Hi, it's [me](https://github.com/swaywm/sway/commit/da26d69cb1b21d582a81af0cad7342fab6596eed), again :)
(Do not merge this just yet!)
So, it works on X11, can't test on DRM/KMS for now because kernel panic. (well, I could install a couple month old kernel where wlc/sway worked, but I'll look into fixing the problem instead)
- `-Wno-error=deprecated-declarations` because `warning: 'wl_buffer' is deprecated`. This comes from `EGL/eglmesaext.h`. I have Mesa 17.2.2 and Wayland 1.13.0, but seems like it was deprecated a [long long time ago](https://mail.gnome.org/archives/commits-list/2013-October/msg08157.html). You didn't encounter this on Linux? o_0
- the libinput ifdefs are for compatibility with version 1.6.0 (damn we have to catch up…)
- There's the `environ` linking issue (undefined …
=> Add FreeBSD compatibility

types/wlr_xdg_shell_v6.c
Prevents accessing freed `wlr_xdg_client_v6` from `xdg_surface_destroy()` after it has been freed.
Prevents segfault when closing `weston-transformed`.
=> Destroy surfaces on client destruction (XDG shell)

types/wlr_seat.c
I don't know how this one got by me.
=> bug: emit wlr-seat pointer grab end event

include/rootston/view.h, include/wlr/types/wlr_output_layout.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/desktop.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c, types/wlr_output_layout.c, types/wlr_xdg_shell_v6.c
Make view initialization never fail instead of doing the initialization at some point in the future and flashing partially rendered content:
1. fix xdg-shell so it emits the new event with window geometry (the first commit after ack_configure)
2. pick the center output if no output is found under the cursor as a sensible default
Also, use the effective resolution of the output to determine centering so it works correctly on rotated outputs (this is understandably confusing and probably needs to be made clearer).
=> bug: fix view centering

types/wlr_xdg_shell_v6.c
Use `surface->texture->valid` instead of `current->buffer != null` to detect whether the surface has a buffer. This fixes configure requests, since now we upload the buffer and set it to NULL immediately, `current->buffer` is always NULL.
=> bug: detect invalid texture in xdg-shell

backend/drm/drm.c, backend/wayland/output.c, include/rootston/input.h, include/wlr/interfaces/wlr_output.h, rootston/cursor.c, types/wlr_output.c, types/wlr_seat.c, types/wlr_surface.c
Test clients:
See https://github.com/swaywm/wlroots/pull/255#issuecomment-335585656
Fixes #253
=> [WIP] Fix client cursors

types/wlr_xdg_shell_v6.c
This bug exists in Weston as well.
Run rootston (or weston) like this:
```
(sleep 1 && gnome-terminal) &
(sleep 1 && gnome-terminal) &
rootston
```
You will see that both of the windows are shown as activated. This is because the pending surface state is set to `activated` and then fipped back to deactivated before the ack_configure (which is the time at which the `next` state is updated) so the state_compare function says there is no difference between pending/current/next state and the configure request is deemed not necessary.
cc @SardemFF7
=> xdg-shell: force configure when pending different

backend/wayland/output.c, types/wlr_output.c
- Fixes `mpv` hidden cursors on wayland backend
- Fixes `gnome-terminal` hidden cursors
=> Fix hidden cursors

rootston/rootston.ini.example
The comment strings are not stripped so the commands are not currently recognised.
=> Moved comments in rootston keybinding example config

backend/multi/backend.c, examples/pointer.c, examples/shared.c, include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/input.c, rootston/keyboard.c, rootston/output.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c, types/wlr_seat.c
I removed some fields in rootston views because they were not used. Calling `wl_list_remove` on a listener not initialized with `wl_signal_add` segfaults.
Also cleanups rootston:
* Add missing allocation checks
* Remove assertions used to check runtime errors
Fixes #283
=> Remove wl_list_init when using wl_signal_add

rootston/rootston.ini.example
Since `Shift` is part of the `Logo+Shift+e` keybinding, the `e` keysym is never received, only `E`.
Should rootston be detecting the presence of `Shift` and automatically working out that it should switch the expected keysyms to uppercase (I guess by querying the xkb layout)? I looked into it briefly, but couldn't tell if there is any simple way to do this.
=> Changed broken example rootston keybinding

rootston/config.c
Same reason as https://github.com/swaywm/wlroots/pull/309. I missed that the default was also set in the code, not just the example config.
=> Fixed default keybinding in config.c

backend/drm/drm.c, examples/screenshot.c, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
Test by running `weston-info`, plugging a monitor, running it again, unplugging a monitor, and running it again.
Fixes #317
=> Create globals only for enabled outputs in DRM backend

include/wlr/types/wlr_surface.h, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c
Add `wlr_surface_has_buffer` and use it instead of `surface->texture->valid` in dependent interfaces. See #319 .
=> abstract buffer exists

examples/shared.c
Did a grep through the codebase and this is the only place where we don't use the result of `wl_container_of`, so this should be the only place where we misused it.
=> Fixes #321, not using result of wl_container_of

backend/drm/backend.c, backend/drm/drm.c
Fix #204
~~Fix `match_obj()` behaviour on `[0, 0b11], [UNMATCHED, 1]`~~ (not required)
=> Update Connector-CRTC bindings after resume in DRM backend

types/wlr_surface.c
This reverts commit 0e7d13fab7f23658a85df58ad26c6c77c9638bff.
=> Revert "wlr-surface: destroy texture on null buffer commit"

xwayland/xwm.c
This seems to fix https://github.com/swaywm/wlroots/issues/232 .
The issue there seems to arise from the fact that the xwayland protocols for the surface are not set up correctly, because the order of items in `atom_map` does not match the order of `atom_name` xwm.h.
=> Fix order of WM_HINTS and WM_PROTOCOLS in xwm atom_map

include/rootston/view.h, rootston/desktop.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c
I renamed `view-initialize` to `view_setup` because I want to keep `initialize` when initializing memory of a struct (like `wlr_keyboard_init`). I added the counterpart `view_teardown`.
Test plan: open a window, open another window, close the active window. Check that the previously unfocused window gets active.
=> Focus last view on close in rootston

backend/drm/backend.c, backend/drm/drm.c, include/backend/drm/drm.h
Fixes the bug reported by @Timidger in this comment: https://github.com/swaywm/wlroots/pull/331#issuecomment-339531064
Test plan:
1. Open `qutebrowser` in rootston, move the mouse in the window
2. Switch VT
3. Switch back to rootston
4. There's only one cursor: the software cursor in the `qutebrowser` window. There's no hardware cursor in the top-left corner.
=> Do not set hw cursor if disabled when switching VT

include/rootston/config.h, rootston/config.c, rootston/cursor.c, rootston/keyboard.c, rootston/rootston.ini.example
* We may want to use `config.devices` instead of `config.keyboard`?
Test plan:
1. Set nothing, no meta key should be set
2. Set `meta-key` in the `keyboard:*` section, meta key should work
3. Set `layout` in the `keyboard:*` section, should change the layout
4. Set another `layout` or `meta-key` in a `keyboard:<device name>` section, should change it for only this keyboard
5. `XKB_DEFAULT_LAYOUT` should still work
Fixes #326
=> Per-keyboard configuration

include/rootston/desktop.h, include/wlr/types/wlr_server_decoration.h, protocol/meson.build, protocol/server-decoration.xml, rootston/desktop.c, rootston/meson.build, types/meson.build, types/wlr_server_decoration.c
Test plan:
1. Launch a server-decoration-aware client (such as KDE or GTK tip)
2. Switch server preference in rootston
3. See that if preference is server, the client respects that (or not)
=> Add server-decoration protocol

include/rootston/input.h, rootston/cursor.c, rootston/desktop.c, rootston/keyboard.c
This field is useless and not at the right place.
Test plan: check that the shortcut to close the active view still works.
=> Remove input.last_active_view

include/rootston/input.h, rootston/cursor.c, rootston/input.c, rootston/meson.build, rootston/output.c, rootston/xcursor.c
Test plan:
- Move a window with its border or with the meta key, check that the cursor is a hand
- Resize a window from each edge, check cursor
- Rotate a window, check cursor
- Make sure the surface cursor is used when move/resize/rotate ends
Updates #342
=> Set compositor cursor for move, resize and rotate

rootston/cursor.c
Test plan: try to force resize from the four quaters of a window. Should resize from the corresponding edge.
Fixes #342
=> Force resize for all edges in rootston

rootston/cursor.c, rootston/xdg_shell_v6.c, rootston/xwayland.c
`wl_shell` doesn't have resize bounds.
Test plan: try to resize a xdg shell surface or a xwayland surface, check it doesn't get smaller than the minimum size.
Fixes #346
=> Enforce resize bounds in rootston

include/rootston/input.h, include/wlr/types/wlr_seat.h, rootston/keyboard.c, types/wlr_seat.c
fixes #287 
fixes #242
I haven't tested it with multiple keyboards because I only have one right now, but that should work correctly.
Tests:
* run a binding and see that the keyboard key event does not go to the window
* unplug the keyboard and plug it back in and see that it works
* plug in two keyboards and alternate typing in a window with them and notice that works
* the above but each keyboard has a different keymap
* press a modifier (shift) on one keyboard and then type on the other and notice the modifier is not considered pressed while you type on the other.
=> wlr-seat: keyboard redesign

rootston/xdg_shell_v6.c
Fix small typos (introduced in #349) in the resize bounds checks
=> Fix resize bounds check in rootson

backend/backend.c, backend/libinput/keyboard.c, backend/libinput/pointer.c, backend/libinput/tablet_pad.c, backend/libinput/tablet_tool.c, backend/libinput/touch.c, backend/wayland/wl_seat.c, backend/x11/backend.c, examples/shared.c, include/wlr/backend.h, include/wlr/types/wlr_keyboard.h, include/wlr/types/wlr_pointer.h, include/wlr/types/wlr_tablet_pad.h, include/wlr/types/wlr_tablet_tool.h, include/wlr/types/wlr_touch.h, rootston/cursor.c, rootston/keyboard.c
Makes rootston code a bit simpler because now it doesn't have to do the weird casting.
`time_usec` is now unused.
=> refactor input time_sec to time_msec

rootston/keyboard.c
I'm trying to find bugs and rough edges with the grab interface.
Currently we grab on popups in xdg-shell and wl-shell as well as drag and drop operations.
Rootston now cancels a grab when you press the esc key. Use this to test grab cancels.
* Press esc key when a popup window is shown. It should close all the popups.
* Press the esc key in the middle of a dnd operation. It should end the dnd operation and destroy the dnd icon (buggy).
=> Input grab tweaks and fixes

backend/drm/drm.c, backend/wayland/output.c, backend/wayland/wl_seat.c, backend/x11/backend.c, examples/meson.build, examples/multi-pointer.c, examples/pointer.c, include/backend/drm/drm.h, include/backend/wayland.h, include/wlr/types/wlr_cursor.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_output_layout.h, rootston/cursor.c, rootston/input.c, rootston/output.c, rootston/xcursor.c, types/wlr_cursor.c, types/wlr_output.c, types/wlr_output_layout.c
Adds `wlr_output_cursor` to add support for multiple cursors displayed on one output. Also fixes hotspot with wayland backend.
Note: for now, compositors must call `wlr_cursor_set_image` when a new output is added to upload the cursor pixels to the new output. This won't be necessary after the renderer redesign, as the texture is cached in `wlr_output_cursor` and will be reusable (currently we cannot read pixels from a texture, and the output interface wants pixels).
Test plan: launch `examples/multi-cursor`, try to hotplug multiple pointers, move them around, unplug them.
Fixes #351
=> Add wlr_output_cursor

rootston/config.c
Would choke on NULL name on strcmp later on:
#0  0x00007ffff6e0ad4a in __strcmp_sse2_unaligned () at /usr/lib/libc.so.6
#1  0x00005555555593d2 in config_get_keyboard (config=0x555555774f80, device=0x555555775768) at ../rootston/config.c:443
#2  0x000055555555d7e3 in keyboard_add (device=0x555555775768, input=0x555555e96d70) at ../rootston/keyboard.c:206
#3  0x000055555555ca39 in input_add_notify (listener=0x555555e96fa8, data=0x555555775768) at ../rootston/input.c:34
#4  0x00007ffff7ba2b80 in wl_signal_emit (signal=0x5555557754f8, data=0x555555775768) at /usr/include/wayland-server-core.h:388
#5  0x00007ffff7ba37e0 in wlr_x11_backend_start (backend=0x5555557754f0) at ../backend/x11/backend.c:286
#6  0x00007ffff7b9372d in wlr_backend_start (backend=0x5555557754f0) at …
=> rootston: fix startup with no config

include/rootston/input.h, include/wlr/types/wlr_data_device.h, rootston/cursor.c, rootston/output.c, types/wlr_data_device.c, types/wlr_seat.c
Cancel a drag and drop operation by pressing the escape key in rootston and make sure that works with weston-dnd and gtk test testdnd2.
=> bugfix: dnd force cancel

types/wlr_seat.c
The focus surface for the state should get cleared in the `*_clear_focus()` functions for the input, not here. If you clear it here, the focus surface won't get cleaned up properly and will lead to crashes.
You can reproduce a crash in wl-shell by closing a transient window (such as qgit about dialog).
The dialog takes a different code path to destroy itself by destroying the resource before using the surface destroy interface which is why we only get the crash in that case.
=> wlr-seat bug: dont set focus surface to null then clear focus

backend/drm/drm.c, backend/wayland/output.c, backend/wayland/wl_seat.c, include/wlr/interfaces/wlr_output.h, rootston/config.c, types/wlr_output.c
* Transforms pointer events under Wayland backend (see #364)
* Fixes broken 180 and flipped transformation under DRM backend (introduced in #188, probably never worked properly)
* Fixes disappearing software cursors when applying a 90 or 270 transformation (regression introduced in #352)
* Replaces mysterious switches with easy-to-understand calls to `wlr_output_transformation_*` helpers
Test plan: try all 8 transformations under Wayland and DRM. Open a view, check that the pointer doesn't jump when entering the view. Check (e.g. with a GTK app with buttons) that the view receives pointer events with the right position.
Currently the hardware cursor isn't transformed under the Wayland backend, waiting for #319 to do this.
=> Cursors ✕ Output Transformations fixes

include/wlr/types/wlr_output.h, types/wlr_output.c
When a client requests to disable a cursor, the last compositor cursor is displayed instead.
This PR also allows compositors to hide cursors by calling `wlr_output_cursor_set_image` with a NULL buffer.
Test plan: open `weston-terminal`, start typing, the cursor should disappear. Move the cursor, it should appear again.
=> Fix disabled cursors

types/wlr_output.c
The spec says:
>On surface.attach requests to the pointer surface, hotspot_x and hotspot_y are decremented by the x and y parameters passed to the request. Attach must be confirmed by wl_surface.commit as usual.
I'm not aware of any client that does this, but it's better to implement correctly the spec.
=> Process surface position for software cursor hotspots

backend/wayland/wl_seat.c
Test plan: open a file in Gedit with Wayland backend. Scroll. It shouldn't scroll directly to the end of the buffer.
Fixes #372
=> Fix pointer axis delta in Wayland backend

include/wlr/types/wlr_keyboard.h, include/wlr/types/wlr_seat.h, rootston/desktop.c, rootston/keyboard.c, types/wlr_data_device.c, types/wlr_keyboard.c, types/wlr_seat.c, types/wlr_xdg_shell_v6.c
Test plan: open two terminals. Press two times <kbd>Ctrl</kbd> + <kbd>D</kbd> without releasing <kbd>Ctrl</kbd>. This should close both terminals.
Fixes #389
=> Send current keyboard state when entering a surface

backend/session/session.c, include/wlr/backend/session.h
VLAs are optional C11 features and not supported by C++.
=> Remove VLA from session.h

include/rootston/view.h, rootston/cursor.c, rootston/desktop.c, rootston/xdg_shell_v6.c
Also renames view_get_size to view_get_box to be more consistent with wlroots API and make it more obvious that x,y are set (while in roots_view.get_size this isn't the case).
Fixes #407
=> Fix resize issues with some xdg-shell apps.

examples/screenshot.c
I cloned this repo and ran makepkg against the `PKGBUILD` in the `dist/archlinux` directory and resulted in the following error:
```% makepkg
==> Making package: wlroots r1270.a538ef3-1 (sab 11 nov 2017, 16.34.51, CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
-> Cloning wlroots git repo...
Cloning into bare repository '/home/tancredi/Projects/swaywm/wlroots/dist/archlinux/wlroots'...
remote: Counting objects: 10343, done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 10343 (delta 17), reused 26 (delta 10), pack-reused 10287
Receiving objects: 100% (10343/10343), 2.14 MiB | 3.33 MiB/s, done.
Resolving deltas: 100% (7585/7585), done.
==> Validating source files with sha1sums...
wlroots ... Skipped
==> Extracting …
```
=> Fix unused-result error while building with PKGBUILD

backend/drm/util.c, include/wlr/types/wlr_output.h, rootston/output.c
Test plan: you should see something similar in your logs:
```
2017-11-11 19:04:28 - [rootston/output.c:212] Output 'VGA-1' added
2017-11-11 19:04:28 - [rootston/output.c:215] Samsung Electric Company SyncMaster HS3P701105 474mm x 296mm
```
Updates #403
=> Add wlr_output.serial

rootston/desktop.c, rootston/output.c
Test plan: set output scale to 2, open `gnome-calculator`, rotate it, check that pointer events work (clicking on buttons, text inputs...). Check that views are rendered at the correct position (open menus), **except** the combobox. The combobox uses a popup and these don't work anymore on non-HiDPI outputs (hence, this is an unrelated regression, #415).
Fixes #402
=> Fix rotated views on HiDPI outputs

rootston/seat.c
Since wlr-seat requires a keyboard to be set to send enter, this fixes a bug where the surface doesn't get keyboard focus if the view appears before any keyboard events have been received.
=> rootston: set keyboard for seat on keyboard add

include/wlr/types/wlr_xdg_shell_v6.h, rootston/output.c, types/wlr_xdg_shell_v6.c
Test plan: open `gnome-calculator`, rotate it, click on the combobox. Test with a different screen scale factor too.
Fixes #415
=> Fix popups position for rotated views

backend/wayland/backend.c, backend/x11/backend.c
Test plan: open rooston, and open another rootston inside it (but not from within rootston):
* With the Wayland backend: `env WAYLAND_DISPLAY=wayland-1 build/rootston/rootston`
* With the X11 backend: `env WAYLAND_DISPLAY= DISPLAY=:1 build/rootston/rootston`
Kill the outer rootston. Check that the inner one exits.
Fixes #397
=> Terminate on parent compositor exit

backend/libinput/events.c, backend/session/session.c, rootston/config.c, rootston/cursor.c, rootston/keyboard.c, rootston/seat.c, types/wlr_data_device.c, types/wlr_keyboard.c, types/wlr_screenshooter.c, types/wlr_wl_shell.c
To run the static analyzer:
```
ninja scan-build -C build
```
I didn't fix the keyboard thing because I'll refactor it anyway when fixing #398.
=> Fix a bunch of mistakes detected with scan-build

include/rootston/keyboard.h, rootston/keyboard.c, rootston/rootston.ini.example
Test plan: keybinds such as `Ctrl+Shift+E` shouldn't work anymore. Keybinds such as `Ctrl+Shift+e` and `Ctrl+E` should work. Check that switching VTs works.
Fixes #398
=> Refactor rootston keyboard

rootston/main.c
Test plan: disable xwayland, launch rootston, should not crash.
=> Fix segfault when xwayland is disabled

include/rootston/config.h, rootston/config.c, rootston/desktop.c, rootston/input.c, rootston/rootston.ini.example, rootston/seat.c, types/wlr_xcursor_manager.c
Test plan: install a [XCursor theme](https://www.archlinux.org/packages/?sort=&q=xcursor-&maintainer=&last_update=&flagged=&limit=50) and update your config, For instance, install `xcursor-themes` and use this config:
```ini
[cursor]
theme = redglass
```
=> Add cursor theme to rootston config

backend/libinput/touch.c, examples/pointer.c, examples/support/shared.c, examples/support/shared.h, examples/touch.c, include/rootston/cursor.h, include/rootston/seat.h, include/wlr/types/wlr_cursor.h, include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_seat.h, include/wlr/types/wlr_touch.h, rootston/cursor.c, rootston/output.c, rootston/seat.c, types/wlr_cursor.c, types/wlr_data_device.c, types/wlr_seat.c
Proper touch support in wlroots.
Move touch point struct from rootston into wlr-seat which now keeps track of touch state.
Touch points are created on "down", moved on "motion", and destroyed on "up". They are bound to a single surface for their lifetime and are destroyed when the surface is destroyed.
The decision of what pointer-like features to give to the touch device belongs to rootston. The compositor can choose to give it a cursor, or press buttons on touch down if it so chooses.
Test with `weston-simple-touch`. Test dnd with `weston-dnd` (try moving across two windows).
You should be able to focus and move windows around with the cursor.
TODO:
=> wlr-seat: touch

include/rootston/desktop.h, rootston/main.c
```
==24914==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffe0e537748 at pc 0x7fdf27134e20 bp 0x7ffe0e537340 sp 0x7ffe0e537330
READ of size 8 at 0x7ffe0e537748 thread T0
#0 0x7fdf27134e1f in wl_signal_emit /usr/include/wayland-server-core.h:387
#1 0x7fdf2713680c in xserver_handle_ready ../xwayland/xwayland.c:214
#2 0x7fdf26eff611  (/lib64/libwayland-server.so.0+0x9611)
#3 0x7fdf26effc51 in wl_event_loop_dispatch (/lib64/libwayland-server.so.0+0x9c51)
#4 0x7fdf26efe499 in wl_display_run (/lib64/libwayland-server.so.0+0x8499)
#5 0x414ddd in main ../rootston/main.c:69
#6 0x7fdf26346889 in __libc_start_main (/lib64/libc.so.6+0x20889)
#7 0x404739 in _start (/home/tony/projects/wlroots/build/rootston/rootston+0x404739)
Address 0x7ffe0e537748 is located in stack of thread T0 at …
```
=> rootston: xwayland ready listener

rootston/output.c, rootston/xwayland.c
An unmapped xwayland surface has no wayland surface and should not be considered part of the desktop to maintain the assumption that all views have non-null surfaces.
=> rootston: remove unmapped surface from desktop

meson.build
c3e0fbdb8f0cb16d99e70d14bb5cef6bd48d4591 breaks older meson versions, so just be explicit about what version is needed before someone complains.
=> Add minimum meson version

backend/session/direct-freebsd.c, backend/session/direct.c, xwayland/sockets.c
I managed to get Xwayland working on FreeBSD, writing this from a GPU accelerated Firefox running under rootston :)
Turns out the problem was literally the same as this from 2014: [Weston confuses SIGUSR1 signals from Xwayland and VT switch](https://phabricator.freedesktop.org/T7080). Xwayland sends SIGUSR1, rootston interprets it as vt switch and freezes the whole desktop. "I'm surprised it hasn't blown up for anyone else yet" indeed. I guess most testing was done with logind.
Also fixed a socket creation error, it was creating at the same path twice (my copy-paste mistake when doing the same changes here as in wlc, forgot the second path thing)
=> Xwayland signal confusion fix & non-Linux socket path fix

backend/wayland/os-compatibility.c
This isn't used. It's probably just an artifact from the file originally being copied from weston.
=> Remove unneeded linux include

types/wlr_output.c
Test plan: open `weston-terminal`, click on the titlebar *without moving the mouse*. The cursor should appear at the right position, not a the last compositor cursor one.
Fixes #395
=> Fix initial hardware cursor position

include/rootston/desktop.h, include/rootston/view.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_surface.h, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/cursor.c, rootston/desktop.c, rootston/keyboard.c, rootston/output.c, rootston/wl_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c, types/wlr_output.c, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c, xwayland/xwm.c
This PR implements basic fullscreen support. This PR doesn't implement hardware fullscreen, this will be done in a separate PR. We need to do software fullscreen anyway in case hardware fullscreen is not supported.
Test plan:
=> Fullscreen support

backend/meson.build, examples/meson.build, examples/screenshot.c, include/util/os-compatibility.h, util/meson.build, util/os-compatibility.c
* Moved os-compatibility.c to util
* Added header under util
* Removed static since it isn't needed (i think so)
* Adjusted meson.build to include lib_wlr 
Linked issue #448
=> Moved os-compatibility and added header

backend/session/logind.c
With logind, only seat0 can use TTYs
=> Attempt to fix #454

include/wlr/types/wlr_wl_shell.h, rootston/wl_shell.c, types/wlr_wl_shell.c
Like xdg-shell commit event, makes sure the user commit handler always runs after the surface commit handlers.
=> wl-shell: add commit event

include/wlr/types/wlr_server_decoration.h, rootston/desktop.c
So we don't make sway use wayland-scanner to get this header.
=> wrap server decoration modes

include/wlr/xwayland.h, rootston/xwayland.c, xwayland/xwm.c
Simplification to make the api easier to use.
=> xwayland: remove xwayland param from xsurface methods

backend/drm/drm.c
@ascent12 Can you confirm it fixes the segfault?
We used to always set the cursor image before moving it, but this has changed recently to ensure the image is always displayed at the right position (no flashes of cursors at previous positions).
Fixes #461
=> Fix segfault when moving hardware cursor

backend/drm/util.c, rootston/config.c, rootston/output.c
This allows for instance to configure the screen you plug in your HDMI connector at home differently from the one you plug in the same connector at work.
Also added fallbacks in DRM backend in case EDID extension data for model and serial is missing.
Test plan: get your output name in rootston logs:
```
2017-12-07 13:57:23 - [rootston/output.c:293] Output 'LVDS-1' added
2017-12-07 13:57:23 - [rootston/output.c:296] 'Chimei Innolux Corporation 0x1484 0x00000000' 310mm x 174mm
```
Add it to your config:
```ini
[output:Chimei Innolux Corporation 0x1484 0x00000000]
scale = 2
```
Check that the config is applied to the output.
Updates #403
=> Configure outputs with make, model, serial in rootston

include/rootston/xcursor.h, include/wlr/types/wlr_output.h, types/wlr_output.c
Test plan: setup a scaled output, spawn `gnome-calculator`. Cursor should be scaled too (and not blurry).
`weston-terminal` doesn't send a scaled cursor, so its cursor is just scaled up (same behavior on Weston).
I changed rootston cursor size from 16 to 24 because the default theme doesn't have 16x16 cursors and fallbacks to 24x24 (that caused issues when loading the theme with a scale factor of 2).
Fixes #471
=> Send wl_surface.{enter,leave} to cursor surfaces

types/wlr_seat.c
We were previously sending modifiers to the leaving client instead.
Fixes #476.
As briefly mentioned over here, I might feel more comfortable with less seat abstraction (letting us pick the destination client instead of forcing onto focused one in `wlr_seat_keyboard_send_modifiers`, could make it an optional-ish argument by saying NULL client would be focused one?), but this works without changing the API.
=> wlr_seat: send keyboard modifiers to the right client on enter

include/rootston/config.h, include/rootston/cursor.h, rootston/config.c, rootston/cursor.c, rootston/desktop.c, rootston/seat.c
Test plan: setup two seats, and use this config:
```ini
[cursor:seat1]
default-image = crosshair
```
=> Set default cursor image in rootston

backend/wayland/output.c, backend/x11/backend.c, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_output.h, rootston/output.c, types/wlr_output.c
Test plan:
```ini
[output:WL-1]
mode = 200x200
[output:X11-1]
mode = 200x200
```
Note: that doesn't work on GNOME because the compositor is sending a configure request with the old size right after initialization.
Fixes #464
=> Add wlr_output_set_custom_mode

backend/wayland/backend.c, backend/wayland/output.c, backend/wayland/wl_seat.c, include/backend/wayland.h, types/wlr_output.c
Test plan: `env WLR_WL_OUTPUTS=2 build/rootston/rootston`, check with one output with scale=2 and rotate=90.
=> Multiple outputs with Wayland backend

include/wlr/types/wlr_seat.h, types/wlr_data_device.c, types/wlr_seat.c
Alacritty still doesn't receive keyboard events, but is built with an older winit. winit examples, in other hand, don't receive keyboard/pointer events on master but receive them in this branch.
A PR updates Alacritty with the latest winit: https://github.com/jwilm/alacritty/pull/811. Everything works as expected with this branch and a newer winit.
Test plan: check that pointer/keyboard/touch events still works, check that wayland-to-wayland keyboard/drag'n'drop still works.
Fixes #270
=> Support multiple resources per seat client

rootston/main.c
It's my fault not making it more obvious that this needed to be reverted before merging #496.
>Since backends are not configurable in rootston, there are some changes in main.c that'll need to be reverted before merge.
=> rootston: revert to auto backend

rootston/keyboard.c, types/wlr_keyboard.c
Test plan:
```ini
[keyboard]
layout = en
```
=> Do not segfault when loading an unknown keymap

backend/backend.c, backend/multi/backend.c, include/backend/multi.h, include/wlr/backend/multi.h, rootston/main.c
That allows to remove the `wlr_backend_destroy` call in `main.c`, because everything is cleaned up by the display destroy.
=> Destroy multi backend on display destroy

backend/drm/drm.c, backend/headless/input_device.c, backend/headless/output.c, backend/libinput/events.c, backend/wayland/output.c, backend/wayland/wl_seat.c, backend/x11/backend.c, include/backend/drm/drm.h, include/backend/headless.h, include/backend/wayland.h, include/backend/x11.h, include/wlr/backend/drm.h, include/wlr/backend/headless.h, include/wlr/backend/libinput.h, include/wlr/backend/wayland.h, include/wlr/backend/x11.h
This adds all the variants of wlr_input_device and wlr_output that I could find **that have and impl**.
This last point is important, because X11 has wlr_input_devices with a NULL implem, so we can't use that to check as we have done with backends.
I've considered creating a dummy impl initialized to 0 to use that just for check, should I?
Closes #482.
Reopens #497. (I'm not sure that's legit, but these really are two separate issues. I doubt I'll forget but feels cleaner with the issue open)
=> Add wlr_input_device_is_foo and wlr_output_is_bar functions

backend/backend.c, backend/drm/backend.c, backend/multi/backend.c, include/backend/drm/drm.h, include/backend/multi.h, include/wlr/backend.h, include/wlr/backend/multi.h, rootston/main.c
Preparation for the multibackend features of sway outlined in [sway#1529](https://github.com/swaywm/sway/issues/1529).
Changes:
Open issues:
* Does the multibackend own the wlr-backend children? That is, do we really want to destroy the wlr-backends when the parent multi is destroyed?
* Current implementation will return an empty (non-NULL but no subbackends) wlr-multi-backend instead of NULL when no backends could be created
* When you add a backend to the multi, will it reemit all of the outputs and inputs on added multibackend for the newly added backend? (current solution: no, use the backend_add and backend_remove events to do this)
=> [wip] multibackend fixes

rootston/cursor.c
When we're moving a window, this can be:
* Because the client has sent a move request, in which case the client got the button press, and we need to send the button released event to the seat
* Because of a keybinding, in which case we don't send the button pressed event to the seat, and we have not to send the button released event to the seat
Test plan: open `weston-dnd`, move the window with the titlebar and with rootston keybindings, try to drag some flowers.
Fixes #493
=> Fix rootston seat button count

backend/meson.build
Without this patch I'm getting the following build error when building
with Nix. On other platforms it probably works because `libdrm` can be found anyway:
```
[34/160] Linking static target render/libwlr_render.a.
[35/160] Generating 'backend/wlr_backend@sta/xdg-shell-unstable-v6-protocol.h'.
[36/160] Generating 'backend/wlr_backend@sta/gamma-control-protocol.h'.
[37/160] Generating 'backend/wlr_backend@sta/screenshooter-protocol.h'.
[38/160] Generating 'backend/wlr_backend@sta/server-decoration-protocol.h'.
[39/160] Generating 'backend/wlr_backend@sta/xdg-shell-unstable-v6-client-protocol.h'.
[40/160] Generating 'backend/wlr_backend@sta/gamma-control-client-protocol.h'.
[41/160] Generating 'backend/wlr_backend@sta/screenshooter-client-protocol.h'.
[42/160] Generating …
```
=> Add libdrm as dependency for wlr_backend

include/rootston/config.h, rootston/config.c, rootston/input.c, rootston/rootston.ini.example
This ought to be enough to serve as an example for other compsitors to use.
I've already done the sway config as well, so not sure this is actually strictly neeeded, but I guess it can't hurt?
One last reference to #497 to properly close it in my head :)
=> rootston: add arbitrary libinput config 'tap_enabled'

backend/session/direct-ipc.c, backend/session/logind.c, backend/session/session.c, examples/support/config.c, include/rootston/desktop.h, include/rootston/server.h, include/rootston/view.h, include/wlr/xwayland.h, meson.build, rootston/config.c, rootston/desktop.c, rootston/main.c, rootston/seat.c, rootston/xwayland.c, types/wlr_xdg_shell_v6.c, xwayland/xwm.c
This makes sense, given that there are installed header-files, which rely on some of those defines.
=> config: Put all defines into config.h

backend/drm/drm.c, include/wlr/types/wlr_output.h, types/wlr_output.c
This PR aims to fix issues with cursor on transformed outputs with the DRM backend. For some output transforms, the hardware cursor was not transformed or not at the correct position. I think these issues have been introduced when fixing flipped-90 and flipped-270 transforms in the surface transforms PR.
This PR aims to fix output transforms and check for any corner case issue.
Test plan:
* For the Wayland and DRM backends
* Configure the output transform to normal, 90, 180, 270, flipped, flipped-90, flipped-180, flipped-270 (90 and flipped-90 are the more important ones, because they're tricky)
* Spawn `weston-terminal` (has a surface transform) and `gnome-calculator` (doesn't have a surface transform), check that both have the same orientation
* Move the mouse over these two windows, …
=> Fix cursor on transformed output with DRM backend

rootston/keyboard.c
The `nop` command can be used by developers to test things at runtime. Arbitrary code can be put in the nop command handler and shared with diffs to demonstrate issues in bug reports.
=> add nop command

include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_surface.h, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, include/wlr/xwayland.h, rootston/wl_shell.c, rootston/xdg_shell_v6.c, types/wlr_data_device.c, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c, xwayland/xwm.c
Add a private role-committed func to wlr-surface to ensure the role commit handler always runs before all the other handlers. This simplifies the api by removing the need for a commit event on the role types.
Role call:
=> [wip] Role committed

include/rootston/cursor.h, include/wlr/types/wlr_seat.h, rootston/cursor.c, rootston/wl_shell.c, types/wlr_seat.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c
Add serial validation for grab requests.
Grab requests handled:
* xdg-shell move,resize
* wl-shell move,resize
Xwayland shell events cannot be validated because there is no serial information.
We thought serial validation was necessary for setting selections, but the the protocol doesn't specify how to validate these serials and Weston does no serial validation, so we won't do any validation of those after all.
fixes #511
=> Serial validation for grab requests

backend/wayland/wl_seat.c, examples/screenshot.c
* Fixes output positions in screenshots
* Fixes Wayland backend pointer events when output layout doesn't start at (0, 0)
Test plan:
```ini
[output:WL-1]
x = -500
y = -200
[output:WL-2]
x = 100
y = 50
```
Run `env WLR_WL_OUTPUTS=2 build/rootston/rootston`. Open some windows. Check that pointer events are at the right position. Put some windows between the two outputs, take a screenshot, check that outputs and windows are displayed correctly on the screenshot.
Fixes #392
=> Fixes for multiple outputs

examples/support/shared.c
This is already done after the changes in #504, and now just causes a
segfault on closing the examples.
=> Don't destroy backend in compositor_fini

types/wlr_output.c
When DRM refreshed, `wlr_output_set_mode` is called. It would then call
the DRM `set_mode` callback which sends the updated matrix and mode info.
However once that call completed it would then immediately send the
information again. This is handled poorly by xwayland, causing it to
scale up the clients twice.
I'm only half sure my reasoning is correct, so if someone with more knowledge on DRM / intricacies of the output part of the Wayland protocol wants to chime in that would be great.
=> Send mode info on DRM refresh only once

include/rootston/seat.h, include/wlr/types/wlr_seat.h, include/wlr/xwayland.h, include/wlr/xwm.h, rootston/seat.c, types/wlr_seat.c, xwayland/selection.c, xwayland/xwayland.c, xwayland/xwm.c
This started as a "simple" kludge to restore rootston hooks when xwayland restarts, ~~I'm still not quite happy with that part so comments more than welcome: basically, I'm just copying over listeners as a list + seat from old struct to new struct and it's not very pretty and quite fragile.
I think there needs to be some work to have a wlr_xwayland_reinit() function instead of using init() that doesn't memset(0) the whole struct as blindly as I used to do. Happy to do that either in this PR or in another one.~~ Done here.
The rest is quite good though:
- some small xwm leak (there's tons left when I switch VT, but it's hard to tell where it comes from)
- on restart, the shutdown happens in a different order to shutdown was completly broken, so added an event for when wlr_seat destroys …
=> Fix xwayland restart... and add wlr_seat destroy listener.

backend/session/logind.c, backend/session/session.c
`WLR_HAS_ELOGIND` isn't a valid preprocessor expression, so the build fails (but only if `WLR_HAS_SYSTEMD` isn't defined).
=> Fix build without systemd

include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_primary_selection.h, include/wlr/types/wlr_seat.h, types/wlr_data_device.c, types/wlr_primary_selection.c, types/wlr_seat.c, xwayland/selection.c
This refactors `wlr_data_source` and adds a new `struct client_data_source`. The `resource` field, only populated when the source comes from a Wayland client, is removed from the abstracted struct. Some new drag'n'drop-related callbacks are added, they'll be useful for the xwayland sync implementation.
Test plan:
* Check that clipboard still works: wayland <-> wayland, xwayland <-> wayland, xwayland <-> xwayland
* Same for primary selection
* Check that drag'n'drop still works (wayland <-> wayland only): `weston-flower`, dragging text
Fixes #528
=> Abstract data sources

meson.build
The generated .pc still contained -I${prefix}/wlroots, this is no longer
needed at all as the prefix is now 'wlr' and all includes are 'wlr/foo'
=> meson: fix include path in generated .pc

types/wlr_seat.c
Without this, a client will lose modifiers for one keyboard, when a key
is pressed on the other.
With this the client will always use the modifiers tate of the keyboard
the key was pressed on.
Testplan:
Connect 2 keyboard to the same seat, focus a window (I tested with weston-terminal).
Hold shift on one keyboard and press a character key, this should input capital letters.
Keep shift pressed, press a key on the other keyboard.
Press the key on the first keyboard again.
With this patch it should insert capital letters, without lower case.
=> sends the modifiers on wlr_seat_set_keyboard

backend/drm/atomic.c
Same as what atomic_crtc_set_cursor does
Core was generated by `_build/rootston/rootston'.
Program terminated with signal SIGSEGV, Segmentation fault.
0  0xb6f28a1c in atomic_crtc_move_cursor (drm=0x1ebc8e8, crtc=0x1ead498, x=0, y=0) at ../backend/drm/atomic.c:170
170		if (!crtc || !crtc->cursor) {
(gdb) bt
0  0xb6f28a1c in atomic_crtc_move_cursor (drm=0x1ebc8e8, crtc=0x1ead498, x=0, y=0) at ../backend/drm/atomic.c:170
1  0xb6f2a856 in wlr_drm_connector_move_cursor (output=0x2242b28, x=0, y=0) at ../backend/drm/drm.c:634
2  0xb6f3cea0 in wlr_output_cursor_set_image (cursor=0x21a0338, pixels=0x22e1290 "", stride=24, width=24, height=24, hotspot_x=4, hotspot_y=4) at ../types/wlr_output.c:516
3  0xb6f39da2 in wlr_cursor_set_image (cur=0x22cfc90, pixels=0x22e1290 "", stride=24, width=24, …
=> Don't crash if crtc->cursor is NULL

include/wlr/xwayland.h, rootston/output.c, xwayland/xwm.c
Test plan: open Firefox in fullscreen mode, the right click menu should show up.
Fixes #561
=> xwayland: render children window in fullscreen

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/legacy.c, backend/headless/backend.c, backend/headless/output.c, backend/wayland/output.c, backend/x11/backend.c, examples/support/shared.c, include/backend/drm/iface.h, include/rootston/config.h, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_output.h, rootston/config.c, rootston/keyboard.c, rootston/output.c, types/wlr_output.c, types/wlr_output_layout.c
This un-exports `wlr_output_{create,destroy}_global`, since this is a protocol matter. This instead adds a `wlr_output_update_enabled` for backends.
This fixes disabled outputs with the DRM backend.
Test plan:
```ini
[bindings]
Logo+t = toggle_outputs
```
See @acrisci's comment for edge cases.
Related Weston patch: https://patchwork.freedesktop.org/patch/194357/
=> Add wlr_output::enabled

examples/idle.c, examples/multi-pointer.c, examples/output-layout.c, examples/pointer.c, examples/rotation.c, examples/screenshot.c, examples/simple.c, examples/tablet.c, examples/touch.c
Recent change means you need to call `wlr_log_init`, which wasn't being done in the examples.
=> Fixed logging for examples

rootston/seat.c
Also set the real seat capabilities instead of always all of them.
Test plan: create a seat with a mouse and a keyboard. Unpluging the mouse should hide the pointer.
Updates https://github.com/swaywm/sway/issues/1568
=> rootston: hide cursor if seat has only keyboards

include/wlr/types/wlr_keyboard.h, include/wlr/types/wlr_seat.h, rootston/keyboard.c, rootston/seat.c, types/wlr_data_device.c, types/wlr_keyboard.c, types/wlr_seat.c, types/wlr_xdg_shell_v6.c
Add the ability to change modifiers in flight with `wlr_seat_keyboard_notify_modifiers()` by giving the compositor control over what modifiers are sent to clients. Further decouples the device from the seat and makes it more consistent with the rest of the interface.
=> compositor modifier hooks

backend/drm/drm.c
This fixes #575, but I'm not sure if this is not patching over a different problem (don't know the DRM code).
=> Check if crtc is null in in cursor cleanup when output removed

.travis.yml, backend/meson.build, include/rootston/view.h, rootston/desktop.c, rootston/output.c, rootston/seat.c
Just recently I tried compiling wlroots without XWayland support, which is obviously broken due to some missing #ifdefs. This problem is easy to fix by itself, but I went a little bit further to try and avoid such problems in the future by adding a second CI job to Travis. While the default job will continue to default to all build options being set to `true`, the second job will set everything to `false`. This should in theory allow wlroots to detect such issues much earlier in the future.
I don't know whether that change is desired by the project, but I think it should be worthwhile. Building wlroots is not really a long-running task, so having the CI build the project twice shouldn't take too long while the benefit is kind of obvious to me.
Anyway. If you feel like the second CI job is …
=> Fix building rootston without XWayland

backend/backend.c, backend/drm/backend.c, backend/headless/backend.c, backend/multi/backend.c, backend/wayland/backend.c, backend/x11/backend.c, examples/screenshot.c, include/backend/headless.h, include/backend/wayland.h, include/backend/x11.h, include/wlr/backend.h, include/wlr/backend/interface.h, include/wlr/render.h, include/wlr/render/interface.h, include/wlr/types/wlr_screenshooter.h, render/gles2/pixel_format.c, render/gles2/renderer.c, render/wlr_renderer.c, rootston/desktop.c, rootston/main.c, types/wlr_screenshooter.c
This backports some changes to #319 to fix the screenshooter data format. This also adds `wlr_backend_get_renderer` which will be useful to support multiple renderers.
=> Backport screenshooter fixes from the renderer redesign v1

backend/drm/renderer.c
The wlr_drm_surface_init function is called (upon others) when the drm
mode is changed.
When the surface was used previously this replaced the gbm_surface, but
did not replace the gbm buffers (front/back).
With this, wlr_drm_surface_get_from never set up the new buffers with
the new glViewport because surf->front existed.
This frees the buffers to get new buffers on the new surface with the
new viewport.
This fixes https://github.com/swaywm/wlroots/issues/593
Testplan: I should rebase the test-code mentioned in the issue, then use that branch with the keybind.
=> relases gbm buffers on init

backend/drm/backend.c, backend/drm/drm.c, meson.build
Prefer initialize over initialise since used more often in the sources.
Debian's lintian tripped on these.
=> Fix some typos

examples/screenshot.c
Sets up correct handling for each possible output transformation in the screenshot example.
Fixes https://github.com/swaywm/wlroots/issues/589
=> Screenshot transform

rootston/rootston.ini.example
The comments should talk about Colons not Semicolons.
=> Fix typo in rootston config

rootston/xdg_shell_v6.c
Surfaces and views get resized only on commit, therefore we may only
change the position of a window if there are no pending commits.
=> Fix jitter when quickly resizing windows

rootston/cursor.c
I am just starting contributions to wlroots, so I may have misunderstood everything. But hunting for bugs is always a good way of getting into a codebase.
When double-clicking a maximized window title, so that the windows size is restored and the mouse pointer ends up _outside_ the window it becomes impossible to move windows.
The reason is that the button_count variable is not counted down if the mouse button is released outside the window, so the button_count remains incremented even after the button is released.
This patch adds a call to wlr_seat_pointer_notify_button if the mouse button is released outside the window.
Is this fix the right way to fix the problem? Are there any undesirable side-effects? I don't quite understand the view and surface concepts.
=> Make pointer button release outside window still count down the button_count

rootston/config.c
Since we support fractional scale, having scale=0.5 can make sense
(and, as far as I can tell, works fine)
=> rootston: allow scale < 1 as well

backend/drm/drm.c, backend/drm/renderer.c, backend/headless/output.c, backend/wayland/output.c, backend/x11/backend.c, include/backend/drm/renderer.h, include/wlr/interfaces/wlr_output.h, include/wlr/render/egl.h, render/egl.c, render/glapi.txt, types/wlr_output.c
Test plan: check that there are no rendering artifacts when `EGL_EXT_swap_buffers_with_damage` or `EGL_KHR_swap_buffers_with_damage` is included in the _Supported EGL extensions_ list.
Fixes #615
=> Swap buffers with damage

backend/meson.build, meson.build, meson_options.txt
The two commits are fairly independant, but under the same theme:
- first commit makes the message printed at meson time to reflect what is actually built, rather than the option default values (been annoying me for a while to have elogind = true in that message when I don't have elogind...)
- second commit implements some sort of auto/true/false mechanism, that by default tries to build whatever we have, but if someone explicitely sets meson -Denable_foo=true will fail when foo is not found.
This should not break either default (true was technically auto before) nor explicit configs as -Denable_foo=false is the same syntax.
Happy to remove this commit if it is not welcome but this usually makes sense to do.
=> Meson option enhancements

include/wlr/types/wlr_output.h, include/wlr/types/wlr_region.h, include/wlr/types/wlr_seat.h, include/wlr/types/wlr_surface.h, types/wlr_compositor.c, types/wlr_data_device.c, types/wlr_gamma_control.c, types/wlr_idle.c, types/wlr_output.c, types/wlr_primary_selection.c, types/wlr_region.c, types/wlr_screenshooter.c, types/wlr_seat.c, types/wlr_server_decoration.c, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell_v6.c, xwayland/xwm.c
This ensures we're not incorrectly casting a resource.
Fixes #628
=> Wrap wl_resource_get_user_data into safer helper functions

include/wlr/types/wlr_idle.h, types/wlr_idle.c
This moves the `struct wl_signal activity_notify` in `struct wlr_idle`
into a local `struct {} events` to keep consistency with other modules
in the library.
Pointing it out on my PR but merging one that doesn't do it >:[
Just noticed that, checking the naming for protocol interface implementations.
=> move activity_notify into events in wlr_idle

examples/idle-inhibit.c, examples/meson.build, include/rootston/desktop.h, include/wlr/types/wlr_idle_inhibit_v1.h, protocol/meson.build, rootston/desktop.c, types/meson.build, types/wlr_idle_inhibit_v1.c
This adds an implementation of the `idle-inhibit-v1` protocol and an example client.
The client is very simple and skips a little bit of error checking (whether the seat actually has a pointer), but works to trigger the code paths in the server.
The implementation in `rootston` does nothing but create the manager.
Since rootston doesn't have any kind of idling action, I'm not sure what else we could do here, ideas?
=> Add idle-inhibit implementation

examples/screenshot.c
The template array given to mkstemp was declared static. This reused the
memory, which caused mkstemp to fail if backingfile is run more than
once, because the array no longer contained the template syntax
(which is forced to end in XXXXXX) but the previous file name.
=> prevent screenshot from resuing template array

backend/libinput/backend.c
If input_event is null (e.g. if backend_start has not been called yet)
`wl_event_source_remove` will result in a null deref.
Hit this when running `rootston` at [rootston/main.c:51](https://github.com/swaywm/wlroots/blob/master/rootston/main.c#L51)
=> Fix null deref in wlr_libinput_backend_destroy

backend/headless/output.c
Without this, it gets a frame after the wlr-output is destroyed and that causes use-after-free.
=> destroy frame timer in headless output

backend/drm/backend.c, backend/drm/drm.c, include/backend/drm/drm.h
If there is no current mode, set outputs to dpms off in drm resume.
Sets current mode to null on disable to ensure this can be checked.
Fixes https://github.com/swaywm/wlroots/issues/675
Testplan: Disable an output in the config (or by any means) and change tty away and back to rootston again.
=> restore dpms state on drm resume

include/rootston/view.h
=> rootston: drop saved.alpha from roots_view

include/rootston/desktop.h, include/wlr/xwayland.h, include/wlr/xwm.h, rootston/desktop.c, rootston/seat.c, rootston/xwayland.c, xwayland/xwayland.c, xwayland/xwm.c
This adds `wlr_xwayland_surface_is_unamanged`, to allow compositors more
fine grained control over XWayland focus.
A surface that is unmanaged should not receive focus, while other
windows that are just override redirect may want it (dmenu).
The way unamanged is determined is taken from wlc.
This fixes https://github.com/swaywm/wlroots/issues/636
I have only tested this with a single seat. With the current way inital focus is applied, it may have interesting effect in multiseat setups when a popup/tooltip doesn't have the `NET_WM_TYPE` set.
=> add xwayland unmanaged tests to support dmenu

rootston/output.c
Fixes https://github.com/swaywm/wlroots/pull/680#discussion_r170856102
Currently the alpha defaults to 0, which causes fullscreen surfaces to be completly transparent when they have to be rendered by the rootston code and aren't managed by `wlr_output`.
=> set fullscreen alpha to 1

render/egl.c
This matches the return value of elgCreateImage in case of error. Stumbled upon while working on linux-dmabuf.
=> wlr_egl_create_image: return NULL when function is missing

backend/drm/backend.c, backend/drm/drm.c
The current mode was set to NULL to abuse it as state variable
persisting DRM suspend/resume, this results resulted in a segfault on
normal DPMS cycle.
This reverts that change and uses the wlr_output enabled variable, which
also persists and makes more sense.
I'm dumb =.=
=> prevent current_mode null on output_enable(false)

xwayland/xwm.c
gcc 6.3.0 (at least) complains about &values:
```
expected ‘const uint32_t * {aka const unsigned int *}’ but argument
is of type ‘uint32_t (*)[1] {aka unsigned int (*)[1]}’
```
Reported by thorwil on irc
=> xwm: fix call of xcb_change_window_attributes for old gcc versions

.travis.yml
Adds the docker service in travis which is now required by arch-travis.
See: https://github.com/mikkeloscar/arch-travis/pull/40
=> Enable docker service in travis

include/wlr/xwayland.h, include/xwayland/xwm.h, meson.build, meson_options.txt, xwayland/meson.build, xwayland/selection.c, xwayland/xwayland.c, xwayland/xwm.c
There are two possible messages, with the optional dependency it will look like:
`[xwayland/xwm.c:991] xcb error: op ChangeProperty (no minor), code Window (no extension), value 6291465`
Without it:
`[xwayland/xwm.c:999] xcb error: op 18:0, code 3, sequence 103, value 6291465`
The value in case of Window is the window id, so we can tell what function applied on which window which is a good start.
The sequence ought to be able to tell us more precisely which invocation it was, but we never log it when calling functions so is useless in practice and no longer logged.
This message appears naturally when closing urxvt here, so it's easy to test without messing with the code to generate fake errors... We must be calling `xcb_change_property` on the window after it got closed?
Fixes #637.
=> Print xcb errors

rootston/seat.c
```
#0  0x00007f2d856e5db7 in wl_list_remove (elm=0x55db001795c8) at src/wayland-util.c:55
#1  0x000055dafd418b5e in handle_tablet_tool_destroy (listener=0x55db001795b0, data=0x55db0013b510) at ../rootston/seat.c:524
#2  0x00007f2d859484dc in wlr_signal_emit_safe (signal=0x55db0013b538, data=0x55db0013b510) at ../util/signal.c:29
#3  0x00007f2d8592e5c3 in wlr_input_device_destroy (dev=0x55db0013b510) at ../types/wlr_input_device.c:33
#4  0x00007f2d85915af3 in wlr_libinput_backend_destroy (wlr_backend=0x55daff607770) at ../backend/libinput/backend.c:110
#5  0x00007f2d8590c74d in wlr_backend_destroy (backend=0x55daff607770) at ../backend/backend.c:39
#6  0x00007f2d859182b6 in multi_backend_destroy (wlr_backend=0x55daff5ff250) at ../backend/multi/backend.c:47
#7  0x00007f2d85918578 in …
```
=> rootston: fix segfault in handle_tablet_tool_destroy

meson.build
Using `source_root` breaks the build when used as a subproject.
=> meson: use current_source_dir instead of source_root

backend/drm/drm.c, types/wlr_output.c
When using the DRM backend and multiple outputs, that reduces the
number of commits.
Test plan: check that cursors aren't broken on a multi-monitor setup
=> output: don't move hidden cursors

types/wlr_output_layout.c
=> output-layout: fix output global not destroyed

types/wlr_xdg_shell_v6.c
Role strings should be unique.
=> differentiate xdg-toplevel roles

render/gles2/texture.c
#698 introduces a regression for xwayland surfaces, they appear inverted wrt the y axis.
=> Fix y-inverted rendering for xwayland surfaces

include/rootston/desktop.h, include/rootston/seat.h, include/rootston/view.h, include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/desktop.c, rootston/output.c, rootston/seat.c, rootston/wl_shell.c, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, rootston/xwayland.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
Test plan:
* Make sure xdg-shell still works
* Try `mpv --fs` or https://gist.github.com/emersion/34ed72adecd78bdfac9208a97ffb46a3
* Try to reproduce crashes described in issues below
Fixes #688
Fixes #674
Fixes #679
Fixes #671
Fixes #650
Closes #681
Closes #708
=> Add map/unmap to xdg-shell

rootston/cursor.c, rootston/desktop.c, rootston/output.c
Fixes #729.
Change rootston's `view->rotation` to be computed with normal expectation.
Test plan:
~~For reference, the old 3d code was this, that seems to agree:~~ The old behaviour was against usual conventions:
```c
wlr_matrix_identity(mat);
float _cos = cosf(radians);
float _sin = sinf(radians);
mat[mind(1, 1)] = _cos;
mat[mind(1, 2)] = _sin;
mat[mind(2, 1)] = -_sin;
mat[mind(2, 2)] = _cos;
```
=> Rootston: fix rotation heading (was: wlr_matrix: fix matrix_rotate)

backend/drm/renderer.c, include/wlr/types/wlr_matrix.h, render/gles2/renderer.c, types/wlr_matrix.c
See https://github.com/swaywm/wlroots/commit/f1cbbac636d59d22373883f6bc85f8863e01c8c5#r28140751
We have two potential solutions:
- Transpose right before binding, this introduces a little overhead
- Use column-major matrices, this makes matrix functions a little confusing because the indices are not in the order we'd expect
=> Don't use OpenGL matrix transposition

include/render/gles2.h, render/gles2/renderer.c, render/gles2/shaders.c, render/gles2/texture.c
Gles2 changes pulled out of
https://github.com/swaywm/wlroots/pull/724
to unbreak rendering GL_TEXTURE_EXTERNAL_OES. See individual commits for details.
=> Gles2 tex target

backend/wayland/wl_seat.c, backend/x11/backend.c, include/backend/wayland.h, include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/output.c, types/wlr_pointer.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
- Some memory leaks in xdg shells, rootston output and x11 backend
- A use after free in wayland backend.
I'm not 100% happy with my use-after-free fix, if someone has a better idea to access the wlr_wl_pointer from the output destroy handler. At first I wanted to add another output event handler listener to the pointer itself but since the wayland backend can have many outputs and a single pointer (at least with the current design, how does it handle being started from a rootston with multiple seats?) it was more straight-forward to cleanup from output, but I'm sure this can be done better.
=> Address sanitizer fixes

backend/drm/drm.c, backend/drm/renderer.c, backend/headless/output.c, backend/wayland/output.c, examples/output-layout.c, examples/rotation.c, examples/tablet.c, examples/touch.c, include/render/gles2.h, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, include/wlr/render/wlr_texture.h, render/glapi.txt, render/gles2/pixel_format.c, render/gles2/renderer.c, render/gles2/shaders.c, render/gles2/texture.c, render/wlr_renderer.c, render/wlr_texture.c, rootston/output.c, wlroots.syms
This ports the GLES2 `wlr_renderer` part of #319. This PR tries not to touch too much to the texture part, which will be redesigned in another PR.
Fixes #55
Updates #558
=> Redesign GLES2 renderer

render/egl.c, render/gles2/texture.c, types/wlr_linux_dmabuf.c, types/wlr_surface.c
This aims to add support for formats with more than one plane like NV12.
Test plan
The drivers I have don't support NV12 but maybe someone's does. Therefore marking as WiP since I can't really test it atm but I'll see if can come up with s.th. else that has more than one plane.
According to https://cgit.freedesktop.org/wayland/weston/commit/?id=ee58911912d88caacf340a5cb6a9e25fcba24996 freedreno supports NV12 if somebody running rootston on freedreno could test it that would be great.
=> Linux-dmabuf with n_planes > 1

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
Unify the xdg-surface close functions for toplevels and popups.
Close popups in rootston before closing the view.
fixes #543
=> unified xdg-surface close

types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
Some clients create an xdg_surface, then create an xdg_toplevel,
but don't map it and destroy it right after. The xdg_surface ends
up in a state where it isn't mapped but role-specific resources
have been allocated. xdg_surface_unmap needs to free these
resources without emitting the unmap signal.
Test plan: try @agx's `weston-simple-dmabuf-drm --import-format=NV12`
Fixes #737
=> xdg-shell, xdg-shell-v6: don't emit unmap if surface is unmapped

backend/x11/backend.c
The xcb_connection_t instance that is used here comes from
XGetXCBConnection(), is created by XOpenDisplay(), and is owned by the
returned Display*. Calling xcb_disconnect() directly on it leads to
various use-after-frees during shutdown, as reported by valgrind. The
first one of the about 30 errors is:
```
Invalid read of size 4
at 0x71F2051: xcb_take_socket (in /usr/lib64/libxcb.so.1.1.0)
by 0x78551DD: ??? (in /usr/lib64/libX11.so.6.3.0)
by 0x7855A14: _XFlush (in /usr/lib64/libX11.so.6.3.0)
by 0x7858504: _XGetRequest (in /usr/lib64/libX11.so.6.3.0)
by 0x7838966: XFreeGC (in /usr/lib64/libX11.so.6.3.0)
by 0x783238B: XCloseDisplay (in /usr/lib64/libX11.so.6.3.0)
by 0x4E680C2: wlr_x11_backend_destroy (backend.c:333)
by 0x4E57E94: wlr_backend_destroy (backend.c:39)
by 0x4E629FB: …
```
=> Fix use-after-free in x11 backend during shutdown

include/rootston/config.h, include/wlr/types/wlr_box.h, include/wlr/util/region.h, rootston/config.c, rootston/output.c, util/region.c
It was broken because the damage extents were rotated about its
own center, not about the center of the surface.
This adds a new wlr_region_rotated_bounds that rotates regions.
This allows us to have only one code path (for both non-rotated
views and rotated views) and optimizes rendering for rotated
views.
Fixes #714
=> Fix damage tracking for rotated surfaces

rootston/seat.c
The output fullscreen surfaces are drawn in front of everything, without
consideration for view z-order.
If a view is brought to front, unset any fullscreen view that would
cover this view to make sure the view is visible.
Testplan: Fullscreen a view, then `[Alt]+[Tab]` to a surface that intersects the relevant output.
Fixes https://github.com/swaywm/wlroots/issues/676
wl_shell mpv misbehaves in two ways.
* It doesn't notice it gets unfullscreened (from a quick check a protocol issue)
* It is placed at the wrong coordinates.
=> unset fullscreen when surface is brought to front

rootston/seat.c
```==32557==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000425f96 bp 0x7fff8ac19de0 sp 0x7fff8ac19d20 T0)
==32557==The signal is caused by a READ memory access.
==32557==Hint: address points to the zero page.
#0 0x425f95 in roots_seat_set_focus ../rootston/seat.c:737
#1 0x40bcd6 in roots_cursor_press_button ../rootston/cursor.c:272
#2 0x40c1f7 in roots_cursor_handle_button ../rootston/cursor.c:298
#3 0x42179b in handle_cursor_button ../rootston/seat.c:58
#4 0x7f1651062367 in wlr_signal_emit_safe ../util/signal.c:29
#5 0x7f165101b532 in handle_pointer_button ../types/wlr_cursor.c:344
#6 0x7f1651062367 in wlr_signal_emit_safe ../util/signal.c:29
#7 0x7f1650ff633b in handle_pointer_button ../backend/libinput/pointer.c:85
#8 0x7f1650ff5291 in wlr_libinput_event …
```
=> rootston: Fix segfault in seat unfullscreening

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
The motivation for this is:
- `get_popup` and `get_toplevel` allocate role-specific resources.
- On the first non-null commit, the surface gets mapped.
- On a null commit, the surface gets unmapped. It can be mapped
again with a non-null commit.
- When the role object (xdg-toplevel or xdg-popup) is
destroyed, the surface is unmapped and role-specific resources
are destroyed. The client can call `get_popup` or `get_toplevel`
again on that surface.
- When the xdg-surface object is destroyed, the surface is
unmapped, role-specific resources are destroyed and the surface
itself is destroyed.
TODO:
Fixes #747
=> xdg-shell-v6: don't destroy role resources on unmap

include/rootston/view.h, rootston/xdg_shell.c, rootston/xdg_shell_v6.c
Test plan: spawn an xdg-shell client that has menus with xdg-popups. Resize the window so that it becomes small. Open a menu and then open a submenu so that the submenu si displayed outside the parent toplevel. Close the submenu. There are damage artifacts on master, there shouldn't be any with this PR.
TODO:
Fixes #752
=> [WIP] xdg-shell: damage view when popup is mapped/unmapped

backend/drm/drm.c, backend/drm/renderer.c, backend/wayland/output.c, examples/multi-pointer.c, examples/output-layout.c, examples/pointer.c, examples/rotation.c, examples/touch.c, include/backend/drm/drm.h, include/render/gles2.h, include/wlr/render/egl.h, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, include/wlr/render/wlr_texture.h, include/wlr/types/wlr_linux_dmabuf.h, render/egl.c, render/gles2/renderer.c, render/gles2/texture.c, render/wlr_renderer.c, render/wlr_texture.c, types/wlr_linux_dmabuf.c, types/wlr_output.c, types/wlr_surface.c, types/wlr_xcursor_manager.c
This PR ports the texture part of #319.
- Textures are now immutable (apart from those created from raw
pixels), no more invalid textures
- Move all wl_drm stuff in wlr_renderer
- Most wlr_texture fields are now private
- Remove some duplicated DMA-BUF code in the DRM backend
- Add more assertions
- Stride is now always given in bytes rather than in pixels
- Drop wl_shm functions
Test plan: try `weston-simple-shm`, `weston-simple-egl` and `weston-simple-dmabuf-drm` (with `--import-format` set to XRGB and then set to NV12). Try GTK clients, `weston-terminal` and Xwayland clients.
Updates #558
=> Redesign wlr_texture

backend/meson.build, backend/x11/backend.c, include/backend/x11.h, meson.build
Test plan: under X11 backend, focus rootston, open a terminal, press Shift, focus another window, release Shift, focus rootston, type something. The characters typed should be lowercase, not uppercase.
TODO:
Fixes #227
=> backend/x11: correctly update keyboard modifiers

include/rootston/view.h, include/wlr/xwayland.h, rootston/cursor.c, rootston/xwayland.c, xwayland/xwm.c
`notify` is never used in event names, and `map` is used in other shells.
Will send a Sway PR when this one gets approved.
=> xwayland: rename map_notify to map for consistency

render/gles2/renderer.c
```
../render/gles2/renderer.c: In function ‘gles2_render_texture_with_matrix’:
../render/gles2/renderer.c:140:2: error: ‘target’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
glBindTexture(target, tex_id);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../render/gles2/renderer.c:145:2: error: ‘prog’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
glUseProgram(prog);
```
=> Fix build error with -O2

examples/layer-shell.c, examples/meson.build, include/rootston/desktop.h, include/rootston/output.h, rootston/cursor.c, rootston/desktop.c
This glues things together in rootston and extends the layer shell example to visually demonstrate pointer events.
Test plan:
1. Run rootston
2. Run layer shell example with various configurations
3. Test that pointer appears in correct place and clicking changes the color of the surface
4. Test that surface gets a client side cursor
5. Bring a shell surface to the party and make sure nothing breaks
6. Test z-ordering works correctly with several layer surfaces
=> Add pointer input to layer surfaces

include/wlr/types/wlr_surface.h, rootston/desktop.c, types/wlr_surface.c
Ref https://github.com/swaywm/sway/pull/1674
=> Add wlr_surface_point_accepts_input

rootston/desktop.c, xwayland/xwm.c
This makes it consistent with the rest of the codebase.
=> xwayland: specify xwm cursor stride in bytes

backend/backend.c, backend/meson.build, backend/wayland/wl_seat.c, backend/x11/backend.c, backend/x11/input_device.c, backend/x11/output.c, include/backend/x11.h, include/wlr/backend/x11.h
I'm not satisfied with the X11 event handling, but it's not like there's a better way to do this.
Test plan:
* Config: `[output:X11-1] rotate = 90 scale=1.5`
* `env WLR_X11_OUTPUTS=2 build/rootston/rootston`
* Open a window, check that input events are correct
Fixes #768
=> backend/x11: add support for multiple outputs

backend/x11/output.c
Otherwise the destroy message is kept buffered and never reaches
the X11 server. Thanks X11.
=> backend/x11: flush after destroying window

backend/drm/renderer.c, backend/headless/backend.c, backend/wayland/backend.c, backend/x11/backend.c, examples/output-layout.c, examples/rotation.c, examples/tablet.c, examples/touch.c, include/wlr/render/gles2.h, render/gles2/renderer.c
There's no reason why the renderer needs the backend. This PR makes the renderer more modular.
This makes it possible to use the renderer in test clients. We probably won't do that because we want to keep our client examples readable for someone unfamiliar with wlr_renderer.
=> Untie wlr_backend from wlr_renderer

include/wlr/render/egl.h, include/wlr/render/wlr_texture.h, render/egl.c, render/gles2/texture.c
This allows external renderers and potential future GL-based
renderers to re-use this function.
Updates #775
=> render/egl: add wlr_egl_create_image_from_wl_drm

examples/output-layout.c, examples/rotation.c, examples/tablet.c, examples/touch.c
We don't need to create a new renderer, the backend already provides one.
=> examples: get wlr_renderer from the backend

include/render/gles2.h, include/wlr/render/egl.h, include/wlr/render/gles2.h, render/egl.c, render/gles2/renderer.c, render/gles2/texture.c
This makes `wlr_gles2_texture` more modular: it can be re-used in another external GLES2 renderer.
Updates #775
=> Untie wlr_gles2_renderer and wlr_gles2_texture

examples/layer-shell.c, include/rootston/seat.h, include/wlr/types/wlr_layer_shell.h, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/cursor.c, rootston/layer_shell.c, rootston/seat.c, types/wlr_layer_shell.c, types/wlr_wl_shell.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
Per the spec, the topmost layer surface above the shell surface layer always has keyboard focus. Beneath the shell surface layer, layer surfaces will receive keyboard focus normally (when clicked). Note that layer surfaces beneath the shell surface layer receive a sort of temporary focus from the seat - they do not participate in the usual focus list for alt-tabbing and such. Layer surfaces that do not want keyboard input continue to not receive keyboard enter events or take focus away from other surfaces when clicked.
To request keyboard events, pass `-k` to the example layer shell and look for key events in the log.
=> Add keyboard input to layer surfaces

include/wlr/types/wlr_cursor.h
This is required for wlroots-rs to implement https://github.com/swaywm/wlroots-rs/issues/125 since we need this field to store a runtime handle to ensure there's not multiple mutable borrows.
=> Added user data field for wlr_cursor

backend/x11/input_device.c, backend/x11/output.c, include/backend/x11.h
This code has been broken for a long time.
Test plan: resize the window, check that the cursor position is still correct during the resize operation.
=> backend/x11: fix cursor position when receiving configure event

render/egl.c
This makes it match 4bf936360d42fb5b96a44fd17028ae66fc462362.
=> egl: silence dmabuf error when extension is not present

include/wlr/types/wlr_surface.h, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/desktop.c, types/wlr_compositor.c, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
* Fix `wlr_surface_subsurface_at` and friends. It was using buffer size instead of surface size.
* Introduce `wlr_surface_surface_at` and friends
* Simplify code
Test plan: add `wlr_log(L_DEBUG, "%p %f,%f", surface, sx, sy);` at line 904 of `wlr_surface.c`, open gnome-calculator, check that sx, sy are correct.
=> Redesign surface input functions

backend/headless/output.c, backend/x11/output.c
This fixes custom modes in Sway.
=> backend/{x11,headless}: use default if supplied refresh is invalid

include/wlr/types/wlr_surface.h, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/output.c, types/wlr_surface.c, types/wlr_wl_shell.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
This PR adds surface iterators to `wlr_surface` and all shells.
Test plan: check that rendering of surfaces, subsurfaces and popups works.
Fixes #822
=> Add surface iterators

xwayland/xwm.c
This allows compositors to access the surface being unmapped. This
is also more consistent with the destroy signal.
=> Emit xwayland unmap signal before unmapping

types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
Test plan: open `gnome-calculator`, open a popup (e.g. the combobox or a right click menu), check that pointer input is fixed.
Fixes #858
=> Fix wlr_xdg_surface_surface_at for popups

types/wlr_output.c
It was like this probably because we inverted flipped-90 and flipped-270 in the past.
Test plan: check that damage tracking works with all transforms.
Fixes #796
=> Fix wlr_output_transform_compose

examples/support/config.c, examples/support/ini.c, include/wlr/types/wlr_output.h, rootston/config.c, rootston/ini.c
Or if you don't like these let's add -Wno-format-truncation -Wno-stringop-truncation (the later only happens in -O2, but I'm not sure what enables both as I only get them on fedora)
likewise, I have the same for sway, just waiting to see how this is received to push.
=> Fix gcc string truncation warnings

protocol/meson.build
They deprecated 'code' for 'public-code', but suggest using 'private-code'...
arch doesn't have that version of wayland yet, so this is only annoying me and either needs me to live with it or wait until the build bot gets the update (I have 1.14.93 but 1.15.0 just got released and should probably be there soonish)
The second question is I haven't deeply checked what difference is between public/private-code. I haven't had any problem with this using private-code (e.g. swaybar works fine) but maybe some will want to use wlroots in a way that require public-code, I don't really understand the implication of the marshaling difference.
Once something is decide here I'll push the same for sway.
=> Use 'private-code' for wayland-scanner code generation

backend/x11/backend.c, backend/x11/input_device.c, backend/x11/output.c, include/backend/x11.h
The first commit is a refactoring with (I think) obviously no change in behaviour.
The second commit has a harmless, internal-only behaviour change that should not make any difference.
The last two commits in this deal with resizing. They can be tested by starting rootston with the X11 backend, (making it floating if on a tiling WM,) and resizing it with the mouse a lot.
=> Some changes to the x11 backend

backend/x11/backend.c
When the X11 server sends an expose event, that means that "this
rectangle here (the event contains x,y,width,height) has undefined
contents on your window; please redraw that". This means that we need a
swap. However, so far the code does not actually enforce that a swap
happens.
For example, start rootston, switch to another workspace and then switch
back. The rootston window will not be redrawn (before commit
52b058c2a31fb, it would just be fully white; after that commit it will
show whatever was visible on the old workspace). This is because the
drawing code concludes that nothing needs to be done. However, in fact a
swap is necessary.
This reverts commit e79d92458852373, because its optimisation is already
done now: wlr_output_update_needs_swap() emits a signal, which is
handled by …
=> x11 backend: Expose events mean "needs swap"

rootston/layer_shell.c
When e.g. running rootston under X11 it would otherwise crash when
closing rootston like:
#0  0x00007f0197da7327 in wl_list_remove () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#1  0x000056306fcee7fb in handle_destroy (listener=0x5630723a2948, data=0x5630723a5d20) at ../rootston/layer_shell.c:273
#2  0x00007f019800a552 in wlr_signal_emit_safe (signal=0x5630723a5e30, data=0x5630723a5d20) at ../util/signal.c:29
#3  0x00007f0197fef808 in layer_surface_destroy (surface=0x5630723a5d20) at ../types/wlr_layer_shell.c:169
#4  0x00007f0197ff0001 in client_handle_destroy (resource=0x56307229c4c0) at ../types/wlr_layer_shell.c:371
#5  0x00007f0197da2f30 in  () at /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
#6  0x00007f0197da77f9 in  () at …
=> rootston: don't crash on shutdown

types/wlr_keyboard.c
wlr_keyboard manages the xkb-common state of the compositor.
It used to update the state, update the modifiers, then notify the
compositor.
When [Shift_L] was pressed and released, this resulted in an event chain:
Modifiers: Shift
Key: Shift_L (Pressed)
Modifiers:
Key: Shift_L (Release)
The xkb-docs state that the state should be updated *after* the key was
handled [1], to prevent the new state from influencing the actual key
generated.
To achieve this, the event to the compositor is emitted, *before*
wlroots handles the xkb and internal keyboard state.
With this patch applied, the emitted events ill be:
Modifiers:
Key: Shift_L (Pressed)
Modifiers: Shift
Key: Shift_L (Release)
[1] https://xkbcommon.org/doc/current/group__state.html#gac554aa20743a621692c1a744a05e06ce
Testplan: Log the …
=> reorder xkb state handling in wlr_keyboard

xwayland/xwayland.c
Some systems don't have xwayland in /usr/bin, but in other paths. 
wlroots was unable to find Xwayland binaries outside of standard locations
=> xwayland: preserve the PATH variable

examples/layer-shell.c, include/rootston/layers.h, include/wlr/types/wlr_layer_shell.h, include/wlr/types/wlr_xdg_shell.h, rootston/desktop.c, rootston/layer_shell.c, rootston/output.c, rootston/xdg_shell.c, types/wlr_layer_shell.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
- Extend the example client to allow to close the popup and handle mouse input
- Send frame_done events so surface updates work
- Damage popups
TODO (in followups):
=> Layer popups: work on top of PR 867

rootston/layer_shell.c
Reuse what already handles rotation and scaling. This unbreaks popups
on rotated or scaled outputs.
Can be tested with layer-shell example.
=> layer-shell: use output_damage_{whole,from}_local_surface

backend/drm/renderer.c, backend/headless/output.c, backend/wayland/output.c, backend/x11/output.c, examples/layer-shell.c, include/wlr/render/egl.h, render/egl.c, render/gles2/texture.c
This also fixes the `eglDestroySurface` error under the Wayland backend.
=> render/egl: add wlr_egl_destroy_surface

rootston/layer_shell.c, types/wlr_layer_shell.c
On the X11 backend the cursor position might be outside the output
window so no output is returned leading to the assert to trigger. Use
sane fallback instead of crashing.
=> layer-shell: Fix crash when cursor is intially outside any output

include/wlr/types/wlr_region.h, include/wlr/types/wlr_surface.h, types/wlr_compositor.c, types/wlr_region.c, types/wlr_surface.c
All public resource creators now take a new ID for the resource
and an optional list where the resource link is added. When the
resource is destroyed it is its own responsibility to remove
itself from the list. This removes the need for the caller to add
a destroy listener.
This commit fixes a few segfaults with resources not removed from
the list when destroyed.
=> compositor: redesign how resources are managed

xwayland/xwm.c
7f70d244a9802207c258bd5da6d4ada5eb15484a made utility windows
managed, because it made sense according to the spec. Turns out
Firefox uses them for popups.
=> xwayland: make utility windows unmanaged again

backend/libinput/events.c, backend/wayland/backend.c, backend/wayland/output.c, backend/wayland/wl_seat.c, backend/x11/backend.c, backend/x11/input_device.c, backend/x11/output.c, include/backend/wayland.h, include/backend/x11.h, include/wlr/backend/wayland.h, include/wlr/types/wlr_input_device.h, rootston/seat.c, types/wlr_input_device.c
This allows the backend to suggest an output mapping for an input device. This is mainly used by the Wayland/X11 backends to suggest a mapping between pointers that give absolute events relative to one surface and the surface itself. This could be used by a backend capable of matching touchscreens to their output.
rootston will try to get a mapping from the config, and default to what the backend suggests.
This removes the nonsense layout coordinates conversions in the Wayland and X11 backends.
Test plan: try opening multiple outputs on the Wayland/X11 backends, check that input events are not messed up. Try adding scaling and transformations to outputs.
Fixes #925
=> Add wlr_input_device.output_name

rootston/output.c
Otherwise rootston will crash when an output is re-plugged.
=> rootston: remove mode and transform signals when output is destroyed

backend/wayland/wl_seat.c, backend/x11/input_device.c, types/wlr_cursor.c
Honor output rotation when processing touch coordinates.
I can't test the tablet related parts, touch works as expected now.
Fixes #928
=> wlr_cursor: transform absolute coordinates

backend/drm/drm.c
Don't allow any value of the env var to disable atomic mode setting.
=> drm: only disable atomic modesetting when WLR_DRM_NO_ATOMIC == 1

docs/env_vars.md
Since this influences the inner workings it might make sense to have them documented.
=> Document env vars used by wlroots/rootston

types/wlr_cursor.c
Fix this weird gcc warning, same as #946, but it was closed.
=> Fix gcc maybe-uninitialized in wlr_cursor apply_output_transform

backend/drm/drm.c, backend/wayland/backend.c, backend/wayland/output.c, include/backend/wayland.h, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
This changes the `wlr_output_impl.set_cursor` function to take a
`wlr_texture` instead of a byte buffer. This simplifies the
DRM and Wayland backends since they were creating textures from
the byte buffer anyway.
With this commit, performance should be improved when moving the
cursor since outputs don't need to be re-rendered anymore.
Test plan: check that client cursors work on the DRM and Wayland backends.
Fixes #281
=> output: always use hardware cursors if available

README.md
Self explanitory fix for the README. Grep makes this appear to be the only place this mixup occurs.
=> Fix xcb/xkb swap in README

include/wlr/types/wlr_output_damage.h, types/wlr_output_damage.c
Test plan: set the limit to 1, open htop on gnome-terminal.
The current value is kind of arbitrary, it just roughly reflects what GTK+ does.
Fixes #949
=> output-damage: limit the number of damaged rectangles

rootston/output.c
We're not inverting the scissored rectangle anymore, this is done by `wlr_renderer`.
=> rootston: remove outdated comment

backend/drm/drm.c, backend/wayland/output.c, include/backend/wayland.h, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
Test plan: try different combinations of output scale/transform, try compositor and client cursors, try clients that support HiDPI (e.g. GTK+) and clients that don't (e.g. Xwayland clients).
cc @Ongy @Timidger: this is a breaking change for the output implementation API.
=> Fix hardware cursors scale & transform

include/wlr/types/wlr_xdg_output.h, types/wlr_xdg_output.c
And rename `xdg_*` functions to prevent clash with protocol structs.
Updates #909
=> xdg-output: redesign resource destroy

backend/libinput/pointer.c, backend/wayland/wl_seat.c, backend/x11/input_device.c, include/backend/wayland.h, include/wlr/types/wlr_pointer.h, include/wlr/types/wlr_seat.h, rootston/cursor.c, types/data_device/wlr_drag.c, types/seat/wlr_seat_pointer.c, types/wlr_wl_shell.c, types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
Test plan: `env WAYLAND_DEBUG=1 weston-clickdot` and check that `axis_discrete` and `axis_source` events are sent. Note that not all hardware supports this.
cc @Ongy @Timidger: this requires changes in your libraries and compositors.
=> Add support for discrete axis values and axis source

types/wlr_xdg_output.c
It should be the size of the output in layout coordinates. Prior to
this commit we were not applying the output transform to the size.
=> xdg-output: fix logical_size

types/wlr_xdg_shell.c, types/wlr_xdg_shell_v6.c
The anchor and gravity enums are no longer a bitfield. That was _fun_ to debug and fix.
Fixes #916
=> Fix xdg-shell stable popups

render/egl.c
Tested  on virtualbox with Fedora 28 guest, which does not have the `EGL_WL_bind_wayland_display` extension. The function pointer `eglBindWaylandDisplayWL `is non-null and causes a crash when used (SIGSEGV in `__strlen_avx2`).
Instead use `struct wlr_egl.egl_exts.bind_wayland_display` which is correctly set in `wlr_egl_init`, but not yet used...
=> fix check of EGL_WL_bind_wayland_display presence

backend/wayland/output.c
This makes it easier to know which output is which window.
This just mirrors what the X11 backend does.
=> backend/wayland: print output name in window title

render/gles2/shaders.c
Corrects alpha handling for the `tex_fragment_src_rgba` and `tex_fragment_src_rgbx` shaders
This fixes the opacity issue in swaywm/sway#1982
=> Fix alpha for src_rgba and src_rgbx

rootston/output.c, types/wlr_output.c
We currently clear with solid transparent, which isn't particularly useful.
=> output: correctly clear screen when fullscreened

rootston/cursor.c, rootston/seat.c
This change is needed to fix edge cases in input methods using layer shells.
Input methods don't want to directly change the focus state of the compositor. With input method as non-interactive layer shell, clicking it would still remove the *active* status from an app, causing confusion when the input method clicks affect focus, like invoking a window switch.
First change fixes the inconsistency of removing focus when un-focuseable things were clicked. The second change makes focus stay where it was before.
This is required to support `virtual-keyboard-unstable-v1` in rootston.
=> Ignore clicks on un-focuseable things.

backend/backend.c, backend/drm/backend.c, backend/drm/renderer.c, backend/headless/backend.c, backend/wayland/backend.c, backend/x11/backend.c, examples/multi-pointer.c, examples/output-layout.c, examples/pointer.c, examples/rotation.c, examples/simple.c, examples/tablet.c, examples/touch.c, include/backend/drm/renderer.h, include/wlr/backend.h, include/wlr/backend/drm.h, include/wlr/backend/headless.h, include/wlr/backend/wayland.h, include/wlr/backend/x11.h, include/wlr/render/wlr_renderer.h, render/wlr_renderer.c, rootston/main.c
Compositors now have more control over how the backend creates its
renderer. Currently all backends create an EGL/GLES2 renderer, so
the necessary attributes for creating the context are passed to a
user-provided callback function. It is responsible for initializing the
provided `wlr_egl` and to return a renderer. On fail, return NULL.
Fixes #987 
Things I'm not sure about:
1) Where to place and how to name `wlr_backend_renderer_autocreate()` - should it be in `backend.c` or `wlr_renderer.c`?
2) Should we allow passing NULL to `wlr_backend_autocreate()` or force the user to specify `wlr_backend_renderer_autocreate` as renderer initialization function?
3) Example - is another example needed? Or maybe implement such a function in rootston to demonstrate how this is done?
4) Testing - I've …
=> [RFC] backends: implement custom EGL and renderer initialization

backend/drm/backend.c, backend/wayland/backend.c, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, render/gles2/renderer.c, render/wlr_renderer.c, rootston/main.c
This adds wl_drm support to the X11 and headless backends.
cc @Ongy @Timidger: this renames `wlr_renderer_init_wl_shm` to `wlr_renderer_init_wl_display`
=> render: bind wl_drm in renderer

types/wlr_surface.c
These statements do the same thing.
=> surface: remove wl_resource_post_event

include/rootston/desktop.h, include/rootston/virtual_keyboard.h, include/wlr/types/wlr_virtual_keyboard_v1.h, protocol/meson.build, protocol/virtual-keyboard-unstable-v1.xml, rootston/desktop.c, rootston/meson.build, rootston/virtual_keyboard.c, types/meson.build, types/wlr_virtual_keyboard_v1.c
This change is to support the recently proposed `virtual-keyboard-v1` protocol.
Because virtual keyboards are privileged, the commits setting up an authorization system - meant to be general for all input methods - are separate.
The main commit provides support in wlroots as well as rootston. The keyboard does not attempt to synchronize its modifier status with the rest of the system, and code for having multiple instances running at the same time has not been extensively tested, however it's rather simple and wasn't failing either.
=> Support virtual keyboard protocol

backend/drm/renderer.c, include/wlr/render/dmabuf.h, include/wlr/render/egl.h, include/wlr/render/gles2.h, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, include/wlr/render/wlr_texture.h, include/wlr/types/wlr_linux_dmabuf.h, render/egl.c, render/gles2/renderer.c, render/gles2/texture.c, render/wlr_renderer.c, render/wlr_texture.c, types/wlr_linux_dmabuf.c, types/wlr_surface.c
The DMA-BUF attributes struct is starting to be used in various parts of wlroots, some of which have nothing to do with the linux-dmabuf protocol. This extracts the common struct into `wlr/render/dmabuf.h`.
This also removes the ability to have per-plane modifiers.
Fixes #908
=> Only allow one modifier per DMA-BUF, split attributes struct in render/

types/wlr_virtual_keyboard_v1.c
* Stop listening to wl_display destroy signal, fixes a segfault if the manager is destroyed prior to the display
* Destroy resources created by the manager, fixes memory leaks if the compositor isn't using `wl_display_destroy_clients`
cc @dcz-purism
=> virtual-keyboard: fix wlr_virtual_keyboard_manager_v1_destroy

include/wlr/types/wlr_surface.h, include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, rootston/xdg_shell.c, rootston/xdg_shell_v6.c, types/wlr_surface.c, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell_v6/wlr_xdg_surface_v6.c
This function defaults and clips the xdg-surface geometry to the
bounding box of the surface + its subsurfaces, as specified by the
protocol spec.
=> Add wlr_surface_get_geometry

include/rootston/seat.h
This function is unimplemented and is redundant because all devices added
with roots_seat_add_device get destruction handlers assigned already.
This fixes #998.
=> Remove redundant roots_seat_remove_device function

types/wlr_linux_dmabuf.c
The printf conversion specifiers in a call to wl_resource_post_error
do not specify the type correctly on armhf:
../types/wlr_linux_dmabuf.c: In function 'params_add':
../types/wlr_linux_dmabuf.c:104:21: error: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t {aka long long unsigned int}' [-Werror=format=]
"sent modifier %lu for plane %u, expected modifier %lu like other planes",
~~^
%llu
To fix this, we use standard printf conversion specifier macros from
inttypes.h.
=> wlr_linux_dmabuf: Fix printf conversion specifiers on armhf

types/wlr_surface.c
This would dead-loop and never walk up if called on a subsurface.
This came up with firefox, this function would just freeze up everything at some point, if I understand the semantics of `root_surface` correctly it makes more sense to walk up to the parent.
=> wlr_surface_get_root_surface: walk up parent

include/wlr/types/wlr_seat.h, types/data_device/wlr_drag.c, types/seat/wlr_seat.c
This lets clients bind to a seat multiple times by re-using the existing
wlr_seat_client whenever a duplicate request happens.
Previously, an independant wlr_seat_client would be created and only
events from one would be processed.
Fixes #1023.
~~FWIW I'm not 100% happy with the style (new_seat_client bool and the need for a new function in the API, and that function's name), but at least it seems to work.~~
Cc @ongy @Timidger as API changes, even if I didn't need to change anything to rootston/sway, it's just a ~~new helper function~~ change in the `wlr_seat_client` struct
=> seat: allow clients to bind to seat multiple times

types/wlr_box.c
Now that box `x` + `width` is not within the box, update the intersection and closest point functions to work correctly.
There are probably a lot more off-by-one errors in the code. This fixes the positioner.
=> fix wlr_box_intersection and closest_point

types/wlr_surface.c
This displays the last surface up in front.
This is more of a monkeying patch (came up with FF-wayland as well, subsurfaces drawn for popups would be at the bottom -- FF draws a tree of surface with one root and two children, the order of the children was wrong).
Now that it's done it kind of makes sense too me, but maybe we should fix the order in which the subsurfaces are happened instead? Anyway, RFC.
=> wlr_surface: walk up surfaces in reverse order

types/wlr_box.c
`x2` and `y2` were computed as inclusive bounds, and then the size was computed with a subtraction on inclusive bounds. To compute a size you need to do a subtraction between an inclusive bound and an exclusive bound. This PR changes `x2` and `y2` to be exclusive bounds instead.
Fixes https://github.com/swaywm/wlroots/issues/1042
=> box: fix wlr_box_intersection

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, types/xdg_shell/wlr_xdg_toplevel.c, types/xdg_shell_v6/wlr_xdg_toplevel_v6.c
Can be used in sway for auto-floating dialogues and similar and to properly position such transient windows relative to their parent.
=> xdg-shells: add a set_parent signal to toplevel surfaces

include/rootston/seat.h, include/wlr/types/wlr_data_device.h, rootston/seat.c, types/data_device/wlr_drag.c
The event is only emitted on unmap, so I renamed it to `unmap`. I don't like the old approach of emitting both map/unmap on the same event because it's inconsistent with the shell behavior. (I wrote this code and it just confused me).
Do we want to have a `map` event? We used to have one, right?
Reviewing to see if we need to `unmap` in other places.
=> drag-icon map and unmap fixes

backend/wayland/wl_seat.c, include/wlr/types/wlr_keyboard.h
Test plan: using the Wayland backend, open `weston-eventdemo` in rootston. In the outer compositor, change focus from the rootston window to another window using keybindings, and back. All keys should be released when rootston looses focus, and pressed again when focusing rootston again.
See #1024
=> backend/wayland: fix keyboard keys not pressed/released when focus changes

rootston/main.c
Destroying all clients disconnects the xwayland client, and
xwayland automatically restarts when disconnected.
Fixes #1026
=> rootston: destroy xwayland before all clients

types/wlr_surface.c
For wl_drm and linux-dmabuf buffers, release now happens in `surface_move_state`.
Test plan: start mpv with `WAYLAND_DEBUG=1`.
Background: https://github.com/swaywm/wlroots/issues/1046#issuecomment-395433065
=> surface: don't release wl_drm and linux-dmabuf buffers early

render/egl.c
If `request_high_priority` is `true`, then `atti` will be `5` in the assert. Since `5` is not less than `5` (`sizeof(attribs)/sizeof(attribs[0])`), the assert fails and sway does not start.
This changes the assert to be less than or equal to.
=> Fix atti assert in wlr_egl_init

include/wlr/render/egl.h, render/egl.c, render/gles2/texture.c
Detecting whether` eglSwapBuffersWithDamageEXT` or `eglSwapBuffersWithDamageKHR` is used should be based on the extension string, not only on the availability of the function.
=> Split eglSwapBuffersWithDamage feature detection

include/wlr/types/wlr_buffer.h, include/wlr/types/wlr_surface.h, types/meson.build, types/wlr_buffer.c, types/wlr_surface.c
This PR introduces `wlr_buffer`, as discussed in https://github.com/swaywm/wlroots/issues/1046#issuecomment-395679806.
`wlr_buffer`s are ref-counted and hold a texture. When they are destroyed, the `wl_buffer` is released and the texture is destroyed.
A compositor can reference the buffer when it needs to:
```c
struct wlr_buffer *buffer = wlr_buffer_ref(surface->buffer);
// Use buffer->texture (can be NULL if client destroys the buffer)
wlr_buffer_unref(buffer);
```
@ammen99 Can you provide some feedback? Would this approach work for you?
Fixes #1046
=> Introduce wlr_buffer

include/render/gles2.h, render/gles2/renderer.c
This is needed as uniform locations are driver implementation-specific and glGetUniformLocation should be normally used according to OpenGL (ES) specification.
I tested this to work on Gemini PDA with Mali graphics proprietary driver and custom hwcomposer backend.
=> Fix GLES2 renderer to use glGetUniformLocations locations

backend/libinput/backend.c, backend/session/direct.c, backend/session/logind.c, backend/session/session.c, include/wlr/backend/session.h
Fixes #1057 
Various little changes to get multi-seat working properly. We were already 99% of the way there.
To test:
- Two GPUs are required
- Another keyboard and mouse helps too, but is not strictly required
- Assign all of the devices to another seat with `loginctl assign seat1 /sys/path/to/device`
logind:
- Start a display manager (I used GDM); it will appear on both seats
- Log in to both seats
There is a limitation with GDM where it doesn't seem to want to start a wayland session on seat1 (the option is not given).
I tested this successfully with sway on seat0 and i3 on seat1.
direct:
GDM doesn't seem to like the direct session. It's probably related to their hard dependency on logind, and I don't care enough to look into it.
- From seat0, run `XDG_SEAT=seat1 sway`
- From seat0, …
=> Multiseat fixes

types/wlr_layer_shell.c
If the layer surface has been closed by the compositor, using `layer_surface_close()`, then the unmap event is emitted immediately. However, when the layer surface is later destroyed by the client, the compositor used to get a second unmap, which is fixed with this commit.
As discussed in IRC, there could be another way to fix this - by not emitting the unmap on in `layer_surface_close()`. However, there is still the possibility the client first unmaps by committing a `NULL` buffer and then destroying the surface, so the change in this PR is needed anyway.
=> layer-shell: check if the surface is mapped in layer_surface_destroy()

include/wlr/types/wlr_buffer.h, include/wlr/types/wlr_surface.h, rootston/output.c, types/meson.build, types/wlr_buffer.c, types/wlr_output.c, types/wlr_surface.c
Running rootston through valgrind revealed that when resizing xwayland is destroying buffers before they are released. So merging #1060 fixes the invalid reads.
This PR is just a combination of #1050 and #1060. Fixes #1061.
cc @Ongy @Timidger @ammen99: this is a breaking change. Here's the sway PR: https://github.com/swaywm/sway/pull/2135
=> Add back wlr_buffer

include/wlr/types/wlr_surface.h, types/wlr_surface.c
This removes the need to allocate a structure for frame callbacks. `wl_resource_get_link` is used instead.
=> surface: remove wlr_frame_callback

backend/session/direct-ipc.c
recvmsg(3) returns 0 if the connection partner has shut down its socket.
The communicate function considered 0 a successful message, though, and
keeps calling recvmsg(3) again and again.
=> FIX: Suprocess loops endlessly when the control socket closes.

include/wlr/types/wlr_surface.h
=> surface: remove matrices

types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell_v6/wlr_xdg_popup_v6.c
Related to #1054 
When you click on another surface during a popup grab, it should end both the keyboard grab and the pointer grab at the same time so that the popup closes when you switch focus (it didn't do that before).
=> xdg-shell: end pointer and keyboard grab at the same time

types/wlr_input_inhibitor.c
It's the last `wl_signal_emit()` in the library.
=> input-inhibit: use wlr_signal_emit_safe

types/wlr_primary_selection.c, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell_v6/wlr_xdg_surface_v6.c, xwayland/xwm.c
see individual commits:
- popups and their parent surface (happens with submenus in konsole)
- primary selection (happens when overwriting selection in e.g. urxvt)
- xwm parents/children (happens when closing gimp)
=> use-after-free fixes (xdg_shell popups, primary selection source, xwm parents)

examples/dmabuf-capture.c, examples/meson.build
Drop new frames if too slow. Speeds up encoding significantly, even with vaapi.
=> examples/dmabuf-capture: move encoding to a separate thread

examples/meson.build, meson.build
This is an optional feature of libavutil, so this will cause a build failure if it's not present (e.g. on Debian/Ubuntu).
Bumps the minimum meson version for the disabler object.
=> Check for libavutil/hwcontext_drm.h

include/wlr/types/wlr_idle.h, types/wlr_idle.c
There was no way to tell wlr_idle to stop processing input events
and rearm timers all the time, such an API is required to have
some form of idle inhibitor.
=> wlr_idle: add helper to enable/disable all timers

types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell_v6/wlr_xdg_popup_v6.c
surface could be NULL there if the popup had been made inert before... I think?
=> xdg_shell popup: fix potential segv in handle_destroy

include/wlr/types/wlr_idle_inhibit_v1.h, types/wlr_idle_inhibit_v1.c
- Added *data pointers to the wlr types
- Cleanup destroy handlers like I think I understood what we talked about, please correct me if I got it wrong
=> Idle inhibit cleanup

CONTRIBUTING.md
`free()` will invalidate the user data field contents, so it makes sense to group these together. We shouldn't call `wl_resource_set_user_data` before emitting the destroy event.
=> contributing: move wl_resource_set_user_data() right before free()

xwayland/xwm.c
In this commit send focus considers the "Client accepts input or input focus" flag. If the client doesn't accept input, it will not set the input focus. The client will do this on her own.
This fixes a bug, where java awt applications (like intellij) do not get focus, if you tab cycle to them or move the focus using the keyboard in sway.
fixes https://github.com/swaywm/sway/issues/2008
=> do not send focus request to a window that doesn't allow it

backend/session/logind.c
Might be a fix for #1090.
Test plan:
* Start rootston with DRM & logind backend.
* Observe that rootston has fds open for /dev/input/event*.
* Switch to another TTY and back.
* Observe that on master those fds have doubled. Another set of fds is added each time libinput is suspended and resumed. This is no longer the case with this patch.
=> Close fd's obtained from logind

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell_v6/wlr_xdg_surface_v6.c
It is common to want to iterate an xdg-surface's popups separately from the toplevel and subsurfaces. For example, popups are typically rendered on top of most other surfaces.
`wlr_xdg_surface_for_each_surface` continues to iterate both subsurfaces and popups to maintain backwards compatibility, <s>though it now iterates all the popups after all the subsurfaces rather than mixing them. Changing this back requires several lines of duplicated code, and I figured it's not likely to cause any issues.</s> This part has been reverted.
=> Introduce wlr_xdg_surface_for_each_popup

CONTRIBUTING.md, xwayland/xwm.c
Enable the stack update again for focus changes on non-focusable views.
I introduced this bug earlier in #1100.
=> fix: add stack update on focus change

rootston/output.c
This is a thing I've already done in sway, but not yet backported to rootston. I originally missed this bug because the parent compositor wasn't implementing damage tracking at that time.
Debugging damage tracking in Sway is a little bit hard because of frequent tree updates and bar repaints. It's usually easier to debug rootston.
=> Fix damage tracking debug mode

include/wlr/types/wlr_xdg_output.h, types/wlr_xdg_output.c
To begin with, no-op updates are unnecessary, so this patch is an
improvement on its own.
Then, this fixes hotplugging issues with xwayland. xwayland waits
for both wl_output and xdg_output to send a "done" event. However,
it doesn't handle well desynchronized "done" updates: if xdg-output
sends "done" twice, the second one will wait for the next wl_output
"done" event. This is an issue when the first is a no-op and the
second is a real update: the second isn't applied. I've considered
patching xwayland instead, but it seems pretty complicated.
=> xdg-output: don't send no-op updates

types/wlr_gamma_control.c
Using redshift-wayland, I occasionally see segfault when unplugging an output. It appears that `gamma_control_set_gamma` receives a `wlr_gamma_control` resource that has already been destroyed. This seems like it must be a bug in redshift, though I haven't yet tracked down exactly what is happening.
If I've misunderstood how the communication happens and it shouldn't be possible to receive one of these, should this instead be an assert?
Traceback and null `gamma_control` returned by `gamma_control_from_resource` (sorry about the lack of debug symbols in sway):
```
>> coredumpctl gdb sway
Journal file /var/log/journal/d0fa6cf37e9f4d1586e8336642604c5d/system@00056c1c68a546c2-8d69904309b2d3d6.journal~ is truncated, ignoring file.
PID: 2334 (sway)
UID: 1000 (vil)
GID: 1001 (vil)
Signal: 11 …
```
=> Bail from setting gamma on destroyed resource

backend/x11/backend.c, backend/x11/output.c
x11: make sure event source is drained
Otherwise running under Xvfb will not deliver any events. This results in e.g. weston-info reporting a 0x0 window size (which results in all sorts of problems) plus some other minor cleanups.
=> Unbreak xvfb

include/wlr/render/interface.h, include/wlr/render/wlr_texture.h, include/wlr/types/wlr_surface.h, render/gles2/texture.c, render/wlr_texture.c, types/wlr_surface.c
This is the enhanced opaque region:
* Clipped to the surface bounds
* Set to the whole surface if the texture is using a format without an alpha channel
Fixes #920
=> Add wlr_surface.opaque_region

include/wlr/xwayland.h, rootston/seat.c, xwayland/xwm.c
The override_redirect flag can change on configure notify and
on map notify. This adds an event to know when it changes.
This removes wlr_xwayland_surface_is_unmanaged which was wrongly
using the window type to decide whether the view should be
unmanaged.
A similar patch was proposed to Weston, but has never been
merged upstream [1].
[1]: https://patchwork.freedesktop.org/patch/211161/
=> xwayland: handle override_redirect flag changes

wlroots.syms
This removes GNU symbol versioning from the dynamic shared object.
Note that this still uses the GNU version file. The alternative would be to use `-export-symbols symfile` (which requires to explicitly list all symbols) or `-export-symbols-regex regex` (which makes it necessary to use a regex instead of simple wildcards, but may be not that bad if we ignore `wlr_signal_emit_safe`'s case and go with something like `^_?wlr_.*`). See for instance https://gitlab.com/axil/gnutls/commit/6c2512405eabc83fe64b72ca81d4c1989a9e0e22
=> Remove symbol versioning from DSO

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, types/xdg_shell/wlr_xdg_toplevel.c, types/xdg_shell_v6/wlr_xdg_toplevel_v6.c
This is useful for example when rendering decorations
I haven't tested much, because I'm not aware of any clients that change app_id. But I successfully managed to get title updates from gedit, so I think it should work fine.
=> xdg-shell(-v6): add set_title and set_app_id toplevel signals

examples/simple.c
- Move a log to where it should be
- Enforce code style
- Rename wlr to backend
=> examples: cleanup simple

include/wlr/xwayland.h, rootston/seat.c, xwayland/xwm.c
https://github.com/swaywm/wlroots/pull/1145 removed the
wlr_xwayland_is_unamanged function while fixing OR, because it was
belieived that it's supposed to work around the broken OR handling.
This was a misunderstanding. is_unmanaged is (while sort of a hack)
intended to work around inherent differences between "real" X sessions
and our Xwayland/wayland situation.
The main reason it exists is to support applications like rofi and dzen,
while not handing focus to other OR windows (which should *not* be
required).
Traditionally, these applications just grabbed input from X and didn't
need to be focused by any logic in the WM. Which of course doesn't work
in wayland compositors. So we have to give them focus in some way.
Giving *every* OR window focus, breaks other applications that don't …
=> reintroduce xwayland is_unmanaged

rootston/main.c
This reverts commit b6ed1f29a4dbba93eb53c32ec5492db8ee1d9343.
This commit breaks xwayland.
=> Revert "rootston: Reap child processes"

include/rootston/cursor.h, include/rootston/input.h, rootston/cursor.c, rootston/desktop.c, rootston/input.c, rootston/layer_shell.c, rootston/xdg_shell.c, rootston/xdg_shell_v6.c
Whenever a new surface is created, we have to update the cursor focus,
even if there's no input event. So, we generate one motion event, and
reuse the code to update the proper cursor focus. We need to do this
for all surface roles - toplevels, popups, subsurfaces.
Fixes #1162
How to test: There are many ways to test, for example open an app and don't move the cursor. The cursor surface should change (and the view should get cursor focus). Or open weston-terminal, right click, hold the button and don't move the mouse - the first menu item should be highlighted.
Further work:
1. I'm not sure, but maybe we should do the same when a surface is unmapped?
2. Port this to sway - it doesn't handle cursor focus properly either
=> rootston: focus newly-created surfaces

backend/drm/atomic.c, backend/drm/drm.c, examples/gamma-control.c, examples/meson.build, include/rootston/desktop.h, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_gamma_control_v1.h, include/wlr/types/wlr_output.h, protocol/meson.build, protocol/wlr-gamma-control-unstable-v1.xml, rootston/desktop.c, types/meson.build, types/wlr_gamma_control.c, types/wlr_gamma_control_v1.c, types/wlr_output.c
See https://github.com/swaywm/wlr-protocols/pull/25
Fixes #1135
=> Implement wlr-gamma-control-unstable-v1

types/meson.build
The file `types/tablet_v2/wlr_tablet_v2.c` includes `libinput.h`, and therefore depends on `libinput`. This fixes a compilation error on some systems that is caused by `libinput.h` not being in the include path.
=> Add missing dependency libinput to types/meson.build

backend/drm/drm.c
This will indicate the user properly when multi-GPU is not supported by their GPU driver.
@n3rdopolis 
I suspect that is what is causing https://github.com/swaywm/wlroots/pull/1168#issuecomment-410449388
=> Check for DRM prime

include/rootston/view.h, rootston/keyboard.c, rootston/xdg_shell.c
This is useful for `xdg-decoration` client devs to test decoration mode changes triggered server-side.
Test plan:
* Add `Ctrl+Shift+d = toggle_decoration_mode` to `rootston.ini`
* Open `rootston` and then spawn `build/examples/toplevel-decoration`
* Press the keybinding
=> rootston: add keybinding to toggle decoration mode

backend/session/session.c
On some systems (most notably laptops with two GPUs) there are GPUs that
don't have attached outputs. However, we still want to load those GPUs
because they could still be used by the compositor for rendering.
=> session: load GPU devices even if they have zero connectors

backend/x11/output.c
Fixes issue #1170. Sets the initial size for the X11 output window  to `(1024,768)` and makes the backend ignore events that try to set one of the window dimensions to zero.
=> Keep X11 backend windows from having an invalid size

include/backend/drm/drm.h, include/wlr/backend/drm.h, rootston/output.c
It is meant to be used by compositors, so it should be in the public headers.
=> move wlr_drm_connector_add_mode to wlr/backend/drm.h

backend/wayland/wl_seat.c, examples/idle-inhibit.c, examples/layer-shell.c, examples/multi-pointer.c, examples/pointer.c, examples/rotation.c, examples/tablet.c, examples/touch.c, rootston/seat.c, types/wlr_virtual_keyboard_v1.c
Note: it's in general not a good idea to define both `_POSIX_C_SOURCE` and `_XOPEN_SOURCE`.
=> Fix build on FreeBSD

meson.build
The later does not exist on FreeBSD
See #725
=> ctags: use -f instead of -o

types/seat/wlr_seat_keyboard.c, types/wlr_virtual_keyboard_v1.c
After destroying the virtual keyboard, listeners could still be pointing to its wlr_input_device signals. This patch sets NULL as the active keyboard if the virtual keyboard is destroyed while in use.
=> virtual_keyboard: fix virtual keyboard destruction

include/wlr/types/wlr_output_layout.h, types/wlr_output_layout.c
Similar to wlr_output_layout_adjacent_output but will return the one that is the farthest away from the reference in given direction.
I refactored the adjacent one to share some code.
=> introduce wlr_output_layout_farthest_output

rootston/layer_shell.c
Surfaces are not notified of cursor position changes if the surface moves, only if the cursor moves. This workaround emits an extra cursor position event before every click to make sure the click lands in the right place.
A better solution would be to update the cursor position while the surface is moving, but it's difficult to provide a correct time value on input events, because the time values are taken from external sources.
Another solution is to set a flag when the surface is moved and clear it on click, after sending the motion event. This reduces the number of motion events: from 1 every click to 1 every click after movement.
=> rootston/surface_layers: fix clicking after surface moved

backend/drm/atomic.c
It doesn't look like there's any motion on a fix from the AMDGPU side,
and using the legacy interface for this isn't so bad.
=> Use legacy modesetting for gamma control

examples/meson.build
Even if the libav* variables were disabler objects, the build targer
dmabuf-capture was being built. Modified the script to support a generic
solution.
=> Fixes examples/dmabuf-capture being built with unmet dependencies

.build.yml, backend/libinput/tablet_pad.c, examples/idle.c, rootston/xdg_shell.c, types/tablet_v2/wlr_tablet_v2_pad.c, types/wlr_cursor.c
A few pedantic changes and unused variables (1-4), and genuine bugs (5,
6).
The reports with the corresponding files and lines numbers are as
follows.
1. backend/libinput/tablet_pad.c@31,44,57
"Allocator sizeof operand mismatch"
"Result of 'calloc' is converted to a pointer of type 'unsigned int',
which is incompatible with sizeof operand type 'int'"
2. types/tablet_v2/wlr_tablet_v2_pad.c@371
"Allocator sizeof operand mismatch"
"Result of 'calloc' is converted to a pointer of type 'uint32_t', which
is incompatible with sizeof operand type 'int'"
3. types/wlr_cursor.c@335
"Dead initialization"
"Value stored to 'dx'/'dy' during its initialization is never read"
4. rootston/xdg_shell.c@510
"Dead initialization"
"Value stored to 'desktop' during its initialization is never read"
5. …
=> Fix bugs listed by clang's static analyzer

include/wlr/types/wlr_screencopy_v1.h
`wlr_screencopy_v1.h` depends on `wlr_box`, but doesn't have the include.
=> add missing wlr_box.h include in wlr_screencopy_v1.h

types/wlr_cursor.c
Fixes compilation error on Arch Linux, gcc 8.2.0-2.
=> Fix uninitialized value in wlr_cursor.

backend/drm/drm.c
This correctly frees CRTCs when disabling outputs without setting
a mode.
Fixes the situation in which some CRTCs were in use by disabled outputs and we want to re-allocate them to other outputs. The first modeset attempt still fails, so this isn't a full fix.
Fixes part of #409
=> backend/drm: allow disabling outputs in NEEDS_MODESET state

backend/drm/drm.c
I failed to see this issue with Valgrind because of the +1.
=> backend/drm: fix invalid VLA size in scan_drm_connectors

types/tablet_v2/wlr_tablet_v2.c
there was an obvious typo leading to NULL pointer dereference
=> fix incorrect NULL check in get_tablet_seat

backend/x11/backend.c, examples/idle.c, examples/multi-pointer.c, examples/output-layout.c, examples/pointer.c, examples/rotation.c, examples/simple.c, examples/tablet.c, examples/touch.c, types/tablet_v2/wlr_tablet_v2.c
The changes in wlroot include a very minor leak in x11/backend.c (7bc2657) and a bug in tablet_manager_v2 (9f511ae).
The other commits to the examples include setting keymaps more securely (7105864), and removing pointers in multi-pointer (6af77e3).
Please let me know if some commits are better merged squashed (say, all the edits to examples).
=> Miscellaneous memory leak fixes

include/wlr/util/log.h, rootston/config.c, util/log.c, xwayland/xwayland.c
Returns the verbosity passed to wlr_log_init().
Used to close stdout/stderr for Xwayland.
=> Add wlr_log_get_verbosity method

.editorconfig
I've recently bothered to configure my editor to actually use this.
Some of us like to use different indent sizes.
=> Remove indent_size from .editorconfig

backend/drm/drm.c, backend/drm/util.c, include/backend/drm/drm.h, types/wlr_output.c
This commit handles better situations in which the number of
connected outputs is greater than the number of available CRTCs.
It'll enable as many outputs as possible, and transfer CRTCs to
outputs that need one on unplug.
This changes CRTC and plane reallocation to happen after scanning
DRM connectors instead of on modeset.
This cleanups CRTCs and planes on unplug to allow them to be
re-used for other outputs.
On modeset, if an output doesn't have a CRTC, the desired mode is
saved and used later when the output gains a CRTC.
Future work includes giving priority to enabled outputs over
disabled ones for CRTC allocation. This requires the compositor to
know about all outputs (even outputs without CRTCs) to properly
modeset outputs enabled in the compositor config file and disable
outputs …
=> backend/drm: better hotplug handling

xwayland/xwayland.c
In rootston, wlr_xwayland_destroy is always called (when compiled with xwayland) which causes a segmentation fault on exit when disabling xwayland per config (e.g. example config).
We could also just fix this by checking in rootston, but this follows the wlr convention of most destroy functions that passing NULL is ok.
=> Fix wlr_xwayland_destroy

backend/drm/legacy.c
I tested sway today on an etnaviv platform (imx6qp/reform) and it worked fine except that the cursor disappeared as soon as I moved it into the swaybar and would not reappear. This was because swaybar clears and then immediately sets a cursor. Both fail in DRM, but the failure of clearing is not seen, leading to a wrong state. This PR adds a missing error handling for the drmModeSetCursor() case where an empty cursor is set.
=> fix cursor loss w/ legacy drm and software cursor (tested on etnaviv)

rootston/layer_shell.c
Layer surfaces are attached to edges of the screen starting with the youngest, causing new ones to always displace existing ones. This changes the order to oldest first, keeping the positions more often.
With this change, layers attached to edges have a more intuitive feeling of "building upon" the edge.
=> rootston: Keep older anchored layers near anchor points

include/wlr/types/wlr_tablet_v2.h, rootston/seat.c, types/tablet_v2/wlr_tablet_v2_pad.c, types/tablet_v2/wlr_tablet_v2_tool.c
Add grabs to the tablet-v2 input device structs.
Also use the tablet-tool grab to implement the logic to *not* change focus when a button is held or the tip is pressed down.
* ~Currently buttons aren't tracked, only the tip works for now.~
Testplan:
Use an application that gives feedback on tablet-tools (e.g. the example client in https://github.com/Ongy/wlroots/tree/tablet-v2-example) [which I should merge at some point] and start two instances.
Hold pen over 1 window and connect tip. Move over other and notice that focus stays with the first.
Release pen over 2nd window and focus should be updated automatically (though no rotate/tilt/pressure/motion etc.)
=> Tablet grabs

include/wlr/types/meson.build, include/wlr/types/wlr_xdg_output_v1.h, rootston/desktop.c, types/meson.build, types/wlr_xdg_output_v1.c
cc @Ongy: this is a breaking change (this should matter to bindings implementors, but not really to compositor implementors).
This doesn't require a sway update.
=> xdg-output: add _v1 suffix

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/util.c, include/backend/drm/drm.h
~~Depends on #1235, new material here is the second commit (https://github.com/swaywm/wlroots/commit/f68740bb9d6dd9364fd1fe958b3b4acfadca7f8b)~~
This commit allows outputs that need a CRTC to steal it from
user-disabled outputs. Note that in the case there are enough
CRTCs, disabled outputs don't loose it (so there's no modeset
and plane initialization needed after DPMS). CRTC allocation
still prefers to keep the old configuration, even if that means
allocating an extra CRTC to a disabled output.
CRTC reallocation now happen when enabling/disabling an output as
well as when trying to modeset. When enabling an output without a
CRTC, we realloc to try to steal a CRTC from a disabled output
(that doesn't really need the CRTC). When disabling an output, we
try to give our CRTC to an output …
=> Steal CRTCs from disabled outputs

backend/session/session.c, docs/env_vars.md
Fixes #1064 
Valid values are "logind"/"systemd" and "direct". If WLR_SESSION is set,
only its value is potentially tried; it will not try any other option.
=> Add support for WLR_SESSION env variable

include/wlr/types/wlr_keyboard.h, types/seat/wlr_seat_keyboard.c, types/wlr_keyboard.c
Fixes #1192 
To prevent wl_keyboard keymap being written to by clients, use a unique
file descriptor for each wl_keyboard resource.
Reference: [weston, commit 76829fc4eaea329d2a525c3978271e13bd76c078](https://gitlab.freedesktop.org/wayland/weston/commit/76829fc4eaea329d2a525c3978271e13bd76c078)
=> Send unique keymap file descriptors

examples/dmabuf-capture.c, include/wlr/types/wlr_export_dmabuf_v1.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_screencopy_v1.h, types/wlr_export_dmabuf_v1.c, types/wlr_output.c, types/wlr_screencopy_v1.c
We need to track the number of times hardware cursors have been disabled to properly support e.g. screenshooting and screen recording at the same time.
=> Disable hardware cursors when capturing output

types/wlr_buffer.c
If this happens, something went really wrong and we should do more
than just logging an error. See [1].
[1]: https://gitlab.freedesktop.org/wayland/weston/issues/148
=> buffer: disconnect clients that commit an unknown buffer type

protocol/meson.build
External dependencies in Meson do not have `include_directories`, therefore `includes: true` means nothing for the `wayland-client` partial dependency in protocol/meson.build. Because of this, the `-I` CFLAGs for wayland-client are not used by the build command. This commit fixes this by using `compile_args`.
=> Fix partial dependency in protocol/meson.build

xwayland/xwm.c
It's not used (XCB_IMAGE_FORMAT_Z_PIXMAP comes from xproto.h) and we
don't even have a pkg-config dependency on xcb-image, making the build
to fail on that inclusion on systems without the package.
=> xwayland/xwm: Stop including xcb_image.h

README.md, meson.build
The Meson option `b_lundef` need to be set to `false` on FreeBSD, because the symbol `environ` is in crt1.o, which is not linked with shared libraries. Until now, it was done by passing the `-Db_lundef=false` flag manually, but with Meson >=0.48.0 it is possible to set this option conditionally inside meson.build.
=> Set b_lundef to false on FreeBSD in meson.build

types/wlr_xdg_decoration_v1.c
When this request was called from a client, the unimplemented callback
was NULL and thus was crashing rootston.
=> Fix a crash on zxdg_decoration_manager_v1 destroy

backend/backend.c, backend/drm/backend.c, backend/multi/backend.c, backend/session/logind.c, include/backend/multi.h, include/wlr/backend.h, include/wlr/backend/drm.h, include/wlr/backend/interface.h, include/wlr/backend/multi.h, rootston/keyboard.c
Sessions can now be retrieved from a backend in a more general manner.
Multi-backend gets back its `session` field that contains the session
if one was created, removing the interfacing from multi backend with the
drm backend directly. This adds the possibility to use sessions even
without the drm backend.
It additionally fixes the bug that 2 session objects got created when
WLR_BACKENDS were set to "libinput,drm".
To allow vt switching without drm backend (and drm fd) on logind, start
listening to PropertiesChanged signals from dbus and parse the session
"Active" property when no master fd was created (this does not change
current drm backend behaviour in any way).
---
The main reason for this pr is to allow future session-based backends other than the drm one (like a VkDisplayKHR …
=> Improve session handling

include/wlr/types/wlr_output.h, rootston/config.c
This fixes an error where in certain compiler configurations (Arch Linux?) compilation will fail because the sizes were not large enough.
=> Update sizes for new EDID database.

types/wlr_output.c
When we send an output frame event, we should not assume that the compositor is going to call `wlr_output_swap_buffers` in response to it. If the compositor does not swap the buffers, the idle event source still exists and is executed every time the Wayland event loop becomes idle, which means we send frame events repeatedly until the buffers are swapped.
This moves the removal of the idle event source out of `wlr_output_swap_buffers` and into `wlr_output_send_frame`, where it is guaranteed to be removed.
Fixes https://github.com/swaywm/sway/issues/2748
=> Prevent excessive frame events when compositor doesn't swap buffers

backend/drm/drm.c, backend/wayland/output.c, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
This desynchronizes our rendering loop with the vblank cycle.
In case a compositor doesn't swap buffers but schedules a frame,
emitting a frame event immediately enters a busy-loop.
Instead, ask the backend to send a frame when appropriate. On
Wayland we can just register a frame callback on our surface. On
DRM we can do a no-op pageflip.
Fixes #617
Fixes swaywm/sway#2748
=> output: don't trigger a frame immediately in schedule_frame

backend/drm/drm.c
Also make sure we don't have zero-length VLAs as this is undefined behaviour.
=> backend/drm: better handle GPUs without CRTCs

backend/drm/drm.c
As per [1] set drmEventContext version to 2, since wlroots does not use the
page_flip_handler2.
[1]: https://s-opensource.org/2017/04/12/libdrm-event-handling-youre-probably-wrong/
=> backend/drm: set drmEventContext version to 2

backend/drm/drm.c, types/wlr_output.c
This prevents the idle event to be activated on a destroyed
output.
This also makes the backend responsible for free-ing modes, as it
is the one allocating them and adding them to the list. Note that
the DRM backend (the only one using modes) already frees them.
Fixes https://github.com/swaywm/wlroots/issues/1296
=> output: remove idle_frame event source when destroying output

backend/drm/drm.c
If a pageflip is pending before cleanup, it's still pending after. This
is used line 1177: drm_connector_cleanup is called and
conn->pageflip_pending is checked afterwards.
Fixes #1297
@Emantor Can you try this?
=> backend/drm: don't reset conn->pageflip_pending in drm_connector_cleanup

rootston/text_input.c, types/wlr_text_input_v3.c
It was possible for listeners on text-input objects to be still attached to signals even after the objects were gone, causing crashes depending on the order objects were destroyed. Not after this patch.
=> text-input: fix releasing destroy handlers

xwayland/xwm.c
An X11 client can leave the hints->input WM hint unspecified,
by not setting the XCB_ICCCM_WM_HINT_INPUT flag in hints->flags.
In that case, we should assume a sane default.
Make the hint default to true, so that clients which do not specify
the hint, like mupdf, still get keyboard focus.
This should fix swaywm/sway#2231
How to test:
1. start rootston like:
`rootston -E xterm`
2. from xterm in rootston start mupdf:
`mupdf some-file.pdf`
3. press left and right arrows to switch pages in PDF, +/- to zoom/unzoom,
switch focus to the xterm and back to mupdf, press some more buttons, press q to quit
Before this patch, mupdf doesn't react to any key presses (if you use a non-Xwayland terminal, then the fisrt mupdf you start will react, until you switch focus, then it will stop reacting).
After …
=> xwayland/xwm: make hints->input default to true

include/wlr/render/dmabuf.h, render/egl.c, types/wlr_linux_dmabuf_v1.c
If a client uses an older version of the dmabuf protocol, use the
`formats` event instead of `modifiers` (since that didn't exist in older
versions).
With a bit of necessary guessing, support dmabuf importing even when
EGL_EXT_image_dma_buf_import_modifiers isn't present instead of
failing up front.
---
Makes weston-simple-dmabuf-v4l work (at least with XR24 formats since the gl renderer does not support yuv). See the help manual of that program for information (loading the dummy vivid kernel module). Mainly useful to test dmabuf support (e.g. in renderers, think you can guess what i needed this for).
Note that the way we support older versions of the protocol is implemented different from weston: in weston, the modifier the client passes the compositor are simply ignored (see …
=> Support older wlr_linux_dmabuf_v1 clients

rootston/text_input.c
The disable signal on text-input objects must not be ignored. It is only sent when the previous state was enabled.
This led to input method not being disabled when the application requested it.
=> text-input: Accept disable requests

render/egl.c
This PR broke a private nixpkgs definition I have for wlroots: https://github.com/swaywm/wlroots/pull/1304
It is fixed by changing `#include <drm_fourcc.h>` to `#include <libdrm/drm_fourcc.h>`, which follows what is already done in the dmabuf example.
=> Fix include path for (libdrm/)drm_fourcc.h

render/egl.c
It was only working if you ran it underneath an already-working Wayland
compositor. Running with the headless backend on the API would break.
=> Fix headless backend

examples/dmabuf-capture.c, examples/meson.build, render/egl.c, render/meson.build
This removes any assumptions about how the libdrm headers are installed, and uses the pkg-config include directories as we're "supposed to".
This only adds a partial dependency, since we don't actually need to link against libdrm.
=> Fix libdrm includes

examples/meson.build, render/meson.build
See https://github.com/swaywm/wlroots/pull/1257 for context for why this seems to be necessary.
This fixes the build issues on my system, I believe the right way.
=> render: fix meson including libdrm

backend/drm/drm.c, backend/multi/backend.c, examples/meson.build
This PR fixes two issues on FreeBSD:
1. `CLOCK_MONOTONIC` appeared in IEEE Std. 1003.1-200x, it was not part of
POSIX.1b (the 1993 version). FreeBSD treats it accordingly, thus `_POSIX_C_SOURCE` needs to be set to `200112L`.
2. `epoll` is not part of FreeBSD, it is provided as a 3rd party library, so it needs to be set as a dependency.
=> FreeBSD fixes

types/wlr_text_input_v3.c
The prevoius implementation would always raise an error in the following sequence:
1. → enter
2. → leave
3. ← enable
The text-input type is not equipped to manage the validity of clents' requests, which should be handled in the compositor, as rootston does.
There *is* one scenario where this error should stay; namely immediately after creating the text input, but handling it introduces additional state and complexity, so I decided against it.
This should also make terminals work again, fixing https://gitlab.gnome.org/GNOME/gtk/merge_requests/369 from the other side.
=> text-input: Don't reject enable requests when unfocused

include/render/gles2.h, include/wlr/render/interface.h, include/wlr/render/wlr_texture.h, render/gles2/texture.c, render/wlr_texture.c, types/wlr_buffer.c
This uses dummy format values (0xFFFFFFFF) for immutable wlr_gles2_texture objects since we don't always know their formats (and don't write the textures anyways so why bother with additional conversions in that case).
The buffer damage handling had to be changed a bit; the previous implementation seemed to rely on being able to change the textures format (which was broken for the gles2 renderer since has_alpha was not updated on format change).
Breaking change, i guess this is relevant for sway and @ongy @Timidger @ammen99 (add anyone i missed) if it gets merged.
=> Remove fmt parameter from wlr_texture_write_pixels

include/types/wlr_data_device.h, include/wlr/types/wlr_data_device.h, types/data_device/wlr_data_device.c, types/data_device/wlr_data_offer.c, types/data_device/wlr_data_source.c
Since the source doesn't always come from a client, this field
doesn't make sense. It is replaced by a new "finalized" field in
wlr_client_data_source. This is used to make sure set_actions is
not sent after start_drag has been sent.
A check in data_offer_choose_action has been removed: if an offer
has been sent then start_drag has been called, no need to check.
I also wanted to add a check for wl_data_source.offer, but it
turns out (1) this isn't in the spec (2) it breaks GTK+.
This is some preliminary work for Firefox on Wayland compatibility.
=> data-device: remove wlr_data_source.seat_client

types/wlr_cursor.c, types/wlr_output_layout.c
wlr_cursor: make sure the output doesn't have a cursor before
creating a new one
wlr_output_layout: don't emit the "add" event when the output is
already in the layout
Fixes https://github.com/swaywm/sway/issues/2486
Fixes https://github.com/emersion/grim/issues/20
=> output-layout, cursor: fix duplicate cursors

types/wlr_output.c
When spawning a new window in Rootston the cursor will disappear if it is over the surface. It is supposed to be set to a surface specific cursor. I think this is caused by the client sending an empty cursor surface when requested causing cursor->visible to be set to false. The surface is then committed but the visibility is not updated so it stays hidden until it registers movement. 
I'm unsure if I put it in the correct place though. Maybe it should be called inside output_cursor_commit since it updates the dimenstions, I don't know what consequences that will have though.
=> Fix cursor visibility on surface commit

rootston/desktop.c
Based on https://github.com/swaywm/wlroots/issues/1325
=> Fix "variable ‘cursor_default’ set but not used"

include/wlr/render/egl.h, render/egl.c
We always manage frame callbacks manually on the Wayland backend. Thus we don't want `eglSwapBuffers` to register an additional frame callback and to block.
=> render: on Wayland, make eglSwapBuffers non-blocking

backend/drm/drm.c, backend/wayland/output.c, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
There was a missing copy_drm_surface_mgpu call in drm_connector_schedule_frame
so we asked for a pageflip with an unknown BO, resulting in ENOENT.
Additionally, this commit makes schedule_frame return a bool indicating
failures. This allows schedule_frame_handle_idle_timer to only set
frame_pending to true if a frame has been successfully scheduled. Thus, if a
pageflip fails, rendering won't be blocked forever anymore.
In case a pageflip is already pending, true is returned because a frame has
already been scheduled and will be sent sometime soon.
@JonnyMako @DawidLoubser @JonathanILevi Please test!
Fixes swaywm/sway#2800
Fixes #1328
=> backend/drm: fix frame scheduling on secondary GPUs

rootston/desktop.c
Make sure the view is mapped.
@dos1: can you try this patch?
Fixes https://github.com/swaywm/wlroots/issues/1333
=> rootston: fix segfault in view_at

backend/drm/renderer.c, include/render/gles2.h, include/wlr/render/interface.h, include/wlr/render/wlr_renderer.h, render/gles2/pixel_format.c, render/gles2/renderer.c, render/wlr_renderer.c, types/wlr_screencopy_v1.c
We were assuming GL_BGRA_EXT was always supported.
We now check that it's supported for rendering. We fail if it isn't because
this format is specified as "always supported" by the Wayland protocol.
We also check if it's supported for reading pixels. A new preferred_read_format
function returns the preferred format that can be used to read pixels. This is
used by the screencopy protocol.
Fixes https://github.com/swaywm/wlroots/issues/1348
Fixes https://github.com/swaywm/wlroots/issues/1349
=> render/gles2: remove assumptions about supported formats

include/wlr/types/wlr_surface.h, rootston/output.c, types/wlr_surface.c
Fixes bugs with running `weston-simple-damage --transform=90` (for example) and `weston-fullscreen` (use 't' to get a non-zero transform, then resize/scale/move mouse around). Both clients are now working (mostly) perfectly.
*Caveat:* `weston-simple-damage --rotating-transform` leads to a very dirty buffer. Damage tracking is correct though (check in rootston). Weston also behaves the same way. ~~No idea how to fix this.~~ It's a bug with `weston-simple-damage`: it damages the previous location incorrectly when the transformation changes.
=> Fix damage tracking for surfaces with transforms

examples/dmabuf-capture.c, examples/idle.c, examples/input-method.c, examples/meson.build, examples/output-layout.c, examples/screencopy.c, examples/screenshot.c, types/data_device/wlr_data_device.c, types/data_device/wlr_data_offer.c, types/data_device/wlr_data_source.c, types/data_device/wlr_drag.c, types/wlr_input_device.c, types/wlr_primary_selection.c, xcursor/wlr_xcursor.c, xwayland/selection/dnd.c, xwayland/selection/incoming.c, xwayland/selection/outgoing.c, xwayland/selection/selection.c, xwayland/sockets.c, xwayland/xwayland.c
* Prefer `_POSIX_C_SOURCE` over `_XOPEN_SOURCE` where possible (we only need `_XOPEN_SOURCE >= 500` for `M_PI`)
* Simplify examples by using `shm_open` instead of `XDG_RUNTIME_DIR`
* Don't link client examples to wlroots if possible
=> Use _POSIX_C_SOURCE, use shm_open

types/data_device/wlr_data_offer.c
I have the following error when compiling latest sway+wlroots on Void Linux with musl 
```
[130/204] Compiling C object 'types/types@@wlr_types@sta/data_device_wlr_data_offer.c.o'.
FAILED: types/types@@wlr_types@sta/data_device_wlr_data_offer.c.o
cc -Itypes/types@@wlr_types@sta -Itypes -I../types -I. -I../ -Iinclude -I../include -Iprotocol -I/usr/include/pixman-1 -flto -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Werror -std=c11 -Wno-unused-parameter '-DWLR_SRC_DIR="/builddir/wlroots-master"' -DWLR_USE_UNSTABLE -DWL_HIDE_DEPRECATED -D_FORTIFY_SOURCE=2 -mtune=generic -O2 -fPIC  -MD -MQ 'types/types@@wlr_types@sta/data_device_wlr_data_offer.c.o' -MF 'types/types@@wlr_types@sta/data_device_wlr_data_offer.c.o.d' -o …
```
=> Fix compilation error on musl

include/wlr/config.h.in, meson.build, util/shm.c
FreeBSD does not allow to use `posix_fallocate` on shared memory objects.
I also think that this function should not be used here anyways, since shared memory objects are not regular files, and `posix_fallocate` should give an ENODEV error if the fd refers to a non-regular file. At least that is my understanding of the POSIX specification.
=> Force ftruncate for shared memory objects on FreeBSD

backend/backend.c, backend/session/direct-ipc.c, backend/session/logind.c, backend/session/session.c, backend/x11/backend.c, backend/x11/input_device.c, backend/x11/meson.build, include/backend/x11.h, include/rootston/desktop.h, include/rootston/server.h, include/rootston/view.h, include/wlr/backend/meson.build, include/wlr/meson.build, include/wlr/render/egl.h, include/wlr/render/interface.h, include/xwayland/xwm.h, meson.build, rootston/desktop.c, rootston/input.c, rootston/main.c, rootston/meson.build, rootston/output.c, rootston/seat.c, xwayland/meson.build, xwayland/xwm.c
This prevents some annoying issues when e.g. not including wlr/config.h or
making a typo in the guard name.
For instance, [it caught a typo](https://github.com/swaywm/wlroots/pull/1372/files#diff-282b30593da47b681ecb7626496f2032R14) of `WLR_HAS_XWAYLAND` (which was written as `WLR_HAS_WAYLAND`).
Fixes https://github.com/swaywm/wlroots/issues/1365
=> Use #if instead of #ifdef for wlroots config data

types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell/wlr_xdg_toplevel.c
ie. don't destroy surface->toplevel on xdg_toplevel destroy. Instead do this on
xdg_surface destroy.
This allows compositors to add toplevel listeners when the surface appears and
remove them when the surface is destroyed.
This fixes part of @Timidger's segfaults:
```
==25315== Invalid write of size 8
==25315==    at 0x490344B: wl_list_remove (wayland-util.c:56)
==25315==    by 0x122FC7: destroy (xdg_shell.c:267)
==25315==    by 0x114806: view_destroy (desktop.c:448)
==25315==    by 0x123516: handle_destroy (xdg_shell.c:396)
==25315==    by 0x48C175F: wlr_signal_emit_safe (signal.c:29)
==25315==    by 0x48A1647: destroy_xdg_surface (wlr_xdg_surface.c:459)
==25315==    by 0x48A011C: xdg_client_handle_resource_destroy (wlr_xdg_shell.c:71)
==25315==    by 0x48FF17D: destroy_resource …
```
=> xdg-shell: don't destroy xdg role state on role destroy

README.md, backend/x11/backend.c, backend/x11/input_device.c, backend/x11/meson.build, backend/x11/output.c, include/backend/x11.h, include/wlr/backend/x11.h, include/wlr/config.h.in, meson.build, meson_options.txt
This contains a lot of the X11 backend refactoring and changes I did in my #1355 that really deserved to be part of a different PR, with the history cleaned up.
This removes xcb-xkb, and adds xcb-xinput and xcb-xfixes as dependencies.
~~While working on this PR, I actually encountered another bug which affects this:~~
~~I've changed the X11 backend to use xfixes to hide the cursor, but we need to turn this off once the pointer leaves our window. However, it seems that sway/wlroots is not sending the "leave" event, so the cursor remains hidden.
While the X11 backend is open in sway, your cursor will be invisible over other Xwayland windows.
This does not affect weston or native X11.
I need to debug this more, but is technically not a bug in this PR.~~
Never mind all that. It was because I …
=> X11 backend improvements

include/wlr/types/wlr_output.h, render/egl.c, rootston/output.c, types/wlr_output.c
This PR removes `wlr_output_set_fullscreen_surface`, adds a new `wlr_output_render_software_cursors` helper, and removes the 180 damage flip in `wlr_output_swap_buffers` (which is GL-specific).
This also fixes frame events for hardware cursors, which were sent too soon.
While this improves the situation, this doesn't completely fix <span></span>#1363, because redesigning how cursor surfaces are handled and how output damage is managed requires more thought.
See #1363
=> Render software cursors in compositor

backend/drm/drm.c
Fixes swaywm/sway#3167
A better solution could be made if there's a need to.
=> Skip interlaced modes during drm mode detection

include/wlr/types/wlr_primary_selection.h, types/wlr_primary_selection.c
When a client was creating multiple data devices for the same seat, we were
only creating one resource. This is a protocol error.
Instead, create one offer per data device.
This commit also makes offers inert when their source is destroyed.
Fixes part of https://github.com/swaywm/wlroots/issues/1041
Supersedes https://github.com/swaywm/wlroots/pull/1113
=> gtk-primary-selection: support multiple devices

include/wlr/render/wlr_renderer.h, include/wlr/types/wlr_output.h, render/wlr_renderer.c, types/wlr_output.c, types/wlr_screencopy_v1.c
The read format is dependent on the output, so we first need to make it
current. This fixes a race condition in wlr-screencopy-v1 where a dmabuf
client would cause EGL_NO_SURFACE to be bound at the time when
screencopy needs to query for the preferred format, causing GL errors.
Fixes #1389
=> output: add wlr_output_preferred_read_format()

README.md
According to `cloc` it's 50k lines I was going to write anyways.
```
$ cloc .
308 text files.
308 unique files.
11 files ignored.
1 error:
Line count, exceeded timeout:  ./examples/cat.c
github.com/AlDanial/cloc v 1.80  T=2.38 s (125.4 files/s, 28323.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                              149           7625           1171          44758
C/C++ Header                   111           1733           2000           6139
XML                             13            373              1           1971
NAnt script                     19             62 …
```
=> Fixed loc count in readme

include/types/wlr_tablet_v2.h, types/tablet_v2/wlr_tablet_v2.c
This fixes the second part of @Timidger's segfaults.
@Timidger: can you test these two PRs?
```
==25315== Invalid write of size 8
==25315==    at 0x4903447: wl_list_remove (wayland-util.c:55)
==25315==    by 0x489903A: handle_wlr_seat_destroy (wlr_tablet_v2.c:34)
==25315==    by 0x48C175F: wlr_signal_emit_safe (signal.c:29)
==25315==    by 0x489401E: wlr_seat_destroy (wlr_seat.c:161)
==25315==    by 0x489424A: handle_display_destroy (wlr_seat.c:204)
==25315==    by 0x48FF0FC: wl_priv_signal_final_emit (wayland-server.c:2064)
==25315==    by 0x48FF826: wl_display_destroy (wayland-server.c:1092)
==25315==    by 0x119E7E: main (main.c:79)
==25315==  Address 0x861cae0 is 32 bytes inside a block of size 88 free'd
==25315==    at 0x48389AB: free (vg_replace_malloc.c:530)
==25315==    by …
```
=> tablet-v2: fix segfault on display destroy

.builds/archlinux.yml
- It's slooooow
- We don't use the results
- It has false positives
=> Disable Clang static analysis

backend/wayland/wl_seat.c
=> backend/wayland: fix zero-length VLA

include/wlr/types/wlr_output.h, rootston/output.c, types/wlr_output.c
This is one more step towards [1]. This gives more freedom to the compositor
wrt. how it handles damage.
[1]: https://github.com/swaywm/wlroots/issues/1363
=> output: switch swap_buffers damage to output-buffer-local coords

include/wlr/types/wlr_gtk_primary_selection.h, types/wlr_gtk_primary_selection.c
I've discovered that some clients _rely_ on the compositor for rejecting `set_selection` requests if the serial is invalid. For instance Gedit under Wayland issues multiple `set_selection` requests with the same serial, and not doing this basic serial validation will break clipboard.
While I haven't found any clients broken for primary selection, it's probably better to add back this basic serial validation, at least until we have a new improved validation mechanism.
=> gtk-primary-selection: basic serial validation

backend/drm/drm.c, backend/drm/properties.c, include/backend/drm/properties.h
This commit changes `scan_drm_connectors` to add new outputs to the end of the
list. That way, it's easier to understand what's going on with indices.
When we need to destroy outputs, we now walk the list in reverse order. This
ensures indices remain correct while iterating and removing items from the
list.
We now also make outputs without a CRTC disappear (those are in
WLR_DRM_CONN_NEEDS_MODESET state).
=> backend/drm: fix disappeared output indices

xwayland/xwayland.c
This has been causing troubles for some of our users and only been there
for legacy reasons, we trust Xwayland just as much as your next program
and weston doesn't take any such care when starting it.
=> xwayland: remove clearenv() call

backend/headless/input_device.c, backend/libinput/events.c, backend/libinput/switch.c, backend/meson.build, include/backend/libinput.h, include/rootston/bindings.h, include/rootston/config.h, include/rootston/seat.h, include/rootston/switch.h, include/wlr/interfaces/meson.build, include/wlr/interfaces/wlr_switch.h, include/wlr/types/meson.build, include/wlr/types/wlr_input_device.h, include/wlr/types/wlr_switch.h, rootston/bindings.c, rootston/config.c, rootston/input.c, rootston/keyboard.c, rootston/meson.build, rootston/seat.c, rootston/switch.c, types/meson.build, types/wlr_input_device.c, types/wlr_switch.c
These are used primarily by laptops to signal
the state of the lid (open/closed) and tablet
mode if supported, based on ACPI events.
AFAICT this should be feature-complete for wlroots itself, I've added what looks correct for rootston but am unsure if this is all I need. 
Seems to be working well within sway, but I assume sway will also need some formal support for these new events.
```
2018-11-15 00:13:53 - [backend/libinput/events.c:94] Added Lid Switch [0:5]
2018-11-15 00:13:53 - [backend/libinput/events.c:173] Switch capability match for device Lid Switch
2018-11-15 00:13:53 - [backend/libinput/switch.c:20] Created switch for device Lid Switch
2018-11-15 00:13:53 - [backend/libinput/events.c:173] Switch capability match for device ThinkPad Extra Buttons
2018-11-15 00:13:53 - …
```
=> Add support for libinput_switch input devices

rootston/desktop.c
Otherwise the initial list of outputs isn't sent to foreign-toplevel clients.
=> rootston: create foreign toplevel handle before sending outputs

.builds/freebsd.yml
Recent libinput-related changes in the ports tree made it necessary to
install devel/evdev-proto before x11/libinput (see the comments in #1432).
=> Fix FreeBSD build manifest

include/wlr/render/egl.h, include/wlr/render/interface.h
When building wlroots for an embedded Linux (hobby) project with Wayland only, I run into errors where `MESA_EGL_NO_X11_HEADERS` is redefined several times.
This PR simply adds a check if it is already defined, before defining it.
=> Protect against redefining MESA_EGL_NO_X11_HEADERS

backend/drm/util.c
Values from libdrm are likely more reliable than raw values from the EDID. We
were already using values from libdrm, but they were overwritten by parse_edid.
See drm.c:
wlr_conn->output.phys_width = drm_conn->mmWidth;
wlr_conn->output.phys_height = drm_conn->mmHeight;
=> backend/drm: get physical size from libdrm

examples/layer-shell.c
Fixes a crash that occasionally occurs if you start this example and right click around a lot, I assume due to the popup being destroyed between scheduling a draw frame and the actual drawing.
=> examples/layer-shell.c: check popup exists before drawing

include/wlr/types/wlr_relative_pointer_v1.h, rootston/cursor.c, types/wlr_relative_pointer_v1.c
This makes sure we always send events to the right client.
=> relative-pointer-v1: move pointer iteration in wlroots

tinywl/tinywl.c, types/tablet_v2/wlr_tablet_v2.c, types/tablet_v2/wlr_tablet_v2_tool.c
Found with `codespell --quiet-level=3`
=> Fix a few typos

examples/multi-pointer.c, examples/pointer.c, tinywl/tinywl.c
Since #1366 was merged, a call to ``wlr_output_render_software_cursors`` is needed to render software cursors. This PR adds a call to that function for:
- examples/pointer
- examples/multi-pointer
- tinywl
I think that's all of them, but let me know if I missed one.
=> Fix software cursor rendering for tinywl and some examples

backend/backend.c, backend/meson.build, backend/noop/backend.c, backend/noop/output.c, docs/env_vars.md, include/backend/noop.h, include/wlr/backend/noop.h
The noop backend is similar to headless, but it doesn't contain a renderer. It can be used as a place to stash views for when there's no physical outputs connected.
See https://github.com/swaywm/sway/pull/3441 for implementation in the compositor.
=> Introduce noop backend

rootston/main.c
A better solution would be to only restart Xwayland if it's exited with a non-zero exit code or if it's been killed. I don't think we have a way to do this though…
=> rootston: document why Xwayland is disconnected before clients

types/wlr_relative_pointer_v1.c
Occurs on subsequent calls to
relative_pointer_manager_v1_handle_get_relative_pointer()
Steps to reproduce:
- run rootston
- run examples/relative-pointer
- switch to relative pointer more than once
Note: if done fast enough it may take more than two switches to crash.
=> Fix segfault in get_relative_pointer

backend/drm/drm.c, types/wlr_output.c
When there aren't enough CRTCs for all outputs, we try to move a CRTC from a
disabled output to an enabled one. When this happens, the old output's state
wasn't changed, so the compositor thought it was still enabled and rendering.
This commit marks the old output as WLR_DRM_CONN_NEEDS_MODESET and sets its
current mode to NULL.
=> backend/drm: fix state for outputs loosing their CRTC

backend/x11/output.c, include/wlr/backend/x11.h
This brings the X11 backend in line with the Wayland backend. I can imagine it's useful here too :) I tested this in Cage.
=> Add wlr_x11_output_set_title

types/wlr_relative_pointer_v1.c
Needed to get pointer locking for Xonotic (and probably other SDL2 appplications) to work under sway.
=> Relative pointer/pointer constraints fixes

include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_gtk_primary_selection.h, include/wlr/types/wlr_primary_selection.h, include/wlr/types/wlr_seat.h, types/seat/wlr_seat.c, types/wlr_gtk_primary_selection.c, types/wlr_primary_selection.c, xwayland/selection/incoming.c, xwayland/selection/selection.c
The serial needs to be bumped when X11 clients set the selection, otherwise
some Wayland clients (e.g. GTK) will overwrite it when they gain focus.
For instance, copy from a GTK app will send `set_selection(serial=42, source)`, then immediately `set_selection(serial=42, NULL)`. If another app is focused and then the GTK app is focused again, GTK will send `set_selection(serial=42, NULL)` again. If X11 has updated the selection in the meantime, this will clear it (and shouldn't).
This isn't a GTK bug, that's how the Wayland protocol works. However this is silly behaviour from GTK.
=> primary-selection: add a serial argument

backend/wayland/output.c
Fixes #1371 
Before resizing the egl window, the buffers must be swapped
=> backend/wayland: fix resizing

types/wlr_xdg_output_v1.c
The xdg-output protocol states that name and description should only be
sent once per output since they do not change.
This fixes a SIGABRT in swaybg when resizing an output on the x11 and
wayland backends.
=> wlr_xdg_output_v1: only send name/description once

include/rootston/seat.h, include/wlr/types/wlr_data_control_v1.h, include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_gtk_primary_selection.h, include/wlr/types/wlr_primary_selection.h, include/wlr/types/wlr_seat.h, include/xwayland/xwm.h, rootston/seat.c, types/data_device/wlr_data_device.c, types/seat/wlr_seat.c, types/wlr_data_control_v1.c, types/wlr_gtk_primary_selection.c, types/wlr_primary_selection.c, xwayland/selection/incoming.c, xwayland/selection/selection.c
~~Depends on https://github.com/swaywm/wlroots/pull/1397~~
~~Depends on https://github.com/swaywm/wlroots/pull/1485~~
This makes compositors able to block and/or customize set_selection requests
coming from clients. For instance, it's possible for a compositor to disable
rich selection content (by removing all MIME types except text/plain). This
commit implements the design proposed in [1].
Two new events are added to wlr_seat: request_set_selection and
request_set_primary_selection. Compositors need to listen to these events and
either destroy the source or effectively set the selection.
Fixes #1138
[1]: https://github.com/swaywm/wlroots/issues/1367#issuecomment-442403454
=> data-device, primary-selection: add request_set_selection

backend/wayland/output.c, backend/x11/output.c
Set the default "wlroots - " title when the title argument to the set_title functions is NULL. Otherwise, for at least the Wayland backend, we'd crash because xdg_toplevel_set_title doesn't handle a NULL pointer.
=> backend/x11 & backend/wayland: make set_title NULL-safe

include/types/wlr_data_device.h, include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_seat.h, types/data_device/wlr_data_device.c, types/data_device/wlr_data_offer.c, types/data_device/wlr_data_source.c, types/data_device/wlr_drag.c, types/seat/wlr_seat.c, types/seat/wlr_seat_keyboard.c, types/wlr_data_control_v1.c, xwayland/selection/incoming.c
Various refactoring commits to improve our data-device implementation.
* `wlr_seat_client_send_selection` has been removed, this is an internal function
* `wlr_data_source_finish` has been removed, this is now handled by `wlr_data_source_destroy`
* `wlr_data_source_cancel` has been renamed to `wlr_data_source_destroy`
=> Refactor data-device

.editorconfig
=> Set .editorconfig ident_size

backend/libinput/events.c, backend/libinput/pointer.c, include/backend/libinput.h, include/rootston/cursor.h, include/rootston/desktop.h, include/wlr/types/meson.build, include/wlr/types/wlr_cursor.h, include/wlr/types/wlr_pointer.h, include/wlr/types/wlr_pointer_gestures_v1.h, protocol/meson.build, rootston/desktop.c, rootston/seat.c, types/meson.build, types/wlr_cursor.c, types/wlr_pointer.c, types/wlr_pointer_gestures_v1.c
This protocol relays touchpad gesture events produced by libinput to supporting clients (e.g. Evince, Eye of GNOME).
---
Tested with gtk3-demo and the apps mentioned above. I should probably reduce the duplication in the code, but by how much? `swipe(…, BEGIN|UPDATE|END)` + `pinch(…, BEGIN|UPDATE|END)` or `gesture(…, SWIPE_BEGIN|SWIPE_UPDATE|SWIPE_END|PINCH_BEGIN|PINCH_UPDATE|PINCH_END)`?
=> Implement the pointer-gestures-unstable-v1 protocol

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/renderer.c, backend/drm/util.c, include/backend/drm/drm.h, include/backend/drm/renderer.h, include/backend/drm/util.h
We create the EGL config with GBM_FORMAT_ARGB8888, but then initialize GBM BOs
with GBM_FORMAT_XRGB8888. This mismatch confuses Mesa.
Instead, we can always use GBM_FORMAT_ARGB8888, and use DRM_FORMAT_XRGB8888
when calling drmModeAddFB2.
Fixes https://github.com/swaywm/wlroots/issues/1438
=> backend/drm: fix GBM format mismatch

examples/dmabuf-capture.c, rootston/config.c
Clang still generates one false-positive:
```
../../../rootston/desktop.c:925:3: warning: 3rd function call argument is an uninitialized value
roots_cursor_constrain(seat->cursor, wlr_constraint, sx, sy);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
=> Fix two issues found with Clang's static analyzer

meson.build
This was necessary because we were using `environ` in the Xwayland code, but it has been removed now. It's better not to use these flags so that the linker errors out if we're using an undefined function (e.g. we include the header but forget to link against it).
=> meson: remove b_lundef=false on FreeBSD

types/wlr_wl_shell.c, types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell_v6/wlr_xdg_popup_v6.c
Test plan: open gnome-calculator, switch to "Programming mode", click on the "Binary/Octal/Decimal/Hexadecimal" combo button. Options should be highlighted as the pointer is moved.
=> Add missing frame events to shell pointer grabs

types/data_device/wlr_data_source.c, types/wlr_data_control_v1.c, types/wlr_gtk_primary_selection.c
Some toolkits like GTK offer twice the same MIME type.
=> De-duplicate data source MIME types

.gitignore
This brings it in line with Sway's gitignore.
The original justification was that it allows for simultaneous gcc and clang builds.
=> Add build-*/ to gitignore.

backend/drm/backend.c, backend/drm/drm.c, include/backend/drm/drm.h
While trying to implement a fix for #1323, I found that when exporting the rendered surface into a DMA-BUF and reimporting it with `GBM_BO_USE_CURSOR`, the resulting object does not appear to be valid. After some digging (turning on drm-kms debugging and switching to legacy mode), I managed to extract the following error:
```
[drm:__setplane_check.isra.1 [drm]] Invalid pixel format AR24 little-endian (0x34325241), modifier 0x100000000000001
```
The format itself refers to ARGB8888 which is the same format as `renderer->gbm_format` used in master to create the cursor bo. However, using `gbm_bo_create` with `GBM_BO_USE_CURSOR` results in a modifier of 0. A modifier of zero represents a linear buffer while the modifier of the surface that is rendered to is  `I915_FORMAT_MOD_X_TILED` (see …
=> Allow cursor render surface to be used as fb

include/types/wlr_xdg_shell.h, types/xdg_shell/wlr_xdg_popup.c, types/xdg_shell/wlr_xdg_surface.c
It doesn't make sense to keep popups opened when unmapped. We also need to do
so in wlr_xdg_popup_destroy so that popups are destroyed in the correct order.
=> xdg-shell: destroy child popups on unmap

types/data_device/wlr_drag.c, xwayland/selection/dnd.c
This supersedes f24e17259e49aef55b7ada54793a4cdb49ae94a1 and
04c9ca4198a729a95a6368bbbf0438d1ba3465fa. These commits were manually removing
wlr_data_source destroy handlers when starting a new drag. This is error-prone.
Instead, this commit destroys the previous source whenever we start a new drag.
=> data-device: destroy previous source when starting drag

include/wlr/types/wlr_gtk_primary_selection.h, include/wlr/types/wlr_screenshooter.h, include/wlr/types/wlr_server_decoration.h, include/wlr/types/wlr_wl_shell.h, include/wlr/types/wlr_xdg_shell_v6.h
All of those have better replacements.
Not sure "deprecated" is the correct wording.
=> Mark old protocols as obsolete

include/wlr/types/wlr_data_control_v1.h, protocol/wlr-data-control-unstable-v1.xml, types/wlr_data_control_v1.c
See https://github.com/swaywm/wlr-protocols/pull/34
There's quite a lot of changes in this PR, for two reasons:
1. There was an issue with the current implementation where data sources didn't track their usage correctly. Setting a data source as selection for two seats and subsequently changing selection of one of the seats freed the data source, even though it was still used for the second seat. Alternatively, setting a data source as selection for a single seat twice in a row would trigger this bug too (it would free the data source and then set the freed data source to the seat). The first commit adds appropriate tracking mechanisms to address this.
2. While data-control works in terms of `wlr_data_source`, the primary selection works in terms of `wlr_primary_selection_source` with no …
=> data-control: Primary selection support

xwayland/xwm.c
Fixes swaywm/sway#2899
Supersedes #1534 
Since xwm only manipulates the stack when focusing a window, newly
mapped windows should be stacked below the focused window. This prevents
the newly mapped window from stealing focus due to being on the top of
the stack.
Thanks psychon for the insight! See https://github.com/swaywm/wlroots/pull/1534#issuecomment-463191842 for the full explanation
=> xwm: stack below on map

include/wlr/types/wlr_output.h, types/wlr_output.c
drmModeConnector.subpixel doesn't seem to detect subpixel order on many displays (especially laptops). Allow subpixel order to be manually set.
My plan is to make a corresponding PR for sway that adds a subpixel output option. Then https://github.com/swaywm/sway/issues/3163 will be fixed.
I'm very unfamiliar with the wlroots codebase so it's quite likely I made a mistake in this PR.
=> Add a wlr_output_set_subpixel()

backend/drm/drm.c
Fixes swaywm/sway#3659
Supersedes swaywm/sway#3161
There is no point in modesetting an output to a mode that it is already
set to. Modesetting will cause the output to briefly flicker which is
undesirable for a noop. This returns early in `drm_connector_set_mode`
when attempting to modeset to the current mode.
=> drm: do not modeset to current mode

backend/drm/drm.c, backend/drm/renderer.c
I have not been able to test this as I do not have a device with multiple supported GPU's, but this should allow #1526 to work in a multi GPU setup.
=> Copy cursor surface to secondery gpu if necessary

types/wlr_surface.c
Letting the scale be set to 0 causes division by zero errors.
=> Post protocol error on invalid wl_surface scale

types/wlr_output.c
Supersedes #1545 which was reverted in #1550 due to
swaywm/sway#3685, which is a sway issue and has
swaywm/sway#3704 open to fix it. 
Fixes swaywm/sway#3659
There is no point in modesetting an output to a mode that it is already
set to. Modesetting will cause the output to briefly flicker which is
undesirable for a noop. This prevents modesetting any wlr_output,
regardless of the backend, to it's currently set mode.
=> wlr_output: do not modeset to current mode

backend/drm/drm.c
This segfault happens on multi-GPU systems.
Fixes https://github.com/swaywm/sway/issues/3717
=> backend/drm: fix NULL dereference when unsetting cursor

types/data_device/wlr_drag.c, xwayland/xwm.c
This commit makes sure surface->mapped is true when the unmapped event is
emitted. This is necessary because listeners can only damage surfaces that are
mapped. This is similar to the fact that the destroy event is emitted before
any destruction is actually made.
Fixes https://github.com/swaywm/sway/issues/3568
=> xwayland, data-device: fix surface state on unmap

types/data_device/wlr_data_device.c
Fixes https://github.com/swaywm/wlroots/issues/1383
=> data-device: make old offers inert before sending selection

types/tablet_v2/wlr_tablet_v2_tool.c
In case a tool was removed, but not yet destroyed by the client, the
tool_client's tool can be NULL. We have to check that as well in the
set_cursor handler to prevent using inert resources
Should fix https://github.com/swaywm/wlroots/issues/1536#issuecomment-463971534
This probably only ever happens with tablets that don't track unique tools (or maybe on unplug?), so I can't test this well.
@wsinnema please test this for me, I can't reproduce it with my hardware.
=> Prevent NULL dereference in tablet_tool handler

backend/drm/backend.c, backend/drm/drm.c, include/backend/drm/drm.h
Fixes #1560 
On DRM resume, such as switching back to a TTY, the output needs to be
modeset to the current mode. However, wlr_output_set_mode will return
early when attempting to set the mode to the current mode. This just
steps around wlr_output_set_mode and calls drm_connector_set_mode
directly.
=> backend/drm: fix modeset on drm fd resume

backend/drm/drm.c
If *changed_outputs is not supplied by the calling function, track the local
allocation with a bool variable and free the allocation at the end of the
function.
=> backend/drm: fix memory leak in realloc crtcs

rootston/desktop.c
It doesn't make much sense and actually breaks stuff when using layer-shell
(fullscreen window gets resized, but it's still fullscreen, leading to black
bars where the shell layers are behind).
=> rootston: don't try to maximize fullscreen surfaces

rootston/desktop.c
Input order didn't match rendering order, causing pointer events to go into surfaces
that were completely obscured by others (like a LAYER_TOP panel behind a fullscreen
window).
=> rootston: surface_at: check for fullscreen surfaces in between TOP and OVERLAY layers

include/rootston/seat.h, include/types/wlr_data_device.h, include/wlr/types/wlr_data_device.h, include/wlr/types/wlr_seat.h, rootston/seat.c, types/data_device/wlr_data_device.c, types/data_device/wlr_data_offer.c, types/data_device/wlr_drag.c, types/seat/wlr_seat.c, types/seat/wlr_seat_pointer.c, types/seat/wlr_seat_touch.c
Test plan:
Maybe consider https://github.com/swaywm/wlroots/issues/1516?
=> Refactor drag-and-drop

backend/drm/drm.c
Fixes https://github.com/swaywm/sway/issues/3017
This will prevent the cursor from persisting on the Linux framebuffer
terminal on exit.
=> backend/drm: Unset cursor on cleanup

.builds/freebsd.yml
Other builders don't test optional dependencies. Let's see if this works after d1409e338175.
=> Install xcb-errors on FreeBSD builder

types/data_device/wlr_data_offer.c
This could cause a segfault in data_offer_destroy if the offer has version < 3.
Fixes https://github.com/swaywm/wlroots/issues/1570
=> data-device: check if there's a source before sending dnd_finish

tinywl/tinywl.c
clang consider error no enum handled,
in BSD and Linux
=> clang compile fix #1572

types/seat/wlr_seat_pointer.c
This is still a compositor bug, and bad events will be sent to clients. We'll
need to track each button separately to handle this in wlroots.
Fixes https://github.com/swaywm/sway/issues/3538
Fixes https://github.com/swaywm/wlroots/issues/1576
=> seat: guard against button count corruption

types/seat/wlr_seat_pointer.c
The grab serial can be used to start a pointer grab. A button pressed event
should be used for this purpose.
Thus, we should only save the grab serial if it's the first button pressed
event we send. This commit makes it so the serial is not saved if a button is
released while another button is still pressed.
=> seat: only store serial if pressing a button

types/seat/wlr_seat_pointer.c
Fixes regression introduced by merging #1589 and #1590 together.
=> seat: fix remaining wlr_button_state enum rename

backend/meson.build, backend/session/noop.c, backend/session/session.c
This is the first step towards being able to run via DRM leasing and on render
nodes.
Test with:
export WLR_BACKENDS=drm
export WLR_SESSION=noop
export WLR_DRM_DEVICES=/dev/dri/renderD128
Fixes https://github.com/swaywm/wlroots/issues/1437
=> backend/session: add noop session

include/rootston/output.h, include/rootston/view.h, rootston/desktop.c, rootston/layer_shell.c, rootston/meson.build, rootston/output.c, rootston/render.c, rootston/view.c, rootston/wl_shell.c, rootston/xdg_shell.c, rootston/xdg_shell_v6.c
Updates https://github.com/swaywm/wlroots/issues/839
=> rootston: refactor rendering

xwayland/xwm.c
This is what ICCCM states that a WM should do.
=> xwm: use min size as base size hint if it is missing and vice versa

xwayland/xwm.c
What I proposed in #1600 was pretty wrong, I'm sorry for that. I didn't notice the problem because of the double bug. This PR should hopefully make things right.
@emersion Please check again :)
=> xwm: fix typos in WM_NORMAL_HINTS handling

include/wlr/xwayland.h, rootston/desktop.c, xwayland/xwayland.c
Let the compositor set it. This allows for multiple Xwayland instances to run
at the same time.
Fixes https://github.com/swaywm/wlroots/issues/1442
* * *
Breaking change: compositors now need to set `DISPLAY` after initializing Xwayland. The value `DISPLAY` needs to be set to is stored in `wlr_xwayland.display_name`.
=> xwayland: don't set DISPLAY

types/seat/wlr_seat_pointer.c, types/seat/wlr_seat_touch.c
Makes it easier to debug when something goes wrong, e.g. button_count stuck
to 2 because the compositor ate a button release event.
=> seat: add debug logs when validating grab serials

backend/session/direct.c
=> backend/session: open TTY with O_CLOEXEC for direct session

backend/drm/drm.c
Some hardware exists which doesn't support XRGB/ARGB overlays, and we aren't even using overlay planes, so don't fail on trying to find a format.
This code will be overhauled in the renderer v6 and related work, but we'll get a quick fix out now for people that are affected.
=> backend/drm: Don't fail on failing to find overlay format

xwayland/xwayland.c
This avoids leaking the FD to Xwayland and its children.
=> xwayland: set CLOEXEC on /dev/null FD

backend/session/direct.c, docs/env_vars.md
Comes in handy when starting the application from an SSH session etc.
=> Allow setting a custom tty via WLR_TTY env variable

types/wlr_output_layout.c
Fixes swaywm/sway#3734
If there were no outputs in the output layout,
wlr_output_layout_get_box would return the box:
```
{
.x = INT_MIN,
.y = INT_MIN,
.width = INT_MIN - INT_MAX,
.height = INT_MIN - INT_MAX
}
```
which results in an integer underflow for both the width and height.
This changes the logic to have the box be all zeroes, since an empty
output layout does not have a width or height and the location of
something without a size is irrelevant so this just uses the origin.
=> wlr_output_layout_get_box: handle empty layout

meson.build
This is causing issues with wayland-scanner generated files. The client and
server headers are declaring the same structs. We include both in the Wayland
backend.
See https://gitlab.freedesktop.org/wayland/wayland/issues/82
=> meson: remove -Wredundant-decls

backend/wayland/output.c, include/backend/wayland.h
This improves the way the output numbers are handled for the wayland
backend. Instead of using the number of active outputs plus one, the
last used number is stored and new outputs will increment it. This
fixes the situation where you start with one output, create a second,
close the first, and create a third. Without this, both outputs will be
`WL-2`, which causes an issue since the identifier will also be
identical. With this, the last output is `WL-3` and the outputs can be
distinguished.
I'll submit a PR to do the same for the x11 backend after this gets merged
=> backend/wayland: improve output number handling

backend/x11/output.c, include/backend/x11.h
_Same as #1615, but for the x11 backend_
This improves the way the output numbers are handled for the x11
backend. Instead of using the number of active outputs plus one, the
last used number is stored and new outputs will increment it. This
fixes the situation where you start with one output, create a second,
close the first, and create a third. Without this, both outputs will be
X11-2, which causes an issue since the identifier will also be
identical. With this, the last output is X11-3 and the outputs can be
distinguished.
=> backend/x11: improve output number handling

backend/headless/output.c, include/backend/headless.h
_Same as #1615, but for the headless backend_
This improves the way the output numbers are handled for the headless
backend. Instead of using the number of active outputs plus one, the
last used number is stored and new outputs will increment it. This
fixes the situation where you start with one output, create a second,
close the first, and create a third. Without this, both outputs will be
HEADLESS-2, which causes an issue since the identifier will also be
identical. With this, the last output is HEADLESS-3 and the outputs can
be distinguished.
=> backend/headless: improve output number handling

backend/noop/output.c, include/backend/noop.h
_Same as #1615, but for the noop backend_
This improves the way the output numbers are handled for the noop
backend. Instead of using the number of active outputs plus one, the
last used number is stored and new outputs will increment it. This
fixes the situation where you start with one output, create a second,
close the first, and create a third. Without this, both outputs will be
NOOP-2, which causes an issue since the identifier will also be
identical. With this, the last output is NOOP-3 and the outputs can be
distinguished.
=> backend/noop: improve output number handling

backend/drm/drm.c, include/wlr/types/wlr_output.h
I was wondering why wlr-randr wouldn't show the preferred mode until I noticed we're not currently setting it. This patch adds support for it to the drm backend. 
#1608 then only needs [this](https://github.com/agx/wlroots/commit/43d31b4847c8b066658d081f96d0ac278c953a7e) trivial patch to make it work.
=> wlr_output: Add preferred property

include/wlr/types/wlr_xdg_shell.h, include/wlr/types/wlr_xdg_shell_v6.h, types/xdg_shell/wlr_xdg_surface.c, types/xdg_shell/wlr_xdg_toplevel.c, types/xdg_shell_v6/wlr_xdg_toplevel_v6.c
Related to swaywm/sway#1813
Required for swaywm/sway#3966
Since the fullscreen request may be made before the toplevel's surface
is mapped, the requested fullscreen output needs to be stored so it
can be retrieved on map (along with the existing fullscreen property).
=> wlr_xdg_toplevel{,_v6}: store pending fullscreen output

types/meson.build, types/tablet_v2/wlr_tablet_v2.c
Build otherwise fails on openSUSE Tumbleweed with the following output:
```
[1/106] Compiling C object 'types/8d84602@@wlr_types@sta/tablet_v2_wlr_tablet_v2.c.o'.
FAILED: types/8d84602@@wlr_types@sta/tablet_v2_wlr_tablet_v2.c.o 
cc -Itypes/8d84602@@wlr_types@sta -Itypes -I../types -I. -I../ -Iinclude -I../include -Iprotocol -I/usr/include/libdrm -I/usr/include/pixman-1 -I/usr/include/wayland -I/usr/include/libxkbcommon -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Werror -std=c11 -g '-DWLR_SRC_DIR="/home/stuart/Applications/wlroots"' -DWLR_USE_UNSTABLE -Wundef -Wlogical-op -Wmissing-include-dirs -Wold-style-definition -Wpointer-arith -Winit-self -Wstrict-prototypes -Wimplicit-fallthrough=2 -Wendif-labels -Wstrict-aliasing=2 -Woverflow …
```
=> types/meson.build: Add compile args for libinput to lib_wlr_types

types/tablet_v2/wlr_tablet_v2_tool.c
When the proximity_in event is sent for tablet_v2 and there's already a
surface that currently has tablet (tool) focus, it should be told that
this is no longer the case, so we need to send the proximity_out event.
=> send proximity_out in proximity in for tablet_v2

include/wlr/render/drm_format_set.h, include/wlr/render/egl.h, include/wlr/render/interface.h, include/wlr/render/meson.build, include/wlr/render/wlr_renderer.h, render/drm_format_set.c, render/egl.c, render/gles2/renderer.c, render/meson.build, render/wlr_renderer.c, types/wlr_linux_dmabuf_v1.c
This type adds a container for formats + modifiers.
This is cherry-picked from #1355. `wlr_format_set` is only used in one place for now, but it'll be useful in other places too in #1641.
=> Introduce wlr_format_set

.builds/alpine.yml, .builds/archlinux.yml, backend/backend.c, backend/meson.build, backend/rdp/backend.c, backend/rdp/keyboard.c, backend/rdp/listener.c, backend/rdp/output.c, backend/rdp/peer.c, backend/rdp/pointer.c, docs/env_vars.md, include/backend/rdp.h, include/wlr/backend/rdp.h, include/wlr/config.h.in, meson.build, meson_options.txt
=> RDP (remote desktop) backend

backend/noop/output.c
I see no reason not to implement this, plus it makes noop outputs a bit more usable (I find it useful to add them to the output layout, so I need to set mode)
=> noop: implement setting a custom mode

backend/headless/output.c, backend/noop/output.c, backend/wayland/output.c, backend/x11/output.c
`size_t` requires `%z`, not `%l` modifier. See error logs: [armv7](https://github.com/swaywm/wlroots/files/3055849/wlroots-0.5.0.19.log), [i386](https://github.com/swaywm/wlroots/files/3055850/wlroots-0.5.0.19.log).
Wayland backend also used `%lu` instead of `%ld` but there should be no difference given `size_t` is unsigned (unlike `ssize_t`).
=> Unbreak -Werror on 32-bit platforms

include/rootston/desktop.h, include/rootston/output.h, include/wlr/types/meson.build, include/wlr/types/wlr_output_management_v1.h, protocol/meson.build, protocol/wlr-output-management-unstable-v1.xml, rootston/desktop.c, rootston/output.c, types/meson.build, types/wlr_output_management_v1.c
This implements the protocol described in https://github.com/swaywm/wlr-protocols/pull/38
A test client is available: https://github.com/emersion/wlr-randr
Compositors need to implement the "apply/test configuration" part. This is mainly because some output properties require the compositor to take action: for instance a disabled output in wlroots can be in DPMS mode in sway, and the position needs to be set on the `wlr_output_layout` (related: https://github.com/swaywm/wlroots/issues/1610). Additionally, a compositor might want to have more freedom, e.g. save applied configurations on disk.
=> Add support for wlr-output-management-unstable-v1

rootston/output.c
Removing from the output layout also means that `wlr_output_layout_get_box()` may return `null`, and we need to be more careful with that. I checked all places, and added checks where it may happen that the output in question is disabled.
=> rootston: remove disabled outputs from the output layout

types/wlr_output.c
This is useful when using the noop backend for example.
=> output: do nothing in output_set_image if backend has no renderer

include/wlr/types/wlr_idle.h, types/wlr_idle.c
Is something like this desirable in wlroots? I want it so that I can set DPMS from inside Wayfire (Wayfire doesn't have swaymsg and so a plugin must turn off the outputs).
=> idle: enable the compositors to add custom idle timeouts

types/data_device/wlr_data_offer.c
It doesn't make sense for clients to send "accept" requests to offers that
aren't drag-and-drop. I discussed with Daniel Stone to make it a protocol
error [1] but too many clients send it (e.g. GTK+). Let's just log it for now.
[1]: https://gitlab.freedesktop.org/wayland/wayland/merge_requests/11#note_149710
=> data-device: ignore accept for selection offers

backend/drm/drm.c, backend/drm/renderer.c, backend/headless/output.c, backend/wayland/backend.c, glgen.sh, include/render/gles2.h, render/egl.c, rootston/output.c
The deleted includes are redundant, because other headers will include the necessary files. Additionally, they cause build failures, because including EGL/egl.h or EGL/eglext.h directly, instead of through wlr/render/egl.h or wlr/render/interface.h, will mean that `MESA_EGL_NO_X11_HEADERS` will not have been defined, and so the EGL headers will attempt to pull in unnecessary X11 headers that may not exist on the system.
For the headers produced by glgen.sh, the includes couldn't simply be deleted, because no other header would include the EGL headers. Neither wlr/render/egl.h or wlr/render/interface.h felt appropriate to include, so I opted instead to copy the `MESA_EGL_NO_X11_HEADERS` definition before
the EGL includes.
=> Fix missing headers when building without X11

include/wlr/types/wlr_output.h, rootston/output.c, types/wlr_output.c
This is a little more robust than assuming the last mode is the preferred one. This also makes compositors' code clearer.
The second commit also fixes rootston setting the preferred mode and then changing it to the configured mode (which causes delays at startup).
=> Add wlr_output_preferred_mode

backend/drm/drm.c, backend/headless/output.c, backend/noop/output.c, backend/rdp/output.c, backend/wayland/output.c, backend/x11/backend.c, backend/x11/output.c, examples/fullscreen-shell.c, examples/multi-pointer.c, examples/output-layout.c, examples/pointer.c, examples/rotation.c, examples/simple.c, examples/tablet.c, examples/touch.c, include/wlr/interfaces/wlr_output.h, include/wlr/types/wlr_export_dmabuf_v1.h, include/wlr/types/wlr_output.h, include/wlr/types/wlr_output_damage.h, include/wlr/types/wlr_screencopy_v1.h, rootston/render.c, tinywl/tinywl.c, types/wlr_export_dmabuf_v1.c, types/wlr_output.c, types/wlr_output_damage.c, types/wlr_screencopy_v1.c, types/wlr_screenshooter.c
This is necessary for direct scan-out and other upcoming features. This patch
changes the output API to look like the wl_surface API.
Outputs now have some double-buffered state: the frame to be submitted
(currently only wlr_renderer frames are supported) and the damaged region.
To attach a pending frame, use wlr_output_attach_render. To set the pending
damaged region, use wlr_output_set_damage.
To submit the pending state, call wlr_output_commit. This will submit the
pending frame to the backend.
To migrate from the old API to the new one:
- Replace wlr_output_make_current calls by wlr_output_attach_render
- Replace wlr_output_swap_buffers calls by wlr_output_set_damage and
wlr_output_commit
- Replace wlr_output_damage_make_current calls by wlr_output_damage_attach_render
- Replace …
=> output: refactor frame submission API

render/egl.c
UBSan says:
```
../render/egl.c:370:10: runtime error: variable length array bound evaluates to non-positive value 0
```
=> render/egl: fix zero-length VLA

backend/wayland/wl_seat.c
```
==31666==ERROR: AddressSanitizer: heap-use-after-free on address 0x611000033fc8 at pc 0x7f5d21f20084 bp 0x7ffcfed7b0f0 sp 0x7ffcfed7b0e0
READ of size 8 at 0x611000033fc8 thread T0
#0 0x7f5d21f20083 in wlr_signal_emit_safe ../util/signal.c:19
#1 0x7f5d21dd2495 in pointer_handle_frame ../backend/wayland/wl_seat.c:135
#2 0x7f5d200ea6cf in ffi_call_unix64 (/lib64/libffi.so.6+0x66cf)
#3 0x7f5d200ea09f in ffi_call (/lib64/libffi.so.6+0x609f)
#4 0x7f5d207bbf8e  (/lib64/libwayland-client.so.0+0x8f8e)
#5 0x7f5d207b86b9  (/lib64/libwayland-client.so.0+0x56b9)
#6 0x7f5d207b9bfb in wl_display_dispatch_queue_pending (/lib64/libwayland-client.so.0+0x6bfb)
#7 0x7f5d21dc810c in dispatch_events ../backend/wayland/backend.c:35
#8 0x7f5d219f07f1 in wl_event_loop_dispatch …
```
=> backend/wayland: fix wlr_wl_pointer use-after-free

types/wlr_output_damage.c
This fixes a segfault after unplug:
```
#0  0x00007f9dd1701c83 in wl_list_insert (list=0x563299a7c2b0, elm=0x7ffc68371250) at src/wayland-util.c:49
#1  0x00007f9dd1d936ba in wlr_signal_emit_safe (signal=0x5632998a4fb0, data=0x5632998a4e40) at ../subprojects/wlroots/util/signal.c:27
#2  0x00007f9dd1d81c29 in wlr_output_commit (output=0x5632998a4e40) at ../subprojects/wlroots/types/wlr_output.c:437
#3  0x000056329900ffd3 in output_render (output=0x563299d39a80, when=0x7ffc683713e0, damage=0x7ffc683713f0) at ../sway/desktop/render.c:1090
#4  0x000056329900bf19 in damage_handle_frame (listener=0x563299d39c08, data=0x563299a7bfe0) at ../sway/desktop/output.c:390
#5  0x00007f9dd1d936d2 in wlr_signal_emit_safe (signal=0x563299a7c040, data=0x563299a7bfe0) at …
```
=> output-damage: fix segfault after destroy

types/seat/wlr_seat.c
This does not require any code changes, as we already copy the keymap
data separately for each client.
For details, see https://gitlab.freedesktop.org/wayland/wayland/commit/905c0a341ddf0a885811d19e2b79c65a3f1d210c
---
Relevant code: https://github.com/swaywm/wlroots/blob/460a630a43c3aa914a84e2a2a0f879f8042d6c7f/types/seat/wlr_seat_keyboard.c#L346-L373
We **could** implement that with proper fd sealing, but since that's linux-specific, I doubt that's going to happen.
=> Advertise wl_seat version 7

include/wlr/types/wlr_output.h, include/wlr/types/wlr_output_damage.h, render/egl.c, rootston/render.c
See the individual commits.
I wonder whether `wlr_output_damage_attach_render` should call `wlr_output_set_damage` for you. Compositors can always call it again to override it (or stop using `wlr_output_damage`, it's just a helper after all). @ammen99 Would this be something you'd want to override?
Fixes #1665
=> Don't submit too much damage

rootston/render.c
We want to damage the whole output in this mode. However if we overwrite the
damaged region after it's useless.
Rename `output_damage` to `frame_damage` while I'm at it, it's a better name.
Fixes: 57d32d03a87ab4a74230294cefc5fa8b1e28c96d
=> rootston: fix damage tracking debug mode

.builds/freebsd.yml
`/latest` has `epoll-shim.pc` as it contains https://github.com/FreeBSDDesktop/epoll-shim/pull/1 after https://github.com/freebsd/freebsd-ports/commit/68b90c9df610ee3d99c719360256fcacf2e83603
Same as #1671.
=> Drop fixup_epoll in .builds/freebsd.yml

.builds/alpine.yml, .builds/archlinux.yml, .builds/freebsd.yml
This makes it so we don't miss build failures because the CI misses a
dependency.
=> ci: enable Meson auto features

.builds/freebsd.yml
FreeBSD is currently the only non-Linux platform covered by automation. Let's keep RDP code portable as well.
See [downstream build log](https://github.com/swaywm/wlroots/files/3142831/wlroots-0.6.0.log).
=> Enable RDP in .builds/freebsd.yml

backend/wayland/backend.c, backend/wayland/output.c, include/backend/wayland.h
This allows the toplevel to have proper decorations on compositors that support
xdg-decoration-unstable-v1.
=> backend/wayland: use xdg-decoration-unstable-v1

backend/wayland/backend.c, include/backend/wayland.h
We bind to it but never use it.
=> backend/wayland: remove wl_shm

render/gles2/renderer.c
This is often the name of the GPU and can help debugging graphics issues.
=> render/gles2: print GL_RENDERER

types/wlr_output.c
Otherwise the damage is accumulated on subsequent frames.
=> output: clear output->damage on successful commit

backend/rdp/output.c
When using the rdp backend and connecting with `xfreerdp ... --rfx`, wlroots
crashes in `backend/rdp/output.c` while attempting to `realloc(..., 0)`.
This commit guards against that and instead returns true, resulting in
no rfx message being sent. This prevents the crash and appears to work, but
it's not obvious if this is correct from a specification perspective.
=> Fixes #1689 RDP RemoteFX crash

backend/session/logind.c
This appears to be a quick fix for compositors freezing when a dock is
disconnected. Disconnection of the dock is causing `pause_device` for
the DRM devices associated with the dock. Since these devices major
number is `DRM_MAJOR`, the session was being set to inactive. This just
makes it so the session is not set to inactive when the device's state
is `gone`.
=> session/logind: keep active for pause_device gone

backend/session/logind.c
"/org/freedesktop/login1/seat/self" path triggers seat-finding code path in logind,
which currently relies on getting the session based on caller's PID.
This behaviour is deprecated in logind as it doesn't work eg. with systemd user units,
which run outside of user session.
We check for "seat0" in logind_change_vt() already as introduced in 47985d2dc56a6af469ac9375e7548136765aff16,
so hard-coding it here is not a problem, otherwise sd_session_get_seat() could be used.
=> session/logind: specify seat exactly

backend/session/logind.c
In order to support compositors running as systemd user units without display manager,
a mechanism for specifying session ID exactly must exist.
Checking for `XDG_SESSION_ID` mimics loginctl behaviour https://github.com/systemd/systemd/blob/e95be7def26c6c5feaf08a4135aa4f50c53263a8/src/login/loginctl.c#L856.
=> session/logind: check for XDG_SESSION_ID first

types/wlr_output.c
If an output is destroyed while an idle_done event is scheduled, it
results in the following Address Sanitizer Output:
```
==1469==ERROR: AddressSanitizer: heap-use-after-free on address 0x6170000bb668 at pc 0x7f49aaa0c348 bp 0x7ffed5da35b0 sp 0x7ffed5da35a0
WRITE of size 8 at 0x6170000bb668 thread T0
#0 0x7f49aaa0c347 in schedule_done_handle_idle_timer ../subprojects/wlroots/types/wlr_output.c:265
#1 0x7f49aa2f875b in wl_event_loop_dispatch_idle (/usr/lib/libwayland-server.so.0+0xa75b)
#2 0x7f49aa2f8815 in wl_event_loop_dispatch (/usr/lib/libwayland-server.so.0+0xa815)
#3 0x7f49aa2f739b in wl_display_run (/usr/lib/libwayland-server.so.0+0x939b)
#4 0x556622dadd51 in server_run ../sway/server.c:216
#5 0x556622dac25d in main ../sway/main.c:397
#6 0x7f49aa0d0ce2 in __libc_start_main …
```
=> wlr_output: remove idle_done on output destroy

types/wlr_virtual_keyboard_v1.c
Fixes #1710 
If mmap fails, it will return MAP_FAILED not NULL. Since the error
handling was incorrectly checking for NULL, MAP_FAILED was being passed
to xkb_keymap_new_from_string, on mmap failure, causing a segfault.
This just fixes the error checking.
=> zwp_virtual-keyboard: fix mmap error handling

backend/drm/legacy.c
The DRM subsystem needs a NULL modeset for connectors which disappear
from the system to disable the hardware pipes, otherwise the pixels get
rendered but are sent nowhere.
The atomic backend does the equivalent by removing the properties and
issuing a commit.
Fixes #1706
Tested by using `WLR_DRM_NO_ATOMIC=1 sway` and toggling my laptops internal eDP-1 display.
=> drm: legacy: issue a NULL modeset on disable

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/properties.c, backend/drm/renderer.c, backend/drm/util.c, include/backend/drm/drm.h, include/backend/drm/properties.h, include/backend/drm/renderer.h, include/backend/drm/util.h, include/wlr/interfaces/wlr_output.h, include/wlr/render/dmabuf.h, include/wlr/render/drm_format_set.h, include/wlr/types/wlr_buffer.h, include/wlr/types/wlr_output.h, render/dmabuf.c, render/drm_format_set.c, rootston/render.c, types/wlr_buffer.c, types/wlr_export_dmabuf_v1.c, types/wlr_output.c, types/wlr_output_damage.c, types/wlr_screencopy_v1.c
This adds support for direct scan-out. This is a required feature before working on planes.
This PR tries to to as little changes as possible to make it easy to review and avoid re-writing everything. The current DRM backend and interface are not great but refactoring can happen incrementally with future PRs.
A new `wlr_output_attach_buffer` function has been introduced.
TODO:
Test plan: try those fullscreen
- `weston-simple-dmabuf-drm`
- `weston-simple-dmabuf-egl`
- `weston-simple-egl`
- mpv
- a glfw demo
Follow-up issues:
- Use atomic test mode to check whether a configuration works
- Support Y_INVERT DMA-BUFs by setting "rotation" = "reflect-y" on planes
Fixes https://github.com/swaywm/wlroots/issues/193
=> Add support for direct scan-out

backend/drm/atomic.c, docs/env_vars.md
This is [fixed on amdgpu](https://github.com/swaywm/sway/issues/2700#issuecomment-500236109), so we don't need this any more.
=> Remove WLR_DRM_NO_ATOMIC_GAMMA workaround

include/util/array.h, include/wlr/types/wlr_seat.h, types/seat/wlr_seat_pointer.c, types/wlr_keyboard.c, util/array.c
In addition to `button_count`, we keep track of the current buttons
pressed just as in `wlr_keyboard`.
Add `set_add` and `set_remove` to assist with this. These functions can
only be used with values greater than 0 (such as the button/key masks
for keyboards and pointers).
Partially addresses:
- https://github.com/swaywm/wlroots/issues/1716
- https://github.com/swaywm/wlroots/issues/1593
This doesn't make it so that button_count is incorruptible, and so some of the solutions described in #1593 might still be necessary (or another alternative), but this makes it possible to recover from errors upon triggering pointer events on another surface.
=> Use a set to track pointer button state.

backend/drm/drm.c, backend/headless/output.c, backend/noop/output.c, backend/rdp/output.c, backend/wayland/output.c, backend/x11/output.c, include/wlr/interfaces/wlr_output.h, types/wlr_output.c
See the individual commits.
Breaking change: `wlr_output_impl.transform` has been removed.
=> Minor output cleanup

backend/x11/input_device.c
Without the immediate frame event, the button event would not be processed in time: https://source.puri.sm/Librem5/phoc/issues/
=> x11: Send a frame event on the pointer after button events

backend/wayland/backend.c, backend/wayland/wl_seat.c, include/backend/wayland.h, protocol/meson.build
This is useful for developing compositors that have their own gestures.
=> Support pointer-gestures on Wayland backend

backend/drm/drm.c, include/backend/drm/drm.h
We originally used `match_obj` on planes, but this was largely unnecessary. Instead, this assigns planes statically at startup.
See https://github.com/swaywm/wlroots/issues/1723#issuecomment-504247814
It'll help if some people could test this as well (especially hotplugging), so it's not just "works for me".
=> backend/drm: Simplify object matching code

backend/drm/drm.c
This fixes an assertion failure if we're using a device that has 0 crtcs
as a renderer.
This would happen on some laptops with discrete GPUs.
=> backend/drm: Exit-early if 0 crtcs

include/wlr/types/wlr_virtual_keyboard_v1.h, types/wlr_virtual_keyboard_v1.c
A simple check capturing the nonsensical case of sending keycodes without having defined a keymap before. Key presses would still go through in case of wlroots due to having a default keymap defined, but I can't see relying on this as anything but a source of mistakes. Therefore, the implementation matches the protocol now, and rejects key presses if there's no keymap.
=> virtual_keyboard: Require keymap before accepting keycodes

backend/drm/atomic.c, backend/drm/drm.c, backend/drm/legacy.c
atomic and legacy now both pass the backend as the user data for the
pageflip event. We than retrieve the correct connector by matching on
the crtc_id passed to the page_flip_handler2.
Fixes #1297
=> backend: drm: switch to pageflip_handler_2

types/wlr_output_damage.c
An output needs swap when there is new damage. If the damage is only accumulated from the last frame, we could simply skip drawing.
A bit of background: https://github.com/WayfireWM/wayfire/issues/248
=> output-damage: set needs swap only when we have new damage
